### ISSUE TITLE
[Feature] 希望能够自定义 proto 生成的 MarshalOptions

### ISSUE THREAD

**Issue by csvwolf** [go-kratos/kratos#1003]
### Use case(s) - what problem will this feature solve?
在这里强制了 UseProtoNames，https://github.com/go-kratos/kratos/pull/985

但是我需要进行取消 omitempty 和 json name 转驼峰的操作。google 的 proto json mapping 中其实 default value 也是会转换成小驼峰的。能否开放一个入口进行设置的变更。read env or 配置进行操作？

**Comment by tonybase** [comment]
`json.UseProtoNames = false`

可以类似直接进行配置，或者自己注册 encoding 进行处理即可

**Comment by csvwolf** [comment]
> `json.UseProtoNames = false`
> 
> 可以类似直接进行配置，或者自己注册 encoding 进行处理即可

这个需要在哪里设置

**Comment by tonybase** [comment]
可以在 main.go，init() { json.MarshalOptions.UseProtoNames = false } 加上一些初始化的配置

**Comment by Cluas** [comment]
> > `json.UseProtoNames = false`
> > 可以类似直接进行配置，或者自己注册 encoding 进行处理即可
> 
> 这个需要在哪里设置

也可以在server.go做

**Comment by Windfarer** [comment]
这个可以搞成WithOption之类的方法来进行配置么？直接改全局有点tricky的样子

**Comment by tonybase** [comment]
可以直接对options 赋值，或者通过register codec进行覆盖就可以了，现在已经修改为 proto 默认 camelCase
