### ISSUE TITLE
[Question] mux 结合项目初始 middleware 使用

### ISSUE THREAD

**Issue by csvwolf** [go-kratos/kratos#1011]
mux 的 example 中有对于怎么使用 mux 的示例，但是初始化中，middleware 的类型是 kratos 的 http option，并不能作为 Mux 的 handler 使用，这样我要怎么结合两者进行使用。

```go
m := http.Middleware(
	recovery.Recovery(),
	tracing.Server(),
	logging.Server(logger),
)
```

```go
// 预期可能是
router := mux.NewRouter()
router.Use(recovery.Recovery())
router.Handle("/projects", handler)
```

**Comment by Windfarer** [comment]
kratos的middleware是试图构造一种grpc和http通用的请求处理组件，这里要看下如何整合起来，相关 https://github.com/go-kratos/kratos/issues/1009

**Comment by miyabyte** [comment]
帮你写了个例子：
`
router := mux.NewRouter()
	var m middleware.Middleware
	var req interface{}
	handleFunc := func(w http.ResponseWriter, r *http.Request) {
		//impl: Bind(r, &req)
		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return nil, nil
		}
		m(next)
		_, _ = next(r.Context(), &req)
		return
	}
	router.HandleFunc("/home", handleFunc).Methods("GET")
`

**Comment by tonybase** [comment]
建议单独写在 middleware 目录下，然后写个具体的 Service 的完整用例

**Comment by tonybase** [comment]
#1029

**Comment by Goxiaoy** [comment]
@miyabyte 你这个写的不对

我改了一下，这样可以将Kratos middleware转化为 http 的middleware格式

```go
import (
	"context"
	"github.com/go-kratos/kratos/v2/middleware"
	"net/http"
)

func MiddlewareConvert(m ...middleware.Middleware) func(http.Handler) http.Handler {
	chain := middleware.Chain(m...)
	return func(handler http.Handler) http.Handler {
		var req interface{}
		handleFunc := func(w http.ResponseWriter, r *http.Request) {
			//impl: Bind(r, &req)
			next := func(ctx context.Context, req interface{}) (interface{}, error) {
				return nil, nil
			}
			a := chain(next)
			_, _ = a(r.Context(), &req)
			handler.ServeHTTP(w, r)
		}
		return http.HandlerFunc(handleFunc)
	}
}
```

https://github.com/Goxiaoy/go-saas-kit/blob/09ad67958c2b78bce6040f10cce0467e3bac8aad/pkg/server/convert.go
