### ISSUE TITLE
kratos proto client 能否指定输出目录？ [Question]

### ISSUE THREAD

**Issue by mrzxy** [go-kratos/kratos#1022]
krtos proto client user.proto 是否知道把编译文件输出到指定目录

**Comment by tonybase** [comment]
其实比较建议直接使用 Makeflies，可以容易自己定制化使用。

https://github.com/go-kratos/kratos-layout/blob/main/Makefile

**Comment by mrzxy** [comment]
帅气，就要这个 :kissing_heart:
