### ISSUE TITLE
[Feature] errors/i18n: 支持多语言

### ISSUE THREAD

**Issue by tonybase** [go-kratos/kratos#1032]
通过 配置文件 或者 embed 进行配置多语言错误信息

**Comment by Windfarer** [comment]
i18n的支持可以不仅局限于error，可以考虑实现通用的i18n支持，在任何有字符串的地方都可以进行i18n。

通常的做法是使用配置文件来写翻译文本的模板，在应用启动时加载配置文件，进行文本渲染。

https://github.com/nicksnyder/go-i18n
这个库就是用上述方式工作，另外提供了工具来管理翻译配置文件

**Comment by Windfarer** [comment]
另一种i18n实现方式是使用GNU的[gettext](https://en.wikipedia.org/wiki/Gettext)系统，它提供了一种更为通用的i18n/l10n配置文件(.mo, .po)，并且[被多种编程语言默认支持](https://www.gnu.org/software/gettext/manual/html_node/List-of-Programming-Languages.html)，但目前golang中没有官方的实现，只有第三方实现https://github.com/chai2010/gettext-go/

**Comment by Windfarer** [comment]
在实践中，翻译文本仅是国际化的一部分，还有一些其它相关的工作：姓名和地址的习惯格式、日期格式、度量单位、标点符号等，这部分工作可能更适合在前端实现，即后端仅提供标准的内容，前端负责根据用户地区进行不同形式的展示

**Comment by Windfarer** [comment]
实际使用中，可以约定i18n相关的配置项来配置默认的语言，并且从诸如`Accept-Language`的metadata来获取客户端接受的语言，这样看来其实不一定要将i18n直接内置到框架内，i18n相关的涉及的逻辑较多，现有的一些库实现也比较完善，可以通过某种约定配置和metadata来提供适配，用户可根据这些信息集成自己想用的库进来进行使用。
