### ISSUE TITLE
新版本发送http Options请求时，请求未到cors middleware就返回405

### ISSUE THREAD

**Issue by FFcjs** [go-kratos/kratos#1089]
#### What happened:
更新版本后当浏览器发送preflight时，直接就返回405，导致跨域请求无法正常返回。
#### What you expected to happen:
options请求能正常流转到middleware进行处理
#### How to reproduce it (as minimally and precisely as possible):
更新版本直最新版，启动服务后发送 curl -i -v -X OPTIONS http://localhost:8000/api/v1/xxx进行测试

#### Environment:
- Kratos version (use `kratos -v`):v2.0.0-rc5
- Go version (use `go version`): go1.16.3 darwin/amd64
- OS (e.g: `cat /etc/os-release`): macos
- Others:

**Comment by tonybase** [comment]
问题已经修复：pr #1080

**Comment by tonybase** [comment]
可以直接使用 v2.0.0-rc6 版本
