### ISSUE TITLE
[建议] 通过 conventionalcommits 规范，规范化 commit message

### ISSUE THREAD

**Issue by ymh199478** [go-kratos/kratos#1096]
是否有考虑过使用：https://www.conventionalcommits.org/en/v1.0.0/ 规范，来规范化 commit message？
这样 [changelog 工具](https://github.com/git-chglog/git-chglog) 可以根据规范化的 commit history 自动生成 changelog

**Comment by shenqidebaozi** [comment]
不错的建议，这样 release changelog 就可以根据 commit 生成信息有助于帮助开发者了解修改了哪些地方

**Comment by shenqidebaozi** [comment]
https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit
