### ISSUE TITLE
[Feature] 能否集成一个工具同时支持swagger定义来做参数验证。

### ISSUE THREAD

**Issue by lyouthzzz** [go-kratos/kratos#1103]
Please see the FAQ in our main README.md before submitting your issue.

### Use case(s) - what problem will this feature solve?
和node.joi的解决的问题类似。https://www.npmjs.com/package/joi
目前proto定义如下：
`
message UpdateEmployeeRequest {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: ["ename", "password"]
    }
  };
  // @inject_tag: json:"ename" form:"ename" uri:"ename" binding:"required"
  string ename = 1 [(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
    title:"员工名";
    format:"string";
    description:"员工姓名";
  }];
  // @inject_tag: json:"password" form:"password"
  string password = 2;
  // @inject_tag: json:"email" form:"email"
  string email = 3;
}
`
目前文档定义和验证是分开定义的，比如我们使用gin验证的话会依赖@inject_tag的信息。其实swagger文档定义就包含了验证逻辑。所以能否集成做成一个工具来做这个事情，两处定义合并成一个定义，既可以生成文档也可以做request验证。
### Proposed Solution
实现还未有什么想法，可以讨论

**Comment by lyouthzzz** [comment]
proto定义
`
message UpdateEmployeeRequest {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: ["ename", "password"]
    }
  };
  // @inject_tag: json:"ename" form:"ename" uri:"ename" binding:"required"
  string ename = 1 [(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
    title:"员工名";
    format:"string";
    description:"员工姓名";
  }];
  // @inject_tag: json:"password" form:"password"
  string password = 2;
  // @inject_tag: json:"email" form:"email"
  string email = 3;
}
`

**Comment by lyouthzzz** [comment]
```
message UpdateEmployeeRequest {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: ["ename", "password"]
    }
  };
  // @inject_tag: json:"ename" form:"ename" uri:"ename" binding:"required"
  string ename = 1 [(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
    title:"员工名";
    format:"string";
    description:"员工姓名";
  }];
  // @inject_tag: json:"password" form:"password"
  string password = 2;
  // @inject_tag: json:"email" form:"email"
  string email = 3;
}
```

**Comment by shenqidebaozi** [comment]
群里面已经回复过了，先 close 掉了哦~
