### ISSUE TITLE
[Question] 请教下pb error的问题

### ISSUE THREAD

**Issue by mrzxy** [go-kratos/kratos#1106]
```proto3
extend google.protobuf.EnumOptions {
  int32 default_code = 1108;
}

extend google.protobuf.EnumValueOptions {
  int32 code = 1109;
}
```

这里的1108和1109是什么意思？为什么我改了_errors.pb.go 无法生成？

**Comment by shenqidebaozi** [comment]
errors.proto 是用于 proto-gen-go-errors, 1108 和 1109 只是怕和其他 option 冲突，无法生成文件和 errors.proto 无关，可以直接详细描述问题

**Comment by shenqidebaozi** [comment]
如果是修改了文件中的 序号导致无法生成，是因为 proto-gen-go-errors 中依赖的 errors.pb 是 kratos/errors 下的。你修改 third_party 后，field 与 kratos/errors 中不一致所以不能生成
```go
var file_errors_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.EnumOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         1108,
		Name:          "errors.default_code",
		Tag:           "varint,1108,opt,name=default_code",
		Filename:      "errors.proto",
	},
	{
		ExtendedType:  (*descriptor.EnumValueOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         1109,
		Name:          "errors.code",
		Tag:           "varint,1109,opt,name=code",
		Filename:      "errors.proto",
	},
}
```

**Comment by mrzxy** [comment]
我们现在api项目和业务项目是分开的，业务项目引用api项目，api项目使用1108 生成_errors.pb.go后，业务项目引用api项目编译的结果会冲突

![image](https://user-images.githubusercontent.com/11501927/123357558-4f7ae280-d59c-11eb-9d82-4ac443f97b79.png)

所以我尝试修改 1108 => 11108

**Comment by shenqidebaozi** [comment]
你们项目中包含 1108 这个 值？

**Comment by mrzxy** [comment]
api项目 error.proto
![image](https://user-images.githubusercontent.com/11501927/123361297-61ab4f80-d5a1-11eb-90b3-9bb5ba58b644.png)

如果不写1108无法生成_errors.pb.go

**Comment by shenqidebaozi** [comment]
用的 kratos client . 生成吗？ 能否提供一个复现仓库

**Comment by shenqidebaozi** [comment]
没太明白到底是什么导致了 errors 无法生成

**Comment by mrzxy** [comment]
[地址](https://github.com/mrzxy/test-pb-error)

**Comment by shenqidebaozi** [comment]
简单试了一下，大概知道问题出现在哪里了，您可以复制 kratos layout 中的 third_party 到你api 仓库中 
proto 文件
```protobuf
syntax = "proto3";

package hierror;
import "google/protobuf/descriptor.proto";
import "errors/errors.proto";
option go_package = "api/cloud/v1;v1";

enum ErrorReason {
  option (errors.default_code) = 500;

  USER_NOT_FOUND = 0 [(errors.code) = 404];
  CONTENT_MISSING = 1 [(errors.code) = 400];;
}
使用命令生成即可
```
protoc --proto_path=. \
>            --proto_path=./third_party \
>            --go_out=paths=source_relative:. \
>            --go-errors_out=paths=source_relative:. \
>            api/cloud/v1/errors.proto 
```shell

```

**Comment by shenqidebaozi** [comment]
我测试了一下，API 仓库单独管理，项目引用API包，可以正常启动没问题
![截屏2021-06-25 上午11 42 49](https://user-images.githubusercontent.com/35397691/123366253-793b0600-d5aa-11eb-8a2e-5c09c3ae701c.png)
![截屏2021-06-25 上午11 43 02](https://user-images.githubusercontent.com/35397691/123366271-822bd780-d5aa-11eb-8262-1eaf41b4f987.png)
![截屏2021-06-25 上午11 43 16](https://user-images.githubusercontent.com/35397691/123366289-8a841280-d5aa-11eb-8090-cc8c82174237.png)

**Comment by mrzxy** [comment]
感谢，问题已经解决，但是有两点疑惑
1.  粗略的看了下protoc-gen-go-erros，并没有看到对1108这个Field有什么逻辑，为什么会无法生成？
2. 第二疑惑，为什么上面这种解决方案，引入kratos-layout的errors.proto编译出来的_errors.pb.go，在业务项目引用不会报 `already registered` 的错误？

**Comment by shenqidebaozi** [comment]
1。 proto-gen-go-errors 里面引用了 pb 文件中的 变量，那个变量对应的 code 就是 1108。所以你改了之后会无法生成。因为你的 proto 中的 code 是其他数字，
```go
eCode := proto.GetExtension(v.Desc.Options(), errors.E_Code)
```
```go
var file_errors_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.EnumOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         1108,
		Name:          "errors.default_code",
		Tag:           "varint,1108,opt,name=default_code",
		Filename:      "errors.proto",
	},
	{
		ExtendedType:  (*descriptor.EnumValueOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         1109,
		Name:          "errors.code",
		Tag:           "varint,1109,opt,name=code",
		Filename:      "errors.proto",
	},
}
```

**Comment by shenqidebaozi** [comment]
2. 第二个问题，因为没有看到你之前的完整代码，所以不太清楚具体的原因，不过问题解决了就是很棒的事情

**Comment by mrzxy** [comment]
再次感谢
