### ISSUE TITLE
[Question] About Code Contributing

### ISSUE THREAD

**Issue by kagaya85** [go-kratos/kratos#1107]
Hi there 

I am a student learning the kratos recently, and I want to contribute code to kratos but I have some problems about how to get involved in contributing:

* is there something like Contributing Guideline or others I should pay attention to?
* I checked the [ROADMAP.md](https://github.com/kagaya85/kratos/blob/main/ROADMAP.md) and find some features that have not been implemented yet, if it is possible, can I have a try on some of them (like the rateLimit middleware, etc.)
* if have some other better suggestions, please let me know

Thanks in advance

**Comment by shenqidebaozi** [comment]
Welcome to contribute code to Kratos, the contribution specification is still improving recently. This part of service governance is still under discussion, because it needs to be combined with **Kratos UI**, so you can try to contribute other code first.
Thank you in advance for your contribution to Kratos

**Comment by shenqidebaozi** [comment]
After Kratos is released, this part of functions will be implemented in v2.1.0 version. You are welcome to contribute

**Comment by kagaya85** [comment]
@shenqidebaozi Thanks for quick reply
Does this mean that the issues (like #889, etc.) in Milestones v2.1.0 is working on, so can I try to pickup other issue first, like #856 or #1032, or any other recommendations?

**Comment by shenqidebaozi** [comment]
You can try to fix it first #856

**Comment by shenqidebaozi** [comment]
After discussion, i18n should not be implemented directly in the framework, because many packages are already excellent and may only provide example

**Comment by kagaya85** [comment]
Understood, I'll spend some time on #856 and we can discuss some details over there later

Thanks again!😀

**Comment by shenqidebaozi** [comment]
you are welcome
