### ISSUE TITLE
type protoreflect.FieldDescriptor has no field or method TextName

### ISSUE THREAD

**Issue by Aresky** [go-kratos/kratos#1109]
I got error response when use bazel build project . please help me!

ERROR: /private/var/tmp/_bazel_root/d156f781b74f47fd81ffa1ec5b946227/external/com_github_go_kratos_kratos_v2/transport/http/binding/BUILD.bazel:3:11: GoCompilePkg external/com_github_go_kratos_kratos_v2/transport/http/binding/binding.a failed: (Exit 1): sandbox-exec failed: error executing command 
  (cd /private/var/tmp/_bazel_root/d156f781b74f47fd81ffa1ec5b946227/sandbox/darwin-sandbox/223/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=11.1 \
    CGO_ENABLED=1 \
    DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer \
    GOARCH=amd64 \
    GOOS=darwin \
    GOPATH='' \
    GOROOT=external/go_sdk \
    GOROOT_FINAL=GOROOT \
    PATH=external/local_config_cc:/bin:/usr/bin \
    SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk \
    TMPDIR=/tmp \
    XCODE_VERSION_OVERRIDE=12.4.0.12D4e \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_root/d156f781b74f47fd81ffa1ec5b946227/sandbox/darwin-sandbox/223/sandbox.sb /var/tmp/_bazel_root/install/5ccdfa437f9a94a683a2b6383c9f8794/process-wrapper '--timeout=0' '--kill_delay=15' bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_amd64 -src external/com_github_go_kratos_kratos_v2/transport/http/binding/bind.go -src external/com_github_go_kratos_kratos_v2/transport/http/binding/encode.go -src external/com_github_go_kratos_kratos_v2/transport/http/binding/form.go -src external/com_github_go_kratos_kratos_v2/transport/http/binding/proto.go -src external/com_github_go_kratos_kratos_v2/transport/http/binding/test.pb.go -arc 'google.golang.org/genproto/protobuf/field_mask=google.golang.org/genproto/protobuf/field_mask=bazel-out/darwin-fastbuild/bin/external/org_golang_google_genproto/protobuf/field_mask/field_mask.x' -arc 'google.golang.org/protobuf/proto=google.golang.org/protobuf/proto=bazel-out/darwin-fastbuild/bin/external/org_golang_google_protobuf/proto/proto.x' -arc 'google.golang.org/protobuf/reflect/protoreflect=google.golang.org/protobuf/reflect/protoreflect=bazel-out/darwin-fastbuild/bin/external/org_golang_google_protobuf/reflect/protoreflect/protoreflect.x' -arc 'google.golang.org/protobuf/reflect/protoregistry=google.golang.org/protobuf/reflect/protoregistry=bazel-out/darwin-fastbuild/bin/external/org_golang_google_protobuf/reflect/protoregistry/protoregistry.x' -arc 'google.golang.org/protobuf/runtime/protoimpl=google.golang.org/protobuf/runtime/protoimpl=bazel-out/darwin-fastbuild/bin/external/org_golang_google_protobuf/runtime/protoimpl/protoimpl.x' -arc 'google.golang.org/protobuf/types/known/durationpb=google.golang.org/protobuf/types/known/durationpb=bazel-out/darwin-fastbuild/bin/external/org_golang_google_protobuf/types/known/durationpb/durationpb.x' -arc 'google.golang.org/protobuf/types/known/timestamppb=google.golang.org/protobuf/types/known/timestamppb=bazel-out/darwin-fastbuild/bin/external/org_golang_google_protobuf/types/known/timestamppb/timestamppb.x' -arc 'google.golang.org/protobuf/types/known/wrapperspb=google.golang.org/protobuf/types/known/wrapperspb=bazel-out/darwin-fastbuild/bin/external/org_golang_google_protobuf/types/known/wrapperspb/wrapperspb.x' -importpath github.com/go-kratos/kratos/v2/transport/http/binding -p github.com/go-kratos/kratos/v2/transport/http/binding -package_list bazel-out/host/bin/external/go_sdk/packages.txt -o bazel-out/darwin-fastbuild/bin/external/com_github_go_kratos_kratos_v2/transport/http/binding/binding.a -x bazel-out/darwin-fastbuild/bin/external/com_github_go_kratos_kratos_v2/transport/http/binding/binding.x -gcflags '' -asmflags '') sandbox-exec failed: error executing command 
  (cd /private/var/tmp/_bazel_root/d156f781b74f47fd81ffa1ec5b946227/sandbox/darwin-sandbox/223/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=11.1 \
    CGO_ENABLED=1 \
    DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer \
    GOARCH=amd64 \
    GOOS=darwin \
    GOPATH='' \
    GOROOT=external/go_sdk \
    GOROOT_FINAL=GOROOT \
    PATH=external/local_config_cc:/bin:/usr/bin \
    SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk \
    TMPDIR=/tmp \
    XCODE_VERSION_OVERRIDE=12.4.0.12D4e \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_root/d156f781b74f47fd81ffa1ec5b946227/sandbox/darwin-sandbox/223/sandbox.sb /var/tmp/_bazel_root/install/5ccdfa437f9a94a683a2b6383c9f8794/process-wrapper '--timeout=0' '--kill_delay=15' bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_amd64 -src external/com_github_go_kratos_kratos_v2/transport/http/binding/bind.go -src external/com_github_go_kratos_kratos_v2/transport/http/binding/encode.go -src external/com_github_go_kratos_kratos_v2/transport/http/binding/form.go -src external/com_github_go_kratos_kratos_v2/transport/http/binding/proto.go -src external/com_github_go_kratos_kratos_v2/transport/http/binding/test.pb.go -arc 'google.golang.org/genproto/protobuf/field_mask=google.golang.org/genproto/protobuf/field_mask=bazel-out/darwin-fastbuild/bin/external/org_golang_google_genproto/protobuf/field_mask/field_mask.x' -arc 'google.golang.org/protobuf/proto=google.golang.org/protobuf/proto=bazel-out/darwin-fastbuild/bin/external/org_golang_google_protobuf/proto/proto.x' -arc 'google.golang.org/protobuf/reflect/protoreflect=google.golang.org/protobuf/reflect/protoreflect=bazel-out/darwin-fastbuild/bin/external/org_golang_google_protobuf/reflect/protoreflect/protoreflect.x' -arc 'google.golang.org/protobuf/reflect/protoregistry=google.golang.org/protobuf/reflect/protoregistry=bazel-out/darwin-fastbuild/bin/external/org_golang_google_protobuf/reflect/protoregistry/protoregistry.x' -arc 'google.golang.org/protobuf/runtime/protoimpl=google.golang.org/protobuf/runtime/protoimpl=bazel-out/darwin-fastbuild/bin/external/org_golang_google_protobuf/runtime/protoimpl/protoimpl.x' -arc 'google.golang.org/protobuf/types/known/durationpb=google.golang.org/protobuf/types/known/durationpb=bazel-out/darwin-fastbuild/bin/external/org_golang_google_protobuf/types/known/durationpb/durationpb.x' -arc 'google.golang.org/protobuf/types/known/timestamppb=google.golang.org/protobuf/types/known/timestamppb=bazel-out/darwin-fastbuild/bin/external/org_golang_google_protobuf/types/known/timestamppb/timestamppb.x' -arc 'google.golang.org/protobuf/types/known/wrapperspb=google.golang.org/protobuf/types/known/wrapperspb=bazel-out/darwin-fastbuild/bin/external/org_golang_google_protobuf/types/known/wrapperspb/wrapperspb.x' -importpath github.com/go-kratos/kratos/v2/transport/http/binding -p github.com/go-kratos/kratos/v2/transport/http/binding -package_list bazel-out/host/bin/external/go_sdk/packages.txt -o bazel-out/darwin-fastbuild/bin/external/com_github_go_kratos_kratos_v2/transport/http/binding/binding.a -x bazel-out/darwin-fastbuild/bin/external/com_github_go_kratos_kratos_v2/transport/http/binding/binding.x -gcflags '' -asmflags '')
external/com_github_go_kratos_kratos_v2/transport/http/binding/encode.go:95:22: fd.TextName undefined (type protoreflect.FieldDescriptor has no field or method TextName)
compilepkg: error running subcommand external/go_sdk/pkg/tool/darwin_amd64/compile: exit status 2

**Comment by tonybase** [comment]
Which Protoc version?

**Comment by Aresky** [comment]
> Which Protoc version?

It has been determined that the version of protobuf is too low，thank you！
