### ISSUE TITLE
[Feature] 命令行工具中增加 changelog  命令

### ISSUE THREAD

**Issue by shenqidebaozi** [go-kratos/kratos#1133]
通过规范 commit message，用以生成规范化的 release 更新日志，并可以快速查看更新日志

### Prefix
```
break -> BREAKING CHANGES
deps -> Dependencies
feat-> New Features
fix -> Bug Fixes
... -> Others

type(pkg): xxx
eg: fix(config): xxx
```

### 增加命令 
kratos changelog
### 用法
kratos changelog version
### 示例
- kratos changelog dev 获取从 dev 到 last-tag 之间的 commit 信息
- kratos changelog v2.0.0 获取 v2.0.0 的更新日志

**Comment by shenqidebaozi** [comment]
#1096

**Comment by Windfarer** [comment]
changelog就行？不用复数吧，其它的几个子命令也不是复数

**Comment by shenqidebaozi** [comment]
@Windfarer 工具最开始的时候是可以查看多个版本的信息，后来简化成单个版本了。

**Comment by shenqidebaozi** [comment]
issue 没有修改

**Comment by ymh199478** [comment]
我也建议不要使用复数，和其他子命令一一致，你看 git log 也是单数的，虽然它可以展现出很多 logs....

**Comment by tonybase** [comment]
https://www.conventionalcommits.org/en/v1.0.0/
