### ISSUE TITLE
[Question]middleware特定路由使用问题

### ISSUE THREAD

**Issue by mrzxy** [go-kratos/kratos#1137]
看了最新`rc7`的middleware设计，有几个疑惑:
- 1. 看了`example`里的例子，是通过htto.Router实现，如果是通过proto来管理http接口，如何支持？
- 2. 为什么grpc不支持特定路由设置？

**Comment by tonybase** [comment]
应该是在各自中间里支持match operation，比如限流 超时，很多情况下面都可以yaml配置，可以配置到对应的method。
也就是中间件内部处理，而不是外部，还有正常也可能治理平台配置高生效了，都是动态配置完成。

**Comment by mrzxy** [comment]
感谢回复，我理解你这边设计的目的了

但是我这边应用场景有点不一样，不需要动态配置，比如 一个 `jwt检验的中间件`，接口会分成 需要jwt认证 或 不需要的 两类接口，按你上面的回复，应该是可以实现这个场景

但是这样`proto 生成Operation` ，如下
```go
http.SetOperation(ctx, "/api.cloud.cloud_core.v1.User/ListUser")
```

将会和我中间件里的白名单（用来做match）强耦合

```go
whileList := map[string]bool{
    "/api.cloud.cloud_core.v1.User/ListUser": true
}

// match步骤
if _, ok := whileList[operation]; ok {
}
```

**Comment by Windfarer** [comment]
用map来做路由，性能是不是会有点差

**Comment by tonybase** [comment]
#1241
