### ISSUE TITLE
kratos的run命令是否在某个特定版本时移除？[Question]

### ISSUE THREAD

**Issue by cppfred** [go-kratos/kratos#1144]
Please see the FAQ in our main README.md before submitting your issue.
系统：Windows 10 20H2
Kratos版本：2.0.0-rc7（latest）
问题描述：通过kratos new 的项目无法使用kratos run运行，检查kratos --help 后发现没有run命令。请问该参数是否在某个特定版本中被移除？或者kratos on windows不支持该参数？

**Comment by cppfred** [comment]
附图：
<img width="328" alt="6c76b49c9ef26c94c1b839a13b159f0" src="https://user-images.githubusercontent.com/47978719/124349079-f0624100-dc1f-11eb-988a-513577836e02.png">

**Comment by overstarry** [comment]
@cppfred  你是什么版本

**Comment by overstarry** [comment]
好像根本就没用这个run命令

**Comment by cppfred** [comment]
kratos版本：2.0.0-rc7

**Comment by shenqidebaozi** [comment]
@cppfred V2 就没这个命令啊

**Comment by tonybase** [comment]
kratos run .
kratos run xxx

可以在项目目录内查找cmd，实现 go run .
