### ISSUE TITLE
[Question] 如何接入消息队列才是最佳实践

### ISSUE THREAD

**Issue by shenqidebaozi** [go-kratos/kratos#1159]
### 背景

在实际业务场景中，框架需要接入消息队列，消息队列的接入方式有很多种，需要讨论一种合理的方案来实现框架接入消息队列的正确姿势

### 一些方案
- 实现 transport 接口, transport 绑定 service 负责接收消息，然后在 data 层中处理消息发送
- 在 data 层中，直接处理消息的接收与发送
- data 层返回 message 的 channel，上抛到上层进行处理

**Comment by shenqidebaozi** [comment]
@Windfarer 
> data模块里做mq实例的初始化和交互逻辑，具体的业务处理在biz里做，将原来的service层替换成某种管理模块，用来控制biz的生命周期，也可以提供一些任务的元信息或者任务管理相关的API
![{8978BAFC-7F1E-AE9D-FE23-DE4A22DF53CF}](https://user-images.githubusercontent.com/35397691/124733687-05541280-df47-11eb-9651-6bad5a9c0f30.jpg)

**Comment by tonybase** [comment]
如果一般小团队，建议直接使用 kafka client 就可以了，跟数据库类似用法即可。
如果大团队中，需要做管理topic和鉴权、限流等等，可以通过 grpc 进行 pubsub，通过 proxy 包一层。

**Comment by shenqidebaozi** [comment]
@tonybase 接收 kafka 订阅的消息的话，实现 transport 吗？

**Comment by shenqidebaozi** [comment]
还是类似 data 层返回 message 的 channel，上抛到上层进行处理

**Comment by tonybase** [comment]
是的，不用做得很复杂直接提供上层使用就可以了，可以写个 example

**Comment by shenqidebaozi** [comment]
@tonybase ok

**Comment by shenqidebaozi** [comment]
#1228
