### ISSUE TITLE
如何标记一个借口需要鉴权？&& 如何给所有的 HTTPresponse 增加固定返回值（如 token )[Question]

### ISSUE THREAD

**Issue by gozelus** [go-kratos/kratos#1165]
Please see the FAQ in our main README.md before submitting your issue.
1. 面向客户端的 bff 服务需要能够标记哪些接口需要登陆，哪些接口不需要登陆。对于这种需求目前是否有最佳实践？
2. 比如如果需要实现 jwt 鉴权及自动刷新，需要给所有接口返回 token 字段（检查过期时间后返回最新的 token），这个如何实现？

**Comment by shenqidebaozi** [comment]
先回答一下问题 2 ，如果想要控制 http 的返回值，可以覆盖默认的 `DefaultResponseEncoder`, 通过 `http.ReponseEncoder()` 配置，注入到http.Server() 中

**Comment by newxiaoming** [comment]
> 
> 
> 先回答一下问题 2 ，如果想要控制 http 的返回值，可以覆盖默认的 `DefaultResponseEncoder`, 通过 `http.ReponseEncoder()` 配置，注入到 `http.Server()` 中

想麻烦你提供一个示例指引吗，初学者。

**Comment by shenqidebaozi** [comment]
@newxiaoming https://mp.weixin.qq.com/s/4ocdoAVXXKTvJ3U65YXltw

**Comment by woorui** [comment]
> https://mp.weixin.qq.com/s/4ocdoAVXXKTvJ3U65YXltw

当proto字段定义为 `google.protobuf.Timestamp updated_at = 4;`, 按照文章中的方法，json 返回如下格式：

```
{
  "updated_at": {
    "seconds": 1627454278,
    "nanos": 308522000
  }
}
```

有什么优雅点的方法给他搞成下面这样的吗？
```
{
  "updated_at": "2021-07-28T06:37:55.334100Z"
}
```

**Comment by shenqidebaozi** [comment]
再做下处理呗。话说这个是数据库字段吗。是不是可以在数据库hook 进行处理

**Comment by woorui** [comment]
> 再做下处理呗。话说这个是数据库字段吗。是不是可以在数据库hook 进行处理

UpdatedAt 是`time.Time`类型

其实离data层还挺远的，现在是api层，在api层中使用`google.protobuf.Timestamp`,   用 `encoding.GetCodec("json").Marshal(reply)`处理，就会有这个问题

`HttpResponseEncoderfunc(w http.ResponseWriter, r *http.Request, v interface{})` 这里的`v`肯定已经是 proto 的reply了

**Comment by shenqidebaozi** [comment]
回答下第一个问题，可以使用最近 PR 的功能 #1241
