### ISSUE TITLE
[Question] grpc调用 context deadline exceeded

### ISSUE THREAD

**Issue by mrzxy** [go-kratos/kratos#1167]
使用 `kratos service`里 `context` 对象直接返回`context deadline exceeded`错误
复现代码:
```go
func (s *PeopleApp) List(ctx context.Context, req *face.ListPeopleRequest) (*face.ListPeopleReply, error) {
	conn, err := kratosGrpc.DialInsecure(
	        // 使用context.Background() 正常
                ctx,
		kratosGrpc.WithEndpoint("127.0.0.1:9000"),
		kratosGrpc.WithMiddleware(recovery.Recovery()),
	)
	if err != nil {
		return nil, errors.BadRequest("a", err.Error())
	}
}
```

怀疑跟 `http.Router.pool`缓存复用了 `http.Context`，导致 `<-ctx.Done` 直接返回

**Comment by shenqidebaozi** [comment]
kratos 默认的 context 超时了吧？配置文件里面改大点试试

**Comment by mrzxy** [comment]
这个在哪里配置？

**Comment by shenqidebaozi** [comment]
> 这个在哪里配置？

配置文件，或者在server/http 那

**Comment by gozelus** [comment]
`怀疑跟 http.Router.pool缓存服用 http.Context，导致 <-ctx.Done 直接返回`
[gin 有过类似的问题](https://github.com/gin-gonic/gin/issues/1731#issue-395448815) 
kratos 是如何避免的呢？

**Comment by mrzxy** [comment]
是我自己配置错了`http`超时时间，

看了下源码，`pool.Put()`的时候，`ctx.req` 已设置为 `nil` ，

这样，`httpContext.Done()`将会返回一个 `nil channel`
```go
func (c *wrapper) Done() <-chan struct{} {
	if c.req == nil {
		return nil
	}
	return c.req.Context().Done()
}
```
