### ISSUE TITLE
How much of this code was taken from go-micro?

### ISSUE THREAD

**Issue by asim** [go-kratos/kratos#1169]
Nice framework. But quick question. How much of this code came from go-micro. I see a lot of what looks like go-micro like abstractions, filenames and source. If it's derived from go-micro make the appropriate attributions to the original project.

**Comment by shenqidebaozi** [comment]
Kratos is totally different from go-micro in design concept.

**Comment by asim** [comment]
Where did the concepts of config's source, reader, value come from? https://github.com/go-kratos/kratos/tree/main/config. This is a complete copy of go-micro's config. Where did your errors package come from and mimic the same format of type and func definitions. The registry, the log helper from v2.... need I go on.

**Comment by shenqidebaozi** [comment]
The go-micro framework integrates too many things and is very complex. It is totally different from Kratos. In Kratos, everything is simple.

**Comment by asim** [comment]
Note on this, you stole a ton of stuff. Its remarkable what you can get away with these days.
