### ISSUE TITLE
[Question]生成的REST API 在请求返回正确的情况下 返回值不是json

### ISSUE THREAD

**Issue by ryouxin** [go-kratos/kratos#1170]
请求返回正常，结构体也定义正确，返回Content-Type值为 text/plain; charset=utf-8

**Comment by tonybase** [comment]
是不是请求时 Accept 传递了 text/plain 引起的？

**Comment by ryouxin** [comment]
从公司出来了现在没法看😂 下周一看一下。
我是用生成的swagger的json文件导入到postman里面后请求接口的 理论上Accept应该是 “*/*” 
而且返回text/plain只有在http status 200的时候 返回正确的结构体时出现这个问题 在返回错误 如 errors.InternalServer() 时返回的content -type 就是application/json 了

**Comment by ryouxin** [comment]
> 是不是请求时 Accept 传递了 text/plain 引起的？

我是用生成的swagger的json文件导入到postman里面后请求接口的 理论上Accept应该是 “/”
而且返回text/plain只有在http status 200的时候 返回正确的结构体时出现这个问题 在返回错误 如 errors.InternalServer() 时返回的content -type 就是application/json 了
