### ISSUE TITLE
[Upgrade] golint 静态分析工具已被弃用，需要使用其他分析工具替代

### ISSUE THREAD

**Issue by ymh199478** [go-kratos/kratos#1173]
[golang/lint](https://github.com/golang/lint) 已被弃用及归档，建议使用 [mgechev/revive](https://github.com/mgechev/revive) 作为替代品

--- 

对于 ci 建议使用：[golangci-lint](https://golangci-lint.run/) 来集成这些工具。

**Comment by Windfarer** [comment]
v1的时候好像用过golangci-lint来着，后面为了简单改用了官方，没想到凉了

**Comment by shenqidebaozi** [comment]
在用 golangci-lint 感觉还阔以

**Comment by tonybase** [comment]
@ymh199478 可以直接帮忙提pr整理下
