### ISSUE TITLE
跨域头案例失效

### ISSUE THREAD

**Issue by 574372469** [go-kratos/kratos#1174]
#### What happened:
启动官方跨域案例, 在浏览器请求案例地址被拦截
![image](https://user-images.githubusercontent.com/24728555/125227517-9c351c00-e305-11eb-8f92-ef64b2e7e60d.png)

#### What you expected to happen:
期望案例运行后会在响应头加上相应得跨域头.并且浏览器能正常响应
#### How to reproduce it (as minimally and precisely as possible):
运行[官方cors案例](https://github.com/go-kratos/kratos/tree/main/examples/http/cors),然后再浏览器请求相应接口路由
#### Anything else we need to know?:
none
#### Environment:
- Kratos version (use `v2.0.0`):
- Go version (use `go1.16.5 windows/amd64n`):
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by shenqidebaozi** [comment]
稍等，我试一下

**Comment by shenqidebaozi** [comment]
试了一下没有问题，应该是你使用 fetch 的问题，fetch 在 cors 请求的时候，貌似需要一些配置

**Comment by shenqidebaozi** [comment]
您可以先尝试下直接使用xhr,或者 axios, request 之类的库

**Comment by shenqidebaozi** [comment]
未开启 cors中间件
![image](https://user-images.githubusercontent.com/35397691/125242683-9a785200-e31f-11eb-9d72-f5b7d8a181fb.png)
开启 cors 中间件后
![image](https://user-images.githubusercontent.com/35397691/125242692-9d734280-e31f-11eb-80dd-f550fbfcf4d2.png)

**Comment by 574372469** [comment]
感谢回答,
确实是 fetch 的问题, 
因为 fetch 请求默认缺少了Origin头. fetch 发起的 OPTIONS 缺少Access-Control-Request-Method. 被gorilla的跨域中间件过滤了
