### ISSUE TITLE
[Question] 如何为http服务添加统一的路由前缀

### ISSUE THREAD

**Issue by evildao** [go-kratos/kratos#1178]
Please see the FAQ in our main README.md before submitting your issue.

**Comment by tonybase** [comment]
srv := http.NewServer()
router := srv.Route("/prefix")
router.GET("/xxx", http.Context)

**Comment by evildao** [comment]
```go
srv := http.NewServer(opts...)
// route := srv.Route("/api")
// srv.HandlePrefix("/api", nil)
v1.RegisterBuyerCartHTTPServer(srv, buyerCartImpl)
```
这种注册的呢？

**Comment by lyouthzzz** [comment]
> ```go
> ```go
> srv := http.NewServer(opts...)
> // route := srv.Route("/api")
> // srv.HandlePrefix("/api", nil)
> v1.RegisterBuyerCartHTTPServer(srv, buyerCartImpl)
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 这种注册的怎么弄的呢？
> 我尝试过，但是框架并没有提供修改srv路由前缀的方法，通过srv.Route方法返回的也是一个新的路由，虽然里面有老的srv，但是也并没有办法使用
> ```

我也有这个问题。这个kratos官方在做路由中间件。可以关注动态，等待发版。

**Comment by tonybase** [comment]
在 proto 应该定义full path的，不然生成swagger可能会对不上

**Comment by evildao** [comment]
swagger也是有basePath这种东西的，子路径是应该在proto定义完全，但是前缀路径，这个可能会在部署中动态改变，不能每次都要改那么多的proto文件吧
