### ISSUE TITLE
[Feature]中间件不支持gin路由

### ISSUE THREAD

**Issue by cq-z** [go-kratos/kratos#1182]
目前的中间件和过滤不支持gin或是echo。

**Comment by tonybase** [comment]
需要自己进行wrapper手动调用

**Comment by cq-z** [comment]
写了个gin中间件调用。但是还是有些小问题。中间件的req和gin控制器的格式还是不一样。官网有解决方案吗？

**Comment by longXboy** [comment]
这个可以安排

**Comment by longXboy** [comment]
https://github.com/go-kratos/gin/blob/main/examples/simple/main.go
看下是否满足需求
@cq-z

**Comment by cq-z** [comment]
大佬辛苦了！。看起来比我自己的好多了

**Comment by CodeFish-xiao** [comment]
> https://github.com/go-kratos/gin/blob/main/examples/simple/main.go 看下是否满足需求 @cq-z

我在使用这个中间件时发现，	
```
ge.Use(kgin.Middlewares(
		//recovery.Recovery(),
		//logging.Server(logger),
		selector.Server(jwt.Server(func(token *jwt2.Token) (interface{}, error) { return []byte(c.Jwt.Key), nil }, jwt.WithSigningMethod(jwt2.SigningMethodHS256))).Match(NewWhiteListMatcher()).Build(),
		//customMiddleware,
	))
```
无法直接返回401，而是会进行实际的gin方法的调用，如果加了log组件后，会打印401，但是请求依旧正常是200

![564581677122508_ pic](https://user-images.githubusercontent.com/48681482/220818354-f92761a6-fa52-42c7-a5d8-8115690198d7.jpg)

**Comment by CodeFish-xiao** [comment]
> > https://github.com/go-kratos/gin/blob/main/examples/simple/main.go 看下是否满足需求 @cq-z
> 
> 我在使用这个中间件时发现，
> 
> ```
> ge.Use(kgin.Middlewares(
> 		//recovery.Recovery(),
> 		//logging.Server(logger),
> 		selector.Server(jwt.Server(func(token *jwt2.Token) (interface{}, error) { return []byte(c.Jwt.Key), nil }, jwt.WithSigningMethod(jwt2.SigningMethodHS256))).Match(NewWhiteListMatcher()).Build(),
> 		//customMiddleware,
> 	))
> ```
> 
> 无法直接返回401，而是会进行实际的gin方法的调用，如果加了log组件后，会打印401，但是请求依旧正常是200
> 
> ![564581677122508_ pic](https://user-images.githubusercontent.com/48681482/220818354-f92761a6-fa52-42c7-a5d8-8115690198d7.jpg)

补充说明：
![image](https://user-images.githubusercontent.com/48681482/220818636-c9ae31fd-42a2-4ecb-914a-ade788168da3.png)
