### ISSUE TITLE
panic when using http.Server as net/http compatible handler

### ISSUE THREAD

**Issue by Reasno** [go-kratos/kratos#1187]
#### What happened:
看到kratos的http.Server实现了net/http的http.Handler接口，试图将kratos的http.server整合到自己的路由，请求时发生panic。原因是http.Server的endpoint字段空指针。看了代码，s.endpoint只有在执行s.Endpoint()时才会赋值，可执行以后就会建立端口监听，这个副作用对我的场景不可接受。建议提供一个新的构造option为s.endpoint手动赋值，并对s.endpoint提供一个合理的默认值。

#### What you expected to happen:
可以将kratos的http.Server当做net/http标准http.Handler使用，不发生panic。

#### How to reproduce it (as minimally and precisely as possible):
```go
        router := mux.NewRouter()
	srv := http.NewServer()
	helloworld.RegisterHelloworldHTTPServer(srv, service.NewHelloworldService())
	router.Handler(srv)
        nethttp.ListenAndServe(":8080", router)
```

请求时发生panic
#### Anything else we need to know?:

记得之前版本kratos的http包是会暴露出net/http的handler的，比较方便整合到自己框架/基础库中。希望正式的v2.0版本依然保持这种灵活性。

#### Environment:
- Kratos version (use `kratos -v`): kratos version v2.0.0
- Go version (use `go version`): 
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by longXboy** [comment]
为啥不使用kratos的启动方式来启动http server呢？

**Comment by Reasno** [comment]
> 为啥不使用kratos的启动方式来启动http server呢？

要整合到内部框架中。

**Comment by longXboy** [comment]
> > 为啥不使用kratos的启动方式来启动http server呢？
> 
> 要整合到内部框架中。希望能支持将kratos作为一个lib来使用。

好的，预计下个版本支持

**Comment by longXboy** [comment]
@Reasno 修复了，升级到v2.0.1试下呢

**Comment by Reasno** [comment]
> @Reasno 修复了，升级到v2.0.1试下呢

可以了👍
