### ISSUE TITLE
[Feature]文件名和代码反了

### ISSUE THREAD

**Issue by hoojos** [go-kratos/kratos#1189]
Please see the FAQ in our main README.md before submitting your issue.

### Use case(s) - what problem will this feature solve?
这两个文件的【命名和代码内容】弄反了
https://github.com/go-kratos/kratos/blob/main/cmd/kratos/internal/project/new.go
https://github.com/go-kratos/kratos/blob/main/cmd/kratos/internal/project/project.go

**Comment by ymh199478** [comment]
没有反，您可以理解为：project 中包含的是项目相关的命令，其中 new 命令用来创建新的项目

https://github.com/go-kratos/kratos/blob/e8c9a361d3294b53479ed7c0801566e6b7e0e47c/cmd/kratos/main.go#L26

**Comment by hoojos** [comment]
> 没有反，您可以理解为：project 中包含的是项目相关的命令，其中 new 命令用来创建新的项目
> 
> https://github.com/go-kratos/kratos/blob/e8c9a361d3294b53479ed7c0801566e6b7e0e47c/cmd/kratos/main.go#L26
现在是：
new.go文件里定义的是 type Project struct {xxx}
project.go文件里定义的是 func CmdNew()
不应该是
new.go定义CmdNew，project.go定义 type Project struct{}吗？

**Comment by ymh199478** [comment]
@hoojos 感谢反馈，产生这个问题的原因应该是由于目前 project 只有一个 new 命令，所以没有被剥离成类似： https://github.com/go-kratos/kratos/blob/main/cmd/kratos/internal/proto/proto.go 这样的结构，如果存在多个命令我们将它变更为和 proto 类似的结构我想就没有此类理解性的问题了。

从行为语义的角度来讲 `project.New()` 这个语义没有什么问题。

**Comment by hoojos** [comment]
你没理解我的意思。我说的问题是文件A.go的内容应该是定义A相关的代码，你们A.go里面定义了B，B.go里面定义了A，不符合Go的习惯。你可以找给其他同事看一下

**Comment by ymh199478** [comment]
@hoojos 感谢反馈，出现这个问题的原因我想应该是由于目前 new 是最顶层的，但是它却被放到了 project 文件夹下。

**Comment by hoojos** [comment]
> @hoojos 感谢反馈，出现这个问题的原因我想应该是由于目前 new 是最顶层的命令，但是它却被放到了 project 文件夹下。
> 
> 但单从 `project.New` 的语义来说没有什么太大的问题，因为这个命令的行为是创建一个新的项目。

我反对的不是【出现这个问题的原因我想应该是由于目前 new 是最顶层的命令，但是它却被放到了 project 文件夹下】，你把issue给其他人看吧

**Comment by hoojos** [comment]
project.go 里面定义了cobra的New子命令，new.go里面定义了类型Project的实现

理应是：

project.go里面定义类Project的实现，new.go里面定义cobra的New子命令

**Comment by ymh199478** [comment]
@hoojos 我的想法是，如果独立放了，那么结构就会是：

```
-- new/
  -- new.go      <- 这里放 cobra 的 new 子命令
  -- project.go   <-  这里申明原本 new.go 中定义的代码
```

**Comment by tonybase** [comment]
new 是关键字，不能当作包名。。这有啥好纠结的

**Comment by hoojos** [comment]
你们先理解我的问题，一直在答非所问。这么说吧，执行以下命令，执行完之后看一下diff，是否更合理了？

mv cmd/kratos/internal/project/project.go cmd/kratos/internal/project/tmp.go
mv cmd/kratos/internal/project/new.go cmd/kratos/internal/project/project.go
mv cmd/kratos/internal/project/tmp.go cmd/kratos/internal/project/new.go
