### ISSUE TITLE
使用 nacos 作为服务发现遇到的问题

### ISSUE THREAD

**Issue by realjustice** [go-kratos/kratos#1198]
#### What happened:
使用nacos作为服务发现，注册的时候，会自动拼上grpc
但是调用服务发现的时候需要手工拼上grpc，否则会引起错误
rpc error: code = Unavailable desc = last resolver error: produced zero addresses
![image](https://user-images.githubusercontent.com/36758476/125886851-0ae631f3-b7ec-4519-87d8-b6c327c580ba.png)
#### How to reproduce it (as minimally and precisely as possible):
直接运行example中nacos demo就可以复现
#### Environment:
- Kratos version (use `kratos -v`):
- Go version (use `go version`):
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by shenqidebaozi** [comment]
这个不算是 bug

**Comment by shenqidebaozi** [comment]
这个问题之前我们有讨论过，nacos 服务发现 无法指定服务类型。比如说 http / grpc，所以只能把类型拼接到服务名称后面

**Comment by shenqidebaozi** [comment]
nacos 不像是 consul 之类的，可以在服务发现时指定。nacos 官方也不准备支持这个需求。

**Comment by shenqidebaozi** [comment]
![截屏2021-07-16 上午11 41 21](https://user-images.githubusercontent.com/35397691/125888375-f9c5a127-4fc1-48b7-8b3b-3557df74330e.png)

**Comment by realjustice** [comment]
谢谢回复，理解了
