### ISSUE TITLE
[Feature] Discussion on the definition and usage of event interface

### ISSUE THREAD

**Issue by shenqidebaozi** [go-kratos/kratos#1201]
## 背景

在实际业务场景中，框架需要接入消息队列，消息队列的接入方式有很多种，框架中应提供抽象接口，并提供一些默认实现，如 kafka 等

## 相关资料
- #1159 
- https://github.com/openmessaging/openmessaging-go
- https://github.com/cloudevents/sdk-go/blob/main/v2/client/client.go
- https://docs.dapr.io/reference/api/pubsub_api/

**Comment by tonybase** [comment]
```go
type Message interface {
    Topic() string
    Key() string
    Value() []byte
    Metadata() metadata.Metadata
}

type Handler func(context.Context, Message) error

type Event interface {
    Send(ctx context.Context, key string, value []byte]) error
    Receive(ctx context.Context, handler Handler) error
    Ack(ctx context.Context, message Message) error
    Nack(ctx context.Context, message Message) error
    Close() error
}
```

可以通过  ctx 结合 metadata 进行传递调用信息

**Comment by shenqidebaozi** [comment]
- https://github.com/openmessaging/openmessaging-go
- https://github.com/cloudevents/sdk-go/blob/main/v2/client/client.go

**Comment by shenqidebaozi** [comment]
@ymh199478 
> 发送系接口：
Send()
接收系接口：
Receive()
Ack(Message)
Reject(Message)

**Comment by ymh199478** [comment]
```go
type Sender interface {
   Send(ctx context.Context, key string, value []byte]) error
}
```

```go
type Receiver interface {
   Get () (context.Context, Message, error)
   Ack (msg Message) error
   Nack (msg Message) error
}
```

**Comment by ymh199478** [comment]
```go
type Sender interface {
   Send(ctx context.Context, msg Message) error
}
```

```go
type Receiver interface {
   Get(ctx context.Context) (Message, error)
   Ack(msg Message) error
   Nack(msg Message) error
}
```

**Comment by Windfarer** [comment]
可不可以有BatchSend和BatchGet

**Comment by kagaya85** [comment]
https://github.com/dapr/components-contrib

**Comment by shenqidebaozi** [comment]
> 可不可以有BatchSend和BatchGet

@Windfarer 接口应该不包含把，实现的时候自己加上。

**Comment by Windfarer** [comment]
用单个请求拼成batch，和直接调batch，性能是有差别的

> > 可不可以有BatchSend和BatchGet
> 
> @Windfarer 接口应该不包含把，实现的时候自己加上。接口保证最小粒度。

**Comment by Nayee7c** [comment]
有没有可能考虑像pulsar 这样的mq 结构，如shcema等

**Comment by MarsonShine** [comment]
事件接口的方法中的 Receive 语义上应该是有返回结构的，这里应该是 publish - subscribe / send - receive 互相匹配

**Comment by Reasno** [comment]
> 用单个请求拼成batch，和直接调batch，性能是有差别的
> 
> > > 可不可以有BatchSend和BatchGet
> > 
> > 
> > @Windfarer 接口应该不包含把，实现的时候自己加上。接口保证最小粒度。

提醒一下，大多数MQ实现不能保证Batch的原子性，即可能会出现batch中部分成功，部分失败的后果。

**Comment by Reasno** [comment]
event接口可以考虑支持async API： https://www.asyncapi.com/

CloudEvent这种标准，对serverless场景做了太多倾斜。相比较下，AsyncAPI更符合实际工业场景。

**Comment by gozelus** [comment]
这个有计划吗？

**Comment by letian0805** [comment]
> ```go
> type Sender interface {
>    Send(ctx context.Context, msg Message) error
> }
> ```
> 
> ```go
> type Receiver interface {
>    Get(ctx context.Context) (Message, error)
>    Ack(msg Message) error
>    Nack(msg Message) error
> }
> ```

```golang
type Receiver interface {
   Receive(ctx context.Context) (Message, error)
   Ack(msg Message) error
   Nack(msg Message) error
}
```

**Comment by Casper-Mars** [comment]
https://cloud.google.com/solutions/event-driven-architecture-pubsub
