### ISSUE TITLE
[Feature] Apache Kafka for async interaction

### ISSUE THREAD

**Issue by musinit** [go-kratos/kratos#1202]
### Use case(s) - what problem will this feature solve?
It will provide async interaction between services, it will help process peaks of load and distribute highload

### Proposed Solution
Implement Kafka consumers/producers

### Alternatives Considered
HTTP/gRPS with loadbalancers, but they are sync.

**Comment by shenqidebaozi** [comment]
@musinit 
Now it is still in the proposal stage. There are plans to introduce the event interface in version 2.2.0 and provide the default implementation, such as Kafka.

**Comment by musinit** [comment]
I can start working on it and make PR
