### ISSUE TITLE
[Question] 关于 kratos new project 命令无法拉取自己的模板仓库

### ISSUE THREAD

**Issue by guowei-gong** [go-kratos/kratos#1218]
您好，在我使用 kratos new repo-url -r layout repo 后，没有拉取成功我的模板仓库，错误信息如下：

”ERROR: open /Users/gongguowei/.kratos/repo/github.com/guowei-gong/kratos-service-modules-layout@master/go.mod: no such file or directory“

![image](https://user-images.githubusercontent.com/62499904/126300840-e543c934-65e8-4a5b-83ad-cd92ece4d5fe.png)

当然，我的模板仓库是不存在 go.mod 文件的，因为它们包管理依赖项目根目录的 go.mod，我在想校验模板仓库中是否存在 go.mod 会不会是多余的呢？还是我的姿势不对？

![image](https://user-images.githubusercontent.com/62499904/126301631-e90c7bc5-d6c2-416e-ac6c-b79883e78f65.png)

**Comment by shenqidebaozi** [comment]
有道理。

**Comment by shenqidebaozi** [comment]
这个功能是用于替换代码中引用的包的路径，我优化下，如果当前目录下不存在就去上层目录找应该就可以了

**Comment by shenqidebaozi** [comment]
问题已经修复，解决办法是，layout 中还是需要包含 go.mod 通过如 `kratos new github.com/go-kratos/beer-shop/app/user`这种方式 创建项目，然后删除 go.mod 即可适用于 monorepo 项目
