### ISSUE TITLE
[Feature] HTTP 请求参数支持带方括号的数组格式

### ISSUE THREAD

**Issue by Ederth** [go-kratos/kratos#1222]
Please see the FAQ in our main README.md before submitting your issue.

### Use case(s) - what problem will this feature solve?
js 或者 php 的 http 请求，如果有数组参数，默认会添加方括号例如 ids[]=1&ids[]=2

希望增加对这种格式数组的支持

**Comment by longXboy** [comment]
可以支持一下

**Comment by exuan** [comment]
```
# code
https://github.com/go-kratos/kratos/blob/ab45baf5ec88cb676f3d1b03d0b1981dbb45b026/transport/http/context.go#L92

# doc
https://go-kratos.dev/docs/component/transport/http#requestdecoderdec-decoderequestfunc-serveroption
```
希望 decoder 可以接管 BindForm BindQuery

**Comment by ymh199478** [comment]
我没有在任何[标准](http://tools.ietf.org/html/rfc3986#section-3.4)文档中看到相关 `[]` 的定义，但在相关 wiki 中看到了一些评论：

https://en.wikipedia.org/wiki/Query_string

> While there is no definitive standard, most web frameworks allow multiple values to be associated with a single field

**Comment by Windfarer** [comment]
感觉挺怪的
