### ISSUE TITLE
[Question]通过pb生成的http接口怎么获取header中的数据呢？

### ISSUE THREAD

**Issue by TargetLiu** [go-kratos/kratos#1225]
想通过header中的Authorization来传递token进行用户鉴权，请问如果使用pb生成的接口，这部分数据怎么优雅的获取，并且呈现在openapi的文档中呢？
目前能想到的方案是通过RequestDecoder解析，但是感觉不是很友好

**Comment by shenqidebaozi** [comment]
metadata 看下文档元数据那部分

**Comment by TargetLiu** [comment]
当前解决方案：
通过middleware获取header内容，正好基于此做token验证，也可以通过operation判断哪些操作需要验证
`transport.FromServerContext(ctx)`

**Comment by shenqidebaozi** [comment]
嗯，这种方式也可以，先 close 了
