### ISSUE TITLE
[Suggest] 建议将 kratos 仓库中的 middleware 单独仓库管理

### ISSUE THREAD

**Issue by shenqidebaozi** [go-kratos/kratos#1230]
### 建议
为了保证 middleware 的依赖不会导致框架 breaking change，同时保证最小依赖，建议将当前仓库下的 middleware 复制一份到单独仓库中管理。当前仓库下的 middleware 不在维护，后续的 bug，特性等开发都在新创建的仓库中。当前仓库下的 middleware 仅保留给已经使用的项目继续使用，同时在文档中提醒用户尽早更换引用的包路径，在后期条件允许的情况下将当前仓库下的middleware 移除。

**Comment by tonybase** [comment]
可以统一放到 kratos 仓库管理，然后通过不同的 go.mod 解决依赖问题：
kratos
-registry
--consul
--go.mod // github.com/go-kratos/kratos/registry/consul/v2
--etcd
--go.mod
--nacos
--go.mod
