### ISSUE TITLE
`config/env` 包的 `matchPrefix` 方法似乎可能会字符串下标越界

### ISSUE THREAD

**Issue by xuyang2** [go-kratos/kratos#1233]
见
https://github.com/xuyang2/kratos/commit/d95b538b3fe0243b40bb49abf220420a477986c9#diff-0ac3535c204690e00f38a257aab0d3f22560b85b308e4c146a231b67022f3a8dR249

**Comment by tonybase** [comment]
这个可以提 pr 上面看看不啊？

**Comment by kagaya85** [comment]
如果环境变量的 Key 与 Prefix 完全匹配，这种情况下 key 为空，可以直接 continue 跳过该环境变量
