### ISSUE TITLE
task和job的最佳实践是怎么样的? 

### ISSUE THREAD

**Issue by jacky-pony** [go-kratos/kratos#1236]
对于定时任务、和后台工作的最佳实践应当是如何的? 

比如一个订单服务的消费者应当是把消费服务和订单服务放在一起吗 还是job是一个独立的服务? 

第三方的job和task有哪些推荐的? 

相关问题

https://github.com/go-kratos/kratos/issues/916
https://github.com/go-kratos/kratos/issues/230
https://github.com/go-kratos/kratos/issues/411

**Comment by peter-wow** [comment]
现在想到的一种方案是、kratos的服务只做业务  
task job 这种用其他独立的服务 比如这样子

还是说把第三方的task 和job以包的方式导入到kratos中合适些

![image](https://user-images.githubusercontent.com/29112597/126870342-ecbeff26-f65b-4f84-b72d-1266dc7da017.png)

**Comment by shenqidebaozi** [comment]
#411
