### ISSUE TITLE
按照文档步骤执行没有http. pb.go文件生成

### ISSUE THREAD

**Issue by alongisme** [go-kratos/kratos#1238]
# 创建项目模板
kratos new helloworld

cd helloworld
# 拉取项目依赖
go mod download
# 生成proto模板
kratos proto add api/helloworld/helloworld.proto
# 生成proto源码
kratos proto client api/helloworld/helloworld.proto
# 生成server模板
kratos proto server api/helloworld/helloworld.proto -t internal/service

**Comment by tonybase** [comment]
kratos proto client
或者
make api

可以生成http？

**Comment by alongisme** [comment]
都不可以。

**Comment by tonybase** [comment]
有报什么错误吗？

可以先 make init 或者 kratos upgrade 一下试试

**Comment by alongisme** [comment]
没有报任何错误 除了http文件没有生成，其他文件都生成了。是否有执行过程可以查看？或者单独使用protoc-gen-go-http这个命令是否有效

**Comment by shenqidebaozi** [comment]
你声明http接口了吗，另外有试过make api？

**Comment by shenqidebaozi** [comment]
如果没声明的话，不会生成的

**Comment by gko1943** [comment]
所以步骤应该是:

**Comment by gko1943** [comment]
所以创建新的 http 接口的步骤应该是:
[kratos API定义](https://go-kratos.dev/docs/component/api)
1. 执行命令: kratos proto add api/hello/hello.proto
2. 编辑 api/hello/hello.proto, 增加get方法. 参照 "定义接口"和"生成接口"段落
3. 编辑 internal/server/http.go 将方法注册进 http server.  参照: "注册接口"段落

**Comment by Lngenuus** [comment]
刚接触kratos同样遇到这个问题， 看了源码发现是 proto-gen-go-http 主要这句代码
`	if len(file.Services) == 0 || (omitempty && !hasHTTPRule(file.Services)) {
		return nil
	}`
默认的omitempty是true这样就会检测你的proto文件中的服务方法是否有声明  要是没声明对不起 直接拜拜😄

要是你偏不定义 还要生成_http.pb.go 那么命令行下执行以下命令😎:

`protoc --proto_paht=. --go-http_out=omitempty=false,paths=source_relative:.  xxx.proto`

这种方法并不推荐
