### ISSUE TITLE
middleware/selector: 支持更丰富的中间件匹配功能

### ISSUE THREAD

**Issue by tonybase** [go-kratos/kratos#1241]
通过middleware支持特定路由匹配：
```go
http.Middleware(
    selector.Client(logging.Server(), authjwt.Server())
        .Prefix("/helloworld.")
        .Regex("/helloworld.{Say*}"),
        .Path("/helloworld.SayHello"),
)

http.Middleware(
    selector.Server(logging.Server(), authjwt.Server())
        .Prefix("/helloworld.")
        .Regex("/helloworld.{Say*}"),
        .Path("/helloworld.SayHello"),
)
```
匹配模式：
```go
builder.Prefix("/helloworld.")
builder.Regex("/helloworld.{Say*}")
builder.Path("/helloworld.method")
```
反正声明：
```go
builder.NotPrefix("/helloworld.")
builder.NotRegex("/helloworld.{Say*}")
builder.NotPath("/helloworld.SayHello")
```

**Comment by shenqidebaozi** [comment]
如果可以的话，第一个参数是否可以传入数组类型？因为有可能某些路由的中间件配置相同，但是通过前缀，正则可能不太好匹配到一起去。

**Comment by shanezhiu** [comment]
> 

翻看源码并没有实现NotPrefix, NotRegex, NotPath

**Comment by shenqidebaozi** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> > 
> 
> Looking at the source code does not implement NotPrefix, NotRegex, NotPath
@shanezhiu 
simply use the custom method mode

**Comment by shanezhiu** [comment]
> > > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> > 
> > 
> > > 
> > 
> > 
> > Looking at the source code does not implement NotPrefix, NotRegex, NotPath
> > @shanezhiu
> > simply use the custom method mode

I can not get you. Do you mean that I can do this with a self defined Match method?

**Comment by shenqidebaozi** [comment]
https://go-kratos.dev/docs/component/middleware/overview#%E5%AE%9A%E5%88%B6%E4%B8%AD%E9%97%B4%E4%BB%B6

**Comment by shanezhiu** [comment]
thanks a lot
