### ISSUE TITLE
变量未定义，阻碍命令kratos proto client api/helloworld/helloworld.proto正常执行

### ISSUE THREAD

**Issue by liehuozhenjun** [go-kratos/kratos#1243]
7月25日本机学习过程中，欲执行命令kratos proto client api/helloworld/helloworld.proto时，命令行提示报错如下：
go get -u github.com/go-kratos/kratos/cmd/kratos/v2
go: downloading github.com/go-kratos/kratos/cmd/kratos/v2 v2.0.0-20210725040938-d09ba5e3eea7
# github.com/go-kratos/kratos/cmd/kratos/v2
../../go/pkg/mod/github.com/go-kratos/kratos/cmd/kratos/v2@v2.0.0-20210725040938-d09ba5e3eea7/main.go:20:11: undefined: kratos.Release
exit status 2

**Comment by tonybase** [comment]
我们先打个 tag，修复下，应该是新加入更新到了latest

**Comment by liehuozhenjun** [comment]
> 我们先打个 tag，修复下，应该是新加入更新到了latest

好的，这个算是阻碍主流程的问题，期待各位大神尽快处理，以便kratos爱好者能继续推进自己的学习进度，谢谢！
