### ISSUE TITLE
Kratos roadmap

### ISSUE THREAD

**Issue by tonybase** [go-kratos/kratos#1245]
# Preface
Thanks to everyone’s efforts in the first half of this year, framework of **kratos v2** has been basically completed. Next, kratos will carry out deep cultivation in the direction of service governance, and will develop **kratos API** and **Kratos UI** in the second half of this year to meet service governance Demand. In addition, we will use generics to reconstruct better postures in the first half of next year. I hope everyone can participate and contribute

# General Plan 
- Completed the basic framework functions (2021 H1)
- Support service management and back office (2021 H2)
- Use generic refactoring for better posture (2022 H1)

# New features

## Recent Work
The most recent work is mainly to improve the basic framework functions, scheduled to be completed in version 2.0.3

### Security
- [x] HTTP TLS #805
- [x] gRPC TLS #891

### Middleware

- [x] selector #1241
- [x] auth #1246 
- [x] ratelimit #889
- [x] circuitbreaker #903

### Others
- [Milestone v2.1.0](https://github.com/go-kratos/kratos/milestone/4)
- [Milestone v2.2.0](https://github.com/go-kratos/kratos/milestone/5)

## Later Work
The **kratos API** gRPC interface and service management platform **kratos UI** will be completed in the 2021 H2.

### Kratos API ( XDS?)
Provide gRPC API service, notify configuration and instance changes through streaming.

- [ ] auth 
- [ ] config
- [ ] registry 

### Kratos UI
Service management platform.

- [ ] Dashboard
- [ ] Services
- [ ] Nodes
- [ ] APIs
- [ ] Policies
- [ ] Configurations
- [ ] Authentications

# Still Discussing
- task/job #411
- event #1201

**Comment by brodyaga773** [comment]
why antd ?, there are more prettier UI's available :)
https://www.vue-tailwind.com/
https://vuetifyjs.com/en/
https://vuesax.com/

**Comment by Windfarer** [comment]
> why antd ? there are more prettier UI's available :)
> https://www.vue-tailwind.com/
> https://vuetifyjs.com/en/
> https://vuesax.com/

Because our team is more familiar with react and antd.
