### ISSUE TITLE
middleware/auth: API 接口鉴权

### ISSUE THREAD

**Issue by tonybase** [go-kratos/kratos#1246]
## Background
支持 JWT 鉴权中间件

## References:
- https://medium.com/hackernoon/designing-an-enterprise-role-based-access-control-rbac-system-96e645c659b7?_branch_match_id=826401137712545405
- https://codeburst.io/aws-attribute-based-access-control-abac-by-example-4dffabed40a4
- https://dev.to/techschoolguru/use-grpc-interceptor-for-authorization-with-jwt-1c5h
- https://istio.io/v0.7/docs/concepts/security/rbac.html
- https://blog.csdn.net/ywq935/article/details/84840935
- https://help.aliyun.com/document_detail/185580.html
- https://demo.consul.io/ui/dc1/services/api/intentions/create
- https://docs.microsoft.com/en-us/azure/role-based-access-control/role-definitions
- https://docs.microsoft.com/en-us/azure/role-based-access-control/custom-roles
- https://mysql.tutorials24x7.com/blog/guide-to-design-database-for-rbac-in-mysql

**Comment by Casper-Mars** [comment]
rfc(jwt): https://datatracker.ietf.org/doc/html/rfc7519

**Comment by Casper-Mars** [comment]
References provided by @tonybase ：

- https://github.com/googleapis/google-cloud-go
- https://github.com/googleapis/google-api-go-client/blob/4a93e84ab2255960edd90ee46e558e2f40a8be07/transport/http/dial.go#L76
- https://pkg.go.dev/golang.org/x/oauth2
- https://auth0.com/blog/authentication-in-golang
- https://cloud.google.com/endpoints/docs/grpc/restricting-api-access-with-api-keys#go

**Comment by Casper-Mars** [comment]
* 认证鉴权分为外部流量和服务间流量的认证鉴权
* 统一在 `framework middleware` 认证鉴权
* 使用 `JWT`，客户端还提供刷新token的机制
* 参考其他第三方鉴权例如：auth0

**Comment by Casper-Mars** [comment]
# 重新整理ref：
## 文档
- rfc(jwt): https://datatracker.ietf.org/doc/html/rfc7519
- rfc(OAuth 2.0): https://datatracker.ietf.org/doc/html/rfc6749
- 使用go对接auth0的例子: https://auth0.com/blog/authentication-in-golang
- Google cloud身份验证文档: https://cloud.google.com/endpoints/docs/grpc/restricting-api-access-with-api-keys#go
- 设计企业级的RBAC系统: https://medium.com/hackernoon/designing-an-enterprise-role-based-access-control-rbac-system-96e645c659b7?_branch_match_id=826401137712545405
- AWS的ABAC例子: https://codeburst.io/aws-attribute-based-access-control-abac-by-example-4dffabed40a4
- 使用grpc拦截器做jwt鉴权的例子: https://dev.to/techschoolguru/use-grpc-interceptor-for-authorization-with-jwt-1c5h
- k8s的RBAC: https://blog.csdn.net/ywq935/article/details/84840935
- Istio的RBAC: https://istio.io/v0.7/docs/concepts/security/rbac.html
- 微软azure的RBAC https://docs.microsoft.com/en-us/azure/role-based-access-control/
- 阿里云服务鉴权方案: https://help.aliyun.com/document_detail/185580.html
- 基于mysql设计RBAC系统: https://mysql.tutorials24x7.com/blog/guide-to-design-database-for-rbac-in-mysql

## 代码仓库
- Google云api: https://github.com/googleapis/google-cloud-go
- oauth2包: https://pkg.go.dev/golang.org/x/oauth2

## 代码片段
- GoogleAPI的go客户端使用api-key的位置: https://github.com/googleapis/google-api-go-client/blob/4a93e84ab2255960edd90ee46e558e2f40a8be07/transport/http/dial.go#L76

**Comment by Casper-Mars** [comment]
auth抽象层接口

对于Server

认证接口
传入上下文和transport，返认证后的上下文和错误。认证后的上下文可能会带上额外的信息，例如经过解析后的jwt token信息。
`
Authtication(context.Context,transport.Transport) (context.Context,error)

`

鉴权接口
传入经过认证的上下文进行鉴权。使用者可以获取上下文中带上的额外信息进行鉴权。鉴权成功则返回nil，否则返回具体的错误。
`
Authorization(context.Context) error
`

对于client

认证鉴权凭证获取接口
使用者自己维护获取凭证的逻辑
`
Token() interface{}
`
