### ISSUE TITLE
 config/env 包的 `env.load()` 可能会字符串下标越界

### ISSUE THREAD

**Issue by xuyang2** [go-kratos/kratos#1251]
原 issue 见 #1233

在 #1247 中未完全修复

复现的单元测试见 #1252

**Comment by ymh199478** [comment]
@kagaya85 看下这个问题

**Comment by kagaya85** [comment]
@xuyang2 感谢反馈，这个case确实遗漏了

在env.go的33行做如下修改，只需要对Key字段做前缀匹配即可
```go
p, ok := matchPrefix(e.prefixs, envstr)
```
修改后：
```go
p, ok := matchPrefix(e.prefixs, k)
```
感谢补充case

**Comment by xuyang2** [comment]
还有，匹配并移除前缀时，是否先对 `prefixs` 按长度逆序排序一下比较好？

**Comment by kagaya85** [comment]
@xuyang2 
> 匹配并移除前缀时，是否先对 prefixs 按长度逆序排序一下比较好？

我个人觉得将匹配顺序交给使用者来决定比较好，也相对符合直觉

> 还有 prefixs 本身好像是个 typo

是的，应该是`prefixes`

**Comment by xuyang2** [comment]
@kagaya85 还有，如果传 `prefixes: []string{""}` 应该如何处理？

**Comment by kagaya85** [comment]
> @kagaya85 还有，如果传 `prefixes: []string{""}` ,
> （当有 key 有 “_” 前缀时）该如何处理？

`prefixes: []string{""}`与不使用任何前缀的效果类似，加载所有的环境变量，但是对于形如`_KEY=value`的变量会转换为`KEY: value`，符合预期，我认为可以不做任何特殊处理

同样，对于形如`_KEY=value`的变量可以通过 prefix `"_"`来选择

**Comment by xuyang2** [comment]
感觉潜规则有点多

prefix "_" 会移除两个 “_”
prefix "" 会移除一个 “_”

**Comment by kagaya85** [comment]
> prefix "" 会移除两个 “”

抱歉，这个我没有理解，是否可以举个例子

以上部分case都是在少数情况下会出现的，我不认为会出现在正常使用 env prefix 的场景中，所以我认为只需要保持原有的逻辑即可，如果有特殊的应用场景是否可以举几个例子说明？

**Comment by xuyang2** [comment]
似乎
```
prefix: "" 会移除一个 "_"
prefix: "_" 会移除两个 "_"
```

**Comment by xuyang2** [comment]
@kagaya85 
#1252 按你说的改成 `p, ok := matchPrefix(e.prefixs, k)` 了
