### ISSUE TITLE
`kratos upgrade` Add golang1.17+ surpport

### ISSUE THREAD

**Issue by czyt** [go-kratos/kratos#1253]
#### What happened:
![image](https://user-images.githubusercontent.com/19337206/126923007-e21267b7-6110-41b7-b311-312bf24c075a.png)

#### What you expected to happen:
Use `kratos upgrade `to update to the latest build
#### Anything else we need to know?:

-  [Deprecation of 'go get' for installing executables](https://golang.org/doc/go-get-install-deprecation)

#### Environment:
- Kratos version (use `kratos -v`): kratos version v2.0.1-dev
- Go version (use `go version`): go version go1.17rc1 windows/amd64
- OS (e.g: `cat /etc/os-release`): Windows 11
- Others:

**Comment by shenqidebaozi** [comment]
你版本太高了

**Comment by shenqidebaozi** [comment]
你重新安装一下kratos 工具，然后就可以了
