### ISSUE TITLE
[Question] HelloRequest does not implement protoreflect.ProtoMessage (missing ProtoReflect method)

### ISSUE THREAD

**Issue by achilsh** [go-kratos/kratos#1272]
1. env:
use new version kratos,

2. local env
in dir:    kratos/helloworld 
run cmd:  go build -o ./bin/ ./...

3. result:
api/helloworld/v1/greeter_http.pb.go:66:27: cannot use in (type *HelloRequest) as type protoreflect.ProtoMessage in argument to binding.EncodeURL:
	*HelloRequest does not implement protoreflect.ProtoMessage (missing ProtoReflect method)

4. any suggestion for above?

**Comment by tonybase** [comment]
需要升级一下 go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

**Comment by Tangruilin** [comment]
我升级了之后运行还是会报这个错误 @tonybase
