### ISSUE TITLE
make build生成版本信息时如果没有初始化git，会报错

### ISSUE THREAD

**Issue by letian0805** [go-kratos/kratos#1276]
#### What happened:
通过kratos命令创建好模板项目后，直接执行make build会报错  fatal: 不是 git 仓库

#### What you expected to happen:
make build 生成版本信息的时候不应该强依赖 git，建议如果没有初始化git的时候用时间戳做版本

#### Environment:
- Kratos version (use `kratos -v`):  v2.0.0-beta4
- Go version (use `go version`):  go1.16
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by tonybase** [comment]
直接初始化一下就可以了？
