### ISSUE TITLE
kratos命令支持指定服务注册方式[Feature]

### ISSUE THREAD

**Issue by letian0805** [go-kratos/kratos#1277]
Please see the FAQ in our main README.md before submitting your issue.

### Use case(s) - what problem will this feature solve?
目前kratos new没有参数能指定服务注册方式
### Proposed Solution
如-d consul指定consul服务注册和发现，代码生成的时候自动使用指定的注册方式

**Comment by shenqidebaozi** [comment]
这个你自己自定义 layout 就好了，后面会做类似 react-create-app 那种工具，kratos cmd 暂时不考虑增加这种功能
