### ISSUE TITLE
在中间件里怎么获取http请求的url和body

### ISSUE THREAD

**Issue by ha666** [go-kratos/kratos#1294]
使用kratos v2.0.3版本开发http应用，在中间件里，我想获取到请求的url和body里的json数据，怎么获取呢？
我试过用transport.FromServerContext，取不到。

**Comment by Windfarer** [comment]
http.FromServerContext能取到，里面有个request对象
https://go-kratos.dev/docs/component/transport/http#middleware-%E4%B8%AD%E5%A4%84%E7%90%86-http-%E8%AF%B7%E6%B1%82

**Comment by tonybase** [comment]
这个应该已经解析到 req 对象里面了，如果 io.ReadAll(body)，有可能会导致 decoder 读不到

**Comment by godsoul** [comment]
grpc-gateway 转发的http请求，我断言成http.Transport，body也是没东西的。
`rpc CreateReport (CreateReportRequest) returns (CreateReportReply){
		option (google.api.http) = {
			post: "/v1/report/index"
			body: "*"
		};
	}`
中间件代码如下
`
func Decoder(opts ...Option) middleware.Middleware {
	op := options{
		logger: log.DefaultLogger,
		handler: func(ctx context.Context, req, err interface{}) error {
			return ErrUnknownRequest
		},
	}
	for _, o := range opts {
		o(&op)
	}
	logger := log.NewHelper(op.logger)
	return func(handler middleware.Handler) middleware.Handler {
		return func(ctx context.Context, req interface{}) (interface{}, error) {
			ts,_ := transport.FromServerContext(ctx)
			if ht,ok := ts.(*http.Transport);ok{
				body, _ := ioutil.ReadAll(ht.Request().Body)
				logger.Debug(len(body))
			}
			return handler(ctx, req)
		}
	}
}`

**Comment by godsoul** [comment]
grpc-gateway 转发的http请求，我断言成http.Transport，body也是没东西的。
`rpc CreateReport (CreateReportRequest) returns (CreateReportReply){
		option (google.api.http) = {
			post: "/v1/report/index"
			body: "*"
		};
	}`
中间件代码如下
`
func Decoder(opts ...Option) middleware.Middleware {
	op := options{
		logger: log.DefaultLogger,
		handler: func(ctx context.Context, req, err interface{}) error {
			return ErrUnknownRequest
		},
	}
	for _, o := range opts {
		o(&op)
	}
	logger := log.NewHelper(op.logger)
	return func(handler middleware.Handler) middleware.Handler {
		return func(ctx context.Context, req interface{}) (interface{}, error) {
			ts,_ := transport.FromServerContext(ctx)
			if ht,ok := ts.(*http.Transport);ok{
				body, _ := ioutil.ReadAll(ht.Request().Body)
				logger.Debug(len(body))
			}
			return handler(ctx, req)
		}
	}
}`
