### ISSUE TITLE
[Question] Serving http and grpc

### ISSUE THREAD

**Issue by lightglitch** [go-kratos/kratos#1301]
It's possible to have one service with both transports? All the examples I see use one or the other.

**Comment by Windfarer** [comment]
If you generate a new project with kratos cli, you will see the default layout is use two transports. You could also take a look at the layout repo https://github.com/go-kratos/kratos-layout

**Comment by lightglitch** [comment]
Thank for pointing that out. I can see that we can pass multiple transports in the server inicialization:

`func Server(srv ...transport.Server) Option {`
