### ISSUE TITLE
JSON、XML等Response输出中的Content-Type缺少charset的默认或者自定义设置支持

### ISSUE THREAD

**Issue by mstmdev** [go-kratos/kratos#1303]
https://github.com/go-kratos/kratos/blob/e5ae8dc3f1f4eee72e52c3c05e158b4c657bdbd2/transport/http/context.go#L108-L112

JSON、XML等Response输出中的Content-Type缺少charset的默认或者自定义设置支持，v1版本中是默认设置为utf-8，某些系统对接时没有charset会有一些乱码问题

**Comment by Cluas** [comment]
> https://github.com/go-kratos/kratos/blob/e5ae8dc3f1f4eee72e52c3c05e158b4c657bdbd2/transport/http/context.go#L108-L112
> 
> JSON、XML等Response输出中的Content-Type缺少charset的默认或者自定义设置支持，v1版本中是默认设置为utf-8，某些系统对接时没有charset会有一些乱码问题

现在是可以支持设置的，c.Response().Header().Set("key",  "val")

**Comment by shenqidebaozi** [comment]
可以在 middleware 里面处理，也可以在 encoder 中处理
```go
// middleware
if tr, ok := transport.FromServerContext(ctx); ok {
    kind = tr.Kind().String()
    operation = tr.Operation()
    // 断言成HTTP的Transport可以拿到特殊信息
    if ht,ok := tr.(*http.Tranport);ok{
        // 设置请求头
    } 
}
```
```go
// encoder
// DefaultResponseEncoder encodes the object to the HTTP response.
func DefaultResponseEncoder(w http.ResponseWriter, r *http.Request, v interface{}) error {
	codec, _ := CodecForRequest(r, "Accept")
	data, err := codec.Marshal(v)
	if err != nil {
		return err
	}
	w.Header().Set("Content-Type", httputil.ContentType(codec.Name()))
        // 继续设置
	w.Write(data)
	return nil
}
```

**Comment by tonybase** [comment]
可以默认 charset 设置为 utf-8？

或者用户自己实现 Encoder。
