### ISSUE TITLE
需增添一行提示?

### ISSUE THREAD

**Issue by wnz27** [go-kratos/kratos#1304]
在这行
https://github.com/go-kratos/kratos/blob/e5ae8dc3f1f4eee72e52c3c05e158b4c657bdbd2/cmd/kratos/internal/project/new.go#L53
之前应该添加一行提示
`fmt.Println(color.WhiteString("$ go mod download"))`

**Comment by shenqidebaozi** [comment]
这个会在你 build 的时候自动下载

**Comment by wnz27** [comment]
> 这个会在你 build 的时候自动下载

  嗯嗯，然后缺啥get啥就行了，欧克欧克
