### ISSUE TITLE
用go mod拉不到文件statsHandler.go

### ISSUE THREAD

**Issue by ha666** [go-kratos/kratos#1307]
golang版本：v1.16.6
kratos版本：v2.0.3
拉不到文件：statsHandler.go
![statsHandler go文件](https://user-images.githubusercontent.com/4374328/128533085-ae3baeda-5b16-4788-a5b0-f762800826c4.png)

**Comment by shenqidebaozi** [comment]
statsHandler.go 这是啥？

**Comment by ha666** [comment]
是我的问题，statsHandler.go是v2.0.4里的功能，我用commit id拉到了。

**Comment by shenqidebaozi** [comment]
你指定最新版就行了 指定带commit 那种
