### ISSUE TITLE
[Question]helloworld

### ISSUE THREAD

**Issue by flanchegong** [go-kratos/kratos#1310]
Please see the FAQ in our main README.md before submitting your issue.
....\api\helloworld\v1\greeter_http.pb.go:66:27: cannot use in (type *HelloRequest) as type protoreflect.ProtoMessage in argument to binding.EncodeURL:
*HelloRequest does not implement protoreflect.ProtoMessage (missing ProtoReflect method)
?[31mERROR: exit status 2?[m

**Comment by Windfarer** [comment]
maybe you should upgrade your protoc-gen-go

**Comment by flanchegong** [comment]
E:\gowork\src\helloworld>kratos run
INFO msg=[gRPC] server listening on: [::]:7000
INFO msg=[HTTP] server listening on: [::]:6000

**Comment by flanchegong** [comment]
<html><!--StartFragment--><head>
  
  <meta http-equiv='Content-Type' content='text/html; charset=UTF-8'/>
  <title>mintty screen dump</title>
  <link rel='stylesheet' type='text/css' href='xterm.css'/>
  <link rel='stylesheet' type='text/css' href='mintty.css'/>
  <style type='text/css'>
  body, pre { margin: 0; padding: 0; }
  pre { font-family: inherit; }
  #vt100 {
    float: left;
    border: 0px solid;
    padding: 1px;
    line-height: 116%;
    font-size: 9pt;
    font-family: 'Lucida Console', 'Lucida Console ', 'Consolas';
    color: #BFBFBF;
    background-color: #000000;
    }
  .bd { font-weight: bold }
  .it { font-style: italic }
  .ul { text-decoration-line: underline }
  .st { text-decoration-line: line-through }
  .lu { text-decoration-line: line-through underline }
  .fg-color0 { color: #000000 } .bg-color0 { background-color: #000000 }
  .fg-color1 { color: #BF0000 } .bg-color1 { background-color: #BF0000 }
  .fg-color2 { color: #00BF00 } .bg-color2 { background-color: #00BF00 }
  .fg-color3 { color: #BFBF00 } .bg-color3 { background-color: #BFBF00 }
  .fg-color4 { color: #0000BF } .bg-color4 { background-color: #0000BF }
  .fg-color5 { color: #BF00BF } .bg-color5 { background-color: #BF00BF }
  .fg-color6 { color: #00BFBF } .bg-color6 { background-color: #00BFBF }
  .fg-color7 { color: #BFBFBF } .bg-color7 { background-color: #BFBFBF }
  .fg-color8 { color: #404040 } .bg-color8 { background-color: #404040 }
  .fg-color9 { color: #FF4040 } .bg-color9 { background-color: #FF4040 }
  .fg-color10 { color: #40FF40 } .bg-color10 { background-color: #40FF40 }
  .fg-color11 { color: #FFFF40 } .bg-color11 { background-color: #FFFF40 }
  .fg-color12 { color: #6060FF } .bg-color12 { background-color: #6060FF }
  .fg-color13 { color: #FF40FF } .bg-color13 { background-color: #FF40FF }
  .fg-color14 { color: #40FFFF } .bg-color14 { background-color: #40FFFF }
  .fg-color15 { color: #FFFFFF } .bg-color15 { background-color: #FFFFFF }
  .cursor { background-color: #BFBFBF }
  .font10 { font-family: 'F25 Blackletter Typewriter' }
  </style>
  <script>
  var b1 = 500; var b2 = 300;
  function visib (tag, state, timeout) {
    var bl = document.getElementsByName(tag);
    var vv; if (state) vv = 'visible'; else vv = 'hidden';
    var i;
    for (i = 0; i < bl.length; i++) {
      bl[i].style.visibility = vv;
    }
    window.setTimeout ('visib ("' + tag + '", ' + !state + ', ' + timeout + ')', timeout);
  }
  function setup () {
    window.setTimeout ('visib ("blink", 0, b1)', b1);
    window.setTimeout ('visib ("rapid", 0, b2)', b2);
  }
  </script>
</head>

<body onload='setup();'>
  

$ curl http://127.0.0.1:6000/helloworld/kratos                                                                           % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                         Dload  Upload   Total   Spent    Left  Speed                                          100   744  100   744    0     0  24000      0 --:--:-- --:--:-- --:--:-- 24000                                       tml>                                                                                                                                                                                                                                     500 Internal Privoxy Error                                                                                                                     pe="image/x-icon">                                                                                                                                                                                                               500 Internal Privoxy Error                                                                                    Privoxy encountered an error while processing your request:                                                     Could not load template file no-server-data or one of its inc                                       luded components.                                                                                              Please contact your proxy administrator.                                                                        If you are the proxy administrator, please put the required file(s)in the                                        de>(confdir)/templates directory.  The location of the (c                                       onfdir) directory is specified in the main Privoxy config                                       > file.  (It's typically the Privoxy install directory).
--



</body>
<!--EndFragment--></html>

**Comment by flanchegong** [comment]
curl http://127.0.0.1:6000/helloworld/kratos
500 Internal Privoxy Error

**Comment by flanchegong** [comment]
{"message":"Hello kratos"}
