### ISSUE TITLE
etcd 3.3版本服务发现存在问题

### ISSUE THREAD

**Issue by lzxhs** [go-kratos/kratos#1315]
你好，使用examples/registry/etcd/client时，发现etcd为3.3版本（如3.3.3）时，client无法从etcd中找到helloworld的服务地址，导致最终调用client.SayHello失败，报 rpc error: code = DeadlineExceeded desc = context deadline exceeded。只有重启helloworld服务后，服务发生变更，才能找到该服务。etcd 3.4.0及以上版本，不存在该问题。

这种机制造成每次需要重启下helloworld服务后，客户端才能发现服务，影响正常使用。排查下原因，3.3版本的etcd在客户端发起watch请求时，程序一直阻塞在go-kratos/etcd/registry/watcher.go下watcher的Next函数中，直到服务发生变更才收到响应，跳出阻塞，这应该是etcd 3.3版本的问题。

由于我们的etcd服务无法立刻升级到3.4版本，能否在kratos框架中兼容下etcd 3.3版本？

**Comment by yuemoxi** [comment]
3.3.15没问题 3.3.8有问题 。。。

**Comment by lzxhs** [comment]
> 3.3.15没问题 3.3.8有问题 。。。

是的，又试了下，3.3.13有问题，3.3.14正常
