### ISSUE TITLE
[Question]Config包Load时没有设置source的watcher

### ISSUE THREAD

**Issue by byteneco** [go-kratos/kratos#1318]
https://github.com/go-kratos/kratos/blob/6d06721fc8f0607bb65554e00b7ea2e997776188/config/config.go#L147
这里的Stop需要遍历watcher，但是Load的时候好像没有设置watcher。

**Comment by kagaya85** [comment]
This seems to be a bug

**Comment by longXboy** [comment]
你能提一个PR修复他吗？

**Comment by byteneco** [comment]
> 你能提一个PR修复他吗？

嗯嗯，好的。

**Comment by shenqidebaozi** [comment]
@byteneco 👏🏻👏🏻👏🏻
