### ISSUE TITLE
[Question] `make config` failed because `make` command is not recognized

### ISSUE THREAD

**Issue by seyoatda** [go-kratos/kratos#1337]
我想定义一些新的配置文件中的选项供 golang 函数读取，参考文档中实现：https://go-kratos.dev/docs/component/config
先在 protobuf 中定义，然后调用 `make config` 生成文件。但是实际上并找不到 make 这个命令。这是需要安装 cmake ? 不太清楚文档中的 make 命令从何而来。在 get-started 文档中提及的工具都已经安装了，且能正常运行 kratos run.

**Comment by fifsky** [comment]
make命令在所有unix系统都是自带的，你是什么系统？

**Comment by seyoatda** [comment]
> make命令在所有unix系统都是自带的，你是什么系统？

我在用 win10系统 。所以这个配置文件的生成在 win10 上没有解决方案吗？
PS:主要是在文档中没有看到有明确指明 get-started 实例是部署在 windows or linux。关于这块的文档建议可以完善一下。

**Comment by tonybase** [comment]
可以直接 kratos proto client . 或者 windows WSL 更好，直接安装 windows make 工具不知道是否可以
