### ISSUE TITLE
从多个源加载配置时的配置覆盖问题

### ISSUE THREAD

**Issue by letian0805** [go-kratos/kratos#1344]
#### What happened:
当使用多个config分别从配置文件、consul等多个源加载配置的时候，后面的配置会完全覆盖前面的配置，而不是增量覆盖。

比如：config.New出一个config对象，先从配置文件中加载配置，再scan到Bootstrap结构体。然后利用配置项中的consul地址，再config.New出一个config对象加载consul中的配置，再scan到同一个Bootstrap结构体。第二次scan会将第一次中的完全替换掉。

示例代码：
`

	var bc conf.Bootstrap
	c := config.New(
		config.WithSource(
			file.NewSource(flagconf),
		),
	)
	c.Load()
	c.Scan(&bc)

	// 从consul中加载配置。consul中配置是空的，结果scan后 bc 也变成空的，把前面从配置文件中加载的都清空了
	cc := config.New(
		config.WithSource(
				NewConsulSource(bc.Registry),
			),
		)

	c.Load()
	c.Scan(&bc)
`
#### What you expected to happen:
两次scan采用增量替换的方式，后面的配置增量替换前面的配置，而不是全量替换
#### How to reproduce it (as minimally and precisely as possible):
根本原因是标准库json.Unmarshal导致的，换成其他json反序列化方式
#### Environment:
- Kratos version (use `kratos -v`):kratos version v2.0.3
- Go version (use `go version`):go version go1.16 linux/amd64
- OS (e.g: `cat /etc/os-release`):ubuntu 20.04.2
- Others:

**Comment by kagaya85** [comment]
我认为全量替换目前是config的默认行为，增量替换是一个很好的建议，但是对于kratos来说很难判断哪些字段需要追加，哪些需要覆盖，kratos只能做到满足最基本的需求，如果需要增量最好还是封装一层替换逻辑实现比较好

**Comment by letian0805** [comment]
> 我认为全量替换目前是config的默认行为，增量替换是一个很好的建议，但是对于kratos来说很难判断哪些字段需要追加，哪些需要覆盖，kratos只能做到满足最基本的需求，如果需要增量最好还是封装一层替换逻辑实现比较好

这个是可以判断的啊！我看了kratos的代码，实现一个json Unmarshal 即可，通过反射来设置结构体的字段。

**Comment by kagaya85** [comment]
> 这个是可以判断的啊！我看了kratos的代码，实现一个json Unmarshal 即可，通过反射来设置结构体的字段。

抱歉，我指kratos很难从业务需要上判断当前配置项是该追加还是覆盖，很多时候远程配置覆盖本地配置是合理的需求，或者某些字段需要覆盖的同时某些需要追加，这些逻辑都是和业务强相关，不好在框架层实现。

如果我没有准确理解你的意思，希望可以补充一些例子来说明:-）

**Comment by letian0805** [comment]
> > 这个是可以判断的啊！我看了kratos的代码，实现一个json Unmarshal 即可，通过反射来设置结构体的字段。
> 
> 抱歉，我指kratos很难从业务需要上判断当前配置项是该追加还是覆盖，很多时候远程配置覆盖本地配置是合理的需求，或者某些字段需要覆盖的同时某些需要追加，这些逻辑都是和业务强相关，不好在框架层实现。
> 
> 如果我没有准确理解你的意思，希望可以补充一些例子来说明:-）

对于scan这个操作来说，只会有覆盖。这个覆盖的前提应该是：远程有值的字段才覆盖，远程没值的不做任何处理。现在这个scan的行为是：不管远程的有没有值，直接覆盖掉结构体里所有字段，这个显然是不合理的。如果为本地配置和远程配置分别再定义配置，对于用户来说显然就多了一些维护成本。

**Comment by tonybase** [comment]
这个应该是直接在 WithSource() 按优先级指定，会进行增量覆盖每个Source的配置。

**Comment by letian0805** [comment]
> 这个应该是直接在 WithSource() 按优先级指定，会进行增量覆盖每个Source的配置。
> 而不是 NewConfig 多次进行 Scan。

会存在scan两次的场景：在配置文件里配置了其他source的参数，需要先从配置文件里scan出参数，然后再用配置文件里的参数创建其他source再次scan

**Comment by pinguo-lixin** [comment]
> > 这个应该是直接在 WithSource() 按优先级指定，会进行增量覆盖每个Source的配置。
> > 而不是 NewConfig 多次进行 Scan。
> 
> 会存在scan两次的场景：在配置文件里配置了其他source的参数，需要先从配置文件里scan出参数，然后再用配置文件里的参数创建其他source再次scan

```go
var tempConfigData map[string]interface{} // 读取文件配置
config.WithSource(fromFile).Scan(&tempConfigData )

var configData map[string]interface{} // 读取文件、远程配置
config.WithSource(fromFile, fromRemote(tempConfigData["remoteConfigURL"])).Scan(&configData)
```

**Comment by letian0805** [comment]
> > > 这个应该是直接在 WithSource() 按优先级指定，会进行增量覆盖每个Source的配置。
> > > 而不是 NewConfig 多次进行 Scan。
> > 
> > 
> > 会存在scan两次的场景：在配置文件里配置了其他source的参数，需要先从配置文件里scan出参数，然后再用配置文件里的参数创建其他source再次scan
> 
> ```go
> var tempConfigData map[string]interface{} // 读取文件配置
> config.WithSource(fromFile).Scan(&tempConfigData )
> 
> var configData map[string]interface{} // 读取文件、远程配置
> config.WithSource(fromFile, fromRemote(tempConfigData["remoteConfigURL"])).Scan(&configData)
> ```

我现在就是这么用的，但感觉fromFile被scan两次不是很优雅
