### ISSUE TITLE
[Feature]支持端口复用

### ISSUE THREAD

**Issue by letian0805** [go-kratos/kratos#1349]
现在kratos是分了两个端口来支持http、grpc，希望能用cmux做端口复用，一个端口同时支持http、http2、grpc，节省端口。

**Comment by Windfarer** [comment]
It seems not necessary. A better solution is deploy your applications with containers instead of bare deployment.

**Comment by letian0805** [comment]
> It seems not necessary. A better solution is deploy your applications with containers instead of bare deployment.

Docker has host mode network, it will use host ip and port in host mode. Host mode performance is better than other modes. Reuse port will save ports in host mode. By the way, it will be easier to do service registration and discovery when reuse port.
