### ISSUE TITLE
[Question]我想知道Kratos如果做BFF如何解决结构体庞大的问题

### ISSUE THREAD

**Issue by xmsz** [go-kratos/kratos#1351]
背景
- 已有其他微服务项目
- 现在需要一个项目来当做BFF层
- 如果把所有结构全部放在`api/helloword/v1/greeter.proto`中，太庞大和不好维护了
- 然后按照正常逻辑，我想剥离出结构，例如user/order... 
- 但是我不知道怎么样才是最佳的实践方法

问题
- 如何解决BFF层逻辑结构或者服务过于复杂需要拆分的情况

其他信息
- 我看到`blog`项目，都放在一起所有没办法参考
- 我看到`beer-shop`项目，但是这个项目每个子服务都自己独立开启，不适合BFF层太麻烦了

目前的思路
- 通过文件方式剥离，然后在主文件进行整合，可以但是感觉怪怪的
- 创建多个服务，启动服务时加载全部 或者说 多个服务只需要启动一个rpc服务

**Comment by tonybase** [comment]
可以考虑按业务域进行聚合，或者流量大小的地方。

首先，web/app/weixin等等先按端拆分，然后就是按业务去抽离，或者页面流量大模块，有一些拆不掉的可以放commom。

**Comment by iamharvey** [comment]
Kratos没有这个义务帮我们来解决架构层面的很多问题。

判断一个BFF所承担的东西是否太多取决于很多因素：比如维护者是否都在一个team，比如是否符合业务架构的拆分逻辑，比如接口更新的频度是否generally一致的。

可以根据需要将一个BFF拆成若干个，这都没问题。

**Comment by fifsky** [comment]
我理解楼主的痛点，我们现在就是前提拆分的时候，我们还不太想将每一个service都独立部署，因此我们将App 和 serviceInstance修改为一对多的关系，在同一个部署RPC Server里面注册多个service，并且他们都有自己独立的serviceName，即便将来需要独立部署，也非常方便，只要保持serviceName不变即可，而现在serviceName=appName，是恒定的一对一的关系，因此只能重写App

```go
// App is an application components lifecycle manager.
type App struct {
	opts      options
	ctx       context.Context
	cancel    func()
	instances []*registry.ServiceInstance  // 这里我们修改了结构为slice
}
```

```go
func (a *App) buildInstance() ([]*registry.ServiceInstance, error) {
	var endpoints []string
	for _, e := range a.opts.endpoints {
		endpoints = append(endpoints, e.String())
	}
	if len(endpoints) == 0 {
		for _, srv := range a.opts.servers {
			if r, ok := srv.(transport.Endpointer); ok {
				e, err := r.Endpoint()
				if err != nil {
					return nil, err
				}
				endpoints = append(endpoints, e.String())
			}
		}
	}

	svcInstances := make([]*registry.ServiceInstance, 0)

	for _, v := range a.opts.services {   // 这里我们注入进来的services循环生成registry.ServiceInstance，但使用service自己的名称
		svcInstances = append(svcInstances, &registry.ServiceInstance{
			ID:        a.opts.id,
			Name:      v.Name(), //  使用service自己的名称，而非AppName
			Version:   a.opts.version,
			Metadata:  a.opts.metadata,
			Endpoints: endpoints,
		})
		a.opts.logger.Infof("[service] register service: %s to endpoints: %v", v.Name(), endpoints)
		v.Register()
	}

	return svcInstances, nil
}
```

最后在Run和Stop里面分别循环注册和注销服务发现即可，仅供参考
