### ISSUE TITLE
怎么做301或302跳转

### ISSUE THREAD

**Issue by ha666** [go-kratos/kratos#1366]
使用kratos做http服务
怎么在rpc接口里做http的301、302跳转？

**Comment by shenqidebaozi** [comment]
可以使用http filter service 层没有这个。

**Comment by ha666** [comment]
感谢，已解决。

**Comment by victory460** [comment]
> 感谢，已解决。

请教下，你是如何解决的哇？@ha666

**Comment by whtiehack** [comment]
> > 感谢，已解决。
> 
> 请教下，你是如何解决的哇？@ha666

https://github.com/go-kratos/kratos/pull/1807
