### ISSUE TITLE
[Question] bbr中cpu的含义

### ISSUE THREAD

**Issue by jordandandan** [go-kratos/kratos#1372]
求教bbr当中limit的条件是cpu > 800 AND (Now - PrevDrop) < 1s AND (MaxPass * MinRt * windows / 1000) < InFlight，根据代码看到cpu usage是 u = uint64(float64((total-cpu.preTotal)*cpu.cores*1e3) / (float64(system-cpu.preSystem) * cpu.quota))，这个数值的含义指的什么，为什么不是一个比例，比如0.9

**Comment by kagaya85** [comment]
确实是一个比例，这里应该是为了保留小数，放大为了整数

**Comment by uucloud** [comment]
total来自cgroup用户进程cgroup cpuacct/cpuacct.usage，这个值是该层cgroup总纳秒；

system来自/proc/stat cpu 第一行去掉guest累加换算，(系统总jiffies-guest) / _SC_CLK_TCK * 1e9，即系统总耗时纳秒；

cores来自sysctl或者cpuinfo，即看到的主机逻辑核；

quota来自核数，如果进程在子cgroup内，会用cgroup cpu限制(limit/quota)替换，相当于容器核数。

所以这个表达式的含义就是业务进程单核cpu使用率 x 1000：

![mylatex20210908_131919](https://user-images.githubusercontent.com/13742734/132450934-a1c66e93-7f5c-49bc-a287-dd451b9704ea.png)

**Comment by jordandandan** [comment]
> total来自cgroup用户进程cgroup cpuacct/cpuacct.usage，这个值是该层cgroup总纳秒；
> 
> system来自/proc/stat cpu 第一行去掉guest累加换算，(系统总jiffies-guest) / _SC_CLK_TCK * 1e9，即系统总耗时纳秒；
> 
> cores来自sysctl或者cpuinfo，即看到的主机逻辑核；
> 
> quota来自核数，如果进程在子cgroup内，会用cgroup cpu限制(limit/quota)替换，相当于容器核数。
> 
> 所以这个表达式的含义就是业务进程单核cpu使用率 x 1000：
> 
> ![mylatex20210908_131919](https://user-images.githubusercontent.com/13742734/132450934-a1c66e93-7f5c-49bc-a287-dd451b9704ea.png)

感谢大神回答，刚才又看了下源码，中间那个是除号
		u = uint64(float64((total-cpu.preTotal)*cpu.cores*1e3) / (float64(system-cpu.preSystem) * cpu.quota))

**Comment by uucloud** [comment]
> > total来自cgroup用户进程cgroup cpuacct/cpuacct.usage，这个值是该层cgroup总纳秒；
> > system来自/proc/stat cpu 第一行去掉guest累加换算，(系统总jiffies-guest) / _SC_CLK_TCK * 1e9，即系统总耗时纳秒；
> > cores来自sysctl或者cpuinfo，即看到的主机逻辑核；
> > quota来自核数，如果进程在子cgroup内，会用cgroup cpu限制(limit/quota)替换，相当于容器核数。
> > 所以这个表达式的含义就是业务进程单核cpu使用率 x 1000：
> > ![mylatex20210908_131919](https://user-images.githubusercontent.com/13742734/132450934-a1c66e93-7f5c-49bc-a287-dd451b9704ea.png)
> 
> 感谢大神回答，刚才又看了下源码，中间那个是除号
> u = uint64(float64((total-cpu.preTotal)_cpu.cores_1e3) / (float64(system-cpu.preSystem) * cpu.quota))

嗯，修改了
