### ISSUE TITLE
yaml 解析错误

### ISSUE THREAD

**Issue by overcls** [go-kratos/kratos#1373]
data:
  database:
    driver: mysql
    host: 127.0.0.1:3306
    username: root
    password: "acdd$REcId"

配置文件是yaml在v2版本读取数据会把$后面的字符截取掉 变成acdd

这个怎么处理

**Comment by ymh199478** [comment]
将密码放置到环境变量中可以解决这个问题。

配置底层使用了 `os.Expand` 来识别占据的变量，并将其替换为环境变量。目前没有提供任何转义字符：https://github.com/golang/go/issues/43482

您不应该将密码直接放置到配置文件中（通常配置会被提交到git仓库），这是不安全的。

**Comment by Windfarer** [comment]
字符串里有$的问题应该还挺常见的吧，想想办法

**Comment by ymh199478** [comment]
有 2 个解决方案：

- 使用自定义的 resolver 来解决
- 我们从 os 里抠出 Expand 的代码为它添加转义字符的功能

**Comment by kagaya85** [comment]
可以考虑增加一下转义的功能
