### ISSUE TITLE
[Notice] 关于部分依赖仓库调整的说明 | The modification of package dependencies

### ISSUE THREAD

**Issue by shenqidebaozi** [go-kratos/kratos#1386]
为了将分散的仓库统一管理，并且减少框架自身依赖，最近对于 kratos 的部分依赖仓库进行了调整

In order to uniformly manage the decentralized warehouses and reduce the dependence of the framework itself, some dependent warehouses of Kratos have been adjusted recently

### Registry
- github.com/go-kratos/nacos/registry -> github.com/go-kratos/kratos/contrib/registry/nacos/v2
- github.com/go-kratos/etcd/registry -> github.com/go-kratos/kratos/contrib/registry/etcd/v2
- github.com/go-kratos/consul/registry -> github.com/go-kratos/kratos/contrib/registry/consul/v2
- github.com/go-kratos/kube/registry -> github.com/go-kratos/kratos/contrib/registry/kubernetes/v2
- github.com/go-kratos/zookeeper/registry -> github.com/go-kratos/kratos/contrib/registry/zookeeper/v2
### Metrics
- github.com/go-kratos/prometheus/metrics -> github.com/go-kratos/kratos/contrib/metrics/prometheus/v2
- github.com/go-kratos/datadog/metrics -> github.com/go-kratos/kratos/contrib/metrics/datadog/v2
### Config
- github.com/go-kratos/kube/config ->github.com/go-kratos/kratos/contrib/config/kubernetes/v2
### Other
- log.SpanID -> tracing.SpanID
- log.TraceID -> tracing.TraceID

**Comment by Windfarer** [comment]
Maybe we should upgrade every legacy repos, add deprecated information to them.

**Comment by Dongss** [comment]
给跪了！！
