### ISSUE TITLE
能否支持下终端的智能提示？[Feature]

### ISSUE THREAD

**Issue by liuwangchen** [go-kratos/kratos#1390]
bashcomplete
zshcomplete

**Comment by Casper-Mars** [comment]
For `zsh`:

1. echo "autoload -U compinit; compinit" >> ~/.zshrc
2. kratos completion zsh > "${fpath[1]}/_kratos"

ref:[cobra-complete](https://github.com/spf13/cobra/blob/master/shell_completions.md)

**Comment by liuwangchen** [comment]
可以可以
