### ISSUE TITLE
errors包 Code 和 Reason方法实现细节个人觉得有点问题。

### ISSUE THREAD

**Issue by wwwhaoxu** [go-kratos/kratos#1392]
原方法：
func Code(err error) int {
	if err == nil {
		return 200
	}
	if se := FromError(err); err != nil {
		return int(se.Code)
	}
	return UnknownCode
}
建议：修改 err != nil 为 se != nil
func Code(err error) int {
	if err == nil {
		return 200
	}
	if se := FromError(err); se != nil {
		return int(se.Code)
	}
	return UnknownCode
}

Reason 方法类似哈！！！

**Comment by shenqidebaozi** [comment]
直接提PR就可以了
