### ISSUE TITLE
[Question] Why does grpc server not open the configuration of health Serveroption?

### ISSUE THREAD

**Issue by pinguo-lixin** [go-kratos/kratos#1397]
我们期望在 GRPC Server 的健康检查中实现一些自定义的逻辑，用以更加可靠地实现 health， ready 探测，但发现没有提供相应的 ServerOption，以致无法注入自定义的逻辑。

请问：出于什么考虑，没有通过 ServerOption 开放对 health 的配置？

https://github.com/go-kratos/kratos/blob/main/transport/grpc/server.go#L118

**Comment by tonybase** [comment]
目前是实现了官方默认的 health server，自定义需要装配进来才可以，直接注册重复的 server 不知道是否可以。

实现自定义的 health proto，或者通过 HTTP health 接口也可以。

**Comment by letian0805** [comment]
> 目前是实现了官方默认的 health server，自定义需要装配进来才可以，直接注册重复的 server 不知道是否可以。
> 
> 实现自定义的 health proto，或者通过 HTTP health 接口也可以。

你说的注册重复的server，是指gRPC的service吧？重复注册相同的service是不行的，需要自己实现一个然后装配进去

**Comment by yuchen-sun** [comment]
@tonybase 那么是否可以增加对health的option操作？

**Comment by herealways** [comment]
这个Issue还会更新吗？试了一下自定义的health proto 不能用grpc_health_probe来healthcheck

https://github.com/grpc-ecosystem/grpc-health-probe
