### ISSUE TITLE
定期偶现服务频繁查询etcd，引起流量暴增

### ISSUE THREAD

**Issue by lzxhs** [go-kratos/kratos#1400]
**背景**
服务A基于registry向etcd注册，服务B通过etcd自动发现服务A。一开始，服务B能正常发现A，运行一段时间后，由于未知原因，etcd集群突然查不到服务A的节点信息（服务A和etcd的grpc连接还在），随后服务B开始频繁向etcd查询服务A节点，etcd正常返回（但返回节点内容为空），引起服务B和etcd集群的网络、CPU、内存占用率暴增。重启服务B后，恢复正常，但会定期出现该现象

服务B网络I/O：
![截屏2021-08-31 下午5 41 49](https://user-images.githubusercontent.com/16593834/131480518-0bb414e0-2d6d-4651-b0f5-4c676917f7e8.png)

服务B CPU：
![截屏2021-08-31 下午5 43 21](https://user-images.githubusercontent.com/16593834/131480712-47afeae2-fe96-4d12-abcd-600f39718345.png)

服务B内存：
![截屏2021-08-31 下午5 43 51](https://user-images.githubusercontent.com/16593834/131480778-607f94a1-315b-4321-8e73-187b1bbe0d05.png)

etcd集群频繁打印：
etcdserver: read-only range request "key:"/grpc/xxx" range_end:"/grpc/xxx" " took too long (630.016437ms) to execute

**版本**
服务A：kratos@v2.0.0-rc1、kratos-etcd@v0.1.0
服务B：kratos@v2.0.0、kratos-etcd@v0.1.3
etcd集群：v3.3.5

**问题**
服务A掉线后（连接还在），服务B频繁查询etcd，引起资源消耗突增，可能是Bug引起的，麻烦排查下；另外，服务A运行一段后经常异常掉线，也很令人费解

**Comment by longXboy** [comment]
这个已经修复了，请升级到kratos v2.0.5

**Comment by lzxhs** [comment]
好的，我升级试下，多谢
