### ISSUE TITLE
[Question] 关于 更新接口 的问题

### ISSUE THREAD

**Issue by zs368** [go-kratos/kratos#1407]
背景

- 一个更新接口，里面有多个字段，我只需要更新一个字段，其它是否需要填写？

问题

- 看了下 examples/blog ，发现有个问题，api 未对 content 字段做限制，当我只传入 title 字段进行更新时，原先的 content 会被修改为空。

复现步骤

1. 运行 examples/blog
2. 创建一个 article ，示例 {"title": "zs666", "content": "777"}
3. 更新刚创建的 article，示例 {"title":"zs777"}
4. 此时 article 就会变为 {"title":"zs777", "content": ""}

目前的思路

1. ent 是有 Nillable() 字段类型的，可以使用这一个，会生成一个 SetNillable... 方法，但是这样要修改 biz 中的 Article 中的字段为对应的指针类型，有点不爽。
2.  在 biz 中新增一个 UpdateArticle struct，里面只放需要更新的字段，全部为 对应的指针类型
3. 在 api 更新接口中，把字段都设为必填

**Comment by shenqidebaozi** [comment]
这个貌似不是 kratos 的问题。更像是业务做法。

**Comment by zs368** [comment]
对，业务规范，我还是选3吧
