### ISSUE TITLE
[Feature] Export mergo option to developer 

### ISSUE THREAD

**Issue by woorui** [go-kratos/kratos#1414]
https://github.com/go-kratos/kratos/blob/a78f740bd50b7c5e6d1bb6baaa31e03f8219f628/config/reader.go#L50

Is it possible to export `mergo.WithOverride` to developer ? I want to use `mergo.WithAppendSlice`.

**Comment by shenqidebaozi** [comment]
@kagaya85 @ymh199478 PTAL.

**Comment by shenqidebaozi** [comment]
这个配置不应该全部暴露出来，应该看看需要哪些

**Comment by woorui** [comment]
1. WithOverride，WithOverwriteWithEmptyValue, WithOverrideEmptySlice 算三种不同的 override 方式
2. WithAppendSlice 算 append 的方式
3. WithTypeCheck 类型检查
4. WithSliceDeepCopy 是深拷贝
一共就这6种option，选项 1 和 2 的可以暴露出来？3 和 4暴露出来感觉也没啥问题

**Comment by tonybase** [comment]
WithAppendSlice，不太好，应该配置中心里面配置的值是怎么样，进行apply时跟配置一致

**Comment by woorui** [comment]
> WithAppendSlice，不太好，应该配置中心里面配置的值是怎么样，进行apply时跟配置一致

说一下我目前遇到的问题吧，目前我写的后端服务，需要支撑10多个甚至更多的app，每个app都会对应一个很大的配置文件，我期望把每个app的配置分开放，而不是把这么多的配置放在一个文件里，不好维护，也容易出问题

**Comment by tonybase** [comment]
配置模块化，也应该是根据配置类型，不同的 prefix key 进行拆分的。

并且，应该按 config key = [array]，以配置内容是怎么样的，mapping 到 struct 就应该怎么样的。而不是一直append，可能会导致 dirty value 问题

**Comment by woorui** [comment]
我明白了，我这个需求可以调用 `config.WithDecoder` api实现

merge option 这个，现在框架默认都是 `WithOverride` 这种行为，以 file的文件夹形式为例，后扫描到的文件配置，不管是否为空，都会覆盖之前扫描到的配置，框架只支持这种默认行为。那是否将 merge option 开放给用户，将 `WithOverride` 作为默认值更好一些，框架感更强一些

**Comment by kagaya85** [comment]
related issue #1344
