### ISSUE TITLE
[BUG]Router bug in HTTP transport

### ISSUE THREAD

**Issue by letian0805** [go-kratos/kratos#1419]
#### What happened:
In `NewServer`
```golang
	srv.Server = &http.Server{
		Handler:   FilterChain(srv.filters...)(srv),
		TLSConfig: srv.tlsConf,
	}
	srv.router = mux.NewRouter()
	srv.router.Use(srv.filter())
```
```golang
func (s *Server) ServeHTTP(res http.ResponseWriter, req *http.Request) {
	s.router.ServeHTTP(res, req)
}
```
When using `ServeHTTP` directly,  will make some routers not work.
#### What you expected to happen:
Router work well when using `ServeHTTP` directly.
#### How to reproduce it (as minimally and precisely as possible):
Set filters and routers, then use `ServeHTTP` directly.
#### Anything else we need to know?:
First, change `NewServer`
```golang
	srv.router = mux.NewRouter()
	srv.router.Use(srv.filter())
	srv.Server = &http.Server{
		Handler:   FilterChain(srv.filters...)(srv.router),
		TLSConfig: srv.tlsConf,
	}
```
Second, change `ServeHTTP`
```golang
func (s *Server) ServeHTTP(res http.ResponseWriter, req *http.Request) {
	s.Handler.ServeHTTP(res, req)
}
```
#### Environment:
- Kratos version (use `kratos -v`):
- Go version (use `go version`):
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by dy201** [comment]
围观大佬，我看过你的 seckill 课程 。
