### ISSUE TITLE
[Help Wanted] fix lint check failures

### ISSUE THREAD

**Issue by kagaya85** [go-kratos/kratos#1430]
After PR #1401 merged, many of our sub modules are failing lint, we should fix all of them.

To fix these, take a look at [hack/.lintcheck_failures](https://github.com/go-kratos/kratos/blob/main/hack/.lintcheck_failures) for a list of currently lint failed modules.

You can check a module by removing it from the `.lintcheck_failures` list and running `make fix` to auto fix some lint errors.

If the module is no longer failing, please file a PR including the fixes and removing it from the list.

Before filing your PR, you should run `make lint` to check your code is already fixed and please keeping PRs scoped down in size for review, fix a package or set of closely related package.

**NOTICE:** 
* Do not use `fixes #...` in your PR, that will close this PR. Instead put something like `part of #1430`
* To attract more contributors in our community, I recommend letting new contributors do this as much as possible

Modules should be fixed:
- [x] ./examples https://github.com/go-kratos/kratos/pull/1454
- [x] ./cmd/protoc-gen-go-errors https://github.com/go-kratos/kratos/pull/1435
- [x] ./cmd/protoc-gen-go-http https://github.com/go-kratos/kratos/pull/1440
- [x] ./cmd/kratos https://github.com/go-kratos/kratos/pull/1442
- [x] ./contrib/metrics/datadog https://github.com/go-kratos/kratos/pull/1517
- [x] ./contrib/config/nacos https://github.com/go-kratos/kratos/pull/1522
- [x] ./contrib/config/apollo https://github.com/go-kratos/kratos/pull/1523
- [x] ./contrib/config/kubernetes https://github.com/go-kratos/kratos/pull/1523
- [x] ./contrib/registry/nacos https://github.com/go-kratos/kratos/pull/1599
- [x] ./contrib/registry/consul https://github.com/go-kratos/kratos/pull/1530
- [x] ./contrib/registry/kubernetes https://github.com/go-kratos/kratos/pull/1599
- [x] ./contrib/registry/zookeeper https://github.com/go-kratos/kratos/pull/1599
- [x] ./contrib/registry/etcd https://github.com/go-kratos/kratos/pull/1441
- [x] ./contrib/log/fluent https://github.com/go-kratos/kratos/pull/1432

**Comment by ShawnAli97** [comment]
Hello I am new to this community. Can I make a attempt at fixing a module?

**Comment by kagaya85** [comment]
> Hello I am new to this community. Can I make a attempt at fixing a module? 

feel free to do it🙌

**Comment by kagaya85** [comment]
All tasks done, thanks to everyone who participated in contributing!
