### ISSUE TITLE
Proto http路径bug

### ISSUE THREAD

**Issue by dy201** [go-kratos/kratos#1433]
#### What happened:
proto文件定义的http访问路径不能被解析

在user.proto中定义

```proto
  rpc GetUserList(GetUserListReq) returns (GetUserListReply) {
    option (google.api.http) = {
      get: "/admin/user/list"
    };
  }
```

访问该路径 `http://localhost:8080/admin/user/list` 时，报错 `{"code":500, "reason":"", "message":"parsing field \"id\": strconv.ParseUint: parsing \"list\": invalid syntax", "metadata":{}}`

当我把上述代码中的 `/admin/user/list` 改为`/admin/users`或其它路径时，即恢复正常，我反复测了好几次。

能力有限，我没有深入去探查，我觉得是个bug，所以提交上来了。

#### Environment:
- Kratos version (v2.0.5):
- Go version (go 1.15):
- OS (win 10):

**Comment by shenqidebaozi** [comment]
是否跟其他路由冲突了呢？

**Comment by yuemoxi** [comment]
我试了一下是可以的 你看下是不是路由冲突了 要不然把问题传到你自己的仓库

**Comment by dy201** [comment]
@yuemoxi  好的，晚上我把代码传到仓库。 @shenqidebaozi  谢谢包子giegie和月墨夕两位大佬。

**Comment by dy201** [comment]
我把出现问题的代码提交了，地址：https://github.com/dy201/krato-demo

**Comment by yuemoxi** [comment]
![image](https://user-images.githubusercontent.com/57396775/132322691-b78a942c-1bb9-475d-8616-2b04499b44a8.png)
当 路由是 ”/admin/user/list“ 是 和这个冲突了 有可能id是list

**Comment by dy201** [comment]
好的，那这个算不算是个bug呢？

还有就是想请教一下，这个要在哪里打断点去调试。

**Comment by dy201** [comment]
这个是根据之前java的blog项目改的，java没有这个问题，所以会不会是个bug呢，还有就想请教一下大佬，这个怎么打断点调试。



***@***.***
 
发件人： yuemoxi
发送时间： 2021-09-07 17:40
收件人： go-kratos/kratos
抄送： Doyle Liang; Manual
主题： Re: [go-kratos/kratos] Proto http路径bug (#1433)

当 路由是 ”/admin/user/list“ 是 和这个冲突了 有可能id是list
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yuemoxi** [comment]
这个不是bug，就是路由冲突。一个提示已经挺明显的了，id不能绑定"list"

**Comment by dy201** [comment]
好的，非常感谢。

**Comment by dy201** [comment]
总结一下：

我有两个路由(按先后顺序)
 - `get: "/admin/user/{id}"`
 - `get: "/admin/user/list"`

访问的时候 list 被解析为 id，失败了，我的处理方法是把路由的名字改了。我觉得这个不太合理，希望后面有大佬可以提供更好的思路，或者是前面的同学已经讲明白了，而我没有听懂。
