### ISSUE TITLE
[Feature]Support H2C transport

### ISSUE THREAD

**Issue by letian0805** [go-kratos/kratos#1445]
### What problem is the feature used to solve?

H2C is faster than http1.1
### Requirements description of the feature

In high-concurrency business scenarios, HTTP1.1 is easy to reach the performance bottleneck, using HTTP2 can get a better performance experience

**Comment by kagaya85** [comment]
Hi @letian0805, I have a question about this, if we only consider the performance experience, we can simply use grpc as kratos transport, is there any other benifits or requirements to support this feature?

**Comment by letian0805** [comment]
> Hi @letian0805, I have a question about this, if we only consider the performance experience, we can simply use grpc as kratos transport, is there any other benifits or requirements to support this feature?

@kagaya85  Migrating from http to grpc has major changes, while migrating to h2c has minor changes. For a large number of existing http services, the benefits of migrating to h2c are greater.

**Comment by haiyux** [comment]
Not supported at the moment
