### ISSUE TITLE
[kratos/examples/blog]go mod tidy 

### ISSUE THREAD

**Issue by flanchegong** [go-kratos/kratos#1455]
go: github.com/go-kratos/kratos/examples@v0.0.0-20210909024053-b38c1145cf5a requires
        github.com/go-kratos/kratos/contrib/metrics/prometheus/v2@v2.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000

**Comment by flanchegong** [comment]
set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=C:\Go\bin
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=-mod=mod
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=E:\gowork\pkg\mod
set GONOPROXY=*.gitlab.com
set GONOSUMDB=*.gitlab.com
set GOOS=windows
set GOPATH=E:\gowork
set GOPRIVATE=*.gitlab.com
set GOPROXY=https://goproxy.cn,direct
set GOROOT=E:\gowork\go1.16.5
set GOSUMDB=off
set GOTMPDIR=
set GOTOOLDIR=E:\gowork\go1.16.5\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.5
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=E:\gowork\src\kratos\examples\blog\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build4083150288=/tmp/go-build -gno-record-gcc-switches

**Comment by flanchegong** [comment]
cd blog/cmd/blog，
go build
./blog -conf ../../configs
[linux环境有效]

**Comment by Cluas** [comment]
> go: github.com/go-kratos/kratos/examples@v0.0.0-20210909024053-b38c1145cf5a requires
> github.com/go-kratos/kratos/contrib/metrics/prometheus/v2@v2.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000

看日志看起来你拉错版本了 拉的不是krotos v2
