### ISSUE TITLE
[Question] data层

### ISSUE THREAD

**Issue by Mrliu8023** [go-kratos/kratos#1468]
data 层不太好用不同的数据库引擎。  代码生成的时候能否做成接口的形式。

**Comment by shenqidebaozi** [comment]
没明白，data 是用于初始化数据的。实际查询都是实现的 biz 接口

**Comment by Mrliu8023** [comment]
就是   `biz` 接口可以有多个实现，在`data`包里面如何去组织多个实现呢？

**Comment by shenqidebaozi** [comment]
可以看下 beershop

**Comment by Mrliu8023** [comment]
emm,我看了，每个`data`包里面也只有一个`repo`实现。 我的意思是，就比如说我现在有一个`repo`需要用`gorm`, 也想用`ent`,或者`mongodb`,那么`Data`里面就会至少有三个`client`，在这可以把这三个`client`做成接口，但就感觉又套了一层。。。想问问这种场景怎么去做比较好？

**Comment by pokitpeng** [comment]
如果biz接口需要同时使用三个数据库，那么可以尝试将这三个client都放到一个data实例里面去。如果是当前biz接口使用mongo，未来需要替换为ent，那么建议分开，然后这两个repo去实现biz接口。

**Comment by Mrliu8023** [comment]
嗯嗯，好的。 谢谢
