### ISSUE TITLE
[Feature] support discovery registry center

### ISSUE THREAD

**Issue by yeqown** [go-kratos/kratos#1472]
Please see the FAQ in our main README.md before submitting your issue.

### What problem is the feature used to solve?

We hope to add `discovery` registry center `registry.Registrar`  to Kratos framework.

### Requirements description of the feature

* support `discovery` registry center works as `registry.Registrar` in kratos

### References

* https://github.com/bilibili/discovery

**Comment by seasrain** [comment]
Are you going to finish it? or do you want us to finish it?

**Comment by seasrain** [comment]
Would you like to submit a PR to complete it?

**Comment by yeqown** [comment]
let me try it, hah ~
