### ISSUE TITLE
middleware default code issues

### ISSUE THREAD

**Issue by woorui** [go-kratos/kratos#1479]
https://github.com/go-kratos/kratos/blob/24ec23f0e41676bfe9726ce612005ac5ab85d67c/middleware/logging/logging.go#L19

https://github.com/go-kratos/kratos/blob/24ec23f0e41676bfe9726ce612005ac5ab85d67c/middleware/metrics/metrics.go#L47

最近对接了日志系统和metrics，查询http的正常请求（httpcode=200）的时候，查询不到数据，看了代码发现这两个地方 code 的默认值都是 0，是否有必要提供一个方法改变这个默认值啊

**Comment by shenqidebaozi** [comment]
emmm。那需要你自己复制中间件代码然后修改下，因为这个是跟 grpc 同构的，code 0 代表的是 grpc 的请求成功

**Comment by woorui** [comment]
ok
