### ISSUE TITLE
怎么获取客户端真实IP

### ISSUE THREAD

**Issue by a245589351** [go-kratos/kratos#1482]
怎么获取客户端真实IP

**Comment by tonybase** [comment]
可以通过  middleware 加上设备信息获取的，比如 DeviceMetadata，然后统一放到 NewContext(ctx, info) 里面，通过 FromContext(ctx) 取出来使用。

**Comment by shenqidebaozi** [comment]
断言 req 然后有个 ip 方法，如果反代了，nginx 配置，然后从 header 取
