### ISSUE TITLE
[Feature] 去除Endpoint()副作用

### ISSUE THREAD

**Issue by longXboy** [go-kratos/kratos#1494]
现在Endpointer接口的Endpoint方法调用时会产生副作用

1.取消Endpointer接口，直接通过Start返回真实的ip和port，这样需要将server.Start改造成异步非阻塞的
2.删除随机端口机制 ，app层可以直接拿到实际的ip和port，这样真实地址和server层无关了

以上这两种方案都会产生breakchange,需要讨论一下，欢迎补充其他方案

**Comment by seasrain** [comment]
3. 删除随机端口机制 在start里listen

**Comment by longXboy** [comment]
@letian0805

**Comment by letian0805** [comment]
4. 给server添加一个Init函数，在app里先调用Init函数，初始化listener和endpoint并返回error结果。成功后再调用Start、Endpoint。这样应该没有breakchange。任何时候，如果没有调用Init，Endpoint应该返回空，防止将异常的server注册到服务注册中心。

**Comment by letian0805** [comment]
不管哪个，建议都删除随机端口机制，这个是个坑

**Comment by seasrain** [comment]
删除端口随机集群吧 目前应该没人用
1. 在docker/k8s 中 不能对外暴露接口
2. 如果不用docker这套  应该不是微服务 不会用服务注册机制 也就不会用随机端口

**Comment by letian0805** [comment]
5.如果在New函数里传address，其实我更倾向于在New函数里就初始化listener，如果listen失败直接panic，将错误前置，后面更好处理，后面的基本都不用动，只需要移除endpoint里的副作用代码

**Comment by Windfarer** [comment]
随机端口挺好的呀，裸部署挺方便

**Comment by haiyux** [comment]
feat  #1729
