### ISSUE TITLE
apollo just can use default namespace

### ISSUE THREAD

**Issue by wangle201210** [go-kratos/kratos#1502]
#### What happened:
配置中心选择使用apollo时，无论namespace怎么填写都只能获取到application的配置
#### What you expected to happen:
配置apollo.WithNamespace("name")后，能生效
#### Environment:
- Kratos version (use `kratos -v`): v2.0.3
- Go version (use `go version`):  go version go1.15.4 darwin/amd64

**Comment by yeqown** [comment]
我提交了一个版本，是类似于file 插件的处理方式：
https://github.com/yeqown/kratos/commit/65243a46a0c3bf1f03e38dbe5304e37d595a0bc6?branch=65243a46a0c3bf1f03e38dbe5304e37d595a0bc6&diff=split

变更清单：
- 每一个 namespace 作为一个文件，也就是一个key； namespace 的内容作为 value
- 更换了 apollo 客户端，这样可以获取到 namespace 的原始内容
