### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by lengyue1084** [go-kratos/kratos#1513]
本地拉取的框架文件，github.com\go-kratos\kratos\v2@v2.0.5\middleware\selector\selector.go
不包含文档中中间件描述的：
“Match(fn) 函数匹配,函数格式为func(operation string) bool,operation为path,函数返回值为true,匹配成功”方法。
主分支中是有的地址：https://github.com/go-kratos/kratos/blob/main/middleware/selector/selector.go

本地显示的版本kratos version v2.0.5

**Comment by shenqidebaozi** [comment]
特性没有 release，如果要体验可以依赖 latest
