### ISSUE TITLE
[Question]errors/errors.proto:10:1: Import "google/protobuf/descriptor.proto" was not found or had errors.

### ISSUE THREAD

**Issue by zt102545** [go-kratos/kratos#1514]
有没有哪位老哥告诉我这个proto的include文件到底应该放在哪个目录下，执行go generate ./...才会被找到啊？？？一直提示找不到，gopath路径下下放了也没用
![image](https://user-images.githubusercontent.com/23187595/134777672-cfa6164c-bb94-405b-934b-eeac00224e6b.png)

![image](https://user-images.githubusercontent.com/23187595/134777721-2873b69f-142b-4647-8b41-723a2891c870.png)

$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Administrator\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Administrator\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.1
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=F:\DEMO\ZZT\ZZTGit\ZZTKratos\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build403041375=/tmp/go-build -gno-record-gcc-switches

**Comment by overstarry** [comment]
可能要添加到环境变量

**Comment by zt102545** [comment]
![image](https://user-images.githubusercontent.com/23187595/134791187-c2640bc0-18d4-4d2f-858f-dad4fa581cf9.png)
自己试了一下把文件放到该目录下就可以了，官方文档并没有说明这一点

**Comment by overstarry** [comment]
不用啊

**Comment by shenqidebaozi** [comment]
FAQ 里面有描述这个问题。https://go-kratos.dev/docs/intro/faq
