### ISSUE TITLE
[Question] 为什么config不考虑key被删除情况？

### ISSUE THREAD

**Issue by optimistic9527** [go-kratos/kratos#1515]
当加载一个配置文件后，第二次加载时部分key被删除，但是config无法感知被删除的key，被删除的key的数据依旧可以查询到老的值

**Comment by shenqidebaozi** [comment]
程序运行中，配置消息会对程序造成影响吧？

**Comment by optimistic9527** [comment]
> 程序运行中，配置消失会对程序造成影响吧？

嗯，可以从业务角度避免
