### ISSUE TITLE
在使用grpc调用服务时提示超时context deadline exceeded

### ISSUE THREAD

**Issue by a245589351** [go-kratos/kratos#1525]
我有两个服务A，B，其中这两个服务的HTTP与GRPC超时时间都设为了100s，但是通过HTTP调用A，A通过GRPC调用B时，只要B的耗时超过2s，B就会抛出context deadline exceeded

问：是使用的姿势不对么？

**Comment by seasrain** [comment]
设置client超时时间了吗？

**Comment by a245589351** [comment]
没设置，client拨号时候直接用的context.Background()

**Comment by seasrain** [comment]
https://github.com/go-kratos/kratos/blob/74e630c21a5bd8c7e28d893131f5df5e21470ece/transport/grpc/client.go#L115 默认是有2s的 用withTimeout 设置一下

**Comment by a245589351** [comment]
解决问题了，谢谢

**Comment by An-uking** [comment]
> 解决问题了，谢谢

请问怎么解决的，我也遇到了这个问题

**Comment by deepX95** [comment]
> > 解决问题了，谢谢
> 
> 请问怎么解决的，我也遇到了这个问题
client 那里加个grpc.WithTimeout 配置
	conn, err := grpc.DialInsecure(
		context.Background(),
		grpc.WithEndpoint(addr),
		grpc.WithTimeout(time.Minute),
	)
