### ISSUE TITLE
[Question] 求助，这是一个关于通过 wire . 生成 wire_gen.go 的问题

### ISSUE THREAD

**Issue by guowei-gong** [go-kratos/kratos#1527]
描述：在我的项目下，执行 wire . ，它提示了如下错误，我已经尽力去查找究竟是什么原因了，但还是没有结果，这个报错信息也没有提供任何帮助。
![image](https://user-images.githubusercontent.com/62499904/135206611-ed4e013f-aead-4fff-b78a-4cac30e9e16d.png)

可以保证的是，我为所有的函数都进行了提供，例如这样：

![image](https://user-images.githubusercontent.com/62499904/135207210-a6597d09-7b4f-4960-b053-0e56b5c22d40.png)

目的：1. 通过 wire . 生成 wire_gen.go
           2. 我应该如何排查这样的依赖注入问题 

环境：go version go1.16.6 darwin/amd64
           kratos v2.0.5

其他：这是我过去的项目，我已经遗忘过去是否生成成功。

**Comment by guowei-gong** [comment]
😞  我通过 kratos new 等操作初始化了一个全新的 helloworld，没有任何问题，我马上进行对比，发现它们之间的 wire 依赖关系并没有差别，我不想推倒以前的代码。

**Comment by Windfarer** [comment]
unused就是有没用到的，要去掉

**Comment by guowei-gong** [comment]
> unused就是有没用到的，要去掉

嗯嗯，换句话说就是：如果 provider(提供) 了没有在 wire 调用链中的结构体，wire 是不允许的？
