### ISSUE TITLE
[Feature] Maybe something like `EmitUnpopulated` should be added for custom http response encoder

### ISSUE THREAD

**Issue by blingblingdev** [go-kratos/kratos#1539]
### What problem is the feature used to solve?

In order to use custom response, I created a http.ResponseEncoder. However, becasue of the `omitempty` tag generated by protobuf, using the default golang json Marshaler will cause default values missing in the response.

And in kratos, the json encoding implemented like this:

``` golang
func (codec) Marshal(v interface{}) ([]byte, error) {
	if m, ok := v.(proto.Message); ok {
		return MarshalOptions.Marshal(m)
	}
	return json.Marshal(v)
}
```

In this situation, without proto defining, it cannot use the `EmitUnpopulated` option.
To take over this, I use the following codes to give back all the values:

``` golang
func responseEncoder(w stdHttp.ResponseWriter, r *stdHttp.Request, v interface{}) (err error) {
	codec, _ := http.CodecForRequest(r, "Accept")
	rawV, err := codec.Marshal(v)
	if err != nil {
		return err
	}
	rawMap := make(map[string]interface{})
	err = codec.Unmarshal(rawV, &rawMap)
	if err != nil {
		return err
	}

	reply := newResponse()
	reply.Code = 200
	reply.Data = rawMap
	reply.Message = "success"
	data, err := codec.Marshal(reply)
	if err != nil {
		return err
	}
	w.Header().Set("Content-Type", contentType(codec.Name()))
	w.WriteHeader(stdHttp.StatusOK)
	_, err = w.Write(data)
	if err != nil {
		return err
	}
	return
}
```

It uses several addtional Marshal/Unmarshals, which is not elegant and low efficiency.
Besides, in order to use the above code, a `json_name` field option has to be specified in the proto file.

### Requirements description of the feature

Maybe something like `EmitUnpopulated` should be added for custom response encoder.

**Comment by ffy** [comment]
> https://github.com/go-kratos/kratos/blob/9743ad8d32890258177e0335d1a0741e9d45833e/encoding/json/json.go#L18

This only works for type `proto.Message`.

``` golang
func (codec) Marshal(v interface{}) ([]byte, error) {
	if m, ok := v.(proto.Message); ok {
		return MarshalOptions.Marshal(m)
	}
	return json.Marshal(v)
}
```

**Comment by shenqidebaozi** [comment]
It is not recommended to use this general structure for the return result of the correct request, but you can solve this problem in other ways, such as proto any or proto struct. Declare your fixed structure as a proto message

**Comment by ffy** [comment]
> Because this structure has no meaning in the correct return body, because it is exactly the same, except for time.
> 
> This structure is recommended in the return value of business error.

I dont think so, since the frontend may use the code or msg to make a judgement, the caller may get a `undefined` without a fixed value to represent OK.

**Comment by shenqidebaozi** [comment]
200 indicates that the request is successful. Business errors in non 200 cases can be judged by reason

**Comment by shenqidebaozi** [comment]
```json
{
    // 错误码，跟 http-status 一致，并且在 grpc 中可以转换成 grpc-status
    "code": 500,
    // 错误原因，定义为业务判定错误码
    "reason": "USER_NOT_FOUND",
    // 错误信息，为用户可读的信息，可作为用户提示内容
    "message": "invalid argument error",
    // 错误元信息，为错误添加附加可扩展信息
    "metadata": {}
}
```

**Comment by shenqidebaozi** [comment]
> Great, maybe i should think it over to change the design of response.

This is mainly the team specification. If the team requires a fixed structure, it is understandable
