### ISSUE TITLE
config 读取的配置，有$符号会造成获取的字符串不正确

### ISSUE THREAD

**Issue by ONG-YA** [go-kratos/kratos#1542]
#### What happened:
github.com/go-kratos/kratos/v2/config/reader.go
config 读取的配置，有$符号会造成获取的字符串不正确
如字符串 97$Td!hxx 会转成 97!hxx
#### Environment:
- Kratos version (use `kratos -v`):version v2.0.5
- Go version (use `go version`): 1.15
- OS (e.g: `cat /etc/os-release`): linux
- Others:
![image](https://user-images.githubusercontent.com/46466799/136946223-1e8c3f00-ddfd-421c-bc9c-e8f4154b66b9.png)

![image](https://user-images.githubusercontent.com/46466799/136946285-3222312d-896f-49cc-85dd-cea7893a268c.png)

**Comment by ONG-YA** [comment]
> kratos 支持通过 `$` 关键词获得环境变量中的数据（例如：密码应该被放置于环境变量中，而非配置，因为配置提交到 vcs 会存在安全风险）
> 
> 如果要关闭该功能，请给定空的 `resolver` 行为

请教一下怎么设置

**Comment by elvizlai** [comment]
using trick: `${:what$u$want}` will got `what$u$want`
