### ISSUE TITLE
[Question]调试报错

### ISSUE THREAD

**Issue by zt102545** [go-kratos/kratos#1543]
blog实例启动调试报错，找不到路径
![image](https://user-images.githubusercontent.com/23187595/137054880-4496b108-9924-4d65-86b6-fd8588f128ff.png)
想知道你们调试是怎么调试的，需要设置什么参数吗
![image](https://user-images.githubusercontent.com/23187595/137055012-87cc0cb3-14f0-4190-847b-738117a6cefe.png)

**Comment by tonybase** [comment]
应该是当前目录运行的，可以试试 `./server -conf ../../configs` 试试

**Comment by yeqown** [comment]
用的IDE自带的Debug的话，需要配置下 Run/Debug Configuration -> Working Directory 为你实际的“启动目录”（我猜测，你是直接点击的 main 函数的 Debug 入口，那启动目录应该是 main 文件在的目录）
