### ISSUE TITLE
Misuse of `context.WithTimeout`

### ISSUE THREAD

**Issue by fynxiu** [go-kratos/kratos#1549]
There is a misuse of `context.WithTimeout/2` in line 37 of file `cmd/kratos/internal/project/project.go`.
The slow operation `project.New/4` does not watch the `Done` channel for cancellation.

**Comment by shenqidebaozi** [comment]
If this is a bug, can you fix it?

**Comment by shenqidebaozi** [comment]
You can try to fix it.

**Comment by wayslog** [comment]
> I'm really sorry. My English is not very good. There may be some grammatical problems. I just want you to fix this bug

Chinese is ok,  我看得懂。
