### ISSUE TITLE
[Question] Is metadata inject by `app.New(Metadata())` same as `metadata.FromServerContext(ctx)` ?

### ISSUE THREAD

**Issue by woorui** [go-kratos/kratos#1556]
Is metadata inject by `app.New(Metadata())` should same as `metadata.FromServerContext(ctx)` ?

I can't get metadata that inject by `app.New(Metadata())` by calling `metadata.FromServerContext(ctx)` .

```go
// metadata != app.Metadata()

metadata, _ := metadata.FromServerContext(ctx)

app, _ := kratos.FromContext(ctx)

```

**Comment by shenqidebaozi** [comment]
Is metadata middleware used？

**Comment by woorui** [comment]
> Is metadata middleware used？

for handler using.

**Comment by shenqidebaozi** [comment]
When metadata library is used to transfer metadata, metadata middleware should be enabled

**Comment by shenqidebaozi** [comment]
@longXboy
