### ISSUE TITLE
[Question] Install kratos cli with a specific version

### ISSUE THREAD

**Issue by szeseong** [go-kratos/kratos#1557]
Is it possible to install kratos cli with a specific version like v2.0.5 instead of latest?

When I ran below line:
`go install github.com/go-kratos/kratos/cmd/kratos/v2@v2.0.5`

I got this
`go install: github.com/go-kratos/kratos/cmd/kratos/v2@v2.0.5: github.com/go-kratos/kratos@v2.0.5: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2`

**Comment by szeseong** [comment]
As I'm not ready to use kratos v2.1.0. I'm using `go install github.com/go-kratos/kratos/cmd/kratos/v2@f3e75bffca735a5c1b5ae388814aed0e37388f09` which depends on kratos 2.0.3.

**Comment by panol** [comment]
One of the solution is:


```
git clone git@github.com:go-kratos/kratos.git
git checkout tags/v2.7.3
cd kratos 
make install 
```
Change the version v2.7.3 to your target version .
And you now can use the specified version of kratos tools.
To check the result :
protoc-gen-go-http --version
protoc-gen-go-http v2.7.3
