### ISSUE TITLE
当 proto 中的 request 有 timestamp 时，使用 http client 请求会报错：parsing time error

### ISSUE THREAD

**Issue by MoeCasts** [go-kratos/kratos#1558]
#### What happened:
当 proto 文件中的 request 有 timestamp 时，使用 http client 请求会报 parsing time 的错误。
#### What you expected to happen:
能使用 http client 正常请求。
#### How to reproduce it (as minimally and precisely as possible):

代码已放在仓库中，直接 clone 运行即可。
```
# clone code
git clone https://github.com/MoeCasts/kratos-registry-consul-test.git

# start service
kratos run

# run tests
go test ./cmd/kratos-registry-consul-test/main_test.go -v
```

#### Environment:
- Kratos version (use `kratos -v`): kratos version v2.1.0
- Go version (use `go version`): go version go1.16.6 darwin/amd64
- OS (e.g: `cat /etc/os-release`): macOS 11.0.1
- Others:

**Comment by longXboy** [comment]
fix #1559
