### ISSUE TITLE
[Question] Have considered changing the consul client registration method

### ISSUE THREAD

**Issue by moecasts** [go-kratos/kratos#1560]
### 代码
https://github.com/go-kratos/kratos/blob/014778b72a2086ace5eb7bdf3c7bb10205b68110/contrib/registry/consul/client.go#L70-L125

### 缺点
只注册一个 service 实例，导致 dns 服务发现只能获取到一个服务节点，
比如同时有 http/8000 和 grpc/9000 两个服务，使用 dns 来做服务发现的话，只能查询到 grpc/9000 一个服务：
```bash
# dig @172.233.0.2 -p 8600 novel-service.service.consul SRV
;; QUESTION SECTION:
;novel-service.service.consul.	IN	SRV

;; ANSWER SECTION:
novel-service.service.consul. 0	IN	SRV	1 1 9000 ace90004.addr.dc1.consul.
```
查询 consul 的服务后发现，http/8000 和 grpc/9000 都是被注册到同一个服务里的 ServiceTaggedAddresses 里：
```
# curl http://172.233.0.2:8500/v1/catalog/service/novel-service
[
    {
        "ID": "32099b46-bdcb-a831-4c7a-64be788f3e6a",
        "Node": "a5158a57e04b",
        "Address": "127.0.0.1",
        "Datacenter": "dc1",
        "TaggedAddresses": {
            "lan": "127.0.0.1",
            "lan_ipv4": "127.0.0.1",
            "wan": "127.0.0.1",
            "wan_ipv4": "127.0.0.1"
        },
        "NodeMeta": {
            "consul-network-segment": ""
        },
        "ServiceKind": "",
        "ServiceID": "16b4cc7e8a6f",
        "ServiceName": "novel-service",
        "ServiceTags": [
            "version=v1.0.0"
        ],
        "ServiceAddress": "172.233.0.4",
        "ServiceTaggedAddresses": {
            "grpc": {
                "Address": "grpc://172.233.0.4:9000",
                "Port": 9000
            },
            "http": {
                "Address": "http://172.233.0.4:8000",
                "Port": 8000
            },
            "lan_ipv4": {
                "Address": "172.233.0.4",
                "Port": 9000
            },
            "wan_ipv4": {
                "Address": "172.233.0.4",
                "Port": 9000
            }
        },
        "ServiceMeta": {},
        "ServicePort": 9000,
]
```

## 期望
将 http/8000 和 grpc/9000 分别注册各自的服务，不再放在同一个服务里，之后就可以正常使用 dns 来做服务发现了。

**Comment by longXboy** [comment]
注册成两个instance通过tag来区分这样不会breakchange，这样如何？

**Comment by letian0805** [comment]
> 注册成两个instance通过tag来区分这样不会breakchange，这样如何？

PR #1730 加了个 Filter 解决这个问题

**Comment by letian0805** [comment]
> ## 现有注册方式
> ### 代码
> https://github.com/go-kratos/kratos/blob/014778b72a2086ace5eb7bdf3c7bb10205b68110/contrib/registry/consul/client.go#L70-L125
> 
> ### 缺点
> 只注册一个 service 实例，导致 dns 服务发现只能获取到一个服务节点， 比如同时有 http/8000 和 grpc/9000 两个服务，使用 dns 来做服务发现的话，只能查询到 grpc/9000 一个服务：
> 
> ```shell
> # dig @172.233.0.2 -p 8600 novel-service.service.consul SRV
> ;; QUESTION SECTION:
> ;novel-service.service.consul.	IN	SRV
> 
> ;; ANSWER SECTION:
> novel-service.service.consul. 0	IN	SRV	1 1 9000 ace90004.addr.dc1.consul.
> ```
> 
> 查询 consul 的服务后发现，http/8000 和 grpc/9000 都是被注册到同一个服务里的 ServiceTaggedAddresses 里：
> 
> ```
> # curl http://172.233.0.2:8500/v1/catalog/service/novel-service
> [
>     {
>         "ID": "32099b46-bdcb-a831-4c7a-64be788f3e6a",
>         "Node": "a5158a57e04b",
>         "Address": "127.0.0.1",
>         "Datacenter": "dc1",
>         "TaggedAddresses": {
>             "lan": "127.0.0.1",
>             "lan_ipv4": "127.0.0.1",
>             "wan": "127.0.0.1",
>             "wan_ipv4": "127.0.0.1"
>         },
>         "NodeMeta": {
>             "consul-network-segment": ""
>         },
>         "ServiceKind": "",
>         "ServiceID": "16b4cc7e8a6f",
>         "ServiceName": "novel-service",
>         "ServiceTags": [
>             "version=v1.0.0"
>         ],
>         "ServiceAddress": "172.233.0.4",
>         "ServiceTaggedAddresses": {
>             "grpc": {
>                 "Address": "grpc://172.233.0.4:9000",
>                 "Port": 9000
>             },
>             "http": {
>                 "Address": "http://172.233.0.4:8000",
>                 "Port": 8000
>             },
>             "lan_ipv4": {
>                 "Address": "172.233.0.4",
>                 "Port": 9000
>             },
>             "wan_ipv4": {
>                 "Address": "172.233.0.4",
>                 "Port": 9000
>             }
>         },
>         "ServiceMeta": {},
>         "ServicePort": 9000,
> ]
> ```
> 
> ## 期望
> 将 http/8000 和 grpc/9000 分别注册各自的服务，不再放在同一个服务里，之后就可以正常使用 dns 来做服务发现了。

@moecasts PR #1730  配合 PR #1729  再加上用 cmux 做端口复用，可以解决你的问题
