### ISSUE TITLE
[Question]为什么通过标准库定义的 http handler 没有日志

### ISSUE THREAD

**Issue by overstarry** [go-kratos/kratos#1566]
通过标准库定义的 http handler，请求没有相应的日志，使用了中间件

**Comment by shenqidebaozi** [comment]
如果不是通过 proto 声明的接口，应该不走 middleware

**Comment by overstarry** [comment]
那要怎么办

**Comment by shenqidebaozi** [comment]
或者实现一个 http filter，example 里面有示例

**Comment by overstarry** [comment]
好的，我看看

**Comment by shenqidebaozi** [comment]
https://github.com/go-kratos/kratos/tree/main/examples/http/middlewares

**Comment by shenqidebaozi** [comment]
> 或者proto有办法得到单个字符串的响应吗，不要 键值对的

单个字符串是什么意思？
