### ISSUE TITLE
[Question]ERROR msg=failed to watch next config: open configs\config.yaml~: The system cannot find the file specified.

### ISSUE THREAD

**Issue by overstarry** [go-kratos/kratos#1569]
## 操作
更新配置文件后触发
ERROR msg=failed to watch next config: open configs\config.yaml~: The system cannot find the file specified.
是不支持windows吗

**Comment by shenqidebaozi** [comment]
windows 上可能兼容性会有一些问题

**Comment by overstarry** [comment]
ok
