### ISSUE TITLE
[Question] 服务优雅退出

### ISSUE THREAD

**Issue by pinguo-lixin** [go-kratos/kratos#1584]
App 中停止 Server 时使用的 `Context` 与启动时是同一个 `Context`，这导致无法对 Stop 附加额外的超时时间。且当前对 `http.Server` 未达到优雅退出的目的（收到退出信号立即退出，未等待当前请求执行完毕）。
[App Start](https://github.com/go-kratos/kratos/blob/main/app.go#L92)

**Comment by qmdx00** [comment]
考虑在新的 `context` 中附加原来的 `AppInfo` 信息，方便在 `Stop()` 中获取对应信息。
