### ISSUE TITLE
The depth of the log package helper caller needs to be controlled separately, which is too cumbersome

### ISSUE THREAD

**Issue by tianping526** [go-kratos/kratos#1591]
#### What happened:

在log包helper.go中，其他方法（如Debug、Info）比Log方法调用层级多一层，也比log.go  中的Log方法多一层，导致每次使用Helper都需要单独控制Caller的Depth，非常繁琐。

#### What you expected to happen:

Helper的其他方法和Log方法具有相同的调用深度，配置一次Caller的Depth，在所有日志使用场景都使用适用，而不需要单独控制。其修改也很简单，示例如下：

```golang
// 旧代码
func (h *Helper) Debug(a ...interface{}) {
	h.Log(LevelDebug, h.msgKey, fmt.Sprint(a...))
}

// 修改后
func (h *Helper) Debug(a ...interface{}) {
	_ = h.logger.Log(LevelDebug, h.msgKey, fmt.Sprint(a...))
}

```

#### Environment:
- Kratos version (use `kratos -v`): v2.1.0
- Go version (use `go version`):
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by tianping526** [comment]
> 可以帮直接提个pr？

**Comment by tianping526** [comment]
> 可以帮直接提个pr？

已经提交了，快来瞅瞅

**Comment by windzhu0514** [comment]
也遇到了这个问题，中间件 logging 和 recovery 的写日志层级不一样
