### ISSUE TITLE
[Question]cannot unmarshal string into Go struct field

### ISSUE THREAD

**Issue by gouez** [go-kratos/kratos#1595]
运行的时候报如下错误，这是什么原因导致的？
panic: json: cannot unmarshal string into Go struct field Data_Redis.data.redis.read_timeout of type durationpb.Duration

**Comment by flanchegong** [comment]
我也遇到了，就是redis 密碼咋配置的啊

**Comment by flanchegong** [comment]
congigs 目錄 string password = 3;
conf.proto 配     string password = 3;
make config

**Comment by Casper-Mars** [comment]
read_timeout is defined as `google.protobuf.Duration`. It is a struct not regular type.  The yaml or json package can not unmarshal that. You can change the config like this:
`
  redis:
    addr: 127.0.0.1:6379
    read_timeout:
      seconds: 1
    write_timeout:
      seconds: 1
`
