### ISSUE TITLE
[Feature] Swagger UI

### ISSUE THREAD

**Issue by Song2017** [go-kratos/kratos#1596]
### What problem is the feature used to solve?
To make the API more visual and easy for callers to use.

### Requirements description of the feature
add a default API UI page, which is shown based on environ: /ui

### References
https://petstore.swagger.io/?_ga=2.52215086.687596535.1635738363-1647535374.1631089476

**Comment by Windfarer** [comment]
https://github.com/go-kratos/swagger-api
