### ISSUE TITLE
[Question] 为什么不做成申明式的框架呢

### ISSUE THREAD

**Issue by swcrbt** [go-kratos/kratos#1597]
K8S那些现在都只需要填写配置就可以的了，而不需要在每个微服务里都加一段 http.NewServer .. grpc.NewServer .. 这样的代码

**Comment by swcrbt** [comment]
既然定位为框架了，应该可以规定一些项目结构和配置项了的吧

**Comment by Windfarer** [comment]
设计如此，这样能给用户更多的可定制空间。把kratos理解为是一套构建微服务的工具组件更合适一些。

**Comment by shenqidebaozi** [comment]
> 设计如此，这样能给用户更多的可定制空间。把kratos理解为是一套构建微服务的工具组件更合适一些。

是的，更建议是 kratos 作为底层框架，来定制一个最适合企业的框架。
