### ISSUE TITLE
[Question]设置的Header不生效

### ISSUE THREAD

**Issue by overstarry** [go-kratos/kratos#1600]
```go
	ctx.Header().Set("Content-Disposition", "attachment; filename="+url.QueryEscape(name))
```
无法生效

**Comment by overstarry** [comment]
@shenqidebaozi

**Comment by overstarry** [comment]
是自定义的HandlerFunc

**Comment by shenqidebaozi** [comment]
完整代码，贴一下？

**Comment by shenqidebaozi** [comment]
另外应该是 `ctx.Response().Header().Set("content-disposition", "attachment; filename="+match.Name+".xlsx")` 吧？

**Comment by overstarry** [comment]
可以了

**Comment by Tsan1024** [comment]
![image](https://github.com/go-kratos/kratos/assets/127735596/ee6be503-f354-4f96-a26c-8e00c3558996)
fan返回时这个
