### ISSUE TITLE
contrib test and docs

### ISSUE THREAD

**Issue by Windfarer** [go-kratos/kratos#1605]
no documentation README:
- [ ] config/apollo @yeqown 
- [ ] config/etcd
- [ ] registry/consul
- [ ] registry/discovery @yeqown 
- [ ] registry/etcd
- [ ] registry/kubernetes
- [ ] registry/zookeeper

no tests:
- [x] config/nacos
- [x] registry/nacos

**Comment by yeqown** [comment]
I can provide the document of `registry/discovery`, assign to me plz.  @Windfarer 

And maybe provide a template for these `contrib` modules can let documents normative?

**Comment by Windfarer** [comment]
@yeqown updated. 

The docs should have the following parts:

1. The examples of initialization
2. The examples of usage.
3. The meaning of options.
4. Additional description of this package, if it is needed.

**Comment by yeqown** [comment]
finished #1625 @Windfarer

**Comment by Windfarer** [comment]
> finished #1625 @Windfarer

Thank you so much
