### ISSUE TITLE
[Feature] Get the configured format type through the configuration center

### ISSUE THREAD

**Issue by shenqidebaozi** [go-kratos/kratos#1610]
### What problem is the feature used to solve?

The current configuration center plug-in lacks settings for the configured format, which makes it impossible to directly parse the configuration to the structure, so some ways need to be used to fix this problem

### Requirements description of the feature

- If the configured format type can be obtained through the API interface provided by the configuration center, the format type returned by the configuration center is directly used. 
- If the format type cannot be read, it is obtained from the suffix of the configuration file, such as `xxxx.json`. 
- When both methods are not satisfied, it is considered as plain text.

### TODO
- [ ] etcd
- [ ] consul
- [ ] kubernetes
- [ ] nacos
- [ ] config loaded log

**Comment by shenqidebaozi** [comment]
@Windfarer PTAL.

**Comment by Windfarer** [comment]
In addition, the key (filename) being loaded and the its' codec format should be print to log.

**Comment by Windfarer** [comment]
As the comment in the source code: 

https://github.com/go-kratos/kratos/blob/main/config/options.go#L35
https://github.com/go-kratos/kratos/blob/main/config/options.go#L60

```go
// WithDecoder with config decoder.
// DefaultDecoder behavior:
// If KeyValue.Format is non-empty, then KeyValue.Value will be deserialized into map[string]interface{}
// and stored in the config cache(map[string]interface{})
// if KeyValue.Format is empty,{KeyValue.Key : KeyValue.Value} will be stored in config cache(map[string]interface{})
```

So the config plugins should try their best to get or detect the config files' format then put it to `KeyValue.Format` in order to let the DefaultDecoder can find and use the right Codec
