### ISSUE TITLE
[Question] http 返回格式

### ISSUE THREAD

**Issue by gofromzero** [go-kratos/kratos#1621]
在proto 中定义字段为 int64 类型， 使用http 请求后，返回的是 string 类型。
使用的是 kratos new helloword 生成的demo

![$D2I}4B318FN HLRZ~IT6](https://user-images.githubusercontent.com/30290644/141269796-e1033026-7d9b-4ac5-bfd9-2bc94496a2ff.png)
![(EHB)Y}}BGBMK359W 4A12P](https://user-images.githubusercontent.com/30290644/141269873-d666f72d-f3df-47b5-a0ae-cbea11040a64.png)

**Comment by haiyux** [comment]
这个是protobuf的特性 是防止int64过长 到js端发生变化

**Comment by gofromzero** [comment]
> 这个是protobuf的特性 是防止int64过长 到js端发生变化

那就是在客户端进行需要的类型转换，转成int64

**Comment by gofromzero** [comment]
> 用int32也可以 客户端就是数字了

好的谢谢
