### ISSUE TITLE
Missing service name

### ISSUE THREAD

**Issue by flanchegong** [go-kratos/kratos#1623]
kratos run
INFO msg=[HTTP] server listening on: [::]:8000
INFO msg=[gRPC] server listening on: [::]:9000
Unexpected response code: 400 (Missing service name)
panic: Unexpected response code: 400 (Missing service name)

**Comment by yeqown** [comment]
I find "Missing service name" text in Kratos and its dependencies, only find it in [github.com/hashicorp/mdns@v1.0.0/zone.go#L69](#), it looks you are using the `consul` library? Could you provide any sample code? @flanchegong

**Comment by shenqidebaozi** [comment]
什么情况下出现的错误，是否声明了服务名称。

**Comment by flanchegong** [comment]
syntax = "proto3";
package kratos.api;

option go_package = "enlightened-account/internal/conf;conf";

import "google/protobuf/duration.proto";

message Bootstrap {
  Server server = 1;
  Data data = 2;
  Trace trace = 3;
}

message Trace {
  string endpoint = 1;
}

message Server {
  message HTTP {
    string network = 1;
    string addr = 2;
    google.protobuf.Duration timeout = 3;
  }
  message GRPC {
    string network = 1;
    string addr = 2;
    google.protobuf.Duration timeout = 3;
  }
  HTTP http = 1;
  GRPC grpc = 2;
}

message Data {
  message Database {
    string driver = 1;
    string source = 2;
  }
  message Redis {
    string network = 1;
    string addr = 2;
    string password = 3;
    google.protobuf.Duration read_timeout = 4;
    google.protobuf.Duration write_timeout = 5;
  }
  Database database = 1;
  Redis redis = 2;
}

message Registry {
  message Consul {
    string address = 1;
    string scheme = 2;
  }
  Consul consul = 1;
}

**Comment by flanchegong** [comment]
consul:
  address: 127.0.0.1:8500
  scheme: http

**Comment by flanchegong** [comment]
trace:
  endpoint: http://127.0.0.1:14268/api/traces
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(xxx.xxx.xxx.xxx:3306)/xxx
  redis:
    addr: xxx.xxx.xxx.xxx:6379
    password : pwd
    read_timeout: 0.2s
    write_timeout: 0.2s

**Comment by shenqidebaozi** [comment]
什么情况下出现的错误，是否声明了服务名称。

**Comment by flanchegong** [comment]
直接在根目录运行 kratos run 的时候啊，；运行kratos run 的时候服务名称默认就是文件夹的名称啊

**Comment by shenqidebaozi** [comment]
```
func newApp(logger log.Logger, hs *http.Server, gs *grpc.Server) *kratos.App {
	return kratos.New(
		kratos.ID(id),
		kratos.Name(Name),// 是不是这里是空字符串？
		kratos.Version(Version),
		kratos.Metadata(map[string]string{}),
		kratos.Logger(logger),
		kratos.Server(
			hs,
			gs,
		),
	)
}
```

**Comment by shenqidebaozi** [comment]
如果用 kratos run，可以手动指定 name 的名称，如果是 go build 可以注入进去。
