### ISSUE TITLE
tracing

### ISSUE THREAD

**Issue by gofromzero** [go-kratos/kratos#1624]
#### What happened:
https://github.com/go-kratos/kratos/blob/0fad751032e5bff76efe659474060449f4818bfc/middleware/tracing/tracer.go#L36-L40

#### What you expected to happen:
这个是否是拼写错误  kratos  kartos

#### Environment:
- Kratos version (use `kratos -v`): 2.1.1

**Comment by fifsky** [comment]
应该是的，你可以提交一个PR
