### ISSUE TITLE
[Feature]根据参数初始化项目

### ISSUE THREAD

**Issue by cbirdcn** [go-kratos/kratos#1631]
### 问题

每次初始化项目时，我用kratos new 新项目，由于helloworld模板中有大量的Greeter字眼，需要替换掉改成自己的项目/service名，很是麻烦，尤其是当服务多了之后更难受。

### 期望

所以我期望，kratos new命令是否可以通过参数形式支持自定义项目初始化结构。比如：
`kratos new projectName -t templateName -s serviceName -p rpc -p http -m crud `
其中参数说明：

- projectName是最外层文件夹名称，可以和service名称不一致。
- templateName是模板名，可以通过官方提供或自定义模板文件，缺省helloworld
- serviceName是服务名，只支持单一service，目前只需要支持service不需要支持biz、data等初始化
- rpc和http协议都可以通过-p参数指定，也可以只指定其中一种，缺省rpc
- crud表示初始化的方法

至此，项目可以自动生成proto，并编译出pb.go，借此自动产生service，server，完成注入等工作。
这个feature可以迭代进行，欢迎讨论。

**Comment by Windfarer** [comment]
目前layout项目的状态是可以直接运行，加入模板变量等功能会让这个仓库的调试和直接运行变得困难。同时，layout可能会不定期改动，将工具与模板耦合会影响工具的通用性，造成难以维护等问题。

有个比较简单的替代方案你可以试试，直接用[cookiecutter](https://github.com/cookiecutter/cookiecutter)来自制你的项目模板使用，不再依赖kratos new，目前我们这个命令也只是帮你拉一下layout项目，不会做太多替换工作。

**Comment by cbirdcn** [comment]
> 目前layout项目的状态是可以直接运行，加入模板变量等功能会让这个仓库的调试和直接运行变得困难。同时，layout可能会不定期改动，将工具与模板耦合会影响工具的通用性，造成难以维护等问题。
> 
> 有个比较简单的替代方案你可以试试，直接用[cookiecutter](https://github.com/cookiecutter/cookiecutter)来自制你的项目模板使用，不再依赖kratos new，目前我们这个命令也只是帮你拉一下layout项目，不会做太多替换工作。

kratos new 的目的应该是创建一个项目，而不是拉取一个模板而已。
框架最重要的事情是简化无意义的手工操作，而不是每个人自己创建自己的模板就可以了。
无论是横向还是纵向对比，beego、laravel、flask这些同为web框架的用命令带项目名生成项目都应该是想当然的事情。
工具与模板耦合的问题，应该是调整模板和实现时也要顺带解决工具生成问题，而不是工具一次生成就要永久兼容。
如果模板变量的加入会让调试和运行变得困难，那每个项目创建时自己改一遍再调试和运行不是更麻烦吗？
希望能重视易用性。

**Comment by Windfarer** [comment]
> > 目前layout项目的状态是可以直接运行，加入模板变量等功能会让这个仓库的调试和直接运行变得困难。同时，layout可能会不定期改动，将工具与模板耦合会影响工具的通用性，造成难以维护等问题。
> > 有个比较简单的替代方案你可以试试，直接用[cookiecutter](https://github.com/cookiecutter/cookiecutter)来自制你的项目模板使用，不再依赖kratos new，目前我们这个命令也只是帮你拉一下layout项目，不会做太多替换工作。
> 
> kratos new 的目的应该是创建一个项目，而不是拉取一个模板而已。 框架最重要的事情是简化无意义的手工操作，而不是每个人自己创建自己的模板就可以了。 无论是横向还是纵向对比，beego、laravel、flask这些同为web框架的用命令带项目名生成项目都应该是想当然的事情。 工具与模板耦合的问题，应该是调整模板和实现时也要顺带解决工具生成问题，而不是工具一次生成就要永久兼容。 如果模板变量的加入会让调试和运行变得困难，那每个项目创建时自己改一遍再调试和运行不是更麻烦吗？ 希望能重视易用性。

还是要重申，layout只是个参考的项目结构，不是强制的，kratos的目标是提供一套松散的微服务工具库，供用户定制自己的所谓“框架”

**Comment by Windfarer** [comment]
就像您提到的flask，kratos与它的设计思路有点类似，并不限制项目的结构长什么样子，如果规模小，完全可以写到一个文件里直接跑，把不需要的部分直接不要，如果是这种情况，就完全不需要用到layout，太臃肿了。而且flask也没有固定的结构，可以按照自己的思路进行设计。对于复杂项目的创建体验优化的问题，我们是有一个初步的设计思路，但还没做细节的设计，它的形态大概率是一个Web App，而不是在命令行敲一大堆命令


参考：https://flask.palletsprojects.com/en/2.0.x/tutorial/layout/

**Comment by cbirdcn** [comment]
> > > 目前layout项目的状态是可以直接运行，加入模板变量等功能会让这个仓库的调试和直接运行变得困难。同时，layout可能会不定期改动，将工具与模板耦合会影响工具的通用性，造成难以维护等问题。
> > > 有个比较简单的替代方案你可以试试，直接用[cookiecutter](https://github.com/cookiecutter/cookiecutter)来自制你的项目模板使用，不再依赖kratos new，目前我们这个命令也只是帮你拉一下layout项目，不会做太多替换工作。
> > 
> > 
> > kratos new 的目的应该是创建一个项目，而不是拉取一个模板而已。 框架最重要的事情是简化无意义的手工操作，而不是每个人自己创建自己的模板就可以了。 无论是横向还是纵向对比，beego、laravel、flask这些同为web框架的用命令带项目名生成项目都应该是想当然的事情。 工具与模板耦合的问题，应该是调整模板和实现时也要顺带解决工具生成问题，而不是工具一次生成就要永久兼容。 如果模板变量的加入会让调试和运行变得困难，那每个项目创建时自己改一遍再调试和运行不是更麻烦吗？ 希望能重视易用性。
> 
> 还是要重申，layout只是个参考的项目结构，不是强制的，kratos的目标是提供一套松散的微服务工具库，供用户定制自己的所谓“框架”

了解了，谢谢
