### ISSUE TITLE
addr.Attributes.WithValues undefined

### ISSUE THREAD

**Issue by flanchegong** [go-kratos/kratos#1632]
D:\workspace\src\helloworld>kratos run
# github.com/go-kratos/kratos/v2/transport/grpc/resolver/discovery
..\..\..\..\pkg\mod\github.com\go-kratos\kratos\v2@v2.1.1\transport\grpc\resolver\discovery\resolver.go:69:36: addr.Attributes.WithValues undefined (type *attributes.Attributes has no field or method WithValues)
..\..\..\..\pkg\mod\github.com\go-kratos\kratos\v2@v2.1.1\transport\grpc\resolver\discovery\resolver.go:99:23: not enough arguments in call to attributes.New
        have (...interface {})
        want (interface {}, interface {})
?[31mERROR: exit status 2?[m

系统：win10，go version 1.16.1

**Comment by shenqidebaozi** [comment]
grpc 最近有 breaking change，降级 grpc 版本到 1.39.1

**Comment by flanchegong** [comment]
好的，OK了
