### ISSUE TITLE
[Question] 下面这种 post 请求如何实现呢

### ISSUE THREAD

**Issue by xiak** [go-kratos/kratos#1641]
有以下的请求：
POST http://xxxxx.com/bot?hello=world
body: {
    "Message":  "This is message"
}

以下是我测试的 proto

rpc HelloWorld (Received) returns (Reply) {
	option (google.api.http) = {
		post: "/{var}"
		body: "test"
	};
}

message Received {
     string var = 1;
     Test test = 2;
}

message Test {
   string context = 1;
}

最终只能获取的到 msg=var:"bot" test:{context:"This is message"}

问题是： 有没有办法同时获取 url 中的 query. hello=world 又能获取到 body 中的数据

**Comment by shenqidebaozi** [comment]
你 body 的字段和 proto message 没对上鸭

**Comment by xiak** [comment]
@shenqidebaozi 这个应该是临时打错了。现在的问题主要是只能获取 URl http://xxxxx.com/bot?hello=world  中的 bot， 不能获取？后的 hello=world.   body是能够正常获取到的。

**Comment by shenqidebaozi** [comment]
你 proto 声明里面没有 hello 这个字段鸭

**Comment by xiak** [comment]
rpc HelloWorld (Received) returns (Reply) {
option (google.api.http) = {
post: "/{var}"
body: "test"
};
}

message Received {
string var = 1;
string hello = 2
Test test = 3;
}

message Test {
string context = 1;
}

@shenqidebaozi  这样也不行

**Comment by yeqown** [comment]
@xiak 要在调用 `Bind-like` 方法的时候，需要分开绑定才行～

```go
// Context is an HTTP Context.
type Context interface {
	Bind(interface{}) error
	BindVars(interface{}) error
	BindQuery(interface{}) error
	BindForm(interface{}) error
}

func (c *wrapper) Bind(v interface{}) error      { return c.router.srv.dec(c.req, v) }
func (c *wrapper) BindVars(v interface{}) error  { return binding.BindQuery(c.Vars(), v) }
func (c *wrapper) BindQuery(v interface{}) error { return binding.BindQuery(c.Query(), v) }
func (c *wrapper) BindForm(v interface{}) error  { return binding.BindForm(c.req, v) }
```

根据 proto 里生成的 HTTP handler 是根据 Method 来确定绑定方法的：post 使用 Bind 方法（只读取 body）,所以你需要额外的再调用 BindQuery 方法。

**Comment by xiak** [comment]
@yeqown 感谢，我试试先

**Comment by BeatsKitano** [comment]
这个问题可有好的解决办法？
