### ISSUE TITLE
[Proposal] Add Bazel support

### ISSUE THREAD

**Issue by commure-stabai** [go-kratos/kratos#1644]
### Proposal

Add support for users on the [Bazel](https://bazel.build/) build system by creating Bazel build files and refactorings in Kratos repositories. This will allow users of the Kratos framework who use Bazel to avoid messy custom patching that has to be redone each version, by instead allowing them to be added as dependencies automatically using [Gazelle](https://github.com/bazelbuild/bazel-gazelle#readme).

The following process would need to be run for each Kratos repository (and possibly each Go module within each repository):
1. Add a basic Bazel [WORKSPACE file](https://docs.bazel.build/versions/main/build-ref.html#workspace) and run Gazelle on the repository itself. This will generate several of the necessary artifacts automatically (but many will have errors that need manual fixing).
3. Fix errors in [Bazel build files](https://docs.bazel.build/versions/main/build-ref.html#BUILD_files) generated by Gazelle. This may in some cases require Go code changes, but hopefully these will be minimal.
4. After getting the repository working properly in Bazel, add [Gazelle directives](https://github.com/bazelbuild/bazel-gazelle#directives) to ensure that future Gazelle runs work normally
5. Document the new process for module updates (e.g. any time you run `go mod tidy`, also run `bazel run :gazelle`)
6. Add a CI check to make sure the Bazel builds work properly after future updates. The check should give details on how to fix common problems when something fails.

**Comment by dontstabai** [comment]
If it helps add context, we are currently using Kratos with a Bazel project. We've had to manually patch the following Kratos repositories (may be more as we continue on our project):

- https://github.com/go-kratos/kratos
- https://github.com/go-kratos/grpc-gateway
- https://github.com/go-kratos/swagger-api

**Comment by Windfarer** [comment]
sgtm
