### ISSUE TITLE
[DOCS] Broken Link inside Examples

### ISSUE THREAD

**Issue by djboboch** [go-kratos/kratos#1645]
#### What happened:

Broken link for the **health** example inside the documentation. The link direct to 404 page.
https://go-kratos.dev/en/docs/getting-started/examples

#### What you expected to happen:

Redirect to example file.

#### How to reproduce it (as minimally and precisely as possible):

Visit the live examples page. (https://go-kratos.dev/en/docs/getting-started/examples)

**Comment by Casper-Mars** [comment]
Hi~There is no trouble for me to open that link(https://go-kratos.dev/en/docs/getting-started/examples).

**Comment by djboboch** [comment]
The error appears when going to the health link inside of the examples page. The link is this broken.

**Comment by haiyux** [comment]
> broken

You can sett [https://haiyux.gitee.io/](https://haiyux.gitee.io/). I will maintain it regularly.
