### ISSUE TITLE
[BUG] Node filtering requires context

### ISSUE THREAD

**Issue by shima-park** [go-kratos/kratos#1646]
#### What happened:
2.1.1版本中，提供的自定义的节点过滤方法选项，支持从上下文中获取信息。
```
// Filter is node filter function.
type Filter func(context.Context, []Node) []Node
```

2.1.2版本中，Filter被移除，取而代之的是NodeFilter，无法获取上下文信息了。
```
// NodeFilter is node filter.
// If it returns false, the node will be removed out from the balancer pick list
type NodeFilter func(node Node) bool
```

#### What you expected to happen:
NodeFilter支持context.Context参数，或者将Filter加回来
```
type NodeFilter func(ctx context.Context, node Node) bool
```

#### How to reproduce it (as minimally and precisely as possible):
尝试实现一个从上下文中获取的信息的自定义节点过滤器，可以复现该问题。

#### Environment:
- Kratos version (use `kratos -v`): kratos version v2.1.0
- Go version (use `go version`): go version go1.17.2 darwin/amd64
- OS (e.g: `cat /etc/os-release`):macOS 10.15.7 (19H1419)
- Others:

**Comment by yeqown** [comment]
补充一点：`NodeFilter` 还无法做一些兜底的策略，如下：

> 背景：基于染色选择节点。最开始我是实现了 gRPC 中的 Picker，现在想要切换到kratos的 selector + NodeFilter 
>

***策略***：
1. 如果客户端有颜色，那么根据客户端颜色选择节点（兜底策略：***如果无法命中任何节点，那么使用没有颜色和颜色为default的节点***）。
2. 如果客户端没有颜色，那么使用没有颜色和颜色为default的节点。

但是使用NodeFilter实现的话，在NodeFilter内部无法感知是否已经命中node了～

```go
// ColoredFilter returns a selector.NodeFilter to filter nodes based on the
// color of the node. This works on the client side, so colors can be empty, and then
// use the "DEPLOY_COLOR" as default.
func ColoredFilter(colors ...string) selector.NodeFilter {
	allowColorsMapping := make(map[string]struct{}, 0)
	if len(colors) == 0 {
		clientColor := os.Getenv("DEPLOY_COLOR")
		allowColorsMapping[clientColor] = struct{}{}
	}

	return func(node selector.Node) bool {
		// TODO: how to apply the strategy
	}
}
```

**Comment by longXboy** [comment]
fixed in (#1656)

**Comment by shima-park** [comment]
👍
