### ISSUE TITLE
[Question] proto 不支持这种写法吗？  get: "/v1/{parent=shelves/*}/books"

### ISSUE THREAD

**Issue by xiak** [go-kratos/kratos#1653]
kratos 是否支持以下这种写法呢，我在谷歌文档上面看到的 [https://cloud.google.com/apis/design/standard_methods](https://cloud.google.com/apis/design/standard_methods)

```
// Lists books in a shelf.
rpc ListBooks(ListBooksRequest) returns (ListBooksResponse) {
  // List method maps to HTTP GET.
  option (google.api.http) = {
    // The `parent` captures the parent resource name, such as "shelves/shelf1".
    get: "/v1/{parent=shelves/*}/books"
  };
}
```
这种写法的好处就是可以获取 parent 的信息，如shelves/no1 或则 users/jone， 然后我可以通过分割字符串获取具体的资源组信息，如 shelves，它的编号是 no1. 又如 users，他的名字是 jone

**Comment by shenqidebaozi** [comment]
暂时不支持这种复杂写法。

**Comment by longXboy** [comment]
#1704 现在支持了

**Comment by xiak** [comment]
@longXboy 感谢感谢 Nice work, 我下来测试下
