### ISSUE TITLE
[Feature] Kratos UI Service Governance Platform（xDS）

### ISSUE THREAD

**Issue by shenqidebaozi** [go-kratos/kratos#1654]
`Kratos UI` is a `Microservice` governance platform based on `Kratos` ecology. 

## Kratos API
Provide gRPC API service, notify configuration and instance changes through streaming.

- auth 
- config
- registry 

## Kratos UI (antd)
Service management platform.

- Dashboard
- Services
- Nodes
- APIs
- Policies
- Configurations
- Authentications

## References
- https://sf.163.com/product/qz
- https://cloud.baidu.com/product/cnap.html

**Comment by shenqidebaozi** [comment]
### proxyless service mesh(X Discovery Service/ gRPC)
- https://www.servicemesher.com/istio-handbook/ecosystem/xds.html
- https://jimmysong.io/istio-handbook/data-plane/envoy-xds-protocol.html
- https://pkg.go.dev/google.golang.org/grpc/xds
- https://github.com/grpc/proposal/blob/master/A27-xds-global-load-balancing.md#xdsclient-and-bootstrap-file
#### exampls
- https://github.com/feuyeux/hello_xds
- https://github.com/salrashid123/grpc_xd
- [[译文]xDS REST and gRPC protocol.pdf](https://github.com/go-kratos/kratos/files/7780369/xDS.REST.and.gRPC.protocol.pdf)
- [Proxyless Service Mesh With gRPC.pdf](https://github.com/go-kratos/kratos/files/7780370/Proxyless.Service.Mesh.With.gRPC.pdf)
- [Service Mesh with gRPC and xDS.pdf](https://github.com/go-kratos/kratos/files/7780371/Service.Mesh.with.gRPC.and.xDS.pdf)

**Comment by longXboy** [comment]
six six six

**Comment by zohar-soul** [comment]
https://github.com/go-kratos/kratos/issues/1616
这个最近有什么进展吗?  我看从v2.3.0里程碑中移除了
@shenqidebaozi

**Comment by shenqidebaozi** [comment]
@zohar-soul 可以看下 openSergo 会直接对接这个

**Comment by zohar-soul** [comment]
> @zohar-soul 可以看下 openSergo 会直接对接这个

感谢大佬, 我去了解一下. 
顺便问下有大约可能体验的时间节点吗?

**Comment by shenqidebaozi** [comment]
XDS-服务治理：
服务发现（注册、发现）
流量调度（动态路由、负载均衡）
熔断降级（实例、接口、服务熔断）
访问控制（ 限流、鉴权）

**Comment by fredmuyu** [comment]
@shenqidebaozi 大佬，这个被重新打开 是要有什么新的进度吗？
