### ISSUE TITLE
[Feature] transport name to distinguish

### ISSUE THREAD

**Issue by to2false** [go-kratos/kratos#1655]
Please see the FAQ in our main README.md before submitting your issue.

### What problem is the feature used to solve?
If I want to start two http server (gin, metrics) with no specified port setting, the start log can't tell which service occupies which port, just tell `[HTTP] server listening on: %s`

### Requirements description of the feature
Can set the name and then print it out when start

### References

https://github.com/go-kratos/kratos/blob/main/transport/transport.go#L34
https://github.com/go-kratos/kratos/blob/main/transport/http/server.go#L252
https://github.com/go-kratos/kratos/blob/main/transport/grpc/server.go#L180

**Comment by Casper-Mars** [comment]
Hi~ Could you name one use case that without port setting?

**Comment by to2false** [comment]
Not a very formal environment, such as local
I usually default to a random port for the metrics service to avoid conflicts when running multiple projects.

```
Gin server: 8080
Metrics server: 23456
Another metrics server: 34567
```

The console sees this result
```
[HTTP] server listening on: 8080
[HTTP] server listening on: 23456
[HTTP] server listening on: 34567
```

I wanna add a identifier to distinguish, work like this
```
[HTTP] gin server listening on: 8080
[HTTP] metrics server listening on: 23456
[HTTP] another metrics server listening on: 34567
```

**Comment by shenqidebaozi** [comment]
Due to the registration logic problem, if a random port is used, the program cannot get which port is registered.

**Comment by to2false** [comment]
The above example is meant to illustrate multiple services.

**Comment by to2false** [comment]
Just want a way to distinguish between service names, not just by judging ports

**Comment by shenqidebaozi** [comment]
Is the PR of the above feature the function you want

**Comment by to2false** [comment]
https://github.com/go-kratos/kratos/pull/1661 This PR achieves a similar effect, without seeing a reason why it is closed
