### ISSUE TITLE
[Question]选择了2.1.1版本进行make install,查看版本却是2.1.0?

### ISSUE THREAD

**Issue by ColeZia** [go-kratos/kratos#1658]
从releases下载了2.1.1版本后make install , kratos -v 显示是2.1.0,这个是什么问题呢？
看了下version.go 版本是v2.1.1,但是好像并没有被引用到

**Comment by shenqidebaozi** [comment]
之前版本号可能有点问题，现在是在插件内部维护版本号了。

**Comment by ColeZia** [comment]
> 之前版本号可能有点问题，现在是在插件内部维护版本号了。

好的
