### ISSUE TITLE
[Question]go install安装不成功，在一个corp proxy后面只拉取了V1.0

### ISSUE THREAD

**Issue by xiaods** [go-kratos/kratos#1659]
在外网可以下载。在内网一个nexus proxy后面，go install报错
```
$ go install github.com/go-kratos/kratos/cmd/kratos/v2@latest
go: downloading github.com/go-kratos/kratos v1.0.1
go install: github.com/go-kratos/kratos/cmd/kratos/v2@latest: module github.com/go-kratos/kratos@latest found (v1.0.1), but does not contain package github.com/go-kratos/kratos/cmd/kratos/v2
```

**Comment by Windfarer** [comment]
用GOPROXY=https://goproxy.cn指定到外网的proxy去拉，或者找nexus的维护者看看为什么没有同步上游

**Comment by xiaods** [comment]
> 用 GOPROXY=https://goproxy.cn 指定到外网的proxy去拉，或者找nexus的维护者看看为什么没有同步上游

谢谢

**Comment by xiaods** [comment]
采用的是nexus go plugin，在库中发现是v1.0版本的。
![image](https://user-images.githubusercontent.com/37678/143846464-d71696c6-346f-45bf-9b18-77d007b775c9.png)

这个谁有经验，如何让proxy更新到V2

**Comment by xiaods** [comment]
go get -u github.com/go-kratos/kratos/cmd/kratos/v2@latest 加上代理就获得不了正确的V2版本
```
go get: module github.com/go-kratos/kratos@latest found (v1.0.1), but does not contain package github.com/go-kratos/kratos/cmd/kratos/v2
```

**Comment by xiaods** [comment]
我们在私有云使用这个框架，发现没有相关文档。还请帮忙看看

**Comment by haiyux** [comment]
这个你用的代理的问题吧。。

**Comment by xiaods** [comment]
> nexus

是的。让运维在nexus go proxy加了goproxy.io，就好了。goproxy.cn、阿里go proxy都还不行
