### ISSUE TITLE
关于配置热加载的问题

### ISSUE THREAD

**Issue by guihouchang** [go-kratos/kratos#1672]
#### What happened:
启动服务后，再修改配置出现报错

#### What you expected to happen:
ERROR msg=failed to watch next config: open ../../configs/test/test: no such file or directory
ERROR msg=failed to watch next config: open ../../configs/test/test: no such file or directory
ERROR msg=failed to watch next config: open ../../configs/test/test: no such file or directory
ERROR msg=failed to watch next config: open ../../configs/test/test: no such file or directory
ERROR msg=failed to watch next config: open ../../configs/test/test: no such file or directory

#### How to reproduce it (as minimally and precisely as possible):
[helloworld.zip](https://github.com/go-kratos/kratos/files/7674915/helloworld.zip)
里面有app/helloworld下 make run 后 再修改配置即可复现
#### Environment:
- Kratos version (use `kratos -v`):
- kratos version v2.1.2
- Go version (use `go version`):
- go version go1.17.2 darwin/arm64
- OS (e.g: `cat /etc/os-release`):
- macbook pro m1
- Others:

**Comment by Casper-Mars** [comment]
按照描述的步骤，在x86_64上无法复现

**Comment by guihouchang** [comment]
经过测试用goland的ide会生成一个config.yaml~的临时文件，watch会以为有新文件创建。导致一系列的热加载问题。
