### ISSUE TITLE
[Feature] support polarismesh registry

### ISSUE THREAD

**Issue by chuntaojun** [go-kratos/kratos#1685]
Please see the FAQ in our main README.md before submitting your issue.

### What problem is the feature used to solve?

We hope to achive registry interface to Kratos framework to access middleware polarismesh

### Requirements description of the feature

1. Service registration discovery can be realized through polarismesh

### References

- [polarismesh](https://github.com/polarismesh/polaris)

**Comment by chuntaojun** [comment]
If the community accepts it, I can participate in submitting contributions

**Comment by longXboy** [comment]
ok, it will be supported in release 2.1.4

**Comment by huyuanxin** [comment]
registry is merged
discovery is await

**Comment by chuntaojun** [comment]
nice
