### ISSUE TITLE
运行例子 examples\registry\discovery 失败

### ISSUE THREAD

**Issue by mjtansin** [go-kratos/kratos#1689]
#### What happened:
1. go to kratos\examples\registry\discovery\server
2. go run  main.go
会不停产生如下错误日志
`ERROR registry.pluginName=Discovery ts=2021-12-14T10:57:57+08:00 caller=discovery.go:410 msg=Discovery: client.Get(http://0.0.0.0:7171/discovery/polls?appid=infra.discovery&env=dev&hostname=localhost&latest_timestamp=0) error(Get "http://0.0.0.0:7171/discovery/polls?appid=infra.discovery&env=dev&hostname=localhost&latest_timestamp=0": dial tcp 0.0.0.0:7171: connectex: No connection could be made because the target machine actively refused it.)`
7171端口一直是SYN_SENT状态
`netstat -aon|findstr "7171"
  TCP    127.0.0.1:56974        127.0.0.1:7171         SYN_SENT        16700`
#### What you expected to happen:
正常运行，没有错误日志产生
#### Environment:
- Kratos version (use `kratos -v`):
- Go version (use `go version`):1.16.2
- OS (e.g: `cat /etc/os-release`):windows10
- Others:

**Comment by haiyux** [comment]
没有复现 我这是正常的
