### ISSUE TITLE
The micro service registered with consul by Kratos cannot be called normally by spring cloud

### ISSUE THREAD

**Issue by kingdom2014** [go-kratos/kratos#1690]
#### What happened:
kratos 向consul注册时采用TaggedAddresses存储grpc和http服务的ip和port，并永远选择第一个checkAddresses的ip和port作为微服务的ip和port。该写法与spring cloud的写法不兼容，导致spring cloud 无法正常调用 kratos提供的http接口。
#### What you expected to happen:
希望kratos 将 grpc和http注册方式能与spring cloud保持一致，达到相互调用http接口的目的，实现一定的跨语言能力。

**Comment by letian0805** [comment]
PR #1730  加了个 Filter 解决这个问题

**Comment by letian0805** [comment]
@kingdom2014 PR #1730 配合 PR #1729 再加上用 cmux 做端口复用，可以解决你的问题
