### ISSUE TITLE
[Question] 关于error中自定义错误消息，有最佳实践方案吗

### ISSUE THREAD

**Issue by guihouchang** [go-kratos/kratos#1691]
Please see the FAQ in our main README.md before submitting your issue.
现在validate中间件验证失败返回的是自带的英文提示，这样子不利于用户交互。所以有什么最佳实践方案吗

**Comment by shenqidebaozi** [comment]
validate 中间件基于的是 PGV，你可以自己做 mapping 映射。映射 PGV 英文错误 到中文错误

**Comment by shenqidebaozi** [comment]
或者给 PGV 提 issue，问他们如何实现国际化

**Comment by guihouchang** [comment]
PGV现在有个 [https://github.com/envoyproxy/protoc-gen-validate/pull/398](https://github.com/envoyproxy/protoc-gen-validate/pull/398) 只是还没合并，在合并之前想找个替代的方案。 上面的说替换中英文好像不太好实现

**Comment by shenqidebaozi** [comment]
> PGV现在有个 [envoyproxy/protoc-gen-validate#398](https://github.com/envoyproxy/protoc-gen-validate/pull/398) 只是还没合并，在合并之前想找个替代的方案。 上面的说替换中英文好像不太好实现

PGV 效率贼低，可以先考虑做 mapping 映射。

**Comment by gabriel614k** [comment]
> > PGV现在有个 [envoyproxy/protoc-gen-validate#398](https://github.com/envoyproxy/protoc-gen-validate/pull/398) 只是还没合并，在合并之前想找个替代的方案。 上面的说替换中英文好像不太好实现
> 
> PGV 效率贼低，可以先考虑做 mapping 映射。

@shenqidebaozi 请问大佬有mapping的例子吗？不胜感激！

**Comment by lovephalcon1990** [comment]
> > > PGV现在有个 [envoyproxy/protoc-gen-validate#398](https://github.com/envoyproxy/protoc-gen-validate/pull/398) 只是还没合并，在合并之前想找个替代的方案。 上面的说替换中英文好像不太好实现
> > 
> > 
> > PGV 效率贼低，可以先考虑做 mapping 映射。
> 
> @shenqidebaozi 请问大佬有mapping的例子吗？不胜感激！

![image](https://user-images.githubusercontent.com/7123896/216257233-b9afb3b6-1472-41c7-9cfd-d1fa9b9af17b.png)
重写Server ene属性
![image](https://user-images.githubusercontent.com/7123896/216257482-8e024b4b-8ab3-4a01-813f-8208e07086fa.png)
