### ISSUE TITLE
biz和service目录应该怎么用呢？

### ISSUE THREAD

**Issue by iiaiaia** [go-kratos/kratos#1695]
我的困惑来自于文档的描述：

- biz   // 业务逻辑的组装层，类似 DDD 的 domain 层，data 类似 DDD 的 repo，而 repo 接口在这里定义，使用依赖倒置的原则。
- service  // 实现了 api 定义的服务层，类似 DDD 的 application 层，处理 DTO 到 biz 领域实体的转换(DTO -> DO)，同时协同各类 biz 交互，但是不应处理复杂逻辑

具体的疑问是：
1. kratos/examples/blog/internal/biz/article.go文件中定义的 Article struct，是和数据库的 Article 表对应的吗？如果不是的话，和数据库的表结构 对应的 struct 应该定义在哪个目录下？（这文件的内容第一眼看上去真的很让人迷惑）
2. 能再描述一下 biz 目录和 service 目录各自的作用吗？文档用DDD做比喻，不是很理解
3. 如果有一个特别复杂的业务逻辑，应该写在哪里，如何组织呢？
4. "Please see the FAQ in our main README.md before submitting your issue." 这个 FAQ 在 README.md 的哪里呀？https://github.com/go-kratos/kratos/blob/main/README.md

提前谢谢各位

**Comment by shenqidebaozi** [comment]
1. 数据库表对应的 struct 应该定义在 data 目录下 data(po) -> biz(do) -> service(dto)
2. biz 用于封装业务逻辑，service 做 DO <-> DTO 的转换。
3. 业务逻辑应该写在 biz
4. FAQ 在官网文档上，readme 指的是项目根目录下的 readme。
