### ISSUE TITLE
[Question]关于kratos的认证和鉴权有点疑问

### ISSUE THREAD

**Issue by ReaderZhang** [go-kratos/kratos#1699]
1. kratos的认证和鉴权里面的server和client作用分别是什么以及examples中的demo如何去理解？
2. springcloud项目中有gateway这个组件可以对路由进行路由重写和鉴权，kratos有没有能做到统一鉴权的工具？

**Comment by Casper-Mars** [comment]
Hi~
server 是用于构造server端的的中间件，client则用于构造client端的中间件（下游服务的client，并不是外部前端的client）。examples中的demo是简单地演示用法，具体的使用请看beer-shop。kratos暂时没有提供统一鉴权的工具。
