### ISSUE TITLE
是否考虑多微服务模板？？

### ISSUE THREAD

**Issue by shuqingzai** [go-kratos/kratos#1708]
现在新建项目，都是单个微服务版本的模板，一般一个项目都是由多个微服务组合而成，目前新建模板，可能需要管理n多个微服代码，犹如 IDE需要打开多个， go mod 都是分开， proto文件也是独立，我看到 [beer-shop](https://github.com/go-kratos/beer-shop) 中，是结合了多个微服务的管理，但是也看到 [issue12](https://github.com/go-kratos/beer-shop/issues/12) 有提到这点，能否在 创建模板的时候，可以加入参数，生成微服务版本的模板呢？？统一化生成模板好使

**Comment by shenqidebaozi** [comment]
这个问题完全可以自己设计一个 monorepo 的 layout 模板，然后通过 kratos new xxx -r xxxx.git 来指定 repo.

**Comment by codingcn** [comment]
看这个：https://github.com/codingcn/kratos-mono-repo/tree/main

**Comment by bilinxing** [comment]
> 这个问题完全可以自己设计一个 monorepo 的 layout 模板，然后通过 kratos new xxx -r xxxx.git 来指定 repo.

layout模板可以解决新项目创建，但是在存量项目中新增service还是要复制粘贴。如果脚手架工具提供类似：kratos mono 
 service add  xxx 命令，无论是创建新项目还是旧项目新增service都很方便。
