### ISSUE TITLE
[bug]consul注册中心，增加实例，实例数一直是1个，被替换的实例(放k8s多个副本，应该多个实例才对的)

### ISSUE THREAD

**Issue by hshe** [go-kratos/kratos#1711]
#### What happened:
consul注册中心，起了多个相同的服务(不同机器)，注册的实例只有一个。
#### What you expected to happen:
应该起我多少服务，就有多少实例。
#### How to reproduce it (as minimally and precisely as possible):
![image](https://user-images.githubusercontent.com/8075773/147254810-e668e83a-b729-4d8b-a313-9674100b963a.png)

#### Environment:
- Kratos version (use `kratos -v`):2.1.3
- Go version (use `go version`):1.17.5
- OS (e.g: `cat /etc/os-release`):linux
- Others:

**Comment by hshe** [comment]
补充：（起了多个服务）关掉其中一个，注册中心的服务就消失了，应该是实例减1。

**Comment by AlstonWilliams** [comment]
这个你是怎么解决的？我也遇到了这个问题，consul里面一直都是只有一个实例 @hshe

**Comment by hshe** [comment]
> 
main入口使用的id动态生成就可以了
![image](https://user-images.githubusercontent.com/8075773/186587435-ac5fe72a-01ce-4666-b75a-a34e74a871d0.png)
