### ISSUE TITLE
[Feature]  请求增加server.Listener(lis net.Listener) Option 方法，便于集成cmux库，在单一port中，同时提供http和grpc服务

### ISSUE THREAD

**Issue by ziguss** [go-kratos/kratos#1714]
我想在单一port中，同时提供http和grpc协议的服务。按目前transport.Server的实现，无法做到，希望能增加server.Listener(lis net.Listener)，可以自定义Listener。

**Comment by letian0805** [comment]
代码我早就实现了，不过kratos项目组不大乐意支持这一特性。这里是PR https://github.com/go-kratos/kratos/pull/1470
你可以用我 fork 出来的仓库 replace

**Comment by ziguss** [comment]
> 

感谢关注。其实我要的很简单，就是kratos能支持下Listener Option，然后在edpoint中判断下是否有lis，有就使用，不然使用addr和port自己Listen一个，整个代码改动量极小且和目前的所有特性都不冲突，给用户多一个选择。另外，之所以提给社区，不自己fork，是想和社区版本保持一致。

**Comment by letian0805** [comment]
> 

哈哈，你看我提的PR，够简单吧

**Comment by ziguss** [comment]
> > 
> 
> 哈哈，你看我提的PR，够简单吧

是的，看了force push后的代码，是够简单了，是我想要的
