### ISSUE TITLE
[Question]请问kratos proto 使用的是哪个protoc-gen-openapi版本？

### ISSUE THREAD

**Issue by olongfen** [go-kratos/kratos#1723]
### 我执行 go generate ./... 出现以下错误；我系统有protoc-gen-openapiv2二进制版本
protoc-gen-openapi: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--openapi_out: protoc-gen-openapi: Plugin failed with status code 1.
exit status 1

**Comment by olongfen** [comment]
已经解决: go get -u github.com/go-kratos/swagger-api

**Comment by olongfen** [comment]
go get github.com/google/gnostic
    go install github.com/google/gnostic/apps/protoc-gen-openapi

**Comment by shenqidebaozi** [comment]
@olongfen  嗯，用的是 gnostic 的，不是 grpc gateway 里面的 proto-gen-openapi-v2
