### ISSUE TITLE
consul服务注册和发现两个问题

### ISSUE THREAD

**Issue by letian0805** [go-kratos/kratos#1727]
问题1：服务A已起来，但其他服务在20秒内无法发现服务A，原因是默认健康检查间隔 20 秒
问题2：服务A启动时去发现其他服务，结果无法找到节点，原因是consul的服务发现底层目前是异步的，需要先同步请求一次

**Comment by longXboy** [comment]
异步不会导致无法发现节点，异步线程拉到了就会立即通知上层的watcher

**Comment by letian0805** [comment]
> 

是这样的，有时候会需要在服务启动前初始化一些东西，依赖其他服务。如果异步还没等到consul返回数据，就会导致请求其他服务报无法找到节点，只能sleep一段时间再请求其他服务。但这个sleep多少，不好把控，也不应该由用户来把控。我改的代码会同步请求一次consul，解决这个问题。
