### ISSUE TITLE
[Feature]proxyless service mesh(X Discovery Service)

### ISSUE THREAD

**Issue by longXboy** [go-kratos/kratos#1747]
We are planning to support the xds protocol in kratos

https://www.servicemesher.com/istio-handbook/ecosystem/xds.html
https://jimmysong.io/istio-handbook/data-plane/envoy-xds-protocol.html
https://pkg.go.dev/google.golang.org/grpc/xds
https://github.com/cncf/xds
https://github.com/grpc/proposal/blob/master/A27-xds-global-load-balancing.md#xdsclient-and-bootstrap-file
[译文]xDS REST and gRPC protocol.pdf
Proxyless Service Mesh With gRPC.pdf
Service Mesh with gRPC and xDS.pdf
xds protool
exampls
https://github.com/feuyeux/hello_xds
https://github.com/salrashid123/grpc_xd

**Comment by longXboy** [comment]
第一期先支持
RDS        Route Discovery Service        路由发现服务
CDS        Cluster Discovery Service        集群发现服务
EDS        Endpoint Discovery Service        集群成员发现服务

**Comment by shenqidebaozi** [comment]
#1654

**Comment by leyou240** [comment]
grpc-go官方库似乎想自己实现xds：https://github.com/grpc/grpc-go/blob/master/examples/features/xds/README.md
