### ISSUE TITLE
[Feature] 关于数组对象的配置合并

### ISSUE THREAD

**Issue by starryrbs** [go-kratos/kratos#1750]
Please see the FAQ in our main README.md before submitting your issue.

### What problem is the feature used to solve?

希望配置合并可以合并多个yaml文件的数组对象，例如: 

a.yaml

```
targets:
  - topic: server1
    group: v2
```

b.yaml

```
targets:
  - topic: server2
    group: v3
```

期望`.Load`得到的结构为:

```
{
  "targets": [
    {
      "topic": "server1",
      "group": "v2"
    },
    {
      "topic": "server2",
      "group": "v3"
    }
  ]
}
```

**Comment by kagaya85** [comment]
这个issue之前有讨论过，通过自定义decoder（`config.WithDecoder`）的方式应该可以满足你的需求，kratos目前应该不会支持

参考 #1414 #1344
