### ISSUE TITLE
生成proto源码 时报错

### ISSUE THREAD

**Issue by bamboo-cp3** [go-kratos/kratos#1756]
#### What happened:
PS E:\demo\helloworld> kratos upgrade
go install github.com/go-kratos/kratos/cmd/kratos/v2@latest
go install github.com/go-kratos/kratos/cmd/protoc-gen-go-http/v2@latest
go install github.com/go-kratos/kratos/cmd/protoc-gen-go-errors/v2@latest
go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
go install github.com/envoyproxy/protoc-gen-validate@latest
go install github.com/google/gnostic@latest
go install github.com/google/gnostic/apps/protoc-gen-openapi@latest
go install: github.com/google/gnostic/apps/protoc-gen-openapi@latest: module github.com/google/gnostic@latest found (v0.6.2), but does not contain package github.com/google/gnostic/apps/protoc-gen-openapi
exit status 1
#### What you expected to happen:
执行kratos upgrade 或者 生成proto源码 时报错
#### Anything else we need to know?:
github.com/google/gnostic@latest 最新版是v0.6.2，该版本没有 protoc-gen-openapi
#### Environment:
- Kratos version (use `kratos -v`):kratos version v2.1.4
- Go version (use `go version`):go1.17 windows/amd64
- OS (e.g: `cat /etc/os-release`):windows
- Others:

**Comment by shenqidebaozi** [comment]
go install github.com/google/gnostic/cmd/protoc-gen-openapi@v0.6.1

**Comment by shenqidebaozi** [comment]
https://github.com/go-kratos/kratos-layout/pull/72/files

**Comment by stardemo** [comment]
gnostic 6.0 把apps修改成了cmd, 5.7是apps
