### ISSUE TITLE
正常json中为啥需要在加入根据value的struct来Marshal? 这样http api如果用protobuf生成，api中header参数accept选择为json也没有什么意义了

### ISSUE THREAD

**Issue by ybdx** [go-kratos/kratos#1760]
Please see the FAQ in our main README.md before submitting your issue.

**Comment by shenqidebaozi** [comment]
I don't understand what you mean. Can you describe it in detail?

**Comment by shenqidebaozi** [comment]
In addition, the problem details should not be described in the title. Please resubmit an issue
