### ISSUE TITLE
[Question] How to write gorm transaction in biz directory

### ISSUE THREAD

**Issue by iiaiaia** [go-kratos/kratos#1764]
如果把gorm的事务写在biz目录下，怎么写比较好？有例子吗？

**Comment by JerryZhou343** [comment]
用闭包

**Comment by bytegolang** [comment]
https://github.com/go-kratos/kratos/tree/main/examples/transaction

**Comment by CYARXGBF** [comment]
> https://github.com/go-kratos/kratos/tree/main/examples/transaction

d.db改为d.DB(ctx)改为是否更好？

```go
func (d *Data) ExecTx(ctx context.Context, fn func(ctx context.Context) error) error{
	return d.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		ctx = context.WithValue(ctx, contextTxKey{}, tx)
		return fn(ctx)
	})
}

// d.db改为d.DB(ctx)
func (d *Data) ExecTx(ctx context.Context, fn func(ctx context.Context) error) error{ 
	return d.DB(ctx).WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		ctx = context.WithValue(ctx, contextTxKey{}, tx)
		return fn(ctx)
	})
}
```

原因：如果一个方法多次调用`ExecTx`，就会创建了多个事务，事务间会产生竞争，而且无法使用嵌套事务

```go
func (u *UserUsecase) CreateUser(ctx context.Context, m *User) (int, error) {
	var (
		err error
		id  int64
	)
	err = u.tm.ExecTx(ctx, func(ctx context.Context) error {
		id, err = u.userRepo.CreateUser(ctx, m)
		if err != nil {
			return err
		}
        // 调用UpdateUser时，会开启一个新事务
        _,err = u.UpdateUser(ctx,m)
        if err != nil {
			return err
		}
        
		return nil
	})
	if err != nil {
		return 0, err
	}
	return int(id), nil
}


func (u *UserUsecase) UpdateUser(ctx context.Context, m *User) (int, error) {
	err = u.tm.ExecTx(ctx, func(ctx context.Context) error {
        // 如果是Mysql的话，UpdateUser的事务会和CreateUser的事务产生竞争，出现错误：
        // Lock wait timeout exceeded; try restarting transaction
		id, err = u.userRepo.UpdateUser(ctx, m)
		if err != nil {
			return err
		}
		return nil
	})
	if err != nil {
		return 0, err
	}
	return int(id), nil
}

```

**Comment by piupuer** [comment]
> > https://github.com/go-kratos/kratos/tree/main/examples/transaction
> 
> d.db改为d.DB(ctx)改为是否更好？
> 
> ```go
> func (d *Data) ExecTx(ctx context.Context, fn func(ctx context.Context) error) error{
> 	return d.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
> 		ctx = context.WithValue(ctx, contextTxKey{}, tx)
> 		return fn(ctx)
> 	})
> }
> 
> // d.db改为d.DB(ctx)
> func (d *Data) ExecTx(ctx context.Context, fn func(ctx context.Context) error) error{ 
> 	return d.DB(ctx).WithContext(ctx).Transaction(func(tx *gorm.DB) error {
> 		ctx = context.WithValue(ctx, contextTxKey{}, tx)
> 		return fn(ctx)
> 	})
> }
> ```
> 
> 原因：如果一个方法多次调用`ExecTx`，就会创建了多个事务，事务间会产生竞争，而且无法使用嵌套事务
> 
> ```go
> func (u *UserUsecase) CreateUser(ctx context.Context, m *User) (int, error) {
> 	var (
> 		err error
> 		id  int64
> 	)
> 	err = u.tm.ExecTx(ctx, func(ctx context.Context) error {
> 		id, err = u.userRepo.CreateUser(ctx, m)
> 		if err != nil {
> 			return err
> 		}
>         // 调用UpdateUser时，会开启一个新事务
>         _,err = u.UpdateUser(ctx,m)
>         if err != nil {
> 			return err
> 		}
>         
> 		return nil
> 	})
> 	if err != nil {
> 		return 0, err
> 	}
> 	return int(id), nil
> }
> 
> 
> func (u *UserUsecase) UpdateUser(ctx context.Context, m *User) (int, error) {
> 	err = u.tm.ExecTx(ctx, func(ctx context.Context) error {
>         // 如果是Mysql的话，UpdateUser的事务会和CreateUser的事务产生竞争，出现错误：
>         // Lock wait timeout exceeded; try restarting transaction
> 		id, err = u.userRepo.UpdateUser(ctx, m)
> 		if err != nil {
> 			return err
> 		}
> 		return nil
> 	})
> 	if err != nil {
> 		return 0, err
> 	}
> 	return int(id), nil
> }
> ```

其中这段代码
```
// 调用UpdateUser时，会开启一个新事务
_,err = u.UpdateUser(ctx,m)
```
为什么不可以改成
```
u.userRepo.UpdateUser(ctx, m)
```
