### ISSUE TITLE
Warden 关于Server端服务重启后 Client 连接断开之后的重试问题

### ISSUE THREAD

**Issue by zyi1992** [go-kratos/kratos#177]
grpc的服务端在重启后 客户端的请求会获取到 code = Unavailable 的异常 而在其它语言中 比如python 如果不主动处理异常 进程则会崩溃 所以需要主动进行重试 然后重新建立连接 所以想问下Warden 是如何处理这种情况的。如果能有自动重试的机制 应该是最好的

**Comment by longXboy** [comment]
@zyi1992 
你的意思是每一次RPC Call，如果出现了网络错误或者服务端的异常情况，客户端收到Unavailable的异常后自动重试是吧？

**Comment by zyi1992** [comment]
@longXboy 是的  一种做法是自己手动捕获异常 然后重试 但是不通用

**Comment by longXboy** [comment]
@zyi1992 考虑到某些接口的幂等性问题，这块Warden暂时是没有做处理。后面我们会加入一个可选的配置（或者是一个CallOption）来控制这块自动重试的逻辑
