### ISSUE TITLE
[Question] kratos如何接收结构不固定的请求

### ISSUE THREAD

**Issue by a245589351** [go-kratos/kratos#1771]
kratos如何接收结构不固定的请求

**Comment by shenqidebaozi** [comment]
可以使用 anypb 或者 structpb

**Comment by a245589351** [comment]
这种看起来需要先定义对应的字段名。如果一个请求，我们预先并不知道结构，比如是一个form，这种应当如何接收呢

**Comment by a245589351** [comment]
场景是用于接收第三方的异步通知，发送方为第三方，我方为接收方，第三方的发送的消息结构不固定

**Comment by shenqidebaozi** [comment]
structpb

**Comment by shenqidebaozi** [comment]
或者掏洞单独注册一个路由，类似 examples/http/upload
