### ISSUE TITLE
TTL check is not added when consul starts heartbeat

### ISSUE THREAD

**Issue by RaynorGu** [go-kratos/kratos#1775]
![image](https://user-images.githubusercontent.com/7893714/149866077-8cde2c5a-bb4d-4e06-92e6-e4e1ec607810.png)
UpdateTTL 会报以下错误:

Unexpected response code: 500 (CheckID "xxx" does not have associated TTL)

**Comment by Casper-Mars** [comment]
The TTL-check and TCP-check cannot both be used. PTAL @tonybase @haiyux @Windfarer
