### ISSUE TITLE
nacos无法作为服务中心，服务注册与服务发现

### ISSUE THREAD

**Issue by shuqingzai** [go-kratos/kratos#1782]
#### What happened:
nacos 作为服务注册中心，注册时，服务名称会拼接 kind ，但是在服务发现时，却没有去除这个，导致无法做服务中心，每次服务发现都需要手动追加拼接 kind ，如果切换别的注册中心，又不一致
![image](https://user-images.githubusercontent.com/44406033/150623088-c4e73535-10fd-49d8-b005-dc30b3b917c0.png)
![image](https://user-images.githubusercontent.com/44406033/150623091-a386bf70-c8ee-4037-9a5a-382ac909a619.png)
![image](https://user-images.githubusercontent.com/44406033/150623181-de454e4b-54e0-4b6a-8810-14f1221e5853.png)

#### What you expected to happen:
应该与consul注册保持一致，获取内部自动转换，无需人工手动转换，保证注册中心输出对外一致性

#### How to reproduce it (as minimally and precisely as possible):
使用nacos作为注册中心，即可复现该问题

#### Environment:
- Kratos version (use `kratos -v`):
- kratos version v2.1.4
- Go version (use `go version`):
- go version go1.16.12 darwin/amd64
- OS (e.g: `cat /etc/os-release`):
- macOS
- Others:

**Comment by shenqidebaozi** [comment]
群里已经回复过了，关闭了
