### ISSUE TITLE
后期是否考虑添加 db orm？

### ISSUE THREAD

**Issue by busyfree** [go-kratos/kratos#179]
现在的框架里对mysql封装只有基础的部分，是否考虑加入db orm支持？

**Comment by sandacn** [comment]
memcache 和 redis 都是基础封装，我建议 redis 换成 [go-redis](https://github.com/go-redis/redis) 
当时没有用 kratos 默认的封装是因为封装的太初级了，对应的类型还需要自己处理一遍，这个没有很大的意义。

只支持一个实例的连接，我倒是没有意见，这个可以用中间层服务来扩展，比如推荐的 overlord。

我在使用的过程中，也没有用 mysql 的封装，用的是 xorm，主要是在 insert 和 update 的时候有大量重复的代码，这个时候用orm就比较合适。

但是我觉得一般意义上的 orm 做得事情还是太多了，裸写 sql，我觉得这个是可以的，而且为了定位问题方便，裸写查询的sql，还是很有意义。我觉得可以的话，可以做一个简单版本的 orm。

**Comment by orca-zhang** [comment]
> memcache 和 redis 都是基础封装，我建议 redis 换成 [go-redis](https://github.com/go-redis/redis)
> 当时没有用 kratos 默认的封装是因为封装的太初级了，对应的类型还需要自己处理一遍，这个没有很大的意义。
> 
> 只支持一个实例的连接，我倒是没有意见，这个可以用中间层服务来扩展，比如推荐的 overlord。
> 
> 我在使用的过程中，也没有用 mysql 的封装，用的是 xorm，主要是在 insert 和 update 的时候有大量重复的代码，这个时候用orm就比较合适。
> 
> 但是我觉得一般意义上的 orm 做得事情还是太多了，裸写 sql，我觉得这个是可以的，而且为了定位问题方便，裸写查询的sql，还是很有意义。我觉得可以的话，可以做一个简单版本的 orm。

确实go-redis设计范式会更好一些。

redigo主要是类似：
1. 连接归还（defer redis.Close()）
2. pipeline方法(Send/Receive不匹配或者Send和Do混用)
极易造成事故

且已经经历or听闻多起类似原因导致的p0/A级事故

**Comment by orca-zhang** [comment]
这里有一个实验室版本：
https://github.com/orca-zhang/borm

已在2+家上市公司的生产环境中使用，会持续完善和修复改进

**Comment by Terry-Mao** [comment]
@busyfree 我们内部讨论过这个问题，目前大家倾向是，使用简单的sql builder来替代手动组装SQL，另外我不太喜欢完整的ORM，而是类似mybaits这种方式，通过mapping struct，以及可见的sql语句，感觉更加的安全， @orca-zhang 要不要考虑下。

**Comment by Terry-Mao** [comment]
@sandacn 你好，我们的memcache、redis 封装主要是针对 trace、超时传递处理、慢查询日志，协议抽象，连接池封装，比如memcache我们已经改好了对外不暴露Pool.Close() 这类的操作，redis正在开发。

至于go-redis，我个人不是非常建议，处于几个考虑，你参考下我们的 #20 ，go-redis 是对指令全部展开，这样redis每次变更指令，意味着基础库升级，非常的不灵活，而且这样基于redis协议可以无限扩展使用任意的组合和其他实现了redis协议的server，更加的灵活。类型转换会考虑redis库暴露一些Helper出来。不知道有何更好的意见？

**Comment by sandacn** [comment]
> @sandacn 你好，我们的memcache、redis 封装主要是针对 trace、超时传递处理、慢查询日志，协议抽象，连接池封装，比如memcache我们已经改好了对外不暴露Pool.Close() 这类的操作，redis正在开发。
> 
> 至于go-redis，我个人不是非常建议，处于几个考虑，你参考下我们的 #20 ，go-redis 是对指令全部展开，这样redis每次变更指令，意味着基础库升级，非常的不灵活，而且这样基于redis协议可以无限扩展使用任意的组合和其他实现了redis协议的server，更加的灵活。类型转换会考虑redis库暴露一些Helper出来。不知道有何更好的意见？

我大概理解你的意思，pipeline 里面可以加入很多操作，而每个操作又在基本函数中定义过。这样维护起来不方便。
我倒是觉得这个还好，工作量还OK，毕竟它增加命令的次数不是很频繁。
我这里觉得比较需要的是一个高级语言和IDE 的帮助提示，这样会犯更少的错误。我举一个简单的例子：
```go
func (r *Redis) Get(key string) (string, error) {
	return r.Redis.Get(key).Result()
}

func (r *Redis) Set(key string, val string, expireTs int64) error {
	setRet := r.Redis.Set(key, val, time.Duration(expireTs))
	return setRet.Err()
}

func (r *Redis) HMSet(key string, fields map[string]string) error {
	iData := make(map[string]interface{}, len(fields))
	for k, v := range fields {
		iData[k] = v
	}
	setRet := r.Redis.HMSet(key, iData)
	return setRet.Err()
}

func (r *Redis) HGetAll(key string) (map[string]string, error) {
}
```

这样设计出来的 API，方便人们使用，而且和 redis 具体实现是一致的，人们可以在上面做简单封装，就可以给自己的应用层用了，不用担心参数和参数位置的情况，另外类型的问题也解决了。

另外一点：由于推荐overlord ，是不是有一些方法不需要实现？

**Comment by Terry-Mao** [comment]
但是如果复杂的类型转换，非string的，你还是要大量手动代码，不感觉这样收益很多？

反而 redis.Scan() 类似database/sql 的做法，提供一些helper类的方式我比较能接受，比如HGetAll ，的Value 未必是stirng 可能是int map[string]int ，那么还要二次转换，当然后续我们这个改法，可以扩展redis struct，提供更多的helper 方法出来，就是我issue里提的，在上层提供包装指令。

另外inteface 可以提供，两种，一个带context、一个不带context。

我们建议是带context、context 要处理tracing、超时传递（控制），但是我们非强制的。

**Comment by sandacn** [comment]
> 但是如果复杂的类型转换，非string的，你还是要大量手动代码，不感觉这样收益很多？
> 
> 反而 redis.Scan() 类似database/sql 的做法，提供一些helper类的方式我比较能接受，比如HGetAll ，的Value 未必是stirng 可能是int map[string]int ，那么还要二次转换，当然后续我们这个改法，可以扩展redis struct，提供更多的helper 方法出来，就是我issue里提的，在上层提供包装指令。
> 
> 另外inteface 可以提供，两种，一个带context、一个不带context。
> 
> 我们建议是带context、context 要处理tracing、超时传递（控制），但是我们非强制的。

不知道是不是我孤陋寡闻，我记得是 redis 的value基本上都是 string，所以当时这样设计了对应的接口，而不是 interface{}， 最好的方式当然是确定的类型。

我也看了 gorm 和 xorm，它也参考了你说的 [database/sql](https://github.com/golang/go/wiki/SQLInterface)。
我觉得这个也挺好，另外可以让对应的 scan 里面的包含数据结构，这样直接可以赋值，类型确定，开发者也更高效，不需要自己去做类型转换。

如果可以的话，你可以写一两个case，不确定是不是和我想的类似。

**Comment by Terry-Mao** [comment]
@sandacn 在redis内部源码实现，如果是Int，分配的redisObject甚至会都int cache复用，redis是有类型一说的。而且很多写入redis的并非string，而是安全的binary。所以很多会有序列化protobuf存储也是有的，如果用string，我觉得是有歧义的。

**Comment by Terry-Mao** [comment]
@sandacn 可以提几个case看看？

**Comment by Terry-Mao** [comment]
比如这个Get，
```
func (r *Redis) Get(key string) (string, error) {
	return r.Redis.Get(key).Result()
}
```
如果对方放入的key对应是protbuf，这里拿到string是尴尬的。而类似Incr，也可以通过Get来获取，实际上又是一个Int；

**Comment by sandacn** [comment]
> 比如这个Get，
> 
> ```
> func (r *Redis) Get(key string) (string, error) {
> 	return r.Redis.Get(key).Result()
> }
> ```
> 
> 如果对方放入的key对应是protbuf，这里拿到string是尴尬的。而类似Incr，也可以通过Get来获取，实际上又是一个Int；

我明白了，我看传输的时候用的是字符串，误以为里面存储也用了字符串。 如果这样的话，更建议引入类似结构体的方式来让类型一次性就是正确的，避免中间的类型转换和数据一致性问题。

**Comment by sandacn** [comment]
> 如果对方放入的key对应是protbuf，这里拿到string是尴尬的。而类似Incr，也可以通过Get来获取，实际上又是一个Int；

这里应该是 value 对应的是 protobuf 吧？ key 应该是 string 类型的

**Comment by Terry-Mao** [comment]
对，key其实一般都是string，value是protobuf。但是也有key是int的

**Comment by leeyongda** [comment]
是否考虑适配下 gorm/xorm 这些orm库？还是打算放弃支持呢？
虽然orm 屏蔽了db 细节，看不到的sql， 只能用日志来输出原生sql 数据，但是用orm这些库的人还是有的，有利有弊。
https://chai2010.cn/advanced-go-programming-book/ch5-web/ch5-05-database.html

**Comment by Colstuwjx** [comment]
目前在使用：https://github.com/didi/gendry 和 kratos集成，还不错，推荐一下！

**Comment by leeyongda** [comment]
> 目前在使用：https://github.com/didi/gendry 和 kratos集成，还不错，推荐一下！
https://github.com/go-xorm/builder
这个使用过吗？

**Comment by Colstuwjx** [comment]
@leeyongda  你贴的这个项目是archive状态啊，是不是不再维护了？滴滴这个项目目前还是活跃状态的，体验下来感觉也挺清爽的

**Comment by leeyongda** [comment]
https://gitea.com/xorm/builder

**Comment by Darrenzzy** [comment]
建议加orm这样的  生成项目后，开包即用
