### ISSUE TITLE
根据约定放置 proto，怎样生成 nodejs 相关的代码

### ISSUE THREAD

**Issue by stardustman** [go-kratos/kratos#1794]
#### What happened:
不知道根据模版放置的proto如何生成 nodejs 的代码

#### What you expected to happen:
需要生成 proto 相关的 nodejs 代码
#### How to reproduce it (as minimally and precisely as possible):
1. 放置的 proto 目录结构如下：
```bash
$ tree api        
api
├── material
│   └── v1
│       └── material.proto
└── material-group
    └── v1
        └── material-group.proto

4 directories, 2 files

$ tree third_party 
third_party
└── validate
    └── validate.proto

1 directory, 1 file
```
其中 material.proto、material-group.proto 分别 import 了 third_party 下的 validate.proto, 
```proto
syntax = "proto3";

import "google/protobuf/wrappers.proto";
import "validate/validate.proto";
```
问题是：protoc 和 grpc_tools_node_protoc 怎样生成相关的nodejs代码？
#### Environment:
- Kratos version (use `kratos -v`):
- Go version (use `go version`):
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by haiyux** [comment]
这个应该是`protobuf`的问题吧

**Comment by aliliin** [comment]
可以看看这个[google protobuf js](https://github.com/protocolbuffers/protobuf/tree/master/js)

**Comment by stardustman** [comment]
关键是这样放置proto后，--proto_path 指定后，依旧找不到 third_party 下的 validate.proto

**Comment by stardustman** [comment]
之前一直放置到项目下的 proto 文件夹，使用就没问题。so，框架这样放置proto图啥呢？

**Comment by haiyux** [comment]
kratos命令行工具是给go语言用的啊 没考虑过其他语言
