### ISSUE TITLE
[Question] proto http 部分如何和 gin 集成

### ISSUE THREAD

**Issue by Colstuwjx** [go-kratos/kratos#1804]
看了 Gin 的集成例子，但是没看到怎么和 proto 生成代码部分做集成的方式，请问 proto 这套定义只适用原生的 net/http 吗？

**Comment by haiyux** [comment]
用proto生成的路由是基础[mux](https://github.com/gorilla/mux)的，`gin` 路由因为用的trie， 不能满足注册各种奇奇怪怪的路由
