### ISSUE TITLE
[Question] kratos可以用proto生成指针类型的field吗

### ISSUE THREAD

**Issue by pikachuxinlin** [go-kratos/kratos#1806]
我们业务需要接口返回的object中的某个field可以为true false null三种类型
在protocol定义时该字段定义为boolean则生成的go代码为bool类型，只能表示true false；若在proto中定义为optional boolean，生成的go代码为*bool，但序列化后发现若字段值为nil，并不能序列化为key:null，而是直接丢弃该字段。希望保留该字段并且值为null

**Comment by Windfarer** [comment]
试试wrapper types https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wrappers.proto
