### ISSUE TITLE
[Question] customize errors during router

### ISSUE THREAD

**Issue by ruinshe** [go-kratos/kratos#1809]
Hi all, is there any way to customize the errors caused in router layer?

The background is, when I setup a API definition like below:

```proto
service GreeterService {
  rpc SayHello(SayHelloRequest) returns (SayHelloResponse) {
    option (google.api.http) = {
      get: "/api/v1/{id}"
    };
  }
}

message SayHelloRequest {
  int32 id = 1;
}
```

In this demo API, the id is `int32` type and when user pass in a non numeric string like `abc`, the router will return a `*strconv.NumError` with http code `500`.

Is there a middleware or similar component using to tackle with this errors? Maybe in this case the simplest way I want to do is rewrite the http code to 400, ;-)

**Comment by shenqidebaozi** [comment]
You can handle errors in the middleware, throw a `Kratos error`, or handle them in `errorsEncoder`

**Comment by shenqidebaozi** [comment]
https://github.com/go-kratos/kratos/blob/471a2aab794b17ae45d531e0b92da3e4d531b7a9/errors/errors.go#L54

**Comment by ruinshe** [comment]
Thanks for the suggestion, will have a try using middleware to wrap the router handlers.
