### ISSUE TITLE
[Feature] Status Code override

### ISSUE THREAD

**Issue by Windfarer** [go-kratos/kratos#1811]
In some RESTful API, the response status code may different from 200, e.g. 201 for creation success. Can we implement some method based on ctx, to pass a custom status code to override the default status code of the response?

**Comment by SinTod** [comment]
you can custom  ResponseEncoder like this: https://mp.weixin.qq.com/s/4ocdoAVXXKTvJ3U65YXltw

**Comment by Windfarer** [comment]
> you can custom ResponseEncoder like this: https://mp.weixin.qq.com/s/4ocdoAVXXKTvJ3U65YXltw

I know, but IMO this may be a frequently used function, we should make it to be a built-in feature of the framework.

**Comment by ruinshe** [comment]
I managed to use GRPC response header for GRPC services, and use grpc-gateway to do response http status code conversion.

```go
grpc.SetHeader(ctx, metadata.Pairs("x-http-code", strconv.Itoa(go_http.StatusAccepted)))
```
+1 for making a similar built-in function for HTTP API servers.

**Comment by Casper-Mars** [comment]
How about export a function like this ?
```go
func SetStatusCode(ctx context.Context,code int)
```
