### ISSUE TITLE
Consul implementation of config interface, unable to obtain Consul Config

### ISSUE THREAD

**Issue by Strluck** [go-kratos/kratos#1823]
#### What happened:
我想获取一些 `YAML` 格式的 Consul Config，但是由于路径后缀问题，配置没有获取

#### What you expected to happen:
成功获取 Consul Config

#### How to reproduce it (as minimally and precisely as possible):
我像 [example](https://github.com/go-kratos/kratos/blob/main/contrib/config/consul/README.md) 中一样编写了获取 Consul Config 的源代码：

```go
package main

import (
    "github.com/go-kratos/kratos/contrib/config/consul/v2"
	consulAPI "github.com/hashicorp/consul/api"
)

func main() {
    defaultConfig := consulAPI.DefaultConfig()
    client, err := consulAPI.NewClient(defaultConfig)
    if err != nil {
        panic(err)
    }
    cs, err := consul.New(client, consul.WithPath("template/dev"))
    if err != nil {
        panic(err)
    }
    pkgConfig := config.New(
        config.WithSource(
            cs,
        ),
    )
}
```

运行时将输出：

```
INFO msg=config loaded: template/dev format:
```

没有 format

但是，当我给 `consul.WithPath` 的 `path` 添加 `format` 后，将代码修改为：

```go
cs, err := consul.New(client, consul.WithPath("template/dev.yaml"))
```

重新运行，它将没有任何输出

#### Anything else we need to know?:
在我的本地环境中

访问 http://127.0.0.1:8500/v1/kv/template/dev.yaml 将返回 HTTP ERROR 404

访问 http://127.0.0.1:8500/v1/kv/template/dev 将获得以下返回：

```json
[
    {
        "LockIndex": 0,
        "Key": "template/dev",
        "Flags": 0,
        "Value": "c2VydmVyOgogIGh0dHA6CiAgICBhZGRyOiAwLjAuMC4wOjMwMDAKICAgIHRpbWVvdXQ6IDFzCiAgZ3JwYzoKICAgIGFkZHI6IDAuMC4wLjA6OTAwMAogICAgdGltZW91dDogMXM=",
        "CreateIndex": 9330,
        "ModifyIndex": 9386
    }
]
```

`kratos/contrib/config/consul` 使用了 `github.com/hashicorp/consul` 获取 Consul KeyValue

源代码：

(kratos/contrib/config/consul/config.go)

```go
func (s *source) Load() ([]*config.KeyValue, error) {
	kv, _, err := s.client.KV().List(s.options.path, nil)
	if err != nil {
		return nil, err
	}

	pathPrefix := s.options.path
	if !strings.HasSuffix(s.options.path, "/") {
		pathPrefix = pathPrefix + "/"
	}
	kvs := make([]*config.KeyValue, 0)
	for _, item := range kv {
		k := strings.TrimPrefix(item.Key, pathPrefix)
		kvs = append(kvs, &config.KeyValue{
			Key:    k,
			Value:  item.Value,
			Format: strings.TrimPrefix(filepath.Ext(k), "."),
		})
	}
	return kvs, nil
}
```

(github.com/hashicorp/consul/api/kv.go)

```go
func (k *KV) List(prefix string, q *QueryOptions) (KVPairs, *QueryMeta, error) {
	resp, qm, err := k.getInternal(prefix, map[string]string{"recurse": ""}, q)
    ......

    
func (k *KV) getInternal(key string, params map[string]string, q *QueryOptions) (*http.Response, *QueryMeta, error) {
	r := k.c.newRequest("GET", "/v1/kv/"+strings.TrimPrefix(key, "/"))
    ......
```

`Format: strings.TrimPrefix(filepath.Ext(k), ".")`  需要一个带有文件后缀的路径，否则kratos无法读取配置，而 `getInternal` 中的 `key` 不应该传入带有文件后缀的路径，否则将无法获取配置

#### Environment:
- Kratos version (use `kratos -v`): v2.1.5
- Go version (use `go version`): v1.17.6
- OS (e.g: `cat /etc/os-release`): windows
- Others:
  - Consul version 1.11.2
  - kratos/contrib/config/consul/v2 version is v2.0.0-20220209030627-9662ef3c213d

**Comment by Casper-Mars** [comment]
Hi~可以把consul的配置也贴出来吗？

**Comment by Strluck** [comment]
> Hi~可以把consul的配置也贴出来吗？觉得你是用dev作为配置的key了，那么path应该是template/

发现了，原来是consul里的key需要文件格式结尾，我原本是key是dev，在consul内改为dev.yaml，获取正常了
