### ISSUE TITLE
[Question] How do i set multi cookies ?

### ISSUE THREAD

**Issue by mrzxy** [go-kratos/kratos#1824]
want:
```yaml
Set-Cookie: key1=1;  Expires=Fri, 18-Feb-2022 13:04:29 GMT; Max-Age=36000; Path=/; Secure
Set-Cookie: key2=2; Expires=Fri, 18-Feb-2022 13:04:29 GMT; Max-Age=36000; Path=/; Secure
```
The interface exposes only `set()`
```go
if tr, ok := transport.FromServerContext(ctx); ok {
  cookies := metadata.AssembleSetCookie(tr.RequestHeader(), jwtToken.GetExpires())
  // 设置请求头
  tr.ReplyHeader().Set("Set-Cookie", cookies[0])
  tr.ReplyHeader().Set("Set-Cookie", cookies[1])
}
```
the set method is not appended
```go
func (h MIMEHeader) Set(key, value string) {
	h[CanonicalMIMEHeaderKey(key)] = []string{value}
}
```

**Comment by GGXXLL** [comment]
Is this ok?
```	
req := tr.Request()
req.Response.Header.Add("Set-Cookie", "")
```

**Comment by realityone** [comment]
[Is it possible to set more than one cookie with a single Set-Cookie](https://stackoverflow.com/questions/2880047/is-it-possible-to-set-more-than-one-cookie-with-a-single-set-cookie).

Assert `transport.Header` to `http.MIMEHeader` to set multiple `Set-Cookie` header if you only using http transport.

**Comment by mrzxy** [comment]
`transport.Header` is `http.headerCarrier`，how do i assert `http.MIMEHeader`

**Comment by GGXXLL** [comment]
`http.Header(tr.ReplyHeader())` or  use original `http.Request` Object From  `tr.Request()`

**Comment by mrzxy** [comment]
i was tried. it's not work

<img width="765" alt="image" src="https://user-images.githubusercontent.com/11501927/154883248-7cc0d013-18ba-495f-8486-5764967074e1.png">

**Comment by realityone** [comment]
```golang
	var h transport.Header = &headerCarrier{}
	reflect.ValueOf(h).Elem().SetMapIndex(
		reflect.ValueOf("Set-Cookie"),
		reflect.ValueOf([]string{"your-cookie"}),
	)
	fmt.Println(h)
```

Temporary using reflect to set these headers, the proper way will be discussed later.

**Comment by GGXXLL** [comment]
sorry, I forget the `ReplyHeader()` returned `transport.Header`.
```
func (tr *Transport) Request() *http.Request {
	return tr.request
}
```
And this `tr.Request().Response.Header.Add()` should be work well.

**Comment by mrzxy** [comment]
> sorry, I forget the `ReplyHeader()` returned `transport.Header`.
> 
> ```
> func (tr *Transport) Request() *http.Request {
> 	return tr.request
> }
> ```
> 
> And this `tr.Request().Response.Header.Add()` should be work well?

no, `tr.Request().Response` is nil

see the comments
```go
// Response is the redirect response which caused this request
// to be created. This field is only populated during client
// redirects.
Response *Response
```

**Comment by mrzxy** [comment]
> ```go
> 	var h transport.Header = &headerCarrier{}
> 	reflect.ValueOf(h).Elem().SetMapIndex(
> 		reflect.ValueOf("Set-Cookie"),
> 		reflect.ValueOf([]string{"your-cookie"}),
> 	)
> 	fmt.Println(h)
> ```
> 
> Temporary using reflect to set these headers, the proper way will be discussed later.

ok, it's work

```go
var h transport.Header = tr.ReplyHeader()
// map type should not be use elem method, right?
reflect.ValueOf(h).SetMapIndex(
  reflect.ValueOf("Set-Cookie"),
  reflect.ValueOf([]string{"your-cookie"}),
)
fmt.Println(h)
```

**Comment by Nomango** [comment]
A better way to deliver to the people who need it

```go
	if tr, ok := transport.FromServerContext(ctx); ok {
		var h any = tr.ReplyHeader()
		if header, ok := h.(http.Header); ok {
			header.Add("Set-Cookie", cookie.String())
		}
	}
```
