### ISSUE TITLE
grul 请求报错 caused by: File not found: third_party/google/api/annotations.proto 这个怎么解决

### ISSUE THREAD

**Issue by overcls** [go-kratos/kratos#1842]
grpcurl -plaintext localhost:9000 list Services

Failed to list methods for service "Services": Symbol not found: Services
caused by: File not found: third_party/google/api/annotations.proto

**Comment by Windfarer** [comment]
As the https://github.com/fullstorydev/grpcurl#proto-source-files says, 

> In addition to using -proto flags to point grpcurl at the relevant proto source file(s), you may also need to supply -import-path flags to tell grpcurl the folders from which dependencies can be imported.

maybe you need set the third_party directory with the `-import-path` flag

**Comment by overcls** [comment]
> https://go-kratos.dev/docs/intro/faq

不是make proto 问题 ，编译运行都可以 使用grpcurl 列出服务出错呢

**Comment by shenqidebaozi** [comment]
> As the https://github.com/fullstorydev/grpcurl#proto-source-files says,
> 
> > In addition to using -proto flags to point grpcurl at the relevant proto source file(s), you may also need to supply -import-path flags to tell grpcurl the folders from which dependencies can be imported.
> 
> maybe you need set the third_party directory with the `-import-path` flag

@overcls Please check the solution.

**Comment by shenqidebaozi** [comment]
> As the https://github.com/fullstorydev/grpcurl#proto-source-files says,
> 
> > In addition to using -proto flags to point grpcurl at the relevant proto source file(s), you may also need to supply -import-path flags to tell grpcurl the folders from which dependencies can be imported.
> 
> maybe you need set the third_party directory with the `-import-path` flag

@overcls Please check the solution.
