### ISSUE TITLE
kratos proto client api --proto_path 参数只支持一个

### ISSUE THREAD

**Issue by CYARXGBF** [go-kratos/kratos#1851]
kratos proto client 命令输入多个--proto_path时，只有最后一个生效，可以改为支持多个proto_path吗？
```
//go:generate kratos proto client api --proto_path=C:/protoc/include --proto_path=./third_party
```
源码中的protoPath是string类型：https://github.com/go-kratos/kratos/blob/main/cmd/kratos/internal/proto/client/client.go#L24

**Comment by shenqidebaozi** [comment]
好像是要这样吧 kratos proto client api - --proto_path=C:/protoc/include --proto_path=./third_party
