### ISSUE TITLE
kratos router cannot match path end by "/"

### ISSUE THREAD

**Issue by mjhalxx** [go-kratos/kratos#1853]
#### What happened:
设置如下路由匹配：
router :=srv.Route("/")
router.GET("/{bucket}/",func).
此时访问 域名方式为 /bucket/ 格式访问会访问失败，返回301，location显示最后一个斜杠 "/" 会丢失
#### Anything else we need to know?:
通过查看kratos 源码，发现在 route.go中 Handle 处理：
r.srv.router.Handle(path.Join(r.prefix, relativePath), next).Methods(method)

此处 path.Join(r.prefix, relativePath) 会将最后一个斜杠 “/”去掉，导致router配置的path与实际不符，路由匹配不上。
#### Environment:
- Kratos version (use `kratos -v`): v2.0.5
- Go version (use `go version`): 
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by tonybase** [comment]
可以通过设置 StrictSlash(false) 控制是否允许

**Comment by dgqypl** [comment]
@tonybase @shenqidebaozi 在 v2.7.2 这个问题依然存在，并且设置 StrictSlash(false) 不生效，原因如 @mjhalxx 所说，**router.go** 中的 `r.srv.router.Handle(path.Join(r.prefix, relativePath), next).Methods(method)` 这行方法会去掉 path 最后面的 "/"

**Comment by dgqypl** [comment]
@mjhalxx 可以看一下 #1855 中最新的 comment 是否对你适用
