### ISSUE TITLE
graceful shutdown err

### ISSUE THREAD

**Issue by hoslo** [go-kratos/kratos#1856]
#### What happened:
send a http request
kill program
return {"code":500,"reason":"","message":"context canceled","metadata":{}}
#### What you expected to happen:
return right response
#### How to reproduce it (as minimally and precisely as possible):
send a http request
kill program
#### Environment:
- Kratos version (use `kratos -v`): v2.1.5
- Go version (use `go version`): go version go1.17.6 linux/amd64
- OS (e.g: `cat /etc/os-release`): centos7
- Others:
this is start log

INFO msg=config loaded: CONSUL_ADDR format:
INFO msg=config loaded: CONSUL_HTTP_TOKEN format:
INFO msg=config loaded: LOG_IP format:
INFO msg=config loaded: NODE_IP format:
INFO msg=watcher's ctx cancel : context canceled
INFO msg=config loaded: homework/user.service/develop/config.yaml format: yaml
seconds:20
INFO msg=[gRPC] server listening on: [::]:9000
INFO msg=[HTTP] server listening on: [::]:8000

and i use handler ctx as redis ctx，if i use context.Background() as redis ctx, it return right response

**Comment by yjunsun** [comment]
it's not a bug if you use global context (just like handler context), because redis handled the context cancel signal and returned a right behavior.
you can create new ctx(like  what you do in the end) or new func to process the behav of those things.

**Comment by hoslo** [comment]
> @hoslo
> 
> it's not a bug if you use global context (just like handler context), because redis handled the context cancel signal and returned a right behavior. you can create new ctx(like what you do in the end) or new func to process the behav of those things.

but in the blog project use global context as redis context, so is it correct?

**Comment by yjunsun** [comment]
@

> > @hoslo
> > it's not a bug if you use global context (just like handler context), because redis handled the context cancel signal and returned a right behavior. you can create new ctx(like what you do in the end) or new func to process the behav of those things.
> 
> but in the blog project use global context as redis context, so is it correct?

It has nothing to do with correctness, just a best way to use it. You should control the usage of the context yourself.
To be precise, you throw the exception directly to the framework to handle, resulting in the exception information being returned to the client.
Therefore, you need to intercept the exception and return or discard it according to your standard. Although passing a new context directly to redis has the expected results, but redis is still processing the request after you program exit, and there may be more other problems.

This is an example:
```go
func (s *AnyService) AnyFunc(ctx context.Context, in *Req) (*v1.Reply, error) {
	select {
	case <- ctx.Done():
		// when context is done, do this
		return nil, nil
	default:
		// when context is not done, do this
		return &v1.Reply{}, nil
	}
}
```
Or write a middleware for unified processing

**Comment by hoslo** [comment]
> @
> 
> > > @hoslo
> > > it's not a bug if you use global context (just like handler context), because redis handled the context cancel signal and returned a right behavior. you can create new ctx(like what you do in the end) or new func to process the behav of those things.
> > 
> > 
> > but in the blog project use global context as redis context, so is it correct?
> 
> It has nothing to do with correctness, just a best way to use it. You should control the usage of the context yourself. To be precise, you throw the exception directly to the framework to handle, resulting in the exception information being returned to the client. Therefore, you need to intercept the exception and return or discard it according to your standard. Although passing a new context directly to redis has the expected results, but redis is still processing the request after you program exit, and there may be more other problems.
> 
> This is an example:
> 
> ```go
> func (s *AnyService) AnyFunc(ctx context.Context, in *Req) (*v1.Reply, error) {
> 	select {
> 	case <- ctx.Done():
> 		// when context is done, do this
> 		return nil, nil
> 	default:
> 		// when context is not done, do this
> 		return &v1.Reply{}, nil
> 	}
> }
> ```
> 
> Or write a middleware for unified processing

I mean, should the global ctx be canceled before the request is completed?

**Comment by yjunsun** [comment]
> 

The context can be canceled at any time. That's just a signal.
But it doesn't mean whether your request is canceled immediately.
That's your standard.

You can return a template response as soon as you context canceled, or you can block the program until all requests are processed and the response is successfully completed. But the second way is often unnecessary.

You don't have to think about it so perfectly, and anomalies are called anomalies because you can't predict them. Sometimes your program disappears without even receiving a signal.

So, a error is a error. Unless the customer has a perverted request. For example, error responses are not allowed. That's when we intercept all the errors at the edge node and return a template response.

**Comment by hoslo** [comment]
> > 
> 
> The context can be canceled at any time. That's just a signal. But it doesn't mean whether your request is canceled immediately. That's your standard.
> 
> You can return a template response as soon as you context canceled, or you can block the program until all requests are processed and the response is successfully completed. But the second way is often unnecessary.
> 
> You don't have to think about it so perfectly, and anomalies are called anomalies because you can't predict them. Sometimes your program disappears without even receiving a signal.
> 
> So, a error is a error. Unless the customer has a perverted request. For example, error responses are not allowed. That's when we intercept all the errors at the edge node and return a template response.

I use k8s rolling update, I want the request during the update to be processed normally, so should I use ctx to pass to something like mysql or redis but create a new context?

**Comment by yjunsun** [comment]
These are two different things.
First of all, you can read https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/ and use preStop hook and terminationGracePeriodSeconds to finish this.
It's not extremely perfect, But enough is enough.

Do you want extreme perfection?
Use client loadbalance. Is it worth it?

**Comment by hoslo** [comment]
> These are two different things. First of all, you can read https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/ and use preStop hook and terminationGracePeriodSeconds to finish this. It's not extremely perfect, But enough is enough.
> 
> Do you want extreme perfection? Use client loadbalance. Is it worth it?



> preStop hook and terminationGracePeriodSeconds

I send a SIGTERM signal to kratos, request ctx canceled, all subroutines using this ctx will cancel, the current request will fail, preStop hook and terminationGracePeriodSeconds can't solve this problem unless I don't use request ctx

**Comment by yjunsun** [comment]
secondly, the connection has been established, so you need to complete it to accomplish your goal.
If you need to return a real response, you need to pass a new context to Redis, blocking the program waits for Redis to respond, at the same time, no more arbitrary requests are accepted.

**Comment by yjunsun** [comment]
Not your fault. I wrote about too many approaches and feasibility that you can't choose. In simple terms, give Redis a new Context and ensure that the response is successfully returned before exiting.

**Comment by yjunsun** [comment]
Not your fault. I wrote about too many approaches and feasibility that you can't choose. In simple terms, give Redis a new Context and ensure that the response is successfully returned before exiting.
