### ISSUE TITLE
[Proposal] import semantic github app to check conventional commits

### ISSUE THREAD

**Issue by kwanhur** [go-kratos/kratos#1864]
### Proposal description
From [contributing guideline](https://github.com/go-kratos/kratos/blob/main/CONTRIBUTING.md#type), it shows some limitations of type in commit message title. 

Suggest using app [semantic pull requests](https://github.com/apps/semantic-pull-requests) to check them.

### Implementation mode
```semantic.yaml
titleAndCommits: true
allowRevertCommits: true
types:
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert
  - break
  - deps

scopes:
  - transport
  - examples
  - middleware
  - config
  - cmd
```
### Usage demonstration
Github action workflow logs and notifications send to PR's owner.

**Comment by kwanhur** [comment]
Any opinions on this? cc @tonybase @shenqidebaozi

**Comment by shenqidebaozi** [comment]
It looks great.
