### ISSUE TITLE
[Question] too strict assertion error about API path reported when generating proto http client stubs

### ISSUE THREAD

**Issue by ruinshe** [go-kratos/kratos#1865]
I found you added a assertion to avoid "/" ending in #1789, any background about that change? I don't think a strict checking is needed in this case although we suggest not adding "/" into the end of API paths as general API design guideline.

I met a problem when I adding IDL for client side API dispatching against legacy APIs, `protoc-gen-go-http` plugin reports this error, those APIs are defined in non go language even not a part of our system.

For example, in the case below, third party API server hosts the API ending with "/".

```protobuf
service UserService {
  rpc ListUsers(ListUsersRequest) returns (ListUsersResponse) {
    option (google.api.http) = {
      post: "/api/v1/users/"
      body: "*"
    };
  }
}

// ...
```

**Comment by shenqidebaozi** [comment]
Sorry to reply so late. We have changed it to a warning earlier
