### ISSUE TITLE
[Question] The context of gin middleware is not passed down correctly

### ISSUE THREAD

**Issue by alphanoah** [go-kratos/kratos#1866]
Please see the FAQ in our main README.md before submitting your issue.

When use [gin middlerware](https://github.com/go-kratos/gin) , the context can not passed down.
This [PR](https://github.com/go-kratos/gin/pull/1) fixes the problem, but doesn't see the close reason.

**Comment by Windfarer** [comment]
There are many issues in this PR. First, this code does not use the correct go mod package name. Second, these logic does not use the codec and hard coded the content type, it will break the default behavior of the request processing. It will be welcome if you could raise a more practicable PR.
