### ISSUE TITLE
[Feature]Transport supports path.

### ISSUE THREAD

**Issue by neo532** [go-kratos/kratos#1877]
1.transport/transport.go
add "PathTemplate() string" to " type Transporter interface".

2.transport/grpc/transport.go
and then add :
// PathTemplate returns a path for all scheme.
func (tr *Transport) PathTemplate() string {
       return tr.operation
}
after that,I can get path,thx.

**Comment by Justyer** [comment]
Use method `Operation()` instead, it's already in `Transporter`.
