### ISSUE TITLE
[Question] app.Stop()报 unkown service 404

### ISSUE THREAD

**Issue by eric-chao** [go-kratos/kratos#1879]
调用app.Stop() 报错：

Unexpected response code: 404 (Unknown service \"638f4389-xxxx-xxxx-xxxx-000c2958cb94\")

是什么原因？

[code]

	opts := []consul.Option{
		consul.WithHeartbeat(true),
		consul.WithHealthCheck(true),
		consul.WithHealthCheckInterval(5),
	}

	r := consul.New(consulCli, opts...)
	app := kratos.New(
		kratos.Name(serviceConfig.Name),
		kratos.Server(
			grpcSrv,
			//httpSrv,
		),
		kratos.Version(serviceConfig.Version),
		kratos.Registrar(r),
	)

	// Initializing the server in a goroutine so that
	// it won't block the graceful shutdown handling below
	go func() {
		if err = app.Run(); err != nil {
			helper.Fatal(err)
		}
	}()

	// Listen for the interrupt signal.
	<-ctx.Done()

	// shutdown
	shutdown(ctx)

	logs.CtxWarnf(ctx, "shutting down gracefully, press Ctrl+C again to force")

	if err = app.Stop(); err != nil {
		logs.CtxWarnf(ctx, "Server forced to shutdown, error: %v", err)
	}

**Comment by haiyux** [comment]
是不是 `run` 还没跑起来

**Comment by eric-chao** [comment]
> 是不是 `run` 还没跑起来

应该不是这个原因引起的，服务可以调通。

**Comment by haiyux** [comment]
> > 是不是 `run` 还没跑起来
> 
> 应该不是这个原因引起的，服务可以调通。

那提供下最小仓库吧

**Comment by eric-chao** [comment]
> > > 是不是 `run` 还没跑起来
> > 
> > 
> > 应该不是这个原因引起的，服务可以调通。
> 
> 那提供下最小仓库吧

	github.com/go-kratos/kratos/contrib/registry/consul/v2 v2.0.0-20220307052055-79057d4326a6
	github.com/go-kratos/kratos/v2 v2.2.0

**Comment by haiyux** [comment]
我说的是 把能运行起来的代码 发下 上边那些代码运行不起来

**Comment by eric-chao** [comment]
就是官方的Server端的代码了，加了graceful shutdown的片段。
`
package main

import (
	"context"
	"fmt"
	"github.com/go-kratos/kratos/contrib/registry/consul/v2"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/errors"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/middleware/logging"
	"github.com/go-kratos/kratos/v2/middleware/recovery"
	"github.com/go-kratos/kratos/v2/transport/grpc"
	"github.com/go-kratos/kratos/v2/transport/http"
	"github.com/hashicorp/consul/api"
	"os"
	"os/signal"
	"syscall"
)

// go build -ldflags "-X main.Version=x.y.z"
var (
	// Name is the name of the compiled software.
	Name = "helloworld"
	// Version is the version of the compiled software.
	// Version = "v1.0.0"
)

// server is used to implement helloworld.GreeterServer.
type server struct {
	helloworld.UnimplementedGreeterServer
}

// SayHello implements helloworld.GreeterServer
func (s *server) SayHello(ctx context.Context, in *helloworld.HelloRequest) (*helloworld.HelloResponse, error) {
	if in.Name == "error" {
		return nil, errors.BadRequest("custom_error", fmt.Sprintf("invalid argument %s", in.Name))
	}
	if in.Name == "panic" {
		panic("server panic")
	}
	return &helloworld.HelloResponse{Message: fmt.Sprintf("Hello %+v", in.Name)}, nil
}

func main() {
	// Create context that listens for the interrupt signal from the OS.
	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	logger := log.NewStdLogger(os.Stdout)
	helper := log.NewHelper(logger)

	consulCli, err := api.NewClient(api.DefaultConfig())
	if err != nil {
		helper.Fatal(err)
	}

	httpSrv := http.NewServer(
		http.Address(":8000"),
		http.Middleware(
			recovery.Recovery(),
			logging.Server(logger),
		),
	)
	grpcSrv := grpc.NewServer(
		grpc.Address(":9000"),
		grpc.Middleware(
			recovery.Recovery(),
			logging.Server(logger),
		),
	)

	s := &server{}
	helloworld.RegisterGreeterServer(grpcSrv, s)
	helloworld.RegisterGreeterHTTPServer(httpSrv, s)

	opts := []consul.Option{
		consul.WithHeartbeat(true),
		consul.WithHealthCheck(true),
		consul.WithHealthCheckInterval(5),
	}

	r := consul.New(consulCli, opts...)
	app := kratos.New(
		kratos.Name("helloworld"),
		kratos.Server(
			grpcSrv,
			httpSrv,
		),
		kratos.Metadata(map[string]string{"app": "kratos-example"}),
		kratos.Version("0.0.1"),
		kratos.Registrar(r),
	)

	if err = app.Run(); err != nil {
		helper.Fatal(err)
	}

	// Listen for the interrupt signal.
	<-ctx.Done()

	// Restore default behavior on the interrupt signal and notify user of shutdown.
	stop()
	log.Warn(ctx, "shutting down gracefully, press Ctrl+C again to force")

	if err = app.Stop(); err != nil {
		log.Warn(ctx, "Server forced to shutdown, error: %v", err)
	}

	// system cleanup
	// cleanup(ctx)

	log.Warn(ctx, "Server exited")
}

`

**Comment by eric-chao** [comment]
刚看了app.Run()的代码段，似乎是app.Stop()已经封装在app.Run()的协程了。

应该是不需要显式调用app.Stop()了。

**Comment by haiyux** [comment]
ok
