### ISSUE TITLE
[Question] Kratos 如何进行跨服务的链路追踪

### ISSUE THREAD

**Issue by xiehongxin** [go-kratos/kratos#1886]
我有两个服务A和B，每个服务的http和grpc中间件都加上了 tracing.Server()

目前的调用链路是，http请求服务A，服务A向服务B发起gRPC请求，但是在这个链路中，服务A和服务B日志记录的trace_id不一致，想问问是哪里有问题

Please see the FAQ in our main README.md before submitting your issue.

**Comment by xiehongxin** [comment]
已解决

**Comment by henryjhenry** [comment]
我也在寻找这个问题的解决办法，在搜索issue之后并没有找到答案，在翻阅源码后，找到了解决办法。
我使用的 `kratos` 版本是 `2.8.0`。

`tracing`中间件会调用 `propagator.Extract()` 将携带的信息注入或生成 `context.Context`，而默认的 `propagator` 会从请求头中获取用于链路追踪的的请求头（在 http server 中是 request header， 在 grpc server 中是 metadata）， 这个过程遵循 W3C 标准（<https://www.w3.org/TR/trace-context/>）

查阅文档以及阅读源码后，解决方案为：

客户端按照标准中的格式，将 `traceID` 和 `spanID` 按照 W3C 的标准拼接后，放入请求头 `traceparent` 中，服务端就可以获取到。
