### ISSUE TITLE
[Feature]考虑Register的时候加个更新metadata函数的参数吗？

### ISSUE THREAD

**Issue by weisd** [go-kratos/kratos#1888]
目前Register的时候instance信息是固定的，是不是可以加个函数参数，方便heartBeat的时候更新一些metadata

**Comment by tonybase** [comment]
metadata 其实不太建议进行更新，应该是部署的固定标签
如果进行更新metadata，是不是会导致所有节点进行 watch & notify，从而形成流量广播
实例跟实例之间的信息，可以通过rpc之间的元信息进行实时传递
