### ISSUE TITLE
[Question] consul 1.11.4 报rpc error: code = DeadlineExceeded desc = context deadline exceeded

### ISSUE THREAD

**Issue by eric-chao** [go-kratos/kratos#1896]
consul 1.11.4 

做benchmark测试的时候报：

rpc error: code = DeadlineExceeded desc = context deadline exceeded

请问这是什么问题？

**Comment by eric-chao** [comment]
或者，

rpc client有重试的机制吗，

或者

官方有什么实现rpc client的重试样例吗？

**Comment by shenqidebaozi** [comment]
链路超时，考虑是不是自己的业务耗时，小于超时配置？适当调整超时设置
