### ISSUE TITLE
metrics 案例无法正常运行

### ISSUE THREAD

**Issue by younglifestyle** [go-kratos/kratos#1903]
按照example中的metrics 示例，prometheus没有收集到指定指标

[issue](https://github.com/go-kratos/examples/issues/6)

#### Environment:
- Kratos version (use `kratos -v`):
  V2.2.1
- Go version (use `go version`):
 1.16
- OS (e.g: `cat /etc/os-release`):
 win10
- Others:

**Comment by shenqidebaozi** [comment]
![截屏2022-03-30 上午11 04 25](https://user-images.githubusercontent.com/35397691/160743012-04c26513-1315-482a-a580-5e6575d86b4d.png)
测试结果正常

**Comment by shenqidebaozi** [comment]
```
go run examples/metrics/main.go

curl 127.0.0.1:8000/helloworld/kratos
```
