### ISSUE TITLE
kratos run 命令多个项目的 main.go 放在同一个 cmd/xxx 目录下后，不会选择菜单

### ISSUE THREAD

**Issue by git-zjx** [go-kratos/kratos#1907]
#### What happened:
![image](https://user-images.githubusercontent.com/24617415/161359672-c8621919-c062-4746-ba35-04f7de752dc5.png)
如图中的目录结构，kratos run 执行之后，只会运行 catalog 项目中的 main.go
#### What you expected to happen:
出现选择菜单
#### How to reproduce it (as minimally and precisely as possible):
beer-shop 项目可以复现
#### Anything else we need to know?:
根源在于
https://github.com/go-kratos/kratos/blob/558ef4ebaefe1bfab84553ae30064b39ea37abc0/cmd/kratos/internal/run/run.go#L85-L89
cmdPath 的 key 使用的是 cmd/xxx，可以使用全目录
#### Environment:
- Kratos version (use `kratos -v`):kratos version v2.2.0
- Go version (use `go version`):go version go1.17.2 windows/amd64
- OS (e.g: `cat /etc/os-release`):windows
- Others:

**Comment by haiyux** [comment]
你可以实现 `kratos run app/cart/service/cmd/server/`
