### ISSUE TITLE
[Feature] Registry: support NATS

### ISSUE THREAD

**Issue by hhstore** [go-kratos/kratos#1922]
### What problem is the feature used to solve?

- Implement `service registration and service discovery` based on [NATS](https://github.com/nats-io/nats-server).

### Requirements description of the feature

> api:

- register
- deregister

> module path: 

```ruby

kratos/contrib/registry/nats/

```

### References

> NATS:

- https://github.com/nats-io/nats-server

> go-micro + NATS + registry:

- https://github.com/asim/go-micro/blob/master/plugins/registry/nats/nats.go#L133
- You can refer to go-micro for the implementation of this feature.

**Comment by shenqidebaozi** [comment]
You can finish it.
