### ISSUE TITLE
[Feature]请问如何在中间件中获取GET和POST参数？

### ISSUE THREAD

**Issue by mowocc** [go-kratos/kratos#1926]
### Discussed in https://github.com/go-kratos/kratos/discussions/1925

<div type='discussions-op-text'>

<sup>Originally posted by **mowocc** April 11, 2022</sup>
1. 请问如何在中间件中获取请求参数，GET和POST参数分别通过什么方式获取，中间件中获取Header参数使用<transport.FromServerContext(ctx)>，但不清楚GET和POST参数获取方式；
2. HTTP请求必须使用application/json类型吗？如果同时兼容其他类型，请问应该如何处理。</div>

**Comment by ZhangHu1225** [comment]
if tr, ok := transport.FromServerContext(ctx); ok {
	ht, _ := tr.(*http.Transport)
	request := ht.Request()
}
从 request这里就能拿到了.

**Comment by mowocc** [comment]
> 如果 tr， ok ：= 运输。FromServerContext（ctx）;ok { ht， _ ：= tr.（*http.传输） 请求 ：= ht.Request（） } 从 request这里就能拿到了.

1. 这种方式无法拿到 POST 参数，因为 http.Request.Body 已经被kratos的 DefaultRequestDecoder 读取，无法二次  http.Request.Body读取。
2. 同时在 api.RegisterXXXHTTPServer 中，写死了通过 ctx.Bind(&XXXRequest) 绑定参数，只允许对应service访问，不支持对外访问。

请问有什么好的解决方案吗？可以在除 api 对应 service 之外，其他地方也可以访问的方式。

**Comment by shenqidebaozi** [comment]
可以实现 requestDecode把body塞回去

**Comment by mowocc** [comment]
> 可以实现 requestDecode把body塞回去

试过把数据再次塞回去，但失败了，不清楚具体原因。
具体参考了 https://blog.csdn.net/harryhare/article/details/80657849，但还是无法再次塞回去
bodyBytes, _ := ioutil.ReadAll(req.Body)
req.Body.Close()  //  must close
req.Body = ioutil.NopCloser(bytes.NewBuffer(bodyBytes))

**Comment by chenyonghui100** [comment]
这个问题有解决方案吗？ 我也遇到了[流泪]

**Comment by zag13** [comment]
> 

上面说了，自己实现一个 http.RequestDecoder()，使用 r.Body = io.NopCloser(bytes.NewBuffer(data)) 再塞回去就好了

**Comment by zag13** [comment]
> 这个问题有解决方案吗？ 我也遇到了[流泪]

上面说了，自己实现一个 http.RequestDecoder()，使用 r.Body = io.NopCloser(bytes.NewBuffer(data)) 再塞回去就好了

**Comment by zoulux** [comment]
`
http.RequestDecoder(func(r *netHttp.Request, v interface{}) error {
			codec, ok := http.CodecForRequest(r, "Content-Type")
			if !ok {
				return errors.BadRequest("CODEC", fmt.Sprintf("unregister Content-Type: %s", r.Header.Get("Content-Type")))
			}
			data, err := io.ReadAll(r.Body)
			if err != nil {
				return errors.BadRequest("CODEC", err.Error())
			}
			if len(data) == 0 {
				return nil
			}
			defer func() {
				// 给 BODY 重新赋值
				r.Body = io.NopCloser(bytes.NewBuffer(data))
			}()
			if err = codec.Unmarshal(data, v); err != nil {
				return errors.BadRequest("CODEC", fmt.Sprintf("body unmarshal %s", err.Error()))
			}
			return nil

		}
`

根据上面的意思是这样处理的
