### ISSUE TITLE
[Question] rpc error: code = Canceled desc = grpc: the client connection is closing 

### ISSUE THREAD

**Issue by eric-chao** [go-kratos/kratos#1933]
rpc error: code = Canceled desc = grpc: the client connection is closing

**Comment by eric-chao** [comment]
这个是什么原因？

**Comment by eric-chao** [comment]
有 rpc client 的样例代码吗，工程级的。

**Comment by Ccheers** [comment]
大概率是你把某个conn复用了，这时候远端服务重启了，但是你依然在复用这个连接，建议你加一个探活的机制
