### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by zhuxubin01** [go-kratos/kratos#1936]
https://github.com/go-kratos/kratos/blob/d0b704b8f38db901488092d0982c114574da76a7/app.go#L99

这个地方是不是应该用 defer wg.Done()

**Comment by Ccheers** [comment]
server start 以后会阻塞，如果 defer wg.Done() 的话不会执行，waitgroup 会阻塞

**Comment by zhuxubin01** [comment]
> 

直接go routine 扔出去就done 那为什么还要add呢,没看懂这个意义是啥 能解释一下吗

**Comment by zhuxubin01** [comment]
能否做下解释再关Close？
