### ISSUE TITLE
[Feature] 本地配置文件scan时，支持自定义编解码器

### ISSUE THREAD

**Issue by yinyajun** [go-kratos/kratos#1955]
### Feature-request
当前版本`github.com/go-kratos/kratos/v2 v2.2.1`， 事情是这么来的，有个配置是第三方库中的，里面有个time.Duration字段

使用了的本地配置文件`conf.yaml`如下
```yaml
timeout: 10s
```
go 加载配置代码如下
```go
package main

import (
	"fmt"
	"log"
	"time"

	"github.com/go-kratos/kratos/v2/config"
	"github.com/go-kratos/kratos/v2/config/file"
)

type Config struct {
	Timeout time.Duration
}

func main() {
	c := config.New(config.WithSource(file.NewSource("conf.yaml")))
	defer c.Close()

	var cfg Config

	if err := c.Load(); err != nil {
		log.Fatal(err)
	}
	if err := c.Scan(&cfg); err != nil {
		log.Fatal(err)
	}
	fmt.Println(cfg)
}

```
最终报错：
```shell
INFO msg=config loaded: conf.yaml format: yaml
2022/04/26 21:39:29 json: cannot unmarshal string into Go struct field Config.Timeout of type time.Duration
````

在`/Go/pkg/mod/github.com/go-kratos/kratos/v2@v2.2.1/config/config.go`中

```go
func (r *reader) Source() ([]byte, error) {
	r.lock.Lock()
	defer r.lock.Unlock()
	return marshalJSON(convertMap(r.values))
}

func (c *config) Scan(v interface{}) error {
	data, err := c.reader.Source()
	if err != nil {
		return err
	}
	return unmarshalJSON(data, v)
}
```
使用了json做了中间的转换`marshalJSON`, `unmarshalJSON`，json不支持将string转为time.Duration。
但是yaml是能直接支持的。
```go
import (
	"fmt"
	"time"

	"gopkg.in/yaml.v3"
)

type Config struct {
	Timeout time.Duration `yaml:"timeout"`
}

func main() {
	var cfg Config

	b := []byte(`timeout: 60s`)
	yaml.Unmarshal(b, &cfg)
	fmt.Println(cfg)
}
```
尽管timeout那里的配置改成数字就不会报错，但是json默认是以ns为单位，还是用10s比较好看。要是这里不强制用json作为中间转换，而是保持和配置文件的reader decoder的方式一致，或者能够自定义就好了。

**Comment by haiyux** [comment]
使用`protobuf`定义 就可以了吧

**Comment by yinyajun** [comment]
当然，把这些第三方库中的conf全部用`protobuf`重新定义肯定是没问题的

**Comment by yinyajun** [comment]
我找了一个比较绕的途径：
* 先将第三方库中的conf的struct用`proto`定义
* 解析成proto struct
* 然后用`protojson`转成json
* 然后用json unmarshal到第三方库中的conf的struct上

**Comment by shenqidebaozi** [comment]
可以详细描述一下你所需要的功能，以及用法，可以使用伪代码来说明，同时也非常欢迎提交一个PR来实现你的feature request

**Comment by Donglong** [comment]
> 可以详细描述一下你所需要的功能，以及用法，可以使用伪代码来说明，同时也非常欢迎提交一个PR来实现你的feature request

@shenqidebaozi 应该是类似java里面的PropertyEditor

**Comment by yinyajun** [comment]
![](https://github.com/yinyajun/Sundries/blob/master/images/abc.jpg?raw=true)

不同于完全用protobuf自定义conf，我的使用场景是这样的，repo层使用的第三方库已经定义好了conf的struct，需要解析到这些struct里。

最简单的就是用蓝色框框里的流程，直接用yaml umarshal解析。

而用kratos的config模块的话，用黄色框框示例，我期待两者有一样的结果。


可是出现了解析失败，我感觉原因在黄色框框中的红色高亮的部分，写死了用json来做转换。如果这里能自定义，或者初始化的时候，也用对应的codec，就好了

**Comment by haiyux** [comment]
yaml 只是把1s识别出字符串了而已吧， 这个功能是proto 提供的 json本身是不支持的
