### ISSUE TITLE
Streaming proto can not generate http code

### ISSUE THREAD

**Issue by hoslo** [go-kratos/kratos#1958]
#### What happened:
Streaming proto can not generate http code
#### What you expected to happen:
generate http code
#### How to reproduce it (as minimally and precisely as possible):
rpc CreateZip (CreateZipRequest) returns (stream CreateZipReply)  {
    option (google.api.http) = {
      post: "/api/util/other/zip",
      body: "*"
    };
  }
#### Environment:
- Kratos version (use `kratos -v`):  v2.2.0
- Go version (use `go version`): go version go1.18 windows/amd64
- OS (e.g: `cat /etc/os-release`):  centos7
- Others:

**Comment by shenqidebaozi** [comment]
HTTP definitions cannot be used in streaming

**Comment by hoslo** [comment]
> HTTP definitions cannot be used in streaming

So how to use http streaming in kratos?

**Comment by shenqidebaozi** [comment]
Not for the time being

**Comment by hoslo** [comment]
> Not for the time being

How to use middleware for this custom HTTP interface?
···go
opts := []http.ServerOption{
		http.Middleware(
			ratelimit.Server(),
			middleware.Recovery(logger),
			tracing.Server(),
			middleware.Server(logger),
			validate.Validator(),
		),
	}
srv := http.NewServer(opts...)
srv.Route("/").POST("/api/util/other/zip", func(ctx http.Context) error {
		var req v1.CreateZipRequest
		if err := ctx.Bind(&req); err != nil {
			return err
		}
		err := us.uc.CreateZipHttp(context.Background(), &req, ctx.Response())
		if err != nil {
			return err
		}
		return nil
	})
```

**Comment by shenqidebaozi** [comment]
You can refer to the usage in the `xxxx.http.pb.go` file generated by the tool

**Comment by wowowoll** [comment]
me too，kratos can‘t’ generate stream code in xxx_http.pb.go，  什么时候可以支持kratos生成stream的http客户端呢？
