### ISSUE TITLE
[Question] Can I validate a user using a OIDC token emitted by a known provider? 

### ISSUE THREAD

**Issue by juan131** [go-kratos/kratos#1960]
According to the documentation, Kratos doesn't store [OIDC tokens in the database](https://www.ory.sh/docs/kratos/guides/sign-in-with-github-google-facebook-linkedin#how-ory-kratos-handles-oidc-token) once the OIDC provider sends it back, instead it gets the user information and returns a session token.

Assuming that **I have a OIDC token that was obtained outside Kratos context**, could I use it to obtain a session object (e.g. making a call to `/sessions/whoami` endpoint or similar)?

**Comment by shenqidebaozi** [comment]
@juan131 Hello, brother, this project is a micro service framework. Are you looking for the wrong place?

**Comment by shenqidebaozi** [comment]
https://github.com/ory/kratos

**Comment by juan131** [comment]
ups sorry for the noise! Closing it right now!
