### ISSUE TITLE
query params: parse list failed, unsupported message type: \"google.protobuf.Struct\"

### ISSUE THREAD

**Issue by Colstuwjx** [go-kratos/kratos#1967]
#### What happened:
When I tried to parse the query parameters with types like `[]{"key": "value"}`, it failed with the following error:

```
parsing list \"test_param_name\": unsupported message type: \"google.protobuf.Struct\"
```

#### What you expected to happen:
In the latest version, it already been supported for proto struct type, see [code](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/query.go#L336). But we're using forked version of the grpc gateway, and our forked repo seems to not well maintained.

**We should update the forked repo and sync code from the upstream repo.**

#### How to reproduce it (as minimally and precisely as possible):
try define some struct-like params in proto.

#### Environment:
- Kratos version (use `kratos -v`): kratos version v2.2.1
- Go version (use `go version`): go version go1.17.2 darwin/amd64
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by spf201304** [comment]
https://cloud.google.com/endpoints/docs/grpc-service-config/reference/rpc/google.api#google.api.HttpRule

Note that fields which are mapped to URL query parameters must have a primitive type or a repeated primitive type or a non-repeated message type. In the case of a repeated type, the parameter can be repeated in the URL as ...?param=A&param=B. In the case of a message type, each field of the message is mapped to a separate parameter, such as ...?foo.a=A&foo.b=B&foo.c=C.
