### ISSUE TITLE
google.protobuf.FieldMask 参数在query中传递大写字母会被重写为小写

### ISSUE THREAD

**Issue by younglifestyle** [go-kratos/kratos#1969]
GET方法，&field_mask=Me1，函数中打印出来的数据是`_me1`，参数若是Me_Te，打印出来则是`_me__te`。

直接从GRPC中请求，打印出来则是正常`Me1`

**Comment by yeqown** [comment]
>  In JSON, a field mask is encoded as a single string where paths are
 separated by a comma. Fields name in each path are converted
 to/from lower-camel naming conventions.

google.protobuf.FieldMask 按照约定，编码的时候应该是小驼峰，那么相应的在解析的时候也应该是从小驼峰来的（代码里就没有考虑非小驼峰的情况）。就目前我看到的代码，gRPC 请求的按理来说应该是和HTTP处理一致，暂时不清楚为什么你从gRPC得到的是原样。

说回你的问题：

1. path 参数使用 snake_case / lower-camel case
2. kratos HTTP 参数解析和 gRPC-go 保持一致（如果你从gRPC得到的结果完全是gRPC-go解析的结果，不过这一点需要确认）

参考：
- https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/FieldMask.html
- https://github.com/protocolbuffers/protobuf-go/blob/8a7ba0762cb3b39fc0536379eac2f7fa5796f187/encoding/protojson/well_known_types.go#L842-L862
