### ISSUE TITLE
[Question] 我通过协程调用另一个RPC时报错 “context canceled”

### ISSUE THREAD

**Issue by mengdu** [go-kratos/kratos#1974]
代码大概这样

```go
func (s *DemoService) DoSome(ctx context.Context, req *pb.DoSomeReq) (*pb.DoSomeResp, error) {
  // do...
  go func(){
     err := rpc.DoOther(ctx, ...)
     log.Error(err)
   }()
   return &pb.DoSomeResp{}, nil
}
```

会获得类似的错误 `error: code = Canceled desc = context canceled`；也就是这个 `rpc.DoOther` 调用，我不应该用 `ctx` 而是用 `context.Background()` 创建一个新的？
那微服务追踪的相关信息不就丢失了么？

**Comment by Casper-Mars** [comment]
请求响应后ctx就没了，为什么要起一个goroutine异步处理？而且这个和框架框架没什么关系吧~: )

**Comment by dingyang666** [comment]
用 sync.WaitGroup 在 http 结束前等 grpc 结束可能可以解决
