### ISSUE TITLE
[Question] cmd/protoc-gen-go-http 生成代码缺少ServiceRegistrar、BindVars等方法

### ISSUE THREAD

**Issue by TanMingqian** [go-kratos/kratos#1980]
Please see the FAQ in our main README.md before submitting your issue.
protoc-gen-http生成代码缺少ServiceRegistrar、BindVars等方法
已经执行过kratos upgrade,还是有问题
protoc-gen-go-http v2.2.2
go    v1.18
kratos    v2.2.2

**Comment by tonybase** [comment]
```
go install github.com/go-kratos/kratos/cmd/kratos/v2@latest
```
可以直接手动更新下到最新版本，然后重新生成下看看
