### ISSUE TITLE
[Roadmap] v2.2.3 task assignment | 任务分配

### ISSUE THREAD

**Issue by shenqidebaozi** [go-kratos/kratos#1983]
Please reply the tasks you want to complete below, and I will assign them to you.
请在下方回复你要完成的任务，我会分配给你.
 - [ ] #1981 @bingxindan
 - [x] #1967  @imzhongqi
 - [x] #1966  @Ccheers
 - [x] #1881 @pwli0755

**Comment by bingxindan** [comment]
[Question]How to get all registered api path for http server #1981
我来搞这个

**Comment by shenqidebaozi** [comment]
> [Question]How to get all registered api path for http server #1981 我来搞这个

done

**Comment by Ccheers** [comment]
https://github.com/go-kratos/kratos/issues/1966 我来🙋‍♂️

**Comment by imzhongqi** [comment]
#1967 报个名！

**Comment by suncle1993** [comment]
when will v2.2.3 be released?

**Comment by bingxindan** [comment]
1、预计5月26日开发完成；
2、看gin代码实现方式，设计kratos实现方案；
3、和包子评审下技术方案；
4、确认技术方案没问题后，进入开发；




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "go-kratos/kratos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月18日(星期三) 下午3:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [go-kratos/kratos] [Roadmap] v2.2.3 task assignment | 任务分配 (Issue #1983)





 
when will v2.2.3 be released?
