### ISSUE TITLE
kratos proto client error

### ISSUE THREAD

**Issue by dengao123** [go-kratos/kratos#1990]
##### version 
 kratos version is v2.2.2

##### appearance
 ```html
$ kratos proto client ./api/helloworld/demo.proto
exec: "kratos": executable file not found in %PATH%
```

**Comment by shenqidebaozi** [comment]
Try to check your environment variable configuration. The error message indicates that Kratos does not exist in your current path

**Comment by shenqidebaozi** [comment]
This is generally due to the incorrect configuration of go bin
