### ISSUE TITLE
requestEncoder/responseEncoder/errorEncoder如何获取tracing.traceID()

### ISSUE THREAD

**Issue by xuchunhua-com** [go-kratos/kratos#1994]
请求开始和结束的日志都需要加上traceID
requestEncoder/responseEncoder/errorEncoder获取traceID有demo吗？

**Comment by tonybase** [comment]
可以直接通过 req.Context 看看是否拿得到，或者直接在一个单独的middleware进行添加

**Comment by guihouchang** [comment]
req.Context好像拿不到
