### ISSUE TITLE
[Feature] 多个Source存在相同key，在初始化或者配置监听更改时，按照Source初始化的顺序合并，来决定最终的value

### ISSUE THREAD

**Issue by shima-park** [go-kratos/kratos#2065]
### Feature-request
多个Source存在相同key，在初始化或者配置监听更改时，按照Source初始化的顺序合并，来决定最终的value

### What problem is the feature used to solve?
有基础配置用于决定所有程序基本行为，以及应用偏好配置决定个别程序特殊行为。
比如所有程序默认日志级别，个别程序做特殊调整。
在偏好配置中日志级别的key删除后，需要使用基础配置的key的配置。

### Requirements description of the feature
比如有配置Source: A, B，程序启动的时候会WithSource(A, B)
A里有配置level: debug
程序监听key: level
B新增配置level: warn
到此为止都是正常的，监听拿到了level从debug修改warn
而当B把配置level:warn 删除时，缓存配置中的level不会被改成debug，会一直是warn
当一个配置key被改变的时候，按照Source的顺序重新Merge一遍

**Comment by kagaya85** [comment]
感谢建议，目前watch的设计可以监听到新增和修改，对于删除的key的场景确实没有考虑到使用基础值补充的情况，我先标记一下可以讨论一下具体的实现方式

**Comment by shenqidebaozi** [comment]
@yingyajun

**Comment by shenqidebaozi** [comment]
[yinyajun](https://github.com/yinyajun)

**Comment by shenqidebaozi** [comment]
@yinyajun
