### ISSUE TITLE
[protoc-gen-go-http] URL parameter fields dropped by generator for HTTP client

### ISSUE THREAD

**Issue by ruinshe** [go-kratos/kratos#2069]
#### What happened:
When I define a API using protobuf with body specified, the extra fields (intended to be regarded as URL parameter) will be dropped in HTTP client code.

> it seems server side service is not affected and I can pass the extra parameters correctly.

#### What you expected to happen:
All fields other than body field should be regarded as URL parameter to be keep align with the behavior of server side transporter.

#### How to reproduce it (as minimally and precisely as possible):
> I committed a quick simple demo in [a public repository](https://github.com/ruinshe/kratos-examples/tree/master/patch-with-fields), you can directly use it to run `go run server/main.go` and `go run client/main.go` to reproduce it.

Simply define a IDL for PATCH with body, then generate the client side code:

```protobuf
service UserService {
  rpc UpdateUser(UpdateUserRequest) returns (User) {
    option (google.api.http) = {
      patch: "/api/v1/users"
      body: "user"
    };
  }
}

message UpdateUserRequest {
  User user = 1;

  google.protobuf.FieldMask fields = 200;
}
```

In the IDL above, fields will be ignored when sending HTTP request to server side.

#### Anything else we need to know?:
May change the [template code](https://github.com/go-kratos/kratos/blob/5de1f081f636cbaf503039eff0ff6ebb004d8337/cmd/protoc-gen-go-http/template.go#L81) to support it, or add a option in protoc-gen-go-http generator to enable this feature?

#### Environment:
- Kratos version (use `kratos -v`): v2.2.2 (I tried latest protoc-gen-go-http v2.3.0, same problem raises)
- Go version (use `go version`): go version go1.18.2 linux/amd64
- OS (e.g: `cat /etc/os-release`): Arch Linux
- Others: N/A

**Comment by tonybase** [comment]
```
PATCH /api/v1/users?fields=username
body {
   id: 1,
   name: xxx
}
```

This is working to me, dont use  the `vars` parameter, Because the body is already specified.

**Comment by ruinshe** [comment]
> ```
> PATCH /api/v1/users?fields=username
> body {
>    id: 1,
>    name: xxx
> }
> ```
> 
> This is working to me, dont use the `vars` parameter, Because the body is already specified.

Actually the server side code works, I raised up this issue because the client side code doesn't work.

The generated http client doesn't pass the fields parameters to the server side, but I can simply pass the HTTP request as you describe above.

I my demo code, run `go run client/main.go` the server log shows the fields is empty.

**Comment by xiak** [comment]
不支持 vars 吗 我想通过 PATCH

{
    "application": {
        "owner": "X",
        "HEEO": 200
    },
    "updateMask": {
        "paths": ["owner", "HEEO"]
    }
}

定义为

    rpc UpdateApplication(UpdateApplicationRequest) returns (UpdateApplicationResponse) {
        option (google.api.http) = {
            patch: "/api/applications/{app_id}"
            body: "*"
        };
    }

message UpdateApplicationRequest {
    string app_id = 1;
    App application = 2; 
    google.protobuf.FieldMask update_mask = 3;
}

@shenqidebaozi
