### ISSUE TITLE
[Question]how to get the responsewriter in the middleware

### ISSUE THREAD

**Issue by czyt** [go-kratos/kratos#2073]
if I want to check the response body length,how to?I checked API but without any result.for some case,for example : to write an `eTag`( see [MDN](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Etag) for more details) middleware ,this behavior is nessesarry.

**Comment by shenqidebaozi** [comment]
The body has been consumed, so it cannot be obtained in the middleware. You need to override the default http Requestdecoder, re insert the body.

**Comment by shenqidebaozi** [comment]
```
bodyRes, err := ioutil.ReadAll(resp.Body)  
resbody :=ioutil.NopCloser(bytes.NewReader(bodyRes))
```

**Comment by shenqidebaozi** [comment]
The response body can be processed in HTTP ResponseEncoder. You need to override the default implementation
