### ISSUE TITLE
[Question] how to write the download file HTTP interface in line with the middleware plugin format

### ISSUE THREAD

**Issue by younglifestyle** [go-kratos/kratos#2091]
as the title

**Comment by shenqidebaozi** [comment]
example/http/upload

**Comment by younglifestyle** [comment]
> You can register routes separately similar to example/http/upload

thank you, the way to write the download interface does not use server middleware, such as ratelimit, metrics

**Comment by shenqidebaozi** [comment]
> > You can register routes separately similar to example/http/upload
> 
> thank you, the way to write the download interface does not use server middleware, such as ratelimit, metrics

You can refer to `http pb.go` file to use middleware
