### ISSUE TITLE
[Question] register grpc encoding incompatible with older code upgrade

### ISSUE THREAD

**Issue by to2false** [go-kratos/kratos#2093]
This [PR](https://github.com/go-kratos/kratos/pull/1908), change the default behavior `encoding.RegisterCodec(codec{})`

If we already replace json encoding  use `init` before, add this part of the code will affect the existing code, it will load after, make the original ineffective.

Use `init` to set default encoding introduces an implicit change leading to inconsistent results, we'd better to declare statement directly, and provide a optional way to overwrite.

**Comment by shenqidebaozi** [comment]
@tonybase PTAL.
