### ISSUE TITLE
The generated code is incorrect

### ISSUE THREAD

**Issue by Allen-Stephen-71** [go-kratos/kratos#2097]
kratos:2.3.1

最新的版本中做了优化，但是也引入了一个bug  当我使用双路由定义api时，自动生成的pb.go文件中，常量被重复声明 |
Optimized in the latest version, but also introduced a bug. 
When I use additional_bindings  route definitions, in the auto-generated pb.go file, each time the API is declared repeatedly

![image](https://user-images.githubusercontent.com/88641265/173268582-e7e7bf86-b5e8-48aa-bc2c-043a2040b027.png)

Can it be repaired urgently?

**Comment by haiyux** [comment]
这个问题修复过了吧 升级下插件

**Comment by Allen-Stephen-71** [comment]
哪个插件 我刚测试的

**Comment by haiyux** [comment]
执行下 `kratos upgrade`

**Comment by Allen-Stephen-71** [comment]
并没有起作用。你方便测试一下看看吗

**Comment by Allen-Stephen-71** [comment]
并没有起作用

**Comment by Allen-Stephen-71** [comment]
相同的文件中 连续两个  _http.go文件中
