### ISSUE TITLE
Cli 工具生成的service/xx.go 大小写有问题

### ISSUE THREAD

**Issue by Xwudao** [go-kratos/kratos#2099]
#### What happened:

```
type HelloService struct {
	pb.UnimplementedHelloServer
}

func NewHelloService() *HelloService {
	return &HelloService{}
}

func (s *HelloService) Createhello(ctx context.Context, req *pb.CreateHelloRequest) (*pb.CreateHelloReply, error) {
	return &pb.CreateHelloReply{Response: req.Name + ", hello"}, nil
}

```

![image](https://user-images.githubusercontent.com/31327868/173484874-1ed981f0-45de-4761-b0a2-327cba845a1c.png)

#### What you expected to happen:

![image](https://user-images.githubusercontent.com/31327868/173484987-da7b83cf-6e23-427a-9de6-a4120ed1701b.png)

#### How to reproduce it (as minimally and precisely as possible):

```

kratos proto add api/xx/v1/xx.proto

kratos  proto client api/xx/v1/xx.proto
kratos  proto server api/xx/v1/xx.proto
```

#### Environment:
- Kratos version (use `kratos -v`): kratos version v2.3.1
- Go version (use `go version`): go1.18.3
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by songzhibin97** [comment]
fix to #2094
