### ISSUE TITLE
为什么官方error包不使用github.com/pkg/errors

### ISSUE THREAD

**Issue by renjun0106** [go-kratos/kratos#2128]
Please see the FAQ in our main README.md before submitting your issue.
用github.com/pkg/errors包，找错更好找错，为啥不用呢

**Comment by Ccheers** [comment]
目测是为了减少依赖，以及 error 的堆栈打印其实对性能也有些许损耗

**Comment by Windfarer** [comment]
kratos的errors包主要是针对业务系统的报错进行设计，可以通过protobuf进行定义和传递
