### ISSUE TITLE
[Help Wanted] supplementary contrib unit test

### ISSUE THREAD

**Issue by shenqidebaozi** [go-kratos/kratos#2135]
To ensure the robustness of the plug-in package code, we need your help to supplement the unit test of contrib package.

- [ ] config 
- - [ ] apollo @lbbniu
- - [ ] consul @freezeChen
- - [ ] etcd @CodeFish-xiao  #2142
- - [x] kubernetes @rogerogers #2140
- - [x] nacos @wcvb13 #2145
- [ ] registry
- - [x] consul @freezeChen #2148
- - [ ] discovery @Juntaran
- - [ ] etcd @CodeFish-xiao
- - [ ] eureka @huangdi426
- - [x] kubernetes @rogerogers #2140
- - [x] nacos @wcvb13 #2145
- - [x] polaris @rogerogers #2196
- - [x] zookeeper @Ccheers  #2136
- [x] log
- - [x] aliyun @u5surf #2164
- - [x] fluent @u5surf #2141 
- - [x] zap @Ccheers #2136
- [ ] metrics @rogerogers
- [x] opensergo @zoujiejun #2137
- [x] encoding
- - [x] msgpack 

You can comment on the tasks you want to receive below, and I will assign them to you.

**Notice**: please use "part of" not "resolves" or "fixes", or it will close this original issue

**Comment by CodeFish-xiao** [comment]
etcd

**Comment by Ccheers** [comment]
zookeeper & zap

**Comment by u5surf** [comment]
fluent
Can I use stretchr/testify?

**Comment by zoujiejun** [comment]
encoding/msgpack

**Comment by zoujiejun** [comment]
opensergo

**Comment by wcvb13** [comment]
nacos

**Comment by freezeChen** [comment]
consul

**Comment by haiyux** [comment]
> fluent Can I use stretchr/testify?

Please don't use it。

**Comment by rogerogers** [comment]
config.kubernetes

**Comment by CodeFish-xiao** [comment]
[registry.etcd](https://github.com/go-kratos/kratos/pull/2142)

**Comment by CodeFish-xiao** [comment]
> 

registry.etcd  https://github.com/go-kratos/kratos/pull/2142

**Comment by rogerogers** [comment]
这个registry.k8s感觉测试有点困难，代码场景是在pod里面，那个getnamespace的文件跟podname都不好构造，用pod直接注册类似dubbo，跳过了k8s的健康检查吧

**Comment by u5surf** [comment]
aliyun

**Comment by rogerogers** [comment]
registry.k8s

**Comment by huangdi426** [comment]
eureka, plz

**Comment by rogerogers** [comment]
metrics

**Comment by rogerogers** [comment]
registry.kubernetes was merged

**Comment by lbbniu** [comment]
config.apollo

**Comment by Juntaran** [comment]
registry.discovery

**Comment by rogerogers** [comment]
registry.polaris

**Comment by guowei-gong** [comment]
I want to try etcd
