### ISSUE TITLE
[Help Wanted] supplementary framework unit test

### ISSUE THREAD

**Issue by shenqidebaozi** [go-kratos/kratos#2147]
In order to ensure the robustness of the code, we need your help to supplement the unit testing of the framework.
![image](https://user-images.githubusercontent.com/35397691/176830028-d7acb32f-c619-4559-a4bf-4fb5a525be17.png)

- [x] config @shengzhou1216 #2168 #2192
- [x] encoding @shengzhou1216 #2160
- [x] middleware @darkweak #2161 #2165
- [x] transport @Ccheers  #2172
- [x] internal  @shengzhou1216 #2192
- [x] metadata  @Loner1024 #2161
- [x] selector @Justyer #2320
- [x] errors @justyer #2175 #2178
- [x] app.go @walrusyu #2190
- [x] options.go @jakezhu9 #2183
- [x] log @jakezhu9 #2197

You can comment on the tasks you want to receive below, and I will assign them to you.

**Notice**: please use "part of" not "resolves" or "fixes", or it will close this original issue

**Comment by Loner1024** [comment]
metadata

**Comment by shengzhou1216** [comment]
encoding

**Comment by Justyer** [comment]
errors

**Comment by shengzhou1216** [comment]
internel

**Comment by jakezhu9** [comment]
options

**Comment by Justyer** [comment]
selector

**Comment by jakezhu9** [comment]
log

**Comment by walrusyu** [comment]
app.go
