### ISSUE TITLE
执行kratos proto client 命令，生成出来的缺少了一个pd文件

### ISSUE THREAD

**Issue by 350543866** [go-kratos/kratos#2153]
执行kratos proto client api/helloworld/v1/greeter.proto命令
生成了greeter_grpc.pd.go和greeter_http.pd.go文件
缺少了greeter.pd.go文件
这是什么原因

- Kratos version (v2.3.1):
- Go version (1.17):
- OS (win10):
- Others:

**Comment by tonybase** [comment]
可以提供下执行打印的 protoc 命令看看？
