### ISSUE TITLE
make api error protoc-gen-openapi: no such flag -fq_schema_naming

### ISSUE THREAD

**Issue by minicloudsky** [go-kratos/kratos#2154]
#### What happened:
I run kratos new project
 make api
protoc --proto_path=./api \
               --proto_path=./third_party \
               --go_out=paths=source_relative:./api \
               --go-http_out=paths=source_relative:./api \
               --go-grpc_out=paths=source_relative:./api \
               --openapi_out=fq_schema_naming=true,default_response=false:. \
               api/helloworld/v1/error_reason.proto api/helloworld/v1/greeter.proto
protoc-gen-openapi: no such flag -fq_schema_naming
--openapi_out: protoc-gen-openapi: Plugin failed with status code 1.
make: *** [api] Error 1

#### Environment:
- Kratos version (use `kratos -v`):
- kratos version v2.3.1
- Go version (use `go version`): go version go1.18.2 darwin/amd64
- OS (e.g: `cat /etc/os-release`): Mac 11.6.6 (20G624)
- Others:

**Comment by tonybase** [comment]
You can try updating the OpenAPI plug-in to solve this problem.
`go install github.com/google/gnostic/cmd/protoc-gen-openapi@latest`

**Comment by minicloudsky** [comment]
> go install github.com/google/gnostic/cmd/protoc-gen-openapi@latest

Ok,I tried it and solved my problem,Thank you,because of you,warming four seasons~
