### ISSUE TITLE
可以提供下执行打印的 protoc 命令看看？

### ISSUE THREAD

**Issue by 350543866** [go-kratos/kratos#2156]
D:\golang\src\htc\user>kratos proto client api/user/v1/user.proto
proto: api/user/v1/user.proto

给我修复了修改proto的参数go_package才可以
但是运行报错了：
D:\golang\src\htc\user>kratos run
user/api/user/v1
..\..\api\user\v1\user_http.pb.go:67:27: cannot use in (type *CreateUserRequest) as type protoreflect.ProtoMessage in argument to binding.EncodeURL:
        *CreateUserRequest does not implement protoreflect.ProtoMessage (missing ProtoReflect method)
?[31mERROR: exit status 2?[m

**Comment by shenqidebaozi** [comment]
grpc 版本有问题吧。

**Comment by tonybase** [comment]
protobuf protoc版本需要升级下
