### ISSUE TITLE
"proto not found" error occured when using kubernetes proto files

### ISSUE THREAD

**Issue by 27149chen** [go-kratos/kratos#2195]
#### What happened:
GET /q/service/{name} failed because of some kubernetes proto files, raise "proto not found" error

```
New err: invalid FileDescriptorProto "xxx.proto": proto: could not resolve import "k8s.io/apimachinery/pkg/apis/meta/v1/generated.proto": not found
```

#### What you expected to happen:
GET /q/service/{name} successfully

#### How to reproduce it (as minimally and precisely as possible):
1. import some kubernetes proto files in your own proto file (such as k8s.io/apimachinery/pkg/apis/meta/v1/generated.proto)
2. visit /q/swagger-ui and go to the service defined in step 1

#### Anything else we need to know?:

related to #2132 , becasue k8s also use gogo/protobuf

#### Environment:
- Kratos version (use `kratos -v`): 2.4.0
- Go version (use `go version`): 1.18
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by 27149chen** [comment]
@shenqidebaozi  what is the plan for this issue?

**Comment by shenqidebaozi** [comment]
Can you provide me with a minimal verification environment to quickly find problems

**Comment by Cluas** [comment]
https://github.com/grpc/grpc-go/blob/master/Documentation/server-reflection-tutorial.md#enable-server-reflection

**Comment by Cluas** [comment]
It is recommended to understand what grpc reflection is first.

**Comment by Cluas** [comment]
https://github.com/go-kratos/kratos/blob/main/api/metadata/server.go#L18

**Comment by Cluas** [comment]
https://github.com/go-kratos/kratos/blob/0ce9e8d069995989a56b827a15c15a91cdfa5a9e/transport/grpc/server.go#L164

**Comment by Cluas** [comment]
https://github.com/go-kratos/kratos/blob/0ce9e8d069995989a56b827a15c15a91cdfa5a9e/api/metadata/server.go#L67

**Comment by 27149chen** [comment]
@shenqidebaozi  I draft an example (https://github.com/27149chen/helloworld), you can download and try

**Comment by shenqidebaozi** [comment]
@27149chen You can read @Cluas  reply, in addition, we recommend using gnostic to generate OpenAPI

**Comment by 27149chen** [comment]
@shenqidebaozi What I need is swagger-ui, not how to generate openAPI

**Comment by yrzs** [comment]
这个问题解决了吗，我也是这样
