### ISSUE TITLE
kratos upgrade error

### ISSUE THREAD

**Issue by BootyDog** [go-kratos/kratos#2201]
#### What happened:
kratos upgrade       
go install github.com/go-kratos/kratos/cmd/kratos/v2@latest
go install github.com/go-kratos/kratos/cmd/protoc-gen-go-http/v2@latest
go install github.com/go-kratos/kratos/cmd/protoc-gen-go-errors/v2@latest
go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
go install github.com/google/gnostic/cmd/protoc-gen-openapi@latest
go: github.com/google/gnostic/cmd/protoc-gen-openapi@latest: no matching versions for query "latest"
exit status 1
#### Environment:
- Kratos version (use `kratos -v`): kratos version v2.4.0
- Go version (use `go version`):  go1.18.3 darwin/amd64
- OS (e.g: `cat /etc/os-release`):  MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
- Others:

**Comment by hshe** [comment]
![image](https://user-images.githubusercontent.com/8075773/179343309-fdc6da76-8324-48d5-92c4-040c5029296a.png)
没有问题呀

**Comment by BootyDog** [comment]
go install github.com/google/gnostic/cmd/protoc-gen-openapi@latest
然后kratos upgrade就好了
