### ISSUE TITLE
[Question] kratos version v2.4.0 生成的openapi 不对

### ISSUE THREAD

**Issue by van-scott** [go-kratos/kratos#2204]
使用kratos 生成项目，然后生成openapi ,版本是3.0.3.但是https://github.com/go-kratos/swagger-api 这个项目却只支持openapi 2.0.希望能够同步更新。如果不支持3.0 就不要生成3.0 的代码

**Comment by shenqidebaozi** [comment]
kratos 现在默认使用的是 gnostic 插件，老的 swagger-api 项目，也只是之前为了修复原始 swagger-api 的bug 问题，单独开的仓库，已经不再维护。

**Comment by shenqidebaozi** [comment]
https://mp.weixin.qq.com/s?__biz=MzAwNzgwMzY2Ng==&mid=2247487196&idx=1&sn=7df9628759145f158d5dddbb8b71aaa2&chksm=9b79c8a1ac0e41b7e25f7e422800be1702618c45c1e668a5d843162f1813285065ff0f3b51f2&token=1826266121&lang=zh_CN#rd

**Comment by van-scott** [comment]
多谢了，但是其实我想让他修复一下bug ,其实我知道怎么生成

**Comment by shenqidebaozi** [comment]
因为 grpc-gateway 生成 swagger 的方式不优雅，我们很早就不使用了，推荐直接使用 google 的 gnostic

**Comment by van-scott** [comment]
google 的 gnostic 这个能很好的集成到 kratos 中吗？ 有比较好的例子吗？ 还有 kratos 不支持多path 配置，感觉挺奇怪的，protoc 都支持

**Comment by shenqidebaozi** [comment]
什么叫多 path 配置，默认生成就是例子啊，而且上方回复也有文章地址

**Comment by whtiehack** [comment]
请问下 go-kratos/swagger-api 有3.0版的吗? 或者类似的, 还是比较喜欢内嵌 😂

**Comment by czyt** [comment]
maybe we can try https://github.com/pseudomuto/protoc-gen-doc
