### ISSUE TITLE
`http.Client.Do()` not support `WithMiddleware()` option

### ISSUE THREAD

**Issue by ionling** [go-kratos/kratos#2228]
https://github.com/go-kratos/kratos/blob/de0e4e222832ff076734ebe50a7df9de46e4ae43/transport/http/client.go#L272

After I looked the code, I found it's hard to implement this feature, as `client.Invoke()` use
`middleware.Hanler` (`type Handler func(ctx context.Context, req interface{}) (interface{}, error)`) model,
but `client.Do()` use the standard http lib model (`func (c *Client) Do(req *Request) (*Response, error)`). 
It's impossible to convert `client.Do()` model to `middleware.Hanler` model.

Does anyone have better ideas?

**Comment by wang-tsh** [comment]
I'll take this in these days
这几天我来搞一下这个吧

**Comment by wang-tsh** [comment]
@tonybase plz review it
@shenqidebaozi   plz review it

**Comment by suncle-c-20230331** [comment]
这个问题后续有更新吗
