### ISSUE TITLE
http client nacos can not get nodes

### ISSUE THREAD

**Issue by sohenk** [go-kratos/kratos#2231]
#### What happened:

i use the httpclient with nacos registry, and get the 503 error, then i use the grpc is work with me but http client

my service name is right and add ".http" in the end. it seems to be happen in line 129 in

https://github.com/go-kratos/kratos/blob/main/transport/http/resolver.go 

```
r.rebalancer.Apply(nodes) (here-_-)
```

this is my error 

```
error: code = 503 reason = NODE_NOT_FOUND message = error: code = 503 reason = no_available_node message =  metadata = map[] cause = <nil> metadata = map[] cause = <nil>
```

**Comment by shenqidebaozi** [comment]
http.WithBlock
