### ISSUE TITLE
[Question]goland ide不兼容怎么办？

### ISSUE THREAD

**Issue by 4566704** [go-kratos/kratos#2233]
kratos在windows环境下编码太难了，花了整整一天时间也没学会

是还不支持windows 10 开发环境，还是不支持goland吗？
系统: windows 10 21H2
IDE: goland 2022.1.4 
GO: 1.18.4

问题：
helloworld中禁用了 Go支持
构建约束排除 'C:/Users/admin/go/pkg/mod/github.com/google/wire@v0.5.0' 中所有的 Go 文件

上面两个问题，都会导致编码时没有智能提示

**Comment by 4566704** [comment]
按照github上的README_zh.md 一步步操作的
https://go-kratos.dev/docs/getting-started/start  也按这上面操作了一遍，结果也是一样

**Comment by 4566704** [comment]
又折腾了一个小时，终于可以编码了。

插件中卸载 go wire util 就好了，一切正常了

**Comment by shenqidebaozi** [comment]
The problems of GoLand wire plug-in are not directly related to Kratos. ❤️

**Comment by guowei-gong** [comment]
> 又折腾了一个小时，终于可以编码了。
> 
> 插件中卸载 go wire util 就好了，一切正常了

tks. It works for me

**Comment by guowei-gong** [comment]
I think this should be added to the frequently asked questions.

I was haunted for a long time. @shenqidebaozi Do you think?
