### ISSUE TITLE
[Question]contribution `X issues need help` code 

### ISSUE THREAD

**Issue by guowei-gong** [go-kratos/kratos#2237]
Hi, These issue have been collected but it's not done.  Can I complete and submit the PR ? e.g

![image](https://user-images.githubusercontent.com/62499904/180905817-83370d5c-fc55-47ac-85fe-17b8daca6af1.png)

**Comment by shenqidebaozi** [comment]
Of course, you can choose the unfinished tasks and assign the owner to you
