### ISSUE TITLE
服务发现不能正确发现不同namespace下的服务

### ISSUE THREAD

**Issue by Nomango** [go-kratos/kratos#2252]
#### What happened:

/ns1/service1 服务通过 Discovery 并不能正确发现 /ns2/service2，而是尝试发现 /**ns1**/service2，因为 Discovery.GetService 接口中 ServiceName 参数忽略了 namespace。

#### What you expected to happen:

grpc.WithEndpoint("discovery://ns2/service2") 可以正确发现 /ns2/service2 而不是 /ns1/service2

#### How to reproduce it (as minimally and precisely as possible):

复现伪代码：

```golang
// 创建 etcd registry 时绑定了namespace=ns1
registry := etcd.New(client, etcd.Namespace("ns1"))

// 通过wire绑定Discovery接口
wire.Bind(new(registry.Discovery), new(*etcd.Registry))

// 在某处使用这个 Discovery 发现 ns2 下的服务
grpc.DialInsecure(ctx, grpc.WithDiscovery(r), grpc.WithEndpoint("discovery://ns2/service2"))
```

#### Anything else we need to know:

原因是 [这一行代码](https://github.com/go-kratos/kratos/blob/b3eff576ce0d5cbadf53ec2a9ab1232d45e5cef3/transport/grpc/resolver/discovery/builder.go#L70) 只取了 target.URL.Path，忽略了target.URL.Host

```golang
w, err := b.discoverer.Watch(ctx, strings.TrimPrefix(target.URL.Path, "/"))
```

然后 [这一行代码](https://github.com/go-kratos/kratos/blob/fea863e7837e808af0a1918cd1f8927fa76585aa/contrib/registry/etcd/registry.go#L128) 直接将 Registry 本身的 namespace 拼接到了 serviceName 前

```golang
key := fmt.Sprintf("%s/%s", r.opts.namespace, name)
```

#### Environment:
- Kratos version (use `kratos -v`): v2.4.0

**Comment by haiyux** [comment]
"discovery:///ns2/service2" discovery后面三个/

**Comment by haiyux** [comment]
有问题再打开

**Comment by shenqidebaozi** [comment]
文档描述有错误，根据 grpc 设计说明，target 的格式为 `scheme://authority/endpoint_name` 并不是指 namespace 
https://github.com/grpc/grpc/blob/master/doc/naming.md

**Comment by Nomango** [comment]
> "discovery:///ns2/service2" discovery后面三个/

还是有点疑问哈，这样的话ns2其实不是namespace，也不能用etcd.Namespace("ns2")来注册，而是要把服务名改成 "ns2/service2" 对吗？

**Comment by shenqidebaozi** [comment]
@Nomango 首先不支持 target 指定 namespace 刚刚有说过
两种方式解决
- 创建 grpc client 的时候 etcd 指定对应的 namespace
- 修改 etcd 插件，将 namespace 加入到 target 里面（和其他注册中心插件不一致）

**Comment by shenqidebaozi** [comment]
- 第一种方式对应的用法就是 etcd.Namespace("ns2")，discovery:///service2

**Comment by Nomango** [comment]
@shenqidebaozi ok，了解了，看了最新的文档和其他registry的实现，kratos的服务发现其实没有namespace这个概念，etcd.Namespace只是个prefix功能
