### ISSUE TITLE
[Feature] multipart/form-data encoding

### ISSUE THREAD

**Issue by czyt** [go-kratos/kratos#2257]
for current version kratos display error
```json
{
    "code": 400,
    "reason": "CODEC",
    "message": "unregister Content-Type: multipart/form-data; boundary=--------------------------187292697950545999179746",
    "metadata": {}
}
```
as discussed before,https://github.com/go-kratos/kratos/issues/2198
it is not nessary to define `mutipart/form-data` in proto,we can define a service as normal,and make a function to overwrite the method in splitted go file ,so that the kratos generated code and be reused and the api can also be included in the openapi file.

**Comment by shenqidebaozi** [comment]
https://github.com/go-kratos/examples/tree/main/http/upload
