### ISSUE TITLE
[Question] 如何在中间件中获取 POST 请求的参数

### ISSUE THREAD

**Issue by chenyonghui100** [go-kratos/kratos#2258]
中间件中可以通过 tr.RequestHeader() 来获取请求头的内容。通过下面的代码，获取到的请求体是空的。

```
if tr, ok := transport.FromServerContext(ctx); ok {
ht, _ := tr.(*http.Transport)
request := ht.Request()
}
```
因为 http.Request.Body 已经被kratos的 DefaultRequestDecoder 读取，无法二次 http.Request.Body读取。
尝试在自定义 RequestDecoder  中将body 重新写入。
`r.Body = ioutil.NopCloser(bytes.NewBuffer(data))`
仍然不能在中间件中读取到 body 的内容。

**Comment by shenqidebaozi** [comment]
框架版本低吧？

**Comment by shenqidebaozi** [comment]
https://github.com/go-kratos/kratos/pull/1906

**Comment by deagon** [comment]
mark, 遇到同样问题，不是框架版本问题。

可能得在 transport 里加字段？

**Comment by shenqidebaozi** [comment]
> mark, 遇到同样问题，不是框架版本问题。
> 
> 可能得在 transport 里加字段？

@deagon 这个功能我有验证过的，可以实现，不确定你们的写法是否存在问题

**Comment by shenqidebaozi** [comment]
可以提供一个最小复现仓库来验证这个问题

**Comment by shenqidebaozi** [comment]
可以实现的前提，框架版本大于 #1906，使用 kratos 提供的 http 包

**Comment by chenyonghui100** [comment]
> 可以实现的前提，框架版本大于 #1906，使用 kratos 提供的 http 包

尝试升级到了最新版，在调试的时候看到请求体是有值的，但是读取会报错，不知道是不是读取方式不对。

**Comment by chenyonghui100** [comment]
> 可以实现的前提，框架版本大于 #1906，使用 kratos 提供的 http 包

尝试升级到了最新版本，在调试时可以看到body时有值的，但是读取的时候会出错，不知道是不是自己读取方式不对。代码如下：
```

if ht, ok := tr.(*http.Transport); ok {
    lens := ht.Request().ContentLength
    // 创建byte切片
    body := make([]byte, lens)
    // 将请求体中内容读到body中
    _, err := ht.Request().Body.Read(body)
    if err !=nil{
        fmt.Println(err)     // 报错  EOF
    }

}
```

**Comment by YeFatBoy** [comment]
我也碰到一样的问题、middleware可以获取http-get参数、post获取不了

**Comment by chenyonghui100** [comment]
> 我也碰到一样的问题、middleware可以获取http-get参数、post获取不了

我尝试了一下， 在中间件中直接读取会报 EOF ，调试中 sawEOF 的值是 true ， 重写了 RequestDecoder 的方法，在decoder 结束后，加上了这句 `r.Body = ioutil.NopCloser(bytes.NewBuffer(data))`  可以在中间件正常获取 body 的内容了。

**Comment by YeFatBoy** [comment]
@chenyonghui100 求一个完整版的

**Comment by chenyonghui100** [comment]
> @chenyonghui100 求一个完整版的

我是这样做的。
升级版本到最新版

在 http.go 文件里加入自定义 自定义decoder
```
var opts = []http.ServerOption{
    http.RequestDecoder(RequestDecoder),   //这句
    http.ResponseEncoder(responseEncoder),
    http.ErrorEncoder(errorEncoder),
    http.Middleware(
        tag.ClientIP(),
        recovery.Recovery(),
        validate.Validator(),
        selector.Server(auth.Identify(userService)).Match(NewSkipRoutersMatcher()).Build(),
    )
}
```
对应的函数
```
func RequestDecoder(r *http.Request, v interface{}) error {
    codec, ok := http.CodecForRequest(r, "Content-Type")
    if !ok {
        return errors.BadRequest("CODEC", fmt.Sprintf("unregister Content-Type: %s", r.Header.Get("Content-Type")))
    }
    data, err := io.ReadAll(r.Body)
    if err != nil {
        return errors.BadRequest("CODEC", err.Error())
    }
    if len(data) == 0 {
        return nil
    }
    if err = codec.Unmarshal(data, v); err != nil {
        return errors.BadRequest("CODEC", fmt.Sprintf("body unmarshal %s", err.Error()))
    }
    r.Body = ioutil.NopCloser(bytes.NewBuffer(data))   //主要是加了这句
    return nil
}

```
在中间件中进行读取
```
if tr, ok := transport.FromServerContext(ctx); ok {
    if ht, ok := tr.(*http.Transport); ok {
        lens := ht.Request().ContentLength
        // 创建byte切片
        body := make([]byte, lens)
        // 将请求体中内容读到body中
        _, err := ht.Request().Body.Read(body)
        if err != nil {
            return nil, v1.ErrorUnauthorized(err.Error())
        }
    }
}
                

```

**Comment by guihouchang** [comment]
https://github.com/go-kratos/kratos/pull/2542
@shenqidebaozi  是否考虑下合并呢？

**Comment by Huang131** [comment]
> r.Body = ioutil.NopCloser(bytes.NewBuffer(data))

r.Body = ioutil.NopCloser(bytes.NewBuffer(data)) 这行必须放在最后吗？我目前的DefaultRequestDecoder函数中有这行代码，但是读取参数还是报错 EOF

**Comment by younglifestyle** [comment]
> > r.Body = ioutil.NopCloser(bytes.NewBuffer(data))
> 
> r.Body = ioutil.NopCloser(bytes.NewBuffer(data)) 这行必须放在最后吗？我目前的DefaultRequestDecoder函数中有这行代码，但是读取参数还是报错 EOF

我也是同样的错误

**Comment by younglifestyle** [comment]
> > r.Body = ioutil.NopCloser(bytes.NewBuffer(data))
> 
> r.Body = ioutil.NopCloser(bytes.NewBuffer(data)) 这行必须放在最后吗？我目前的DefaultRequestDecoder函数中有这行代码，但是读取参数还是报错 EOF

+1，验证了确实是这样
