### ISSUE TITLE
post请求时 重定向未生效

### ISSUE THREAD

**Issue by Naist4869** [go-kratos/kratos#2259]
#### What happened:
post请求时 重定向未生效  返回200, get请求正常
#### What you expected to happen:
 状态码返回302
#### Anything else we need to know?:
```go
	if rd, ok := v.(http.Redirector); ok {
		url, code := rd.Redirect()
		stdhttp.Redirect(w, r, url, code)
		return nil
	}
```
改为以下代码时成功返回302
```go
	if rd, ok := v.(http.Redirector); ok {
		url, code := rd.Redirect()
		stdhttp.Redirect(w, r, url, code)
		return errors.New(code, "", "")
	}
```
#### Environment:
- Kratos version (use `kratos -v`): kratos version v2.3.1
- Go version (use `go version`):1.18
- OS (e.g: `cat /etc/os-release`):macos
- Others:

**Comment by shenqidebaozi** [comment]
https://github.com/go-kratos/examples/blob/main/http/redirect/main.go

**Comment by Naist4869** [comment]
> https://github.com/go-kratos/examples/blob/main/http/redirect/main.go

redirectURL如果是带参数的  怎么从service获得  r.context吗

**Comment by shenqidebaozi** [comment]
放到 ctx 里面就好了

**Comment by shenqidebaozi** [comment]
可以判断 ctx 里面是否存在某个值，如果存在就跳转，很多方式的

**Comment by Naist4869** [comment]
> ```go
> http.Redirector
> ```

好的,  因为kratos中有个http.Redirector想用一下结果用不了 我还是自己跳转吧
