### ISSUE TITLE
the wg.Done in app.New() doesn't seem to work [Question]

### ISSUE THREAD

**Issue by rhythmszn1011** [go-kratos/kratos#2267]
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/89074234/183863208-357357ea-3fca-4e68-8db1-58dbd77e687f.png">
even delete the wg,The service still starts normally,so what is the point of wg.

**Comment by tonybase** [comment]
Right, because it's synchronous, I haven't thought of a good way.
