### ISSUE TITLE
[Feature] kratos protoc gen go http route with gin

### ISSUE THREAD

**Issue by wang-tsh** [go-kratos/kratos#2282]
能否通过改动cmd/kratos/下文件，在kratos 生成http时，选择其他框架，如gin

can we to change file in cmd/kratos/ to make kratos gen http with gin

**Comment by shenqidebaozi** [comment]
The idea of using the gin framework is not considered for the time being.

**Comment by wang-tsh** [comment]
I'll just have to use it myself

那我只能自己做自己用了。。。

**Comment by soarYe** [comment]
强烈希望官方能增加gin这块
