### ISSUE TITLE
`kratos new -r` not support scp styled git url

### ISSUE THREAD

**Issue by czyt** [go-kratos/kratos#2294]
PS C:\Users\czyt> kratos new tinyApp -r git@gitee.com:czyt/kratos-layout.git
🚀 Creating service tinyApp, layout repo is git@gitee.com:czyt/kratos-layout.git, please wait a moment.

2022/08/19 10:44:41 mkdir C:\Users\czyt/.kratos/repo/git@gitee.com:czyt: The directory name is invalid.
PS C:\Users\czyt> kratos -v
kratos version v2.5.0

**Comment by haiyux** [comment]
为什么不用 https://gitee.com/czyt/kratos-layout.git

**Comment by czyt** [comment]
> 为什么不用 https://gitee.com/czyt/kratos-layout.git

昨晚突然想试试ssh那种，结果就失败了。哈哈

**Comment by haiyux** [comment]
好的 我看一下

**Comment by haiyux** [comment]
```
git clone git@gitee.com:czyt/kratos-layout.git
Cloning into 'kratos-layout'...
The authenticity of host 'gitee.com (212.64.63.190)' can't be established.
ED25519 key fingerprint is SHA256:+ULzij2u99B9eWYFTw1Q4ErYG/aepHLbu96PAUCoV88.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'gitee.com' (ED25519) to the list of known hosts.
git@gitee.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists
```

在本地执行也是失败的 好像要配置秘钥啥的？

**Comment by czyt** [comment]
> ```
> git clone git@gitee.com:czyt/kratos-layout.git
> Cloning into 'kratos-layout'...
> The authenticity of host 'gitee.com (212.64.63.190)' can't be established.
> ED25519 key fingerprint is SHA256:+ULzij2u99B9eWYFTw1Q4ErYG/aepHLbu96PAUCoV88.
> This key is not known by any other names
> Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
> Warning: Permanently added 'gitee.com' (ED25519) to the list of known hosts.
> git@gitee.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists
> ```
> 
> 在本地执行也是失败的 好像要配置秘钥啥的？

嗯这个是knownhosts的问题  需要 ssh-keyscan -T 下，这部分逻辑感觉放在工具这边 还是不太好，只能提示。

**Comment by czyt** [comment]
pr merged
