### ISSUE TITLE
不兼容golang1.18

### ISSUE THREAD

**Issue by 1511563371** [go-kratos/kratos#2301]
#### What happened:
kratos new ProjectName 时，go mod 中的Module 中go 显示1.17 但是当前编译器为go1.18
#### Environment:
- Kratos version (use `kratos -v`):v2.5.0
- Go version (use `go version`):1.18
- OS (e.g: `cat /etc/os-release`):win10

**Comment by Windfarer** [comment]
不影响使用，根据自己的版本改一下就好了

**Comment by shenqidebaozi** [comment]
这个是layout指定的gomod版本，和你本机go版本无关。
