### ISSUE TITLE
[Question] 为什么读取 apollo 配置要多加一层啊？

### ISSUE THREAD

**Issue by XieWeiXie** [go-kratos/kratos#2314]
Please see the FAQ in our main README.md before submitting your issue.

配置：
server:
  http:
    addr: 0.0.0.0
    port: 8710

apollo 远程读取后：

application:
     server:
        http:
            addr: 0.0.0.0
            port: 8710

导致：c.Scan 后内容为空。

如何保持一致？

**Comment by shenqidebaozi** [comment]
func WithOriginalConfig() Option

**Comment by XieWeiXie** [comment]
thx @shenqidebaozi
