### ISSUE TITLE
kratos v2.5 third_party/openapi/v3 annotations.proto error

### ISSUE THREAD

**Issue by chcaty** [go-kratos/kratos#2319]
#### What happened:
kratos v2.5 third_party/openapi/v3 annotations.proto 文件报错
#### What you expected to happen:
输入命令创建项目后，打开对应文件提示错误，应该把import "openapiv3/OpenAPIv3.proto";改为import "openapi/v3/openapi.proto";？
#### Environment:
- Kratos version (use `kratos -v`):
- Go version (use `go version`):
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by shenqidebaozi** [comment]
IDE displays red, please check FAQ https://go-kratos.dev/en/docs/intro/faq/

**Comment by chcaty** [comment]
![image](https://user-images.githubusercontent.com/19309511/187115990-54894caf-e85a-4099-b1ce-ca72f7231d71.png)
![image](https://user-images.githubusercontent.com/19309511/187116938-33f0cac7-9bbf-4b33-bae8-dc1896e18973.png)

**Comment by chcaty** [comment]
![image](https://user-images.githubusercontent.com/19309511/187166229-7a570b7f-c714-4faf-900f-cea3577ecff2.png)
The corresponding repository is fine, now the problem seems to be that the third-party proto files in kratos have only partially been updated

**Comment by shenqidebaozi** [comment]
No, you misunderstood me. I mean, please submit it to Kratos layout. In addition, you can help repair it directly.
