### ISSUE TITLE
需要commiter 支援一下Kratos UI

### ISSUE THREAD

**Issue by Terry-Mao** [go-kratos/kratos#235]
目前虽然Kratos很多服务治理的理念，是尽量少配置，基本不配置的方式。

但是某些场景还是需要一个完整的Dashboard来Overview看Kratos 服务的内部各种状态，比如熔断器的当前情况，某个熔断开关之类的。

需要完整的各个模块的类似expvar的方式暴露元数据，以及管理接口来完成Dashboard

**Comment by LibiChai** [comment]
目前熔断器的状态有统一存储吗？还是需要改造熔断器来提供状态查看和控制接口？

**Comment by Terry-Mao** [comment]
@LibiChai 未来是熔断器会基于paladin sdk（config sdk）来热加载更改，我们内部是watch 配置中心的变更，外网可以watch 文件，或者接下来他们基于paladin适配的apollo配置中心

**Comment by Terry-Mao** [comment]
@LibiChai 我单独开一个熔断器暴露配置的issue，方便热更新
