### ISSUE TITLE
[Help Wanted] supplementary framework unit test （补充框架单元测试）

### ISSUE THREAD

**Issue by haiyux** [go-kratos/kratos#2354]
In order to ensure the robustness of the code, we need your help to supplement the unit testing of the framework.
为了确保代码的健壮性，我们需要您的帮助来补充框架的单元测试。

- [ ] app.go
- [ ] log #2373 
- [ ] config
- - [ ] p2c
- - [ ] wrr
- - [ ] random
- - [ ] node
- [ ] encoding @guowei-gong 
- - [ ] form
- - [ ] json
- [ ] internal @bingxindan 
- - [ ] host
- - [ ] group
- - [ ] endpoint
- [ ] transport
- - [ ] grpc @Loner1024 #2371
- - [ ] http  @Mo3et 

You can comment on the tasks you want to receive below, and I will assign them to you.

**Notice**: please use "part of" not "resolves" or "fixes", or it will close this original issue

你可以在下面评论你想要收到的任务，我会把它们分配给你。

**注意**：请使用“part of”而不是“resolves”或“fixes”，否则将关闭此原始问题

**Comment by bingxindan** [comment]
【weopen star】

**Comment by haiyux** [comment]
> 【weopen star】

what?

**Comment by guowei-gong** [comment]
hey, I can add 【internal/host】testcase.

**Comment by guowei-gong** [comment]
hey, I looked at some of the modules listed in the list, Have any of them been completed? e.g host @haiyux

**Comment by Loner1024** [comment]
Please give me the job of `transport/grpc`

**Comment by Mo3et** [comment]
`transport/http`

**Comment by bingxindan** [comment]
please give me the job of internal

**Comment by bingxindan** [comment]
您好，第一次操作，没太明白：
1、我该拉哪个分支（已经有了还是我自已新创建分支）？
2、我该在哪里增加单元测试代码，没看到有aliyun的log呀？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月11日(星期天) 下午5:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [go-kratos/kratos] [Help Wanted] supplementary framework unit test （补充框架单元测试） (Issue #2354)





 
Assigned #2354 to @bingxindan.

**Comment by guowei-gong** [comment]
hey, `encoding`
