### ISSUE TITLE
[Feature] kratos new 增加自定义module名

### ISSUE THREAD

**Issue by 180909** [go-kratos/kratos#2355]
Please see the FAQ in our main README.md before submitting your issue.

### What problem is the feature used to solve?

使用`kratos new 项目名`时自动生成了go.mod，其中module名是 项目名，需要自己手动去更新module名。

### Requirements description of the feature

增加一个参数，用于生成自定义module名。

**Comment by windzhu0514** [comment]
Is no one maintaining this project now?
