### ISSUE TITLE
[BUG]Cannot create a service template under the specified path

### ISSUE THREAD

**Issue by tmdhhl** [go-kratos/kratos#2358]
#### What happened:
Cannot create a service template under the specified path, the new service template is always created at current working directory.

#### What you expected to happen:
Create a service template under the specified path

#### How to reproduce it (as minimally and precisely as possible):
<img width="894" alt="image" src="https://user-images.githubusercontent.com/38372955/188295407-ec72fd9d-d2da-45de-a43c-1a34aa000da4.png">
<img width="579" alt="image" src="https://user-images.githubusercontent.com/38372955/188295423-868e6bf8-3097-4a67-9e7a-b3604412242e.png">

#### Anything else we need to know?:
It looks like [this line](https://github.com/go-kratos/kratos/blob/617ee1aa39a09f1b93ce246d7a569e30605690fd/cmd/kratos/internal/project/new.go#L42) is wrong, because the value of variable `dir` is `os.Getwd()`.
```go
// file path: cmd/kratos/internal/project/project.go
func run(cmd *cobra.Command, args []string) {
	wd, err := os.Getwd()
	if err != nil {
		panic(err)
	}
        ...
	go func() {
		if !nomod {
			done <- p.New(ctx, wd, repoURL, branch)
			return
		}
                ...
	}()
        ...
}

// file path: cmd/kratos/internal/project/new.go
// New new a project from remote repo.
func (p *Project) New(ctx context.Context, dir string, layout string, branch string) error {
	to := path.Join(dir, p.Name)
        ...
	if err := repo.CopyTo(ctx, to, p.Path, []string{".git", ".github"}); err != nil {
		return err
	}
        ...
}
```
#### Environment:
- Kratos version (use `kratos -v`): kratos version v2.5.0
- Go version (use `go version`): go version go1.18.4
- OS (e.g: `cat /etc/os-release`): NAME="Ubuntu" VERSION="20.04.5 LTS (Focal Fossa)"
- Others:

**Comment by yzrzr** [comment]
It is recommended to support the relative path and the absolute path, but the problem is not big, `cd` to the corresponding directory to execute again is not troublesome

**Comment by Darrenzzy** [comment]
这样修改后，指定path，就无法实现指定mod了
