### ISSUE TITLE
sql.DB的重新封装导致无法获取官方sql driver的*sql.DB句柄

### ISSUE THREAD

**Issue by Colstuwjx** [go-kratos/kratos#239]
如题，kratos目前是对官方的sql.DB句柄做了重新封装，埋了读写连接分离，以及慢日志记录等，但是有个问题是，如果遇到调用其他库的时候需要用到官方的*sql.DB句柄时，可能就会有问题，这块有什么好办法吗？

举个例子，在使用 [gendry](https://github.com/didi/gendry/blob/master/builder/utils.go#L11) 做聚合查询时，需要传入*sql.DB句柄：
```
...
result,err = AggregateQuery(ctx, db, "tableName", where, AggregateCount("*")) 
numberOfRecords := result.Int64()
...
```
上述调用里第二个参数即官方库的*sql.DB句柄。

目前我这边是没使用gendry的这块功能，直接自己重新又封装了一个聚合查询的util，是否有更好的解决方案或者有啥推荐写法？
谢谢！

**Comment by LibiChai** [comment]
可以尝试提交一个pr，给DB结构体增加一个导出conn的getter。
https://github.com/bilibili/kratos/blob/09224ec67c588f0c4f631f7e86352d67ddf06e22/pkg/database/sql/sql.go#L38

**Comment by Colstuwjx** [comment]
但是读写是不同的conn啊，只暴露write conn吗？
这方面我还是存在点困惑，主要是因为官方的DB是struct...

**Comment by tonyboxes** [comment]
这个看看使用场景，其它如果不用sql.go操作数据库，直接通过driver实例化db也是可以的，因为埋点和trace估计也是不会统计到了的
