### ISSUE TITLE
自定义HTTP Handler，获取不到metadata信息

### ISSUE THREAD

**Issue by baojiliu** [go-kratos/kratos#2395]
- HTTP Clinet 
`
curl -H "x-md-tokenuser: 123"
`

- HTTP Handler
![image](https://user-images.githubusercontent.com/73427065/191493684-afa5fc80-5837-40cb-b672-fcd518661b07.png)
![image](https://user-images.githubusercontent.com/73427065/191491733-1378cd2c-1513-4668-8529-6d8ef2567888.png)

- 获取metadata信息，逻辑。此处，传递`http.Request.Context()`不能获取到`x-md-tokenuser`的值
![image](https://user-images.githubusercontent.com/73427065/191492299-b5616c5d-7165-41b2-a245-10f5f96affd7.png)

期待任何建议，谢谢。

**Comment by shenqidebaozi** [comment]
middleware 不会生效与自定义路由
