### ISSUE TITLE
使用additional_bindings后生成的xxx.http.pb.go文件无法编译

### ISSUE THREAD

**Issue by fx8080** [go-kratos/kratos#2410]
#### What happened:
生成代码错误,无法编译
#### What you expected to happen:
编译错误,报告常量重复了
#### How to reproduce it (as minimally and precisely as possible):
在protobuf文件里面用additional_bindings添加另外一个url后,使用kratos proto client 生成的http.pb.go文件里面,会重复生成常量定义
列如
const OperationSystemCreate = "/api.web.v2.System/Create"
const OperationSystemCreate = "/api.web.v2.System/Create"
多条一样的,导致代码无法编译,估计为bug

#### Environment:
- Kratos version (use `kratos -v`): v2.5.0
- Go version (use `go version`):1.17.2
- OS (e.g: `cat /etc/os-release`):windows 11
- Others:

**Comment by tonybase** [comment]
这个对应的 proto 定义是怎么样的？

**Comment by fx8080** [comment]
service Safety {
	rpc Get (api.rpc.safety.v2.Root) returns (api.rpc.safety.v2.Root){
		option (google.api.http) = { get: "/api/web/v2/root/safety/{header.bind}/get" };
	};
	rpc List (api.rpc.safety.v2.Root) returns (api.rpc.safety.v2.Root){
		option (google.api.http) = { get: "/api/web/v2/root/safety/{header.bind}/list",
		additional_bindings {
            // 定义一个 POST 接口，并且把 body 映射到 HelloRequest
            post: "/v1/greeter/say_hello",
            body: "*",
        }};
	};
}
生成代码,编译报错
api\web\v2\safety_http.pb.go:23:7: OperationSafetyList redeclared in this block
api\web\v2\safety_http.pb.go:22:7: other declaration of OperationSafetyList

生成的代码部分
const OperationSafetyGet = "/api.web.v2.Safety/Get"
const OperationSafetyList = "/api.web.v2.Safety/List"
const OperationSafetyList = "/api.web.v2.Safety/List"

type SafetyHTTPServer interface {
	Get(context.Context, *v2.Root) (*v2.Root, error)
	List(context.Context, *v2.Root) (*v2.Root, error)
}
注意有两个一样OperationSafetyList 的常量

**Comment by haiyux** [comment]
没有复现
