### ISSUE TITLE
http下返回值类型与proto定义不相符

### ISSUE THREAD

**Issue by pengzhong2010** [go-kratos/kratos#2415]
#### What happened:

-------------分隔---------------
proto如下:

syntax = "proto3";
package api.todo.v1;
option go_package = "goproject/api/todo/v1;v1";
service Todo {
  rpc CreateTodo (CreateTodoRequest) returns (CreateTodoReply) {
    option (google.api.http) = {
      post: "/todo/create",
      body: "*",
    };
}
message CreateTodoRequest {
  // title
  string title   = 1;
  // detail
  string detail  = 2;
}
message CreateTodoReply {
  // id
  int64  id     = 1;
}
-------------分隔---------------
service文件如下：

package service

import (
	"context"
	pb "goproject/api/todo/v1"
)

type TodoService struct {
	pb.UnimplementedTodoServer
}

func NewTodoService() *TodoService {
	return &TodoService{}
}

func (s *TodoService) CreateTodo(ctx context.Context, req *pb.CreateTodoRequest) (*pb.CreateTodoReply, error) {
	return &pb.CreateTodoReply{
		Id: 1,
	}, nil
}
-------------分隔---------------
实际调用创建请求放回json:
{
    "id": "16"
}

#### What you expected to happen:
期望返回
{
    "id": 16
}

#### Environment:
- Kratos version (use `kratos -v`): kratos version v2.5.0
- Go version (use `go version`): go version go1.17.5 darwin/amd64
- OS (e.g: `cat /etc/os-release`): Darwin xxx 17.7.0 Darwin Kernel Version 17.7.0
- Others:

**Comment by pengzhong2010** [comment]
看了一下源码，是在codec的地方出问题，encoding/json/json.go => 34行Marshal函数，使用了proto判断，这里看能修一下，或者有其他解决方式

**Comment by Loner1024** [comment]
我认为这样是没有问题的，你在 proto 中定义的 id 为 int64 类型，如果直接在 json 中返回 int64，由于在 javascript 中的 number 实际上是浮点数，因此直接将 go 中的 int64 类型作为number类型传递，当数字较大时可能会有溢出发生，因此将 int64 作为字符串在 json 中传递才是一种安全行为。

**Comment by pengzhong2010** [comment]
个人认为框架在int64的json返回格式不应随解析语言是js而变化，这样就失去了http传输规范的意义。这个问题可以是js的解析问题，只因js适配而改变就抛弃了其他语言接入的可能（我用的是dart，不知道有没有影响）。

目前原因我大概明白了，在现行框架下，请问除了将proto强制改成int32，有什么其他的解决方法么?

**Comment by realityone** [comment]
https://github.com/google/protobuf.dart/blob/b79707a747a7fa6ea9e36ffb83771e7aedf75754/protobuf/test/json_test.dart

proto3 一般自带 json 实现

**Comment by pengzhong2010** [comment]
> https://github.com/google/protobuf.dart/blob/b79707a747a7fa6ea9e36ffb83771e7aedf75754/protobuf/test/json_test.dart
> 
> proto3 一般自带 json 实现

谢谢大佬，我学习一下
