### ISSUE TITLE
[Question]怎么从service层中的context获取到response_writer呢

### ISSUE THREAD

**Issue by rampagecong** [go-kratos/kratos#2429]
现在我想做一下下载附件的接口，需要用response_writer来添加header和进行io.copy对文件进行下载。

**Comment by yeqown** [comment]
1. 看下 http.Context 的定义
2. 看下 internal/testdata/helloworld/helloworld_http.pb.go#31 中 _Greeter_SayHello0_HTTP_Handler 中 ctx 如何传递
