### ISSUE TITLE
cannot find flag --nomod  

### ISSUE THREAD

**Issue by 5trongHust** [go-kratos/kratos#2446]
quick start kratos new app/user --nomod
but  unknown flag: --nomod

kratos new app/user --nomod
Error: unknown flag: --nomod
Usage:
  kratos new [flags]

Flags:
  -b, --branch string     repo branch
  -h, --help              help for new
  -r, --repo-url string   layout repo (default "https://github.com/go-kratos/kratos-layout.git")
  -t, --timeout string    time out (default "60s")

2022/10/13 20:46:25 unknown flag: --nomod

➜  helloworld kratos -v       
kratos version v2.2.0

**Comment by 180909** [comment]
Hi, please upgrade kratos version, this flag implement on version 2.2.2

**Comment by haiyux** [comment]
use `kratos upgrade` to upgrade version.

**Comment by 5trongHust** [comment]
thx
