### ISSUE TITLE
google.protobuf.Any 获取到的值一直是零值

### ISSUE THREAD

**Issue by jiangsikai** [go-kratos/kratos#2463]
#### What happened:
message ProjectWebHookRequest {
	google.protobuf.Any data = 1;
}

type HookProjectVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	ProjectId uint32 `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"` // 项目id
}

func (s *ProjectmanagerService) ProjectWebHook(ctx context.Context, req *pb.ProjectWebHookRequest) (*pb.ProjectWebHookReply, error) {
	data := pb.HookProjectVersion{}
	req.Data.UnmarshalTo(&data)
获取到的req.Data 一直为nil

请求参数： 
{
    "data": {
        "projectId":1
    }
}

#### What you expected to happen:
在req中怎么才能拿到动态请求数据；我不知道是不是哪里配置的不对。

#### Environment:
- Kratos version (use `kratos -v`):
- Go version (use `go version`):
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by shenqidebaozi** [comment]
- https://pkg.go.dev/google.golang.org/protobuf/types/known/anypb

**Comment by shencw** [comment]
> proto any 也需要声明对应的 proto message，any 只是可以传入任意的 proto message 数据，如果想接收动态JSON数据，应该使用 google.protobuf.Struct，建议先阅读一下 protobuf 文档。

这个有推荐的中文的protobuf文档嘛，英文实在是太差了 😅😅😅😅😅
