### ISSUE TITLE
[Question]kratos可以返回一个纯字符串吗 

### ISSUE THREAD

**Issue by wanyuetian** [go-kratos/kratos#2470]
目前是正则对接微信公众号扫码登陆功能，微信公众号平台要求返回一个字符串
在kratos框架中我尝试使用 google.protobuf.StringValue 的方式，但是经过json序列化后会有双引号包裹

**Comment by Windfarer** [comment]
简单做法是单独在server那里挂一个http handler上去，不走proto生成的api

**Comment by wanyuetian** [comment]
> 简单做法是单独在server那里挂一个http handler上去，不走proto生成的api

恩恩，是的，后来我把gin接入进去了

**Comment by shencw** [comment]
> 简单做法是单独在server那里挂一个http handler上去，不走proto生成的api

除了这种做法还有其他的嘛？

**Comment by zoulux** [comment]
支付宝的支付也需要返回一个字符串，但是如果不走 proto 生成 api，我发现中间件什么的也走不到

**Comment by zoulux** [comment]
https://github.com/go-kratos/kratos/pull/2162

这里面我提供了一个方案 @shencw @wanyuetian
