### ISSUE TITLE
[Proposal] service health status check

### ISSUE THREAD

**Issue by shenqidebaozi** [go-kratos/kratos#2479]
- https://www.amitph.com/custom-health-check-spring-boot-actuator/

**Comment by haiyux** [comment]
https://github.com/grpc/grpc-go/blob/master/health/server.go

**Comment by tonybase** [comment]
HTTP/gRPC -> Health -> Component[ ping: redis/mysql ]

**Comment by haiyux** [comment]
@shifengbin

**Comment by shifengbin** [comment]
here

**Comment by tonybase** [comment]
```go
type Checker interface {
	Check(ctx context.Context) error
}
type CheckerFunc func() error
func (f CheckerFunc) Check() error {
	return f()
}

type Health struct {}
func (h *Health) Check(ctx context.Context) error {}
func (h *Health) Start(ctx context.Context) error {}
func (h *Health) Stop(ctx context.Context) error {}
func (h *Health) SetStatus(service string, status Status) {}
func (h *Health) ServeHTTP(w http.ResponseWriter, r *http.Request) {}
```
```

**Comment by Darrenzzy** [comment]
https://github.com/go-kratos/kratos/issues/2479#issuecomment-1305004846

对func的处理简单了点，需要支持如 any 这样类型的返回参数，gomock设计中接口设计较完善，可以参考下。

**Comment by perriea** [comment]
@tonybase @shenqidebaozi #2541 fix the problem right ? Often the http scope is not covered

**Comment by shenqidebaozi** [comment]
> @tonybase @shenqidebaozi #2541 fix the problem right ? Often the http scope is not covered

this issue is the design of the planned kratos health check interface, which has no direct relationship with your modification.
