### ISSUE TITLE
[Question] 询问框架的设计理念

### ISSUE THREAD

**Issue by jiaswee1995** [go-kratos/kratos#2485]
我已经使用了这个框架1～2个月了 感觉拿来开发微服务真的很优。
直接提高了开发的速度。

然而除了微服务 我也想开发大型http接口项目
我在意的是 虽然kratos能做到开发http接口，可是kratos的主打还是以微服务为主没错吧？

因为感觉上使用其他框架来开发http接口好像会来的比较便利，而kratos比较像是以微服务为主。

基于以上我的意见，希望开发团队可以回复一下让我知道你们的想法，应证一下我的理解是否有误。
我的想法是这个框架真的很牛 可是主要应付的场景 还是微服务为主 对吧？

**Comment by shenqidebaozi** [comment]
大型 http 接口项目我们也可以做到，但我们主要做的是多协议同构，所以如果你只需要 HTTP 的话，开发效率可能会有所下降，但是从规范性和扩展性上来说，使用 Google API 来定义你的 HTTP 接口更佳规范，可维护性更好。同时也可以应对未来的微服务需求。

**Comment by jiaswee-jiangxia** [comment]
> 大型 http 接口项目我们也可以做到，但我们主要做的是多协议同构，所以如果你只需要 HTTP 的话，开发效率可能会有所下降，但是从规范性和扩展性上来说，使用 Google API 来定义你的 HTTP 接口更佳规范，可维护性更好。同时也可以应对未来的微服务需求。

谢谢你的回复，现在我觉得我更了解这个框架了！

**Comment by shenqidebaozi** [comment]
不客气，如果有比较紧急的问题，可以通过即时通讯工具获得支持。
