### ISSUE TITLE
[Question] 接口使用 google.protobuf.Timestamp 怎么返回本地时间呢？

### ISSUE THREAD

**Issue by shencw** [go-kratos/kratos#2499]
我`.proto`文件使用了`google.protobuf.Timestamp`

代码中使用`timestamppb.New(v.Ctime)`进行转化，但是输出的时间被转化啦，这个该怎么解决呀？

```go
ctime := time.Now()
pbCtime := timestamppb.New(ctime)
fmt.Println(ctime)
fmt.Println(pbCtime.AsTime())
```

**Comment by shencw** [comment]
看了下官方文档

https://pkg.go.dev/google.golang.org/protobuf@v1.28.1/types/known/timestamppb

好像是只能返回UTC时间。。。

**Comment by shenqidebaozi** [comment]
可以看下 protojson 序列化的时候是否可以重写字段序列化

**Comment by shencw** [comment]
> 可以看下 protojson 序列化的时候是否可以重写字段序列化

没有搜到这种操作  可能是我太菜了不太会用 😭

@shenqidebaozi  包子giegie 有推荐的帖子 啥的可以看看嘛
