### ISSUE TITLE
[Question] nacos注册服务后无法被发现报错

### ISSUE THREAD

**Issue by xushuhui** [go-kratos/kratos#2512]
一个服务A注册到nacos后无法被调用，服务B的代码发现A的时候报错，msg=[resolver] Zero endpoint found,refused to write, instances: []
<img width="846" alt="image" src="https://user-images.githubusercontent.com/13704743/202075438-8cca2db8-a25d-4ec4-83bc-02c85fa7be13.png">
服务B的发现代码
```
func NewGreetClient(r registry.Discovery) v1.GreeterClient {
	conn, err := grpc.DialInsecure(
		context.Background(),
		grpc.WithEndpoint("discovery:///greet"),
		grpc.WithDiscovery(r ),
		grpc.WithMiddleware(
			recovery.Recovery(),
		),
	)
	if err != nil {
		panic(err)
	}
	return v1.NewGreeterClient(conn)

}
```
在服务B调用服务A的方法时，报错 rpc <nil> rpc error: code = DeadlineExceeded desc = context deadline exceeded

**Comment by shenqidebaozi** [comment]
服务名写错了。

**Comment by shenqidebaozi** [comment]
https://github.com/go-kratos/examples/blob/ea4257a028389233ebbf307a2e56e24ee8dc28ca/registry/nacos/client/main.go#L43

**Comment by xushuhui** [comment]
> 服务名写错了。
@shenqidebaozi 
改成 grpc.WithEndpoint("discovery:///greet.grpc")还是不行，报同样的错误

**Comment by shenqidebaozi** [comment]
namesapce 之类的配置是否正确

**Comment by guolianyu** [comment]
> > 服务名写错了。
> 
> @shenqidebaozi 改成 grpc.WithEndpoint("discovery:///greet.grpc")还是不行，报同样的错误

把nacos-sdk-go 改成1.0.9 版本试一下。  github.com/nacos-group/nacos-sdk-go@v1.0.9

**Comment by ppmsgit** [comment]
> > > 服务名写错了。
> > 
> > 
> > @shenqidebaozi 改成 grpc.WithEndpoint("discovery:///greet.grpc")还是不行，报同样的错误
> 
> 把nacos-sdk-go 改成1.0.9 版本试一下。 github.com/nacos-group/nacos-sdk-go@v1.0.9 对应的naming-client 都要改成1.0.9

智者啊！这个问题困扰两天了

**Comment by LF-DevJourney** [comment]
发现有些consul版本有这个问题，我把自己的consul改成1.15.4，就解决了。

**Comment by guolianyu** [comment]
已经收到您的来信，我会尽快回复。
