### ISSUE TITLE
[Feature]errors package constructors enhancement with fmt.Errorf like signature

### ISSUE THREAD

**Issue by tarupo** [go-kratos/kratos#2513]
### What problem is the feature used to solve?
Handy methods for constructing preset errors like `BadRequest`, `Forbidden` etc.
What we do now:
```go
var id = "whatever"
// some code
return errors.BadRequest("INVALID_ID", fmt.Sprintf("invalid id %s", id))
```

What we expect:

```go
var id = "whatever"
// some code
return errors.BadRequestf("INVALID_ID", "invalid id %s", id)
```

**Comment by shenqidebaozi** [comment]
I feel that the significance is not very great. If you want to, you can submit a PR

**Comment by tarupo** [comment]
Indeed, it does only make limited convenience. Close for now until more people need it.
