### ISSUE TITLE
The proto nested structure cannot be bound to http

### ISSUE THREAD

**Issue by Rascal0814** [go-kratos/kratos#2516]
![image](https://user-images.githubusercontent.com/80660375/202598891-d340f9c9-a884-4f30-8ece-b6ac8c8c661f.png)
/user/v1/list?index=1&size=10
#### What happened:
The proto nested structure cannot be bound to http
req{
 page:nil
}
#### What you expected to happen:
req{
 page:{
  index:1
  size:10
 }
}

#### Environment:
- Kratos version (use `kratos -v`):v2.5.2
- Go version (use `go version`):v1.9

**Comment by shenqidebaozi** [comment]
body:"*"

**Comment by Rascal0814** [comment]
Inner_object does not work with body 
![image](https://user-images.githubusercontent.com/80660375/203699351-66f211cd-261f-45e8-830f-b9d46daea583.png)

**Comment by shenqidebaozi** [comment]
The structure of the body should be consistent with the definition of protobuf

**Comment by Rascal0814** [comment]
thanks，i'm stupid！！！！

**Comment by shenqidebaozi** [comment]
If you use body, you can try body: "field name"

**Comment by shenqidebaozi** [comment]
body: "page"
