### ISSUE TITLE
kratos run目录问题

### ISSUE THREAD

**Issue by mowangchuxin** [go-kratos/kratos#2519]
kratos run运行之后，如果代码里有生成文件或者目录等操作，会被创建到相对于main.go的目录，而不是相对于项目根目录。
比如我的项目根目录叫testProject
main文件在testProject/cmd/server/main.go
如果执行kratos run运行后
我现在使用os.OpenFile()创建一个文件test.log
这个文件就会生成在 testProject/cmd/server/ 目录
而不是 testProject/ 目录

**Comment by AppleTreeQ** [comment]
hi, I am new to kratos. However, I want to make contributions to kratos.
Would you like to assign this task to me?
Thank you very much.
