### ISSUE TITLE
About Consul watch callback func problem

### ISSUE THREAD

**Issue by guolianyu** [go-kratos/kratos#2521]
I use consul to load configuration，the configuration is JSON formater, when I change value, my project c.Watch no response ，I don't how to reslove it

![image](https://user-images.githubusercontent.com/29138525/203020355-7bb7c996-4a1b-40c0-8c64-d216d988c68b.png)

![image](https://user-images.githubusercontent.com/29138525/203020719-62f85aa0-8241-41ac-917c-b306314f6470.png)

**Comment by shenqidebaozi** [comment]
you can try to watch a key instead of the file name.

**Comment by guolianyu** [comment]
已经收到您的来信，我会尽快回复。

**Comment by guolianyu** [comment]
已经收到您的来信，我会尽快回复。
