### ISSUE TITLE
[Question]守护进程的问题

### ISSUE THREAD

**Issue by benny502** [go-kratos/kratos#2531]
想请教一下，Kratos在项目使用中，经常遇到进程被系统杀死的问题，想请教一下大家都是怎么解决的。

**Comment by feiyangbeyond** [comment]
放docker、k8s里呢

**Comment by guihouchang** [comment]
首先，你要解决为什么会panic，而不是用守护进程。
守护进程的话可以使用PM2或者superversor之类的。

**Comment by benny502** [comment]
> 首先，你要解决为什么会panic，而不是用守护进程。 守护进程的话可以使用PM2或者superversor之类的。

谢谢，但是panic的情况可以用recovery恢复，但是内存占用过高时貌似也会被系统杀死，我发现过几次日志里没有报错，进程却挂掉的情况，所以才想着是不是有一种能自动重启的方法

**Comment by shenqidebaozi** [comment]
可以用 supervisor 或者 k8s 之类的守护进程管理。
