### ISSUE TITLE
在apollo删除某个key之后，通过config接口仍然可以获取到数据

### ISSUE THREAD

**Issue by qshuai** [go-kratos/kratos#2532]
在watch方法上，如果reader中没有查询到该数据，应该将cache的数据一并移除掉
<img width="584" alt="image" src="https://user-images.githubusercontent.com/20664531/203317550-ef69696f-f763-4b8f-9681-adb89e1b1bf3.png">

**Comment by shenqidebaozi** [comment]
If it is not troublesome, would you like to help us repair it？

**Comment by qshuai** [comment]
OK, my pleasure

**Comment by qshuai** [comment]
> If it is not troublesome, would you like to help us repair it？

OK, my pleasure
