### ISSUE TITLE
如何定制日志

### ISSUE THREAD

**Issue by Colstuwjx** [go-kratos/kratos#254]
Hi，

由于种种原因，一些公司内部总会需要特定的输出格式，常见的如直接输出JSON日志，或者约定格式的日志。想问一下，Kratos的日志输出是否可以定制？比如如下这样的日志：

```
INFO 08/06-18:53:30.988 http-access-log ip=127.0.0.1 params= ret=0 method=GET path=/api/v1/clusters msg=0 traceid= stack=<nil> timeout_quota=0.999965878 ts=0.004704854 user=no_user err=
```

想要定制时间部分该怎么做呢，麻烦补充下文档，谢谢！

**Comment by tomwei7** [comment]
目前日志并没有暴露注册 Handler 的接口，需要修改 log 包下的代码.
可以自己自定义一个 Handler 实现定制日志的功能:
https://github.com/bilibili/kratos/blob/2ef7f7e10c1e11f749cc7788bbd46289c2efea9d/pkg/log/handler.go#L54

**Comment by ctrysbita** [comment]
log里面有个SetFormat来着？

**Comment by Colstuwjx** [comment]
@ctrysbita SetFormat 只能设置log库里定义过的format，我上文提到的格式，log库里是不支持这样的格式的，我这边希望的日志格式是类似这样：

`[2018-06-23T03:00:00.002+08] INFO: This is a test messsage.`

@tomwei7 能否提示一下，该如何把注册handler的接口暴露出来？我这边可以PR一下，stdout和log的格式都想自定义一下。

谢谢。

**Comment by frogkind** [comment]
> 目前日志并没有暴露注册 Handler 的接口，需要修改 log 包下的代码.
> 可以自己自定义一个 Handler 实现定制日志的功能:
> https://github.com/bilibili/kratos/blob/2ef7f7e10c1e11f749cc7788bbd46289c2efea9d/pkg/log/handler.go#L54
你说的是自己修改log包代码,就是实现Handler并且赋值到这里的h Handler对吗?
https://github.com/go-kratos/kratos/blob/2ef7f7e10c1e11f749cc7788bbd46289c2efea9d/pkg/log/log.go#L58
请问有暴露日志注册 Handler 的接口的计划吗?
我理解就是直接暴露上述h Handler接口,使用者就可以不用修改kratos代码实现Handler了,是这样吗?
现在只是想包裹下日志,都需要修改 log 包的代码,很不方便

**Comment by aimpsmile** [comment]
想问一下，最终有结论了吗？是需要魔改代码吗？

**Comment by lintanghui** [comment]
参考 Logger() 的 实现自己实现个HandlerFunc 然后在engine.Use(yourLogFunc())
