### ISSUE TITLE
[Question] Deprecated: use global logger instead. 

### ISSUE THREAD

**Issue by han-meiemi** [go-kratos/kratos#2558]
```go
// Logger with server logger.
// Deprecated: use global logger instead.
func Logger(logger log.Logger) ServerOption {
	return func(s *Server) {}
}
```
请问为什么部分组件废弃 logger 注入功能，如 https://github.com/go-kratos/kratos/blob/main/transport/http/server.go#L55
这样不能让日志得到想要的输出格式，不是很合理吧
有具体的上下文讨论细节吗？没有找到有对应的 issue

**Comment by shenqidebaozi** [comment]
https://github.com/go-kratos/kratos/pull/2265

**Comment by shenqidebaozi** [comment]
The global logger will be directly used within the framework. You can also use `kratos.Logger` used by the Logger registration framework
