### ISSUE TITLE
[Question] kratos 在 k8s 环境中使用双向流是否可以负载均衡？

### ISSUE THREAD

**Issue by xichengliudui** [go-kratos/kratos#2569]
由于 grpc 双向流使用 http/2 来实现，而 http/2 是基于 tcp 长链接实现的。所以 gRPC client 直接使用 ClusterIP Service 会导致负载不均衡。
今天使用 kratos 测试发现会有一样的问题，多个请求流量会到达同一个服务端。我不确定是我测试的问题，还是 kratos 不具备这种能力所以创建个这个 Question。

**Comment by xichengliudui** [comment]
我的测试
server
```go
	r := registry.NewRegistry(client.K8sClient)
	return kratos.New(
		kratos.ID(id),
		kratos.Name("helloworld"),
		kratos.Version(Version),
		kratos.Metadata(map[string]string{}),
		kratos.Logger(logger),
		kratos.Server(
			gs,
		),
		kratos.Registrar(r),
	)
```
client
```go
	r := registry.NewRegistry(client.K8sClient)
	r.Start()
	defer r.Close()

	conn, err := grpc.DialInsecure(
		context.Background(),
		grpc.WithEndpoint("discovery:///helloworld"),
		grpc.WithDiscovery(r),
		grpc.WithMiddleware(
			recovery.Recovery(),
		),
	)
```
或者说我是否应该搭配 hendless 一起使用？任意回答都非常感谢。

**Comment by shenqidebaozi** [comment]
流式本身也无法负载均衡吧？流传输的过程中切换到了不同的后端服务

**Comment by shenqidebaozi** [comment]
流式建立之后就没办法重新负载吧，除非后端实例发生了变化

**Comment by shenqidebaozi** [comment]
例如 A 和 B 建立了流式连接，传输的过程中没办法重新负载，除非 B 发生了切换

**Comment by xichengliudui** [comment]
> 例如 A 和 B 建立了流式连接，传输的过程中没办法重新负载，除非 B 发生了切换

是这样的

**Comment by shenqidebaozi** [comment]
grpc 本身也没有流式负载均衡的概念

**Comment by shenqidebaozi** [comment]
流式一旦创建就没办法随意 rebalance，重新负载势必会影响数据传输

**Comment by shenqidebaozi** [comment]
> 这里我使用 headless service 的方式，客户端只有 A, 服务端有 B、C、D（也就是多副本），建立了三个连接分别对应
> 
> ```
> A - B
> A - C
> A - D
> ```
> 
> 这种方式看起来更像是连接池

我理解这里面某个流建立之后也是没办法重新负载的

**Comment by fengyeall111** [comment]
双向流默认情况下只能在流级别做负载均衡，不能在流内的消息级别进行负载均衡.双向流是被做当长连接来处理的.需要自定义客户端负载均衡策略或者mesh这样的网格支持自定义负载均衡插件。
