### ISSUE TITLE
当message中有自定义list消息且url中有参数时，使用生成的http client无法生成正确的url

### ISSUE THREAD

**Issue by TorryLuo** [go-kratos/kratos#2574]
#### What happened:
定义如下proto，并生成http.pb.go文件:
service Greeter {
  rpc PostSth(PsReq) returns(OK){
    option (google.api.http) = {
      post: "/hello/{id}/abc"
      body: "list1"
    };
  }
}
message PsReq {
  int32 id = 1;
  repeated ListItem list1 = 2; 
}

message ListItem {
  string name = 1;
  int32 no = 2;
}

用kratos自带客户端发起调用:
func TestGreeterService_PostSth(t *testing.T) {
	ctx := context.TODO()
	client, err := http.NewClient(ctx, http.WithEndpoint("127.0.0.1:8000"))
	if err != nil {
		t.Fail()
	}
	conn := v1.NewGreeterHTTPClient(client)
	rep, err := conn.PostSth(ctx, &v1.PsReq{
		Id:    123,
		List1: []*v1.ListItem{{Name: "abc", No: 123}},
	})
	if err != nil {
		t.Fatal(err)
	}
	t.Log(rep.Message, rep.GetSuccess())
}

得到错误信息：
error: code = 404 reason =  message =  metadata = map[] cause = proto: syntax error (line 1:1): unexpected token 404

#### What you expected to happen:
正常调用接口
#### Environment:
- Kratos version (use `kratos -v`): 2.5.3
- Go version (use `go version`):  1.17.5
- OS (e.g: `cat /etc/os-release`): macOS13
- Others:

**Comment by ruinshe** [comment]
不确定是否是同一个问题，目前我们有遇到 `POST /api/v1/{any_variable}:verb`，这里的 `any_variable` 没被传递的情况。

发现的版本是 `v2.5.4`，而在 `v2.5.0` 上是正常的。

一个简单的snippet：

```protobuf
service SampleController {
  rpc Start(StartRequest) returns (StartResponse) {
    option (google.api.http) = {
      post: "/api/v1/samples/{definition_key}:start"
      body: "data"
    };
  }
}


message StartRequest {
  string definition_key = 1 [(google.api.field_behavior) = REQUIRED];
  Sample data = 2 [(google.api.field_behavior) = REQUIRED];
}
```

**Comment by tangqiu0205** [comment]
@ruinshe 同样的问题, 一直没有升版本, 还在v2.5.0.

**Comment by ruinshe** [comment]
Hi, do you have plan to review and merge #2774 ?

**Comment by shenqidebaozi** [comment]
@ruinshe ok
