### ISSUE TITLE
[Question] kratos 如何更好的集成 swagger

### ISSUE THREAD

**Issue by wmvm0** [go-kratos/kratos#2587]
### 如何更好的集成 swagger
grpc gateway 支持从 go template 注释中提取 openapi

参考连接 https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/customizing_openapi_output/#using-go-templates-in-proto-file-comments

请问 kratos 的 openapi 中如何开启这个选项呢？

现在我有一个请求体
req.proto
```
message TradReq {
   // 最小价格
   string min_price = 1;
   string max_price = 2 [(options.openapiv2_field) = {description: "最大价格"}]; 
}
```

我希望采用备注的方式描述字段，而不是用 openapiv2_field, （openapiv2_field这样太繁琐了，影响代码体验）

**Comment by lzw5399** [comment]
@shenqidebaozi  +1 同样的问题
