### ISSUE TITLE
完整的k8s服务注册和服务发现示例

### ISSUE THREAD

**Issue by fengyeall111** [go-kratos/kratos#2588]
k8s集群内，官网的例子在grpc服务注册和发现这一点上，只有服务注册的代码，没有k8s服务发现的代码呢
另外，如果提前配置好需要的服务列表, grpc 客户端只需要向k8s api server 获取endpoint信息就可以了，有没有单纯利用这点实现服务发现的案例呢

**Comment by shenqidebaozi** [comment]
the plug-ins in contrib are the contributions of community members. If you need more support, you can contact the original author.

**Comment by shenqidebaozi** [comment]
the second point of the question is not clear. do you want to use k8s service load balancing directly?

**Comment by guihouchang** [comment]
用k8s的svc不是挺好的吗？
