### ISSUE TITLE
[Question]请问有在统一仓库中管理Proto的范例吗？

### ISSUE THREAD

**Issue by mackwan84** [go-kratos/kratos#2599]
我们正准备将历史的项目使用kratos进行重构。由于之前项目采用的微服务架构，不同服务是由不同的团队运维的，服务与服务之间数据交换也是采用gRPC调用实现的。

我们在阅读kratos文档的时候，发现了**统一仓库中管理Proto**这个方式，但是没有找到更多的相关内容了，所以想在这里请教一下具体的解决方案是如何的。
![image](https://user-images.githubusercontent.com/4495151/210513962-9a175d9f-0a8f-4782-b995-b70635fcbea4.png)

**Comment by shenqidebaozi** [comment]
github.com/go-kratos/beer-shop

**Comment by shenqidebaozi** [comment]
文档后面也有举例 googleapis、envoy-api、istio-api，可以自己 github 搜索下

**Comment by mackwan84** [comment]
> envoy-api

看了一下，似懂非懂的。主要不太理解实际实现接口的kratos微服务项目如何引用这个统一仓库，然后如何使用kratos cli工具根据统一仓库中的proto文件生成 Service 代码

**Comment by mackwan84** [comment]
> 文档后面也有举例 googleapis、envoy-api、istio-api，可以自己 github 搜索下

看了一下，似懂非懂的。主要不太理解实际实现接口的kratos微服务项目如何引用这个统一仓库，然后如何使用kratos cli工具根据统一仓库中的proto文件生成 Service 代码

**Comment by shenqidebaozi** [comment]
> 

github.com/go-kratos/beer-shop

**Comment by shenqidebaozi** [comment]
> > 文档后面也有举例 googleapis、envoy-api、istio-api，可以自己 github 搜索下
> 
> 看了一下，似懂非懂的。主要不太理解实际实现接口的kratos微服务项目如何引用这个统一仓库，然后如何使用kratos cli工具根据统一仓库中的proto文件生成 Service 代码

github.com/go-kratos/beer-shop

**Comment by shenqidebaozi** [comment]
可以看下 beer-shop 的目录，这个目录可以单独拆分为一个仓库，然后其他服务引用

**Comment by shenqidebaozi** [comment]
> > 文档后面也有举例 googleapis、envoy-api、istio-api，可以自己 github 搜索下
> 
> 看了一下，似懂非懂的。主要不太理解实际实现接口的kratos微服务项目如何引用这个统一仓库，然后如何使用kratos cli工具根据统一仓库中的proto文件生成 Service 代码

kratos cli 生成 service 模板功能非常简单，只是用于第一次接触 gRPC 的用户使用，且只能用于第一次生成，不推荐使用。

**Comment by mackwan84** [comment]
> 可以看下 beer-shop 的目录，这个目录可以单独拆分为一个仓库，然后其他服务引用

好的，那我努力钻研一下这个项目
