### ISSUE TITLE
[Question] DefaultResponseEncoder & DefaultErrorEncoder uses a internal package `httputil`

### ISSUE THREAD

**Issue by Nomango** [go-kratos/kratos#2600]
想设置自定义 ResponseDecoder 时，发现 DefaultResponseEncoder 和 DefaultErrorEncoder 用了一个 internal 的包 `httputil`，虽然 httputil.ContentType 函数很短我可以直接 copy 过来，但是想问下是否可以把这里改一下呢？

**Comment by shenqidebaozi** [comment]
internal 的本意就是不想被外部依赖

**Comment by Nomango** [comment]
是的，这样就没办法在 DefaultResponseEncoder 的基础上修改了，除非把 httputil 也复制到我自己项目来

**Comment by shenqidebaozi** [comment]
避免依赖 internal 包，internal 包不会做向下兼容保证
