### ISSUE TITLE
[Question] http服务使用nacos不稳定

### ISSUE THREAD

**Issue by jihenry** [go-kratos/kratos#2601]
一、问题现象
1. 使用transport/http包下http.NewClient方法创建实例（使用nacos）后保存，第一次请求可以成功，后面就会报“code = 503 
reason = NODE_NOT_FOUND message = error: code = 503”

二、尝试步骤
1. 尝试使用每次使用transport/http包下http.NewClient方法，但不加WithBlock基本发现不了，加了之后又非常慢

三、环境
github.com/go-kratos/kratos/contrib/registry/nacos/v2 v2.0.0-20220607143821-123fc1e6c81a
github.com/go-kratos/kratos/v2 v2.3.1
github.com/nacos-group/nacos-sdk-go v1.1.1

四、期待
1. 能否像rpc一样通过nacos稳定使用http服务的姿势，或者直接使用nacos包做发现，还是说我的nacos版本问题

**Comment by shenqidebaozi** [comment]
NODE_NOT_FOUND 的意思就是当前没有可用节点。自己检查下实例状态，NewClient 指定 WithBlock 即可，不需要每次都创建新的连接

**Comment by shenqidebaozi** [comment]
先关闭了，后续有问题可以重新打开
