### ISSUE TITLE
[Question]安装最新版本kratos初始化项目报错

### ISSUE THREAD

**Issue by EscAlice** [go-kratos/kratos#2602]
go install github.com/go-kratos/kratos/cmd/kratos/v2@latest      
                           
kratos upgrade
go install github.com/go-kratos/kratos/cmd/kratos/v2@latest
go install github.com/go-kratos/kratos/cmd/protoc-gen-go-http/v2@latest
go install github.com/go-kratos/kratos/cmd/protoc-gen-go-errors/v2@latest
go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
go install github.com/google/gnostic/cmd/protoc-gen-openapi@latest

kratos new xy_admin
🚀 Creating service xy_admin, layout repo is https://github.com/go-kratos/kratos-layout.git, please wait a moment.

error: Your local changes to the following files would be overwritten by merge:
        .gitignore
        Makefile
        api/helloworld/v1/error_reason.proto
        cmd/server/main.go
        cmd/server/wire.go
        cmd/server/wire_gen.go
        go.mod
        go.sum
        internal/biz/greeter.go
        internal/data/data.go
        internal/data/greeter.go
        internal/server/grpc.go
        internal/server/http.go
        internal/server/server.go
        openapi.yaml
        third_party/google/protobuf/descriptor.proto
Please commit your changes or stash them before you merge.
Updating cc5192f..783d0de
Aborting

ERROR: Failed to create project(exit status 1)

go version
go version go1.18.7 windows/amd64

kratos --version
kratos version v2.5.3

**Comment by shenqidebaozi** [comment]
删除用户目录下的 .kratos 文件夹

**Comment by EscAlice** [comment]
已解决，感谢
