### ISSUE TITLE
[Question]使用nacos服务发现方式如何获取remoteAddr

### ISSUE THREAD

**Issue by kqbi** [go-kratos/kratos#2607]
conn, err := grpc.DialInsecure(
		context.Background(),
		grpc.WithEndpoint("discovery:///helloworld.grpc"),
		grpc.WithDiscovery(nacos.New(cli)),
	)
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close()

	client := helloworld.NewGreeterClient(conn)
	reply, err := client.SayHello(context.Background(), &helloworld.HelloRequest{Name: "kratos"})
	if err != nil {
		log.Fatal(err)
	}
使用nacos服务发现方式发送请求怎么知道发到了哪个服务（具体服务端的IP和端口）上去了，相应的
// SayHello implements helloworld.GreeterServer
func (s *server) SayHello(ctx context.Context, in *pb.HelloRequest) (*pb.HelloReply, error) {
	return &pb.HelloReply{Message: fmt.Sprintf("Welcome %+v!", in.Name)}, nil
}
服务端收到相应的请求怎么知道这个请求是从哪个客户端发过来的（具体客户端的IP和端口）

**Comment by shenqidebaozi** [comment]
服务端获取客户端地址可以使用 grpc peer 包，客户端获取请求的实际服务 可以用 selector.FromPeerContext(ctx)

**Comment by kqbi** [comment]
在服务端获取客户端地址可以使用 grpc peer 包，是可以成功获取的。
在客户端使用selector.FromPeerContext(ctx)没获取成功
ctx := context.Background()
	client, err := o.data.fsAgentClient.Originate(ctx, c)
	
	peer, ok := selector.FromPeerContext(ctx)
	fmt.Println("Address3 ==================== ",  ok)
	if ok && peer != nil && peer.Node != nil {
		// 统计服务发现数据
		fmt.Println("Address4 ==================== ", peer.Node.Address(), ok)
	}
这边ok返回的是false
这个是参照example/registry/nacos/client里的
	client := helloworld.NewGreeterClient(conn)
	reply, err := client.SayHello(context.Background(), &helloworld.HelloRequest{Name: "kratos"})

**Comment by kqbi** [comment]
是不是context初始化的问题

**Comment by shenqidebaozi** [comment]
> 在服务端获取客户端地址可以使用 grpc peer 包，是可以成功获取的。 在客户端使用selector.FromPeerContext(ctx)没获取成功
> 
> ```
> ctx := context.Background()
> 	client, err := o.data.fsAgentClient.Originate(ctx, c)
> 	
> 	peer, ok := selector.FromPeerContext(ctx)
> 	fmt.Println("Address3 ==================== ",  ok)
> 	if ok && peer != nil && peer.Node != nil {
> 		// 统计服务发现数据
> 		fmt.Println("Address4 ==================== ", peer.Node.Address(), ok)
> 	}
> ```
> 
> 这边ok返回的是false 这个是参照example/registry/nacos/client里的
> 
> ```
> 	client := helloworld.NewGreeterClient(conn)
> 	reply, err := client.SayHello(context.Background(), &helloworld.HelloRequest{Name: "kratos"})
> ```

首先是要在调用之后获取，你这是在连接初始化的地方获取

**Comment by shenqidebaozi** [comment]
你这个代码很乱，看不出来都是什么，可以尝试在 client 的 middleware 增加我贴的中间件示例代码进行测试

**Comment by kqbi** [comment]
```
func discovery() middleware.Middleware {
	return func(handler middleware.Handler) middleware.Handler {
		return func(ctx context.Context, req interface{}) (interface{}, error) {
			reply, err := handler(ctx, req)
			
			peer, ok := selector.FromPeerContext(ctx);
			fmt.Println("Address5 ==================== ",  ok)
			if ok && peer != nil && peer.Node != nil {
				// 统计服务发现数据
				fmt.Println("Address6 ==================== ",  peer.Node.Address(), ok)

			}
			return reply, err
		}
	}
}
```
```
conn, err := grpc.DialInsecure(
		context.Background(),
		grpc.WithEndpoint("discovery:///helloworld.grpc"),
		grpc.WithDiscovery(dis),
		grpc.WithMiddleware(discovery()),
		
	)
	
	client := v1.NewGreeterClient(conn)
	ctx := context.Background()
	reply , err :=client.SayHello(ctx, &v1.HelloRequest{Name: "kratos"})

	peer, ok := selector.FromPeerContext(ctx)
	fmt.Println("Address3 ==================== ",  ok)
	if ok && peer != nil && peer.Node != nil {
		// 统计服务发现数据
		fmt.Println("Address4 ==================== ", peer.Node.Address(), ok)
	}
```
使用examps里的helloworld例子，在middleware里的discovery是正常的，但是在client.SayHello之后调用selector.FromPeerContext(ctx)就失败
```
Address5 ====================  true
Address6 ====================  172.30.92.68:9200 true
Address3 ====================  false
```

然后examps里的helloworld例子的peotobuf是非流式的
```
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {
    option (google.api.http) = {
      get: "/helloworld/{name}"
    };
  }
}
```
我的实际业务代码的peotobuf是这样的带stream的
 ```
 rpc originate(callReq) returns (stream event) {
  }
```
这种接口不管是在middleware里的discovery还是client.originate之后调用selector.FromPeerContext(ctx)都是失败

**Comment by shenqidebaozi** [comment]
kratos middleware 不支持流式

**Comment by shenqidebaozi** [comment]
> 使用examps里的helloworld例子，在middleware里的discovery是正常的，但是在client.SayHello之后调用selector.FromPeerContext(ctx)就失败

这个是 grpc client call 的问题，和我们无关

> 我的实际业务代码的peotobuf是这样的带stream的
rpc originate(callReq) returns (stream event) {
 }
这种接口不管是在middleware里的discovery还是client.originate之后调用selector.FromPeerContext(ctx)都是失败

kratos middleware 对流式支持有限

**Comment by kqbi** [comment]
好的，了解了，感谢大佬！！！
