### ISSUE TITLE
[Question] kratos new app/user --nomod 问题

### ISSUE THREAD

**Issue by sunhuafengzeishuai** [go-kratos/kratos#2609]
kratos new helloworld
cd helloworld
kratos new app/user --nomod
运行最后提示go.mod don't exists ，kratos 是最新版的。v2.5.2是没有问题的

**Comment by shenqidebaozi** [comment]
kratos new xxx--nomod 要求当前目录下需要存在 go.mod 文件，从支持 --nomod 参数时，就有此限制，至于你说的 v2.5.2 版本没有问题，是不是你两个版本命令的执行环境有区别

**Comment by sunhuafengzeishuai** [comment]
我根据文档上用的大仓模式，然后helloworld里面有go.mod。环境是用docker跑的，最新版有问题，就新建一个容器去跑，俩个版本分开的。

**Comment by shenqidebaozi** [comment]
这部分逻辑没有修改过，建议再确认下执行环境区别

**Comment by shenqidebaozi** [comment]
https://github.com/go-kratos/kratos/pull/2024

**Comment by sunhuafengzeishuai** [comment]
![image](https://user-images.githubusercontent.com/27751420/211257146-74b367af-4969-4d04-8757-e042d669225d.png)
我对比了v2.5.3和v2.5.2版本代码。
文件路径cmd/kratos/internal/project/project.go 
v2.5.3版本第69行多了wd = getProjectPlaceDir(name, wd)。把wd原本的的路径给替换了，v2.5.2校验的是/go/src/helloworld下有没有go.mod。v2.5.3版本校验的是/go/src/helloworld/app

**Comment by shenqidebaozi** [comment]
明白，可以直接帮忙修改一下吗？

**Comment by czyt** [comment]
sorry,之前是我加的这部分代码，`--nomod`这个参数也确实没理解它的具体场景。问题的pr已经提交 https://github.com/go-kratos/kratos/pull/2611 处理方式是，检查对应的目录下是否有go.mod文件，如果没有就再向上一级寻找，找到以后，将该路径作为gomod项目的根目录。如果一直没找到，到最顶级根目录的时候，如`c:`或者`/`，则会返回最顶层的目录,并且check failed。
