### ISSUE TITLE
JWT Middleware

### ISSUE THREAD

**Issue by luminosita** [go-kratos/kratos#2617]
It could be that I am using middleware in a wrong way but what is the reason for Authentication (JWT) middleware to skip on gRPC stream calls? That is a big security hole in my opinion. All middleware are attaching only to unary operations and skipping stream operations in general. I guess there is a good reason for that.

BTW, I can not see FAQ section in README.md. Sorry if this is already asked and answered somewhere.

**Comment by shenqidebaozi** [comment]
Kratos middleware does not support gRPC stream completely

**Comment by urdarinda** [comment]
@shenqidebaozi any plans to add middleware support for streams?
