### ISSUE TITLE
[Question] protoc-gen-go-http 是否可以是增量生成变更

### ISSUE THREAD

**Issue by baojiliu** [go-kratos/kratos#2629]
在使用 `protoc-gen-go-http`  在不同开发者，编译proto到目标语言时，不是增量生成变更。如
![image](https://user-images.githubusercontent.com/73427065/213226906-c07da3f6-fb5e-4c3b-9253-8cd24715b8ca.png)

我发现如下代码
https://github.com/go-kratos/kratos/blob/2a989ea0fee7e1f30966ad314529ef7bea882f08/cmd/protoc-gen-go-http/http.go#L163

期待，任何建议，谢谢!

**Comment by Yangruipis** [comment]
编译proto前排序一下即可，比如：

```bash
API_PROTO_FILES=$(shell find api -name *.proto | sort -u)

# ...

protoc --proto_path=./api/schema \
	       ... \
	       ${API_PROTO_FILES}
```
