### ISSUE TITLE
服务运行一段时间后会出现rpc error: code = DeadlineExceeded desc = context deadline exceeded 

### ISSUE THREAD

**Issue by EayonLee** [go-kratos/kratos#2641]
服务刚启动一段时间内rpc调用都是正常的，过一段时间后（如一两小时）会出先rpc error: code = DeadlineExceeded desc = context deadline exceeded

客户端和服务端的timeout设置均为3s，不存在业务超时的情况

func NewPayOrderServiceClient(r registry.Discovery) order.OrderClient {
        ctx, _ := context.WithTimeout(context.Background(), 3*time.Second)
	clientConn, err := grpc.DialInsecure(
		ctx,
		grpc.WithEndpoint("discovery:///tme-dating-payment-service-test.grpc"),
		grpc.WithDiscovery(r),
		grpc.WithMiddleware(
			recovery.Recovery(),
		),
		grpc.WithTimeout(time.Second*3),
	)
	if err != nil {
		panic(err)
	}
	return order.NewOrderClient(clientConn)
}

**Comment by EayonLee** [comment]
使用的注册中心是nacos

**Comment by shenqidebaozi** [comment]
要看是哪里抛出的 ctx 超时，另外确认业务不会超时吗？

**Comment by longsmiler** [comment]
这个问题是否已经解决？ 我也遇到了同样的情况

**Comment by shenqidebaozi** [comment]
> 这个问题是否已经解决？ 我也遇到了同样的情况

必现？是否可以提供复现代码

**Comment by longsmiler** [comment]
> > 这个问题是否已经解决？ 我也遇到了同样的情况
> 
> 必现？是否可以提供复现代码

并不是必现，多次情况是跑了一段时间之后就会复现，我注册的 etcd 集群，刚启动的时候没问题，一段时间过后报错如下：服务可以正常访问，

**Comment by longsmiler** [comment]
> > 这个问题是否已经解决？ 我也遇到了同样的情况
> 
> 必现？是否可以提供复现代码

并不是一定出现，刚启动的时候是正常的，跑一段时间就会复现。我用的 etcd 注册服务集群，出错后用 postman 可以访问到对应的服务，服务之间调度会报错：

WARN ts=2023-02-03T01:32:37Z caller=resolver.go:74 service.id=user service.name=user-management service.version=v1.0.0 trace_id= span_id= msg=[resolver] Zero endpoint found,refused to write, instances: []
WARN ts=2023-02-03T01:32:37Z caller=resolver.go:74 service.id=user service.name=user-management service.version=v1.0.0 trace_id= span_id= msg=[resolver] Zero endpoint found,refused to write, instances: []
WARN ts=2023-02-03T01:32:37Z caller=resolver.go:74 service.id=user service.name=user-management service.version=v1.0.0 trace_id= span_id= msg=[resolver] Zero endpoint found,refused to write, instances: []

**Comment by shenqidebaozi** [comment]
> > > 这个问题是否已经解决？ 我也遇到了同样的情况
> > 
> > 
> > 必现？是否可以提供复现代码
> 
> 并不是一定出现，刚启动的时候是正常的，跑一段时间就会复现。我用的 etcd 注册服务集群，出错后用 postman 可以访问到对应的服务，服务之间调度会报错：
> 
> WARN ts=2023-02-03T01:32:37Z caller=resolver.go:74 service.id=user service.name=user-management service.version=v1.0.0 trace_id= span_id= msg=[resolver] Zero endpoint found,refused to write, instances: [] WARN ts=2023-02-03T01:32:37Z caller=resolver.go:74 service.id=user service.name=user-management service.version=v1.0.0 trace_id= span_id= msg=[resolver] Zero endpoint found,refused to write, instances: [] WARN ts=2023-02-03T01:32:37Z caller=resolver.go:74 service.id=user service.name=user-management service.version=v1.0.0 trace_id= span_id= msg=[resolver] Zero endpoint found,refused to write, instances: []

这不是没有可用的实例节点吗？不是一个问题呀

**Comment by shenqidebaozi** [comment]
> > > 这个问题是否已经解决？ 我也遇到了同样的情况
> > 
> > 
> > 必现？是否可以提供复现代码
> 
> 并不是一定出现，刚启动的时候是正常的，跑一段时间就会复现。我用的 etcd 注册服务集群，出错后用 postman 可以访问到对应的服务，服务之间调度会报错：
> 
> WARN ts=2023-02-03T01:32:37Z caller=resolver.go:74 service.id=user service.name=user-management service.version=v1.0.0 trace_id= span_id= msg=[resolver] Zero endpoint found,refused to write, instances: [] WARN ts=2023-02-03T01:32:37Z caller=resolver.go:74 service.id=user service.name=user-management service.version=v1.0.0 trace_id= span_id= msg=[resolver] Zero endpoint found,refused to write, instances: [] WARN ts=2023-02-03T01:32:37Z caller=resolver.go:74 service.id=user service.name=user-management service.version=v1.0.0 trace_id= span_id= msg=[resolver] Zero endpoint found,refused to write, instances: []

这个是你初始化连接之后，没有可用的对端服务实例，可以考虑使用 with block。这个不是 bug。

**Comment by longsmiler** [comment]
> > > > 这个问题是否已经解决？ 我也遇到了同样的情况
> > > 
> > > 
> > > 必现？是否可以提供复现代码
> > 
> > 
> > 并不是一定出现，刚启动的时候是正常的，跑一段时间就会复现。我用的 etcd 注册服务集群，出错后用 postman 可以访问到对应的服务，服务之间调度会报错：
> > WARN ts=2023-02-03T01:32:37Z caller=resolver.go:74 service.id=user service.name=user-management service.version=v1.0.0 trace_id= span_id= msg=[resolver] Zero endpoint found,refused to write, instances: [] WARN ts=2023-02-03T01:32:37Z caller=resolver.go:74 service.id=user service.name=user-management service.version=v1.0.0 trace_id= span_id= msg=[resolver] Zero endpoint found,refused to write, instances: [] WARN ts=2023-02-03T01:32:37Z caller=resolver.go:74 service.id=user service.name=user-management service.version=v1.0.0 trace_id= span_id= msg=[resolver] Zero endpoint found,refused to write, instances: []
> 
> @longsmiler 这个是你初始化连接之后，没有可用的对端服务实例，可以考虑使用 with block。这个不是 bug。

好的，我试试，感谢！

**Comment by fans3210** [comment]
这个我也遇到了，withblock会一直block下去，确实找不到，也是注册在etcd里的，会不会注册失败但是没有报错呢？服务开了挺长时间的，偶尔会遇到这个问题

**Comment by shenqidebaozi** [comment]
出现问题的时候可以看下 etcd 中是否有对应的键值对

**Comment by EayonLee** [comment]
经过排查是因为项目抛出fatal error 后 K8S的pod重启，重启之后再次进行rpc调用会必现 rpc error: code = DeadlineExceeded desc = context deadline exceeded 的问题，请问大概是什么原因呢？

**Comment by ppmsgit** [comment]
> 使用的注册中心是nacos

请问解决了吗？我也遇到了

**Comment by swurtheone** [comment]
我也遇到了这个问题，服务注册后一段时间会出现：rpc error: code = DeadlineExceeded desc = context deadline exceeded
nacos中的心跳检测、实例都是正常的，刚开始部署时服务都是正常的，大概过了1-2个小时就开始出现异常

**Comment by swurtheone** [comment]
> 使用的注册中心是nacos

大佬，你后面是怎么处理的？

**Comment by ruohone** [comment]
我遇见过这个问题，是因为grpc版本的原因，我使用grpc v1.56.1没有问题。但是升级到v1.58就有问题。具体原因还没有找到。

**Comment by swurtheone** [comment]
通过测试排查，排除nacos问题，根本原因是grpcx.WithIdleTimeout(0)的参数设置问题，idleTimeout为空闲管道超时时间，默认超时时间为30min，超过该时间没有rpc服务调用，则会关闭解析器

**Comment by swurtheone** [comment]
> 通过测试排查，排除nacos问题，根本原因是idleTimeout的参数设置问题，idleTimeout为空闲管道超时时间，默认超时时间为30min，超过该时间没有rpc服务调用，则会关闭解析器,解决办法禁用空闲超时时间，
conn, err := grpc.DialInsecure(
		context.Background(),
		grpc.WithEndpoint(endpoint),
		grpc.WithDiscovery(rr),
		grpc.WithMiddleware(
			metadata.Client(),
			recovery.Recovery(),
		),
		grpc.WithTimeout(3*time.Second),
		// 设置空闲连接超时时间
		grpc.WithOptions(grpcx.WithIdleTimeout(0)),
	)
