### ISSUE TITLE
[Question] go-kratos 如何打包线上包，有没有一个最佳实践

### ISSUE THREAD

**Issue by gaoyong06** [go-kratos/kratos#2650]
Please see the FAQ in our main README.md before submitting your issue.
平时开发的时候，都是 kratos run 这样跑起来

打线上包，就会有编译好的二进制文件，配置文件，日志文件 等等，这些

不知道，大家在实践中，是如何操作的？

**Comment by aveyuan** [comment]
进入到cmd 然后go build 这个样子。

**Comment by hoslo** [comment]
1. The configuration file is usually read from the registry.
2. Logs are usually output to the log server or stdout
So the end product is usually a binary, more commonly packaged as a docker image
