### ISSUE TITLE
[Question]api将一个服务proto拆分，grpc，http是否需要配置多个服务？

### ISSUE THREAD

**Issue by HalcyonDaysssss** [go-kratos/kratos#2654]
例如，admin服务。我拆分功能为：user.proto、menu.proto、api.proto。
如此的话，在grpc跟http，需要配置UnimplementedUserServer、UnimplementedMenuServer、UnimplementedApiServer。以及
RegisterUserHTTPServer,xxx,xxx 跟 RegisterUserServer、xxxx。

能否将user.proto、menu.proto、api.proto。在用一个比如bffAdmin.proto整合在一起，这样grpc，http只需要填一个即可？

**Comment by whtiehack** [comment]
不需要,用同一个svr注册就行了

**Comment by HalcyonDaysssss** [comment]
> 不需要，用同一个svr注册就可以了

不是很懂，能详细说下吗，大佬。。。。

**Comment by HalcyonDaysssss** [comment]
> 不需要,用同一个svr注册就行了

我原本是只有一个sys.proto的，但是业务一多，proto就很乱，我在api/sys/v1目录下拆分为user.proto、menu.proto，然后生成了对应的http.pb，grpc.pb，服务端是不是只能填对应的UnimplementedXXXXServer、RegisterXXXXHTTPServer??

**Comment by czyt** [comment]
xxxServer 是针对service定义的  proto的rpc不支持拆分

**Comment by whtiehack** [comment]
> > 不需要,用同一个svr注册就行了
> 
> 我原本是只有一个sys.proto的，但是业务一多，proto就很乱，我在api/sys/v1目录下拆分为user.proto、menu.proto，然后生成了对应的http.pb，grpc.pb，服务端是不是只能填对应的UnimplementedXXXXServer、RegisterXXXXHTTPServer??

貌似理解错你的问题了. 这个没办法共用一个 注册. 只能一个一个注册

**Comment by shenqidebaozi** [comment]
> > 不需要,用同一个svr注册就行了
> 
> 我原本是只有一个sys.proto的，但是业务一多，proto就很乱，我在api/sys/v1目录下拆分为user.proto、menu.proto，然后生成了对应的http.pb，grpc.pb，服务端是不是只能填对应的UnimplementedXXXXServer、RegisterXXXXHTTPServer??

如果存在多个 Service 需要注册多个，如果只是拆分文件不需要
