### ISSUE TITLE
[Question] 生成路由和googleapis.http.proto注释表述不同

### ISSUE THREAD

**Issue by shencw** [go-kratos/kratos#2656]
在kratos中使用代码生成路由
```proto
service Messaging {
       rpc GetMessage(GetMessageRequest) returns (Message) {
         option (google.api.http) = {
             get: "/v1/{name=messages/*}"
         };
       }
}
message GetMessageRequest {
     string name = 1; // Mapped to URL path.
 }
message Message {
     string text = 1; // The resource content.
}
```
生成结果为
![image](https://user-images.githubusercontent.com/30680771/217478014-9d2510e2-cc72-4f1b-9a26-1803e389925d.png)

而不是文档中所描述的
 HTTP | gRPC
 -----|-----
 `GET /v1/messages/123456`  | `GetMessage(name: "messages/123456")`

与文件[http.proto](https://github.com/googleapis/googleapis/blob/master/google/api/http.proto#L67:L87)中描述不同，不确定是不是我的使用姿势有问题~

还请大佬指教

**Comment by shenqidebaozi** [comment]
按照你提供的信息来测试，没能复现
<img width="783" alt="image" src="https://user-images.githubusercontent.com/35397691/217503767-a6a39515-e8ff-4bb5-94aa-eb4162c9e4b7.png">
<img width="604" alt="image" src="https://user-images.githubusercontent.com/35397691/217503792-7c4a8ce0-3bbc-4a45-88be-ddbfdeb989a8.png">

**Comment by shencw** [comment]
> /v1/messages/

抱歉啊，我代码粘贴错了 😅😅😅😅😅😅

我重新改了代码

**Comment by shencw** [comment]
实际是没有问题的，写错了
