### ISSUE TITLE
nodes modifyed by append func

### ISSUE THREAD

**Issue by ZBIGBEAR** [go-kratos/kratos#2666]
#### What happened:
selector/filter/version.go Version func has bug.

#### How to reproduce it (as minimally and precisely as possible):
modify like this:

newNodes := make([]selector.Node, 0, len(nodes))

#### Environment:
- Kratos version (use `kratos -v`):
- Go version (use `go version`):
go version go1.19.1 darwin/amd64
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by shenqidebaozi** [comment]
I hope you can submit PR directly for modification.
