### ISSUE TITLE
[Question] 使用阿里云mse nacos作为服务注册中心，但是对nacos-go-sdk版本有要求，可以升级吗

### ISSUE THREAD

**Issue by jiangwennn** [go-kratos/kratos#2673]
Please see the FAQ in our main README.md before submitting your issue.
目前使用 nacos-go-sdk@v1.1.4，服务发现会报错，改为v1.0.9后就正常了
```
panic: failed to build resolver: discovery create watcher overtime
```

https://help.aliyun.com/document_detail/417901.html

![image](https://user-images.githubusercontent.com/21187340/220816019-096bb97d-2cb4-46b6-930e-ad67380d4a08.png)

**Comment by shenqidebaozi** [comment]
可以升级到 nacos 最新版本

**Comment by shenqidebaozi** [comment]
如果没有不兼容更新的话，是否可以直接帮忙提交一个 PR 升级呢？

**Comment by jiangwennn** [comment]
升级到nacos-go-sdk@v1.1.4会报错，这个还没看是啥原因😅 @shenqidebaozi 

```
panic: failed to build resolver: discovery create watcher overtime
```

**Comment by shenqidebaozi** [comment]
可能nacos 接口有变更吧，可以直接帮修一下吗？

**Comment by shenqidebaozi** [comment]
我看升级sdk版本之后本地会报错

**Comment by shenqidebaozi** [comment]
https://github.com/go-kratos/kratos/pull/2622

**Comment by jiangwennn** [comment]
好，我试试看

**Comment by shenqidebaozi** [comment]
这个是nacos 不同版本实现不同？可以帮忙适配一下

**Comment by jiangwennn** [comment]
#2682

**Comment by wu-weichao** [comment]
#2682 没有合并到主干上，这个问题你们解决了吗？ @shenqidebaozi @jiangwennn
