### ISSUE TITLE
在kratos中使用gin路由时中间件无法拦截请求的返回值

### ISSUE THREAD

**Issue by CodeFish-xiao** [go-kratos/kratos#2674]
> > https://github.com/go-kratos/gin/blob/main/examples/simple/main.go 看下是否满足需求 @cq-z
> 
> 我在使用这个中间件时发现，
> 
> ```
> ge.Use(kgin.Middlewares(
> 		//recovery.Recovery(),
> 		//logging.Server(logger),
> 		selector.Server(jwt.Server(func(token *jwt2.Token) (interface{}, error) { return []byte(c.Jwt.Key), nil }, jwt.WithSigningMethod(jwt2.SigningMethodHS256))).Match(NewWhiteListMatcher()).Build(),
> 		//customMiddleware,
> 	))
> ```
> 
> 无法直接返回401，而是会进行实际的gin方法的调用，如果加了log组件后，会打印401，但是请求依旧正常是200
> 
> ![564581677122508_ pic](https://user-images.githubusercontent.com/48681482/220818354-f92761a6-fa52-42c7-a5d8-8115690198d7.jpg)

补充说明：
![image](https://user-images.githubusercontent.com/48681482/220818636-c9ae31fd-42a2-4ecb-914a-ade788168da3.png)

_Originally posted by @CodeFish-xiao in https://github.com/go-kratos/kratos/issues/1182#issuecomment-1441190080_

**Comment by shenqidebaozi** [comment]
gin 插件不是官方维护的，如果有问题可以直接帮忙修复

**Comment by shenqidebaozi** [comment]
看起来是 gin 实现没有处理返回的 errors，也就是默认 http 的 errorsEncoder 功能
