### ISSUE TITLE
使用框架的httpClient发送请求，无法获取服务端回复的http中的replyHeader信息

### ISSUE THREAD

**Issue by kqbi** [go-kratos/kratos#2680]
一个如下请求，可以获取服务端回复的body信息，无法获取回复的replyHeader信息

ctxClient := context.Background()
if s.Range != "" {
  ctxClient = metadata.AppendToClientContext(ctxClient, "Range", s.Range)
}
reply, err := client.Download(ctxClient, &pb.DownloadReq{BusyId: gr.storageConfig.Bucket, Key: s.Key})
res.Buf = reply.GetData()

使用的是v2.5.3版本

**Comment by shenqidebaozi** [comment]
是提一个 feature 要求支持 http client 的结果的 header 获取

**Comment by kqbi** [comment]
大佬，这个有什么计划吗？大概什么时间能更新？

**Comment by shenqidebaozi** [comment]
这个没办法支持的，ctx 都是派生的，没办法把后续增加的元数据，赋值到最开始传入的 ctx 上，可以在中间件里获取。

**Comment by kqbi** [comment]
这个不是在另一个issue讨论过了吗，中间件拿不到啊replyHeader是空值#2665，这个问题就是当时使用中间件方式获取不到，重开的问题啊

**Comment by kqbi** [comment]
@shenqidebaozi

**Comment by shenqidebaozi** [comment]
是经过研究之后发现不能实现，原因就是我说的那个，因为现在的返回值是具体方法结果，不是类似标准库的request 对象，所以没办法取header，另外我记得中间件获取你试了没问题的

**Comment by kqbi** [comment]
```
h := func(ctx context.Context, in interface{}) (interface{}, error) {
		res, err := client.do(req.WithContext(ctx))
		if res != nil {
			cs := csAttempt{res: res}
			for _, o := range opts {
				o.after(&c, &cs)
			}
		}
		if err != nil {
			return nil, err
		}
		defer res.Body.Close()
		if err := client.opts.decoder(ctx, res, reply); err != nil {
			return nil, err
		}
		return reply, nil
	}

func DefaultResponseDecoder(ctx context.Context, res *http.Response, v interface{}) error {
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}
	return CodecForResponse(res).Unmarshal(data, v)
}
```
kratos里边header没处理啊
![220344348-7efc074e-0408-4da9-bef3-35f108caea9e](https://user-images.githubusercontent.com/40823194/226081083-a5c026d1-1f14-473c-a57f-934eb837d76a.png)
中间件拿不到

**Comment by kqbi** [comment]
我知道了从重载的responseDecoder里拿

**Comment by shenqidebaozi** [comment]
中间件里面无法获取header 的问题可以尝试解决，但是直接通过返回值去获取没办法解决，首先 ctx 是派生的，不会影响到你传入的ctx，另外是返回了方法的结果而不是req 对象

**Comment by kqbi** [comment]
![i讯飞图片_1679109114682](https://user-images.githubusercontent.com/40823194/226081485-34c5dde0-b5a2-49da-b66c-4697d7573001.png)
![i讯飞图片_1679109128531](https://user-images.githubusercontent.com/40823194/226081488-62c6b92c-a980-43ad-a77e-bb1b0d53c4ce.png)
这样子重载的话中间件里res里的header怎么跟后边解析的body结果关联起来啊

**Comment by shenqidebaozi** [comment]
刚才就解释了呀，返回的是方法结果，所以没办法携带header

**Comment by kqbi** [comment]
就没办法解决吗？好纠结啊，同时拿到body和header

**Comment by shenqidebaozi** [comment]
你可以用类似 client 上的 invoke 的方法看下，有没有header

**Comment by kqbi** [comment]
invoke不行，目前用的下面调用的其实就是Invoke,封装死了，我用Do试下吧!!!

**Comment by kqbi** [comment]
用Do就可以了，感谢大佬这段时间的一些解惑！！！
