### ISSUE TITLE
配置文件加载如果是文件夹，更新配置重新加载则会报错

### ISSUE THREAD

**Issue by shuqingzai** [go-kratos/kratos#2681]
#### What happened:
1. 如果配置文件存在多个，加载整个文件夹启动，此时去修改文件夹下的配置会报错，显示没找到配置文件，文件找不到是因为文件名会加个 `~` 号

```bash
# 示例 编译后启动项目，可以正常启动
cmd/server/app -app-config configs/env/
```

修改 `env` 目录下某项目配置，然后就会报错，`yaml` 后缀变成 `yaml~` ，导致无法加载？
```json
{"caller": "config/config.go:75", "environment": "LOCAL", "service.name": "xxx", "service.id": "xxx", "service.version": "0.0.1", "service.build": "go version: go1.20.1 darwin/amd64 [gc] git-build version:  [ - ]", "trace_id": "", "span_id": "", "msg": "failed to merge next config: unsupported key: config.yaml~ format: yaml~"}

2023-02-24T14:15:39.430264+08:00	ERROR	v2@v2.0.0-20230223102623-19f008b48379/zap.go:41		{"caller": "config/config.go:71", "environment": "LOCAL", "service.name": "xxx", "service.id": "xxx", "service.version": "0.0.1", "service.build": "go version: go1.20.1 darwin/amd64 [gc] git-build version:  [ - ]", "trace_id": "", "span_id": "", "msg": "failed to watch next config: open configs/env/config.yaml~: no such file or directory"}
```

断点停在 https://github.com/go-kratos/kratos/blob/main/config/file/watcher.go#L51

![image](https://user-images.githubusercontent.com/44406033/221106868-378fc5b4-9be7-4c6f-af6b-a7ae43dd783d.png)

#### Environment:
- Kratos version (use `kratos -v`):
```bash
kratos -v
kratos version v2.5.3
```
- Go version (use `go version`):
```bash
go version
go version go1.20.1 darwin/amd64
```
- OS (e.g: `cat /etc/os-release`):
```bash
MacOS 12
```
- Others:

**Comment by shenqidebaozi** [comment]
ide 问题和框架无关呢

**Comment by shenqidebaozi** [comment]
ide 在修改文件的时候，会创建一个临时文件，可以换其他方式编辑

**Comment by shuqingzai** [comment]
直接编译运行也是会报错，所以才使用 IDE 调试一下的，两个的结果一致，都是会报错

**Comment by whtiehack** [comment]
配置文件在git版本库里吗? 在版本库里改.然后这里git pull 试试

**Comment by shuqingzai** [comment]
> 配置文件在git版本库里吗? 在版本库里改.然后这里git pull 试试

配置文件不会放在 版本库啦

**Comment by shuqingzai** [comment]
> ide 在修改文件的时候，会创建一个临时文件，可以换其他方式编辑

指定文件夹就会报错，指定文件则不会

**Comment by shenqidebaozi** [comment]
指定文件肯定不会有问题呀，因为 fsnotify 监听的是指定的文件，当你指定目录的时候，整个目录的变化都会被监听到。

**Comment by shenqidebaozi** [comment]
kratos 接收 fsnotify 的文件夹变化通知，因为你保存之后文件没了，但是 fsnotify 又通知了变化, kratos 去读取的时候肯定会出错的，如果忽略错误也不合理，因为如果真的是文件不存在如果忽略了错误还去 watch 配置可能会导致更严重的问题。建议是通过不会产生临时文件的方式去修改文件

**Comment by shenqidebaozi** [comment]
另外我本地使用 goland 修改文件进行测试，传入目录，貌似也不会出错，可能跟 goland 版本实现有关？

**Comment by shenqidebaozi** [comment]
<img width="606" alt="image" src="https://user-images.githubusercontent.com/35397691/221506359-fda8f897-d915-4500-86df-a27408b6e991.png">

**Comment by whtiehack** [comment]
> > 配置文件在git版本库里吗? 在版本库里改.然后这里git pull 试试
> 
> 配置文件不会放在 版本库啦

自己写个工具去直接重写这个文件试一下?

**Comment by guihouchang** [comment]
先删掉 yaml~文件，不要用vim命令。用goland Ide工具修改就好。 我以前也遇到过，原因是编辑后会生成一个类似backup的文件。

**Comment by junneyang** [comment]
非 IDE 环境，直接 vim 也会报同样的错
