### ISSUE TITLE
install kratos error

### ISSUE THREAD

**Issue by Jack-An** [go-kratos/kratos#2684]
go: downloading github.com/google/gnostic v0.6.9
go: github.com/google/gnostic/cmd/protoc-gen-openapi@latest: github.com/google/gnostic@v0.6.9: verifying module: github.com/google/gnostic@v0.6.9: checking tree#15705967 against tree#15977901: reading https://goproxy.io/sumdb/sum.golang.org/tile/8/1/239: 404 Not Found
	server response: not found
exit status 1

**Comment by shenqidebaozi** [comment]
这个是 goproxy 问题吧？ 问题不应该提给我们呢

**Comment by shenqidebaozi** [comment]
goproxy.io 反馈已解决 cloudflare 缓存策略问题
