### ISSUE TITLE
[Question]有没有消息队列或者分布式事务的相关实例，谢谢

### ISSUE THREAD

**Issue by introspection3** [go-kratos/kratos#2711]
[Question]有没有消息队列或者分布式事务的相关实例，谢谢

**Comment by shenqidebaozi** [comment]
example，公众号文章都有相关，自己翻一下

**Comment by shenqidebaozi** [comment]
自己找一下吧，很多资料
- https://github.com/go-kratos/examples/tree/main/event
- https://github.com/go-kratos/examples/tree/main/transaction
- https://github.com/go-kratos/examples/tree/main/chatroom
