### ISSUE TITLE
[Question] goland 调试 context deadline exceeded

### ISSUE THREAD

**Issue by Huang131** [go-kratos/kratos#2712]
goland 调试时，ctx是一路传递，虽然超时时间设置了很大，单步调试还是很容易报context deadline exceeded，除了ctx不透传外，还有啥处理方法吗？可以设置debug的时候取消超时机制吗

**Comment by shenqidebaozi** [comment]
超时设置为 0

**Comment by Huang131** [comment]
> 超时设置为 0

谢谢，我发现超时时间设置不起作用的原因了。我的限频器的时间太小。
