### ISSUE TITLE
How to inject trace in response for server

### ISSUE THREAD

**Issue by jjkoh95** [go-kratos/kratos#2723]
How do we inject trace in server response? 

I'm not sure if it is intended, but it will be nice even if the parent has no tracing enabled, if they somehow manage to log the header, i can easily debug from my service.

Here's my temporary solution.
```go
	func(handler kmiddleware.Handler) kmiddleware.Handler {
		return func(ctx context.Context, req interface{}) (interface{}, error) {
			if tr, ok := transport.FromServerContext(ctx); ok {
				p := otel.GetTextMapPropagator()
				p.Inject(ctx, tr.ReplyHeader())
			}
			return handler(ctx, req)
		}
	},
```

Thanks.

**Comment by shenqidebaozi** [comment]
- https://github.com/go-kratos/kratos/tree/main/middleware/tracing
- https://github.com/go-kratos/examples/tree/main/traces

**Comment by jjkoh95** [comment]
Thanks @shenqidebaozi !

Do we have to manually instrument all metadata forwarding?
Is there a way in Kratos that we can at least automatically instrument traces forwarding? Though I can understand that the usecase for this might not be very useful for the mass users.

**Comment by shenqidebaozi** [comment]
@jjkoh95 middleware metadata

**Comment by jjkoh95** [comment]
Thanks! I'll close this
