### ISSUE TITLE
[Feature] Middlewares on http.Handler level

### ISSUE THREAD

**Issue by d-ulyanov** [go-kratos/kratos#2728]
Right now it's impossible to measure "real" response time or span duration for HTTP handlers because middleware in Kratos is designed as a decorator around internal function `err := handler(ctx, req)`. It's obviously doesn't include request reading, request unmarshaling, response writing, so it means that all metrics / traces collected in MW will cover only handler time.

Also, right now we can't read response code in MW, because it's generated inside wrappers in Server. 

### Feature-request

1. Add possibility to inject middleware on http.Handler lever to make developers able to measure latency which is closest to real.
2. Add hooks / callbacks to be able to measure request / response (un)marshal time.
3. Add possibility to inject custom implementation of http.ResponseWriter
4. Make http Server and Router exnendable (nice to have)

**Comment by shenqidebaozi** [comment]
It looks good. Can you help me submit an MVP version? Shall we have a look together?

**Comment by shenqidebaozi** [comment]
but I think most problems can be solved
1. you can use the http.Filter function to implement.
2. ditto
3. Kratos provides http.RequestDecoder、http.ResponseEncoder、http.ErrorsEncoder function
