### ISSUE TITLE
[Feature] config配置文件根据 tag 指定对应解析器

### ISSUE THREAD

**Issue by aveyuan** [go-kratos/kratos#2740]
## 目的
在配置结构体中，如果指定了相关字段的的 tag 解析方式，例如 `json,yaml,xml`，在scan的时候可以根据他们指定的 tag 来得到正确的配置。

## 需求详情
当我们独立使用结构体对配置文件进行配置，如下：
config.go
```
package conf

type Cs struct {
	AppName string `yaml:"app_name"`
	Version string `yaml:"version"`
}

```

配置文件 cs.yaml

```
app_name: app0
version: "1.1.0"
```

然后再使用配置文件进行 `Load` 和 `Scan`，发现 AppName 为空

```
main.go

	if err := c.Load(); err != nil {
		panic(err)
	}

	var bc conf.Bootstrap
	if err := c.Scan(&bc); err != nil {
		panic(err)
	}

	var cs conf.Cs
	if err := c.Scan(&cs); err != nil {
		panic(err)
	}
```

结果如下：
![image](https://user-images.githubusercontent.com/10907648/225840888-bf25a2ef-9063-4a87-9a19-887ea2c69b93.png)

是的，`yaml` 配置文件没有被得到正确的解析

## 原因
因为时间有限，没有仔细看，实际上，`Scan` 调用的方法如下：
```
func (c *config) Scan(v interface{}) error {
	data, err := c.reader.Source()
	if err != nil {
		return err
	}
	return unmarshalJSON(data, v)
}

func unmarshalJSON(data []byte, v interface{}) error {
	if m, ok := v.(proto.Message); ok {
		return protojson.UnmarshalOptions{DiscardUnknown: true}.Unmarshal(data, m)
	}
	return json.Unmarshal(data, v)
}

```

最后解析的时候，使用的是 `Json`，导致 `Yaml` 格式配置没有解析到正确的值。 我们可以通过配置json tag 来得到正确的值，很明显，这不是我们想要的（更像是一个bug?）：

```
package conf

type Cs struct {
	AppName string `yaml:"app_name" json:"app_name"`
	Version string `yaml:"version"`
}

```

## 提议

增加对 结构体 `Tag` 指定解析配置的支持，例如我的配置结构指定了 `yaml` 的名称，在Scan 的时候，通过Yaml 解析器就能得到正确的值。或者，我可以直接指定一种/多种解析器，而不是直接使用默认的行为（这种多种解析混用确实存在一定问题）？

**Comment by shenqidebaozi** [comment]
config 现在这样设计是为了支持多配置源的配置合并，如果所有的文件都使用同一种类型，可以支持，但多类型的还是无法支持
