### ISSUE TITLE
[Question]/debug/pprof/

### ISSUE THREAD

**Issue by jason837** [go-kratos/kratos#2762]
Please see the FAQ in our main README.md before submitting your issue.
this debug/pprof, 怎么快速配置，生产环境和测试环境

**Comment by shenqidebaozi** [comment]
I don't see what you're asking

**Comment by jason837** [comment]
就是kratos启动后可以访问http://ip:port/debug/pprof/的路径，会出现信息泄露(go的测试本地性能分析全在上面)，kratos似乎没有直接提供可以关闭此路径的配置，目前我的解决是用空的路由替换了这个路径。

**Comment by shenqidebaozi** [comment]
Kratos does not register a pprof route by default

**Comment by shenqidebaozi** [comment]
<img width="853" alt="image" src="https://user-images.githubusercontent.com/35397691/228149468-49256332-759e-4637-bb54-c721ee18e9a3.png">

**Comment by jason837** [comment]
![image](https://user-images.githubusercontent.com/58881730/228157804-8c20da34-7beb-4f5c-8f81-7a02773625c5.png)

**Comment by jason837** [comment]
this okay?

**Comment by shenqidebaozi** [comment]
we do not register for pprof by default, so we are not sure what you want to do with your question

**Comment by shenqidebaozi** [comment]
after attempting to start the kratos service, there is no default provision of the pprof interface. In addition, your problem description is very vague. Please provide a minimum recurrence repository or method.
<img width="581" alt="image" src="https://user-images.githubusercontent.com/35397691/228418099-998f1c7a-df17-4cd1-baf2-fd860305862e.png">

**Comment by jason837** [comment]
但是我启动kratos项目后，可以通过此路径访问到其内容。
![image](https://user-images.githubusercontent.com/58881730/228418973-3ce49efa-81f8-46f7-93eb-0f31f726ab7a.png)

**Comment by shenqidebaozi** [comment]
i have just replied that I tried to start a kratos service and cannot directly access it. It is recommended to provide a replication repository

**Comment by shenqidebaozi** [comment]
using the standard kratos-layout, version 2.6.1 of the Kratos framework, requests the path you specified, and returns a result of 404. There is no default registered pprof interface
<img width="496" alt="image" src="https://user-images.githubusercontent.com/35397691/228419536-2316d7e7-3f42-49cb-b416-5c8869968d51.png">

**Comment by shenqidebaozi** [comment]
Kratos does not have a default registration for pprof and has provided you with a series of code screenshots. If you cannot provide a replication repository, please check your code to see if you or other libraries have registered for pprof

**Comment by jason837** [comment]
okay, i see, thx
