### ISSUE TITLE
English documents and Chinese documents are inconsistent or not updated in time

### ISSUE THREAD

**Issue by yaodong-li** [go-kratos/kratos#2769]
只是一个例子：
<img width="1187" alt="Screenshot 2023-03-29 at 4 53 54 PM" src="https://user-images.githubusercontent.com/6023208/228481348-f0421fef-b0e3-441f-8193-effa75833eca.png">
<img width="1018" alt="Screenshot 2023-03-29 at 4 54 14 PM" src="https://user-images.githubusercontent.com/6023208/228481401-2888fd72-e0fb-4a90-a807-2abc4508b1f4.png">

**Comment by fans3210** [comment]
grpc.WithBalancerName这个改动好像已经变了

**Comment by shenqidebaozi** [comment]
the problem should be mentioned under the doc project, and can be directly repaired
