### ISSUE TITLE
[Question] How to restrict the server from registering with the registration center

### ISSUE THREAD

**Issue by fulltimelink** [go-kratos/kratos#2773]
使用kratos.server 启动多个http server，比如 8081 业务服务   6060 pprof 服务，那么在注册中心会将8081和6060会注册到同一个服务名下
6060并不需要注册到注册中心，但是transport.http.server默认实现了transport.Endpointer 所以也会进行注册
可否为transport.http.server追加相关控制参数？

**Comment by shenqidebaozi** [comment]
approv is registered on the default server, not through kratos http
