### ISSUE TITLE
[Feature] The logger cannot be configured when the client adds service discovery

### ISSUE THREAD

**Issue by jackylong1** [go-kratos/kratos#2786]
目前版本
文件：transport/grpc/client.go
函数：func dial(ctx context.Context, insecure bool, opts ...ClientOption) (*grpc.ClientConn, error)
当添加服务发现时候，目前写死服务发现的ops
	if options.discovery != nil {
		grpcOpts = append(grpcOpts,
			grpc.WithResolvers(
				discovery.NewBuilder(
					options.discovery,
					discovery.WithInsecure(insecure),
					discovery.WithSubset(options.subsetSize),
				)))
	}
期望可以通过参数允许添加discovery.NewBuilde的 option 如：	
				discovery.DisableDebugLog()
实现方案：
// clientOptions is gRPC Client
type clientOptions struct {
	endpoint     string
	subsetSize   int
	tlsConf      *tls.Config
	timeout      time.Duration
	discovery    registry.Discovery
	middleware   []middleware.Middleware
	ints         []grpc.UnaryClientInterceptor
	streamInts   []grpc.StreamClientInterceptor
	grpcOpts     []grpc.DialOption
	balancerName string
	filters      []selector.NodeFilter
	builderOps []discovery.Option // 新增builder option
}

添加暴露接口
func WithBuilderOps(bops []discovery.Option) ClientOption {
	return func(o *clientOptions) {
		o.builderOps = bops
	}
}

**Comment by shenqidebaozi** [comment]
this problem has been resolved
