### ISSUE TITLE
Unable to fetch Kratos v2.x.x package using Go get

### ISSUE THREAD

**Issue by helloxjade** [go-kratos/kratos#2815]
#### What happened:
I am encountering an error when trying to fetch the Kratos v2.x.x package using the Go get and go install command. The error message says "invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2". I have tried running go clean -modcache and setting the GOPROXY environment variable, but the issue persists.
#### What you expected to happen:
The Kratos v2.x.x package should be fetched and installed successfully.
#### How to reproduce it (as minimally and precisely as possible):
1、run the following command: go get  -u github.com/go-kratos/kratos/cmd/kratos/v2@v2.6.1  or go install -v github.com/go-kratos/kratos/cmd/kratos/v2@v2.6.1
2、Observe the error message.
#### Anything else we need to know?:
fails with the error message "invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2".
#### Environment:
- Kratos version (use `kratos -v`):  v2.x.x
- Go version (use `go version`):  1.17
- OS (e.g: `cat /etc/os-release`):  windows11
- Others:

**Comment by shenqidebaozi** [comment]
limited by the usage mode of go.mod, except for the main module, other modules have not released branch tags, and can pull the specified version of sub modules based on the release's commit ID
https://github.com/go-kratos/kratos/releases/tag/v2.6.1
![image](https://user-images.githubusercontent.com/35397691/236718626-b7c83f25-0b35-42e3-a002-c90fb996b86e.png)
