### ISSUE TITLE
[ServiceComb] Two microservices, provider and consumer, are constructed to complete registration discovery and request invocation, and the dependencies of microservices cannot be viewed in the tool

### ISSUE THREAD

**Issue by little-cui** [go-kratos/kratos#2830]
#### What happened:

按照云厂商的Kratos接入文档：
https://support.huaweicloud.com/bestpractice-cse/cse_05_0028.html

编写了2个微服务，并完成注册发现和请求调用，此功能正常

#### What you expected to happen:

希望能通过工具看到微服务的拓扑
https://support.huaweicloud.com/devg-cse/cse_devg_0036.html

#### How to reproduce it (as minimally and precisely as possible):

但使用工具查看2个微服务不存在调用关系

#### Anything else we need to know?:

在代码中发现，consumer服务发现时候没有传递自身的serviceID
github.com/go-kratos/kratos/contrib/registry/servicecomb/v2/registry.go:68

#### Environment:
- Kratos version (use `kratos -v`): latest
- Go version (use `go version`): 1.19
- OS (e.g: `cat /etc/os-release`): ubuntu 20
- Others:

**Comment by shenqidebaozi** [comment]
@little-cui hi，how should I fix this and deploy servicecomb locally?
