### ISSUE TITLE
[Question] How to define an http interface for uploading files through proto?

### ISSUE THREAD

**Issue by Mashiro707** [go-kratos/kratos#2834]
```
service xxx {
    rpc xxxx(xxxRequest) returns (xxxxReply) {
        option (google.api.http) = {
            post: "v1/xxx"
            body: "*"
        };
    }
}

```
我尝试通过 proto 定义一个 post 用于上传文件，但是在调用接口的时候得到错误如下：
```
{
    "code": 400,
    "reason": "CODEC",
    "message": "unregister Content-Type: multipart/form-data; boundary=--------------------------252181601228174911379250",
    "metadata": {}
}
```
看了下 google/api/annotations.proto 的代码，似乎并没有关于 Conten-type 的定义？

**Comment by shenqidebaozi** [comment]
`protobuf` and `google.api` do not have a definition of file types, so to achieve HTTP file upload, we need to create a separate route, which can be found in [examples/http/upload](github.com/go-kratos/examples)

**Comment by Mashiro707** [comment]
> `protobuf` and `google.api` do not have a definition of file types, so to achieve HTTP file upload, we need to create a separate route, which can be found in [examples/http/upload](github.com/go-kratos/examples)

是的，最后我是使用新的路由解决的。感谢~
