### ISSUE TITLE
v2.6.2 not found env.NewSource

### ISSUE THREAD

**Issue by samuelyao314** [go-kratos/kratos#2850]
<img width="1201" alt="image" src="https://github.com/go-kratos/kratos/assets/2543265/af50b27f-285d-4542-a92a-5b332c806770">

Here is a document

```go
c := config.New(
    config.WithSource(
        // 添加前缀为 KRATOS_ 的环境变量，不需要的话也可以设为空字符串
        env.NewSource("KRATOS_"),
        // 添加配置文件
        file.NewSource(path),
    ))
```

but  `env.NewSource` not in  v2.6.2 code.

**Comment by shuqingzai** [comment]
![image](https://github.com/go-kratos/kratos/assets/44406033/2aecaf0f-ef4b-48ae-9ab7-fe02255834ee)

my normal

https://github.com/go-kratos/kratos/tree/v2.6.2/config/env

**Comment by shenqidebaozi** [comment]
Is it a `vendor` issue? we are currently using `go module`

**Comment by shenqidebaozi** [comment]
the `vendor` is not officially supported and is currently using `go.mod`. It is recommended to switch the package management method
