### ISSUE TITLE
wrong path using kratos new app/user --nomod

### ISSUE THREAD

**Issue by EyTest-bang** [go-kratos/kratos#2851]
#### What happened:
absolute path is generated using 'kratos new app/user --nomod '
![image](https://github.com/go-kratos/kratos/assets/64853344/8ca399fb-3810-42f8-b188-cd77dd233fb0)

#### What you expected to happen:
relative path

#### How to reproduce it (as minimally and precisely as possible):
kratos new app/user --nomod 

#### Environment:
- Kratos version (use `kratos -v`): v2.6.2
- Go version (use `go version`):  go1.20.4 
- OS (e.g: `cat /etc/os-release`): windows/amd64
- Others:

**Comment by haiyux** [comment]
sorry, it is a bug when use windows os, and i will fix it
