### ISSUE TITLE
[BUG] Generated HTTP Client NOT Support Path Parameter with underline

### ISSUE THREAD

**Issue by pplmx** [go-kratos/kratos#2857]
#### What happened:

![image](https://github.com/go-kratos/kratos/assets/26994103/b0ae65ad-d929-4747-9c90-5121427e87b9)

#### What you expected to happen:

Generated HTTP Client support path parameter with underline

#### How to reproduce it (as minimally and precisely as possible):

define a http api using path parameter with underline

#### Anything else we need to know?:

NOTES:

1. You should define three parameters, the two of them are `path parameter`, the left one is `query parameter`.
`Path and Query Parameter` exist at the `same time`, and `Path Parameter` contains the underline, which will cause this bug.

2. If I use `pid` and `tversion` without underline instead of `project_id` and `project_tree_version`, it can work fine again.

3.

#### Environment:
- Kratos version (use `kratos -v`): kratos version v2.6.2
- Go version (use `go version`): go version go1.20.4 windows/amd64, linux/arm64
- OS (e.g: `cat /etc/os-release`): Win11 and MacOS
- Others:

**Comment by shifengbin** [comment]
I can't reproduce the issue, can you show me the proto?

**Comment by pplmx** [comment]
Like this:
```proto

// ...
    rpc GetProjectTrees(GetProjectTreesRequest) returns (GetProjectTreesResponse) {
        option (google.api.http) = {
            get : "/api/v1/projects/{project_id}/tree/{project_tree_version}"
            additional_bindings {get : "/api/v1/projects/{project_id}/tree/{project_tree_version}"}
        };
    }

// ...

message GetProjectTreesRequest {
    int32 project_id = 1;
    int32 project_tree_version = 2;
    bool is_with_ancestor = 3;
}
```

**Comment by shifengbin** [comment]
Why did you write "additional_bindings"

**Comment by pplmx** [comment]
For using `Query Parameter`

**Comment by pplmx** [comment]
> 

Thanks a lot. This can fix my issue.

But I think this is a bug for the kratos, which is needed to be fixed.

**Comment by pplmx** [comment]
FYI.
If without `[json_name = "project_id"]`, it will handle `project_id` (a path parameter) as a query parameter.
![image](https://github.com/go-kratos/kratos/assets/26994103/826009ed-0a83-49ae-b581-aac650f5bb3d)

**Comment by czyt** [comment]
try to change your rpc define:
```
 rpc GetProjectTrees(GetProjectTreesRequest) returns (GetProjectTreesResponse) {
        option (google.api.http) = {
            get : "/api/v1/projects/{project_id}/tree/{project_tree_version}"
            additional_bindings {
		get : "/api/v1/projects/{project_id}/tree/{project_tree_version}",
		body:"project_id"
		}
        };
    }
```
not tested,but I think it should work
