### ISSUE TITLE
The grpc client is mapped incorrectly for the put operation

### ISSUE THREAD

**Issue by lanpang** [go-kratos/kratos#2871]
#### What happened:
grpc映射为put操作，生成的client端的代码，不能正确解析request请求。
代码如下:
```
syntax = "proto3";

package realworld.v1;

import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";

option go_package = "kratos-realworld/api/conduit/v1;v1";

// The greeting service definition.
service Conduit {
  rpc UpdateArticle(UpdateArticleRequest) returns (SingleArticleReply) {
    option (google.api.http) = {
      put : "/api/articles/{slug}",
      body : "*",
    };
  }
}

message UpdateArticleRequest {
  message Article {
    string title = 1;
    string description = 2;
    string body = 3;
    repeated string tagList = 4;
  }
  Article article = 1;
  MM M = 2;
  string slug = 3;
}

message MM {
  // 唯一值
  int32 id = 1;

  repeated XX xx_data = 2;
  // [ json_name = "xx_data" ];
  repeated YY isotropic_data = 7 [ json_name = "YY_data" ];
}
message YY {
  double length = 1;
  double re = 2;
  double im = 3;
  double cond = 4;
}
message XX { string wavelength = 1; }

message Attrs {
  string color = 1;
  uint32 xx_order = 2 [ json_name = "xx_order" ];
  uint32 xx = 3;
}

message SingleArticleReply {}
```
我目前定位到的问题是 `github.com/go-kratos/kratos/v2@v2.6.2/encoding/form/proto_encode.go`
 在 `encodeMessage`函数中，走到了defualt分支，内部添加日志打印出 `err:unsupported message type: "realworld.v1.XX"`
#### What you expected to happen:
希望能够生成正确的put请求
#### Environment:
- Kratos version (use `kratos -v`): kratos version v2.6.2
- Go version (use `go version`): go version go1.20 darwin/arm64
- OS (e.g: `cat /etc/os-release`):  macOS 13.0.1 (22A400)
- Others:

**Comment by XiaoK29** [comment]
PUT是不允许这样使用的，你可以尝试其他http框架

**Comment by XiaoK29** [comment]
建议body传参

**Comment by lanpang** [comment]
> PUT是不允许这样使用的，你可以尝试其他http框架

当时设计的时候，为什么不支持这种传参方式呢，是因为http client这种应用场景比较少吗？大部分都是grpc client吗？

**Comment by XiaoK29** [comment]
> > PUT是不允许这样使用的，你可以尝试其他http框架
> 
> 当时设计的时候，为什么不支持这种传参方式呢，是因为http client这种应用场景比较少吗？大部分都是grpc client吗？

你可以尝试gin框架，也是会404的
