### ISSUE TITLE
goroutine ctx is canceled

### ISSUE THREAD

**Issue by towithyou** [go-kratos/kratos#2884]
``` golang
func (t *TaskPlatformService) CreateTemplate(c context.Context, tpl *v1.Template) (*v1.Template, error) {
	// validate template params
	cu := auth.FromContext(c)
	tpl.Creator = cu.Username
	dataTpl := dto.ProtoToTemplate(tpl)
	err := t.tplRepo.Create(c, dataTpl)
	if err != nil {
		t.log.Errorf("create template err %v", err)
		return nil, err
	}

	go func() {
		// 这里的 putEvent 函数，调用连比较长，可以能需要几秒中完成，所以这里使用了 goroutine
		resp, err := t.grpcCli.PutEvent(c, &task_platform.Event{})
		if err != nil {
			t.log.Errorf("put event err %v", err) // 每次这里的 error 是  context canceled.我怀疑是因为这里的 ctx 在返回的时候把 ctx销毁了，导致这里的 ctx 也被销毁了
			return
		}
	}()

	return dto.TemplateToProto(dataTpl), nil
}
```

**Comment by lonetrail** [comment]
The context param is a context  with a timeout(1 second by default, and can be set by the timeout option in grpc.NewServer or http.NewServer). The context will be canceled after the response returns. So you may create a new context for a goroutine if you want run an async task.

**Comment by shenqidebaozi** [comment]
> The context param is a context with a timeout(1 second by default, and can be set by the timeout option in grpc.NewServer or http.NewServer). The context will be canceled after the response returns. So you may create a new context for a goroutine if you want run an async task.

yes, because you have used the requested context, you will also be limited by the requested context. If it is an asynchronous task, a separate context should be used
