### ISSUE TITLE
[Question] middleware can't catch and log the encode error

### ISSUE THREAD

**Issue by NeoyeElf** [go-kratos/kratos#2893]
If the `EncodeResponseFunc` return an error, the middleware can't catch it, so the http status in the access log is 200. But the actual http status is 500.

I want to know is there a way to let middleware catch the error and print the correct access log?

**Comment by shenqidebaozi** [comment]
`ErrorsEncoder`

**Comment by windzhu0514** [comment]
> `ErrorsEncoder`

use ErrorsEncoder,the code also cant handled by log middleware,how about the log could start from the decoded request and end with the encoded response result.
```
// log start
// decode request
// other middleware
// encode response
// log over
```

**Comment by NeoyeElf** [comment]
> `ErrorsEncoder`

implement a custom `EncodeErrorFunc`? seems to be a solution.

**Comment by NeoyeElf** [comment]
`use ErrorsEncoder, the code also can't handled by log middleware` agreed
