### ISSUE TITLE
steam type error in proto file

### ISSUE THREAD

**Issue by xushuhui** [go-kratos/kratos#2896]
#### What happened:
I write a function in proto file，reply stream type，and greeter_http.pb.go no change, SayHello function is different in GreeterServer and  GreeterHTTPServer，So func (s *GreeterService) SayHello is error.

```
// greeter.proto
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (stream HelloReply) {
    option (google.api.http) = {
      get: "/helloworld/{name}"
    };
  }
}
//greeter_grpc.pb.go
type GreeterServer interface {
	// Sends a greeting
	SayHello(*HelloRequest, Greeter_SayHelloServer) error
	mustEmbedUnimplementedGreeterServer()
}
//greeter_http.pb.go
type GreeterHTTPServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

```

#### What you expected to happen:

SayHello function is same in GreeterServer and  GreeterHTTPServer，So func (s *GreeterService) SayHello no error.

#### Environment:
- Kratos version (use `kratos -v`): kratos version v2.6.2
- Go version (use `go version`): go version go1.20.3 darwin/amd64
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by shenqidebaozi** [comment]
Google API does not support the definition of stream interface

**Comment by xushuhui** [comment]
I want use http stream in kratos,   try to do in kratos
```
   hx, _ := ctx.(transport.http.Context)
   w := hx.Response()
   w.Header().Set("Content-Type", "text/event-stream")
   w.Header().Set("Cache-Control", "no-cache")
   w.Header().Set("Connection", "keep-alive")
    flusher, _ := w.(http.Flusher)
for {
		response, err := stream.Recv()
		if errors.Is(err, io.EOF) {
			fmt.Println("\nStream finished")
			return nil, nil
		}

		if err != nil {
			return nil, errors.InternalServer("Stream error", err.Error())
		}
		
		fmt.Fprint(w, response.Content)
		flusher.Flush()
	}
```
But I found a problem，If I use return a new context in middleware，this is error，not assert transport.http.Context
```
// authMiddleware
func WithContext(ctx context.Context, user *CurrentUser) context.Context {
	return context.WithValue(ctx, "user", user)
}
// service/greeter.go
  hx, _ := ctx.(transport.http.Context) //it error 
  
```
How to solve it? 
Thanks
