### ISSUE TITLE
httputil.DumpRequestOut return error when dump request

### ISSUE THREAD

**Issue by ymh199478** [go-kratos/kratos#2899]
```
if it, ok := transport.FromServerContext(ctx); ok {
    if tr, ok := it.(*http.Transport); ok {
        dump, err := httputil.DumpRequestOut(tr.Request(), true)
        // err not nil
    }
}
```

The problem is that the data in `request.URL` is invalid，No Schema, no Host

**Comment by XiaoK29** [comment]
我使用RequestFromServerContext获取是没问题的，底层实现
![image](https://github.com/go-kratos/kratos/assets/38639105/6503d05f-e9cb-418d-baf6-0e62d2ced4f8)

**Comment by XiaoK29** [comment]
if httpCtx, ok := http.RequestFromServerContext(ctx); ok {
    fmt.Println(httpCtx.URL.Path)
}
