### ISSUE TITLE
[Question]How to specify the service registration endpoint when binding a server to multiple network interfaces?

### ISSUE THREAD

**Issue by youzhixiaomutou** [go-kratos/kratos#2902]
How to listen on 0.0.0.0 for a service while specifying a custom registration endpoint in the service registry? Currently, there doesn't seem to be a direct way.

**Comment by shenqidebaozi** [comment]
```
// Endpoint with service endpoint.
func Endpoint(endpoints ...*url.URL) Option {
	return func(o *options) { o.endpoints = endpoints }
}
```

**Comment by youzhixiaomutou** [comment]
Using Endpoint() With kratos.New()? If I start multiple servers in kratos.Server(), I have to explicitly specify the endpoint for each server, and I also need to manually convert 0.0.0.0:port to the actual ip:port. Would it be a solution to prioritize using the internal IP for service registration when specifying 0.0.0.0:port?

**Comment by shenqidebaozi** [comment]
The current design of HTTP/gRPC transport is to use private IP as the endpoint value, and it is unclear what exactly you want to do. If you want to control the registered values yourself, you can use the `endpoint` configuration item to override them yourself
https://github.com/go-kratos/kratos/blob/db2a565d1c7929dc7810d69a26a3a32246fe7b5d/transport/grpc/server.go#L221

**Comment by shenqidebaozi** [comment]
When you listen to port `0.0.0.0`, the private IP of the service will be parsed and registered with the registry. Is the expression of your issue question incorrect.

It is recommended to conduct actual testing. If there are any issues, please provide the minimum replication environment or describe the relevant information clearly

**Comment by youzhixiaomutou** [comment]
My goal is to prioritize registering the internal IP when configuring 0.0.0.0, but in reality, it doesn't seem to work that way. This issue is difficult to reproduce. Our production services are deployed on physical machines with one network card bound to the internal network and another network card bound to the external network. According to the Extract() method in internal/host/host.go, it seems to iterate through all network cards that meet the conditions and ultimately return the last one, making the actual registered IP unpredictable. Is my understanding correct?
https://github.com/go-kratos/kratos/blob/32b1d13f904f021f9e5d275c3e19c9f008efbca0/internal/host/host.go#L89
I will also try to provide a minimal replication environment.

**Comment by youzhixiaomutou** [comment]
I think Extract() code should include a condition to return early if it is an internal IP.

**Comment by shenqidebaozi** [comment]
It is difficult to coexist with the needs of different users. It is recommended to use endpoint to handle the address registered to the registration center on your own, or consider changing this part to an interface for users to implement on their own

**Comment by youzhixiaomutou** [comment]
Thanks a lot for the answer. I can handle this part of the code myself (although I believe it deviates from the original design in terms of the Extract() method). 
There is an another question. Can transport/server.go expose a function option:
https://github.com/go-kratos/kratos/blob/32b1d13f904f021f9e5d275c3e19c9f008efbca0/transport/grpc/server.go#L119

 ``` go
func Endpoint(endpoint *url.URL) ServerOption {
	return func(s *Server) {
		s.endpoint = endpoint
	}
}
```

that allows me to specify the endpoint when defining the server, instead of manually specifying it for each server when creating a new app? I believe this implementation would be more elegant.
