### ISSUE TITLE
Post requests do not support binding both body and query

### ISSUE THREAD

**Issue by hoslo** [go-kratos/kratos#2907]
#### What happened:
The Post request did not get the query parameter
#### What you expected to happen:
Get both body and query
#### How to reproduce it (as minimally and precisely as possible):
Post requests have both query and body
#### Environment:
- Kratos version (use `kratos -v`): v2.5.3
- Go version (use `go version`): go version go1.20.5 darwin/arm64
- OS (e.g: `cat /etc/os-release`): macos
- Others:

**Comment by tonyhal** [comment]
有没有其他解决方案，比较着急!

**Comment by kingofzihua** [comment]
`http.Context` 里面是有 `Bind`、`BindQuery` 和 `BindVars` 这个三个方法的，只不过protobuf 生成的内容是没有的，建议逐层替换

以下只是一个例子 
在生成的 xxx.pb.go 文件同级目录创建一个新的go文件，重写掉 _UserService_CreateUser0_HTTP_Handler 方法，自己手动绑定

<img width="1154" alt="image" src="https://github.com/go-kratos/kratos/assets/21213820/1469888a-3181-49a2-9fb0-d1ca7adcc03d">

然后重写 RegisterUserServiceHTTPServer 方法的路由注册方法 ，指向自己重写掉的 handler
```

```

**Comment by tonyhal** [comment]
啥时候 把模板改掉

**Comment by czyt** [comment]
```proto
rpc CreateUser(CreateUserRequest) returns (CreateUserResponse) {
    option (google.api.http) = {
      post: "/users",
      body: "user"
    };
  }
  
message CreateUserRequest {
  string password = 1;
  User user = 2;
}
message CreateUserResponse {
  string response = 1;
}

message User {
  string first_name = 1;
  string last_name = 2;
}
  

```
in your service code
```go
func (s *GreeterService) CreateUser(ctx context.Context, req *v1.CreateUserRequest) (*v1.CreateUserResponse, error) {
	info := fmt.Sprintf("password:%s,userName:%s %s", req.Password, req.User.FirstName, req.User.LastName)
	return &v1.CreateUserResponse{Response: info}, nil
}
```
