### ISSUE TITLE
[Question] Is there a plan to replace Gorilla/MUX package since it was archived ?

### ISSUE THREAD

**Issue by snownd** [go-kratos/kratos#2912]
Please see: [gorilla/mux#659](https://github.com/gorilla/mux/issues/659)
> ⚠️ The Gorilla Toolkit is now in archive-mode, and is no longer actively maintained.

So, there may be some security vulnerabilities in the future that will not be fixed。

I wonder if the community has discussed alternatives like [go-chi/chi](https://github.com/go-chi/chi) or [httptreemux](https://github.com/dimfeld/httptreemux)。

**Comment by shenqidebaozi** [comment]
He is already stable enough, and if there is really a need, we will maintain it
