### ISSUE TITLE
How to read the xml data carried in the POST request?

### ISSUE THREAD

**Issue by tonyhal** [go-kratos/kratos#2914]
Please see the FAQ in our main README.md before submitting your issue.

**Comment by tonyhal** [comment]
怎么获取到 body 里面 xml 数据

**Comment by hoslo** [comment]
> 怎么获取到 body 里面 xml 数据

You can check out this repo
https://github.com/srikrsna/protoc-gen-gotag

**Comment by shenqidebaozi** [comment]
Registering XML encoding
https://go-kratos.dev/en/docs/component/encoding

**Comment by shenqidebaozi** [comment]
Additionally, your problem description is very general and it is unclear what exactly you are trying to express
