### ISSUE TITLE
开发kratos使用macos? windows? arch linux ? Ubuntu ？[Question]

### ISSUE THREAD

**Issue by tonyhal** [go-kratos/kratos#2916]
开发kratos使用macos还是用windows？

**Comment by tonyhal** [comment]
需要买m1？ inter？

**Comment by tonyhal** [comment]
买16G 还是 32G ？

**Comment by tonyhal** [comment]
苹果M2 Ultra：AI大模型的新希望_哔哩哔哩_bilibili
https://www.bilibili.com/video/BV1fh4y1M7DX/?spm_id_from=333.880.my_history.page.click&vd_source=6038a04cde146e5aaf172fd79e440370

**Comment by Windfarer** [comment]
应该都可以用，但是mac或者linux的开发体验会更好一些

**Comment by zuoliang0** [comment]
文档中有提到使用make config 来实现构建proto的config到go strict 这个命令我实测在windows中的make无法运行会提示：
这个问题不清楚是make导致的 还是windows环境不支持导致的
```
PS C:\Users\onlyx\work\goproject\helloworld> make config
'C:/' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
protoc --proto_path=./internal \
               --proto_path=./third_party \
               --go_out=paths=source_relative:./internal \
               
Missing input file.
make: *** [config] 错误 1
```
