### ISSUE TITLE
[BUG] Apollo config watch report error in the latest versions.

### ISSUE THREAD

**Issue by fighterhit** [go-kratos/kratos#2918]
#### What happened:
Error reported when apollo configuration hot update.

```
WARN apollo get config failed=err load default cache fail=KEYVALS UNPAIRED
```

#### What you expected to happen:

When apollo configures hot update, the watch updated result is normal.

#### How to reproduce it (as minimally and precisely as possible):

```
c := config.New(
		config.WithSource(
			apollo.NewSource(
				apollo.WithAppID("xxx"),
				apollo.WithCluster("xxx"),
				apollo.WithEndpoint(xxx),
				apollo.WithNamespace(xxx),
				apollo.WithEnableBackup(),
			),
		),
	)

	if err := c.Load(); err != nil {
		panic("config load err!")
	}

	log.Printf("application: %v", c.Value("application"))

	err := c.Watch("application", func(key string, value config.Value) {
		logger.Infof("config(key=%s) changed: %s\n", key, value.Load())
	})
	if err != nil {
		logger.Errorf("watch config err: %v", err)
	}
```

#### Anything else we need to know?:

I found the same code, it is normal to use the `github.com/go-kratos/kratos/contrib/config/apollo/v2 v2.0.0-20220309025117-4387085047b9` version in the [example repository](https://github.com/go-kratos/examples/blob/main/go.mod), but there will be problem in the latest versions.

#### Environment:
- Kratos version (use `kratos -v`): v2.6.3
- Go version (use `go version`): go version go1.20.5 linux/amd64
- OS (e.g: `cat /etc/os-release`): Ubuntu18.04
- Others:

**Comment by hoslo** [comment]
> #### What happened:
> Error reported when apollo configuration hot update.
> 
> ```
> WARN apollo get config failed=err load default cache fail=KEYVALS UNPAIRED
> ```
> 
> #### What you expected to happen:
> When apollo configures hot update, the watch updated result is normal.
> 
> #### How to reproduce it (as minimally and precisely as possible):
> ```
> c := config.New(
> 		config.WithSource(
> 			apollo.NewSource(
> 				apollo.WithAppID("xxx"),
> 				apollo.WithCluster("xxx"),
> 				apollo.WithEndpoint(xxx),
> 				apollo.WithNamespace(xxx),
> 				apollo.WithEnableBackup(),
> 			),
> 		),
> 	)
> 
> 	if err := c.Load(); err != nil {
> 		panic("config load err!")
> 	}
> 
> 	log.Printf("application: %v", c.Value("application"))
> 
> 	err := c.Watch("application", func(key string, value config.Value) {
> 		logger.Infof("config(key=%s) changed: %s\n", key, value.Load())
> 	})
> 	if err != nil {
> 		logger.Errorf("watch config err: %v", err)
> 	}
> ```
> 
> #### Anything else we need to know?:
> I found the same code, it is normal to use the `github.com/go-kratos/kratos/contrib/config/apollo/v2 v2.0.0-20220309025117-4387085047b9` version in the [example repository](https://github.com/go-kratos/examples/blob/main/go.mod), but there will be problem in the latest versions.
> 
> #### Environment:
> * Kratos version (use `kratos -v`): v2.6.3
> * Go version (use `go version`): go version go1.20.5 linux/amd64
> * OS (e.g: `cat /etc/os-release`): Ubuntu18.04
> * Others:

I can't reproduce this BUG,this my code

```golang
func main() {
	c := config.New(
		config.WithSource(
			apollo.NewSource(
				apollo.WithAppID("SampleApp"),
				apollo.WithCluster("dev"),
				apollo.WithEndpoint("http://127.0.0.1:8080"),
				apollo.WithNamespace("application"),
				apollo.WithEnableBackup(),
			),
		),
	)

	if err := c.Load(); err != nil {
		panic("config load err!")
	}

	log.Printf("application: %v", c.Value("application"))

	err := c.Watch("application", func(key string, value config.Value) {
		log.Printf("config(key=%s) changed: %s\n", key, value.Load())
	})
	if err != nil {
		log.Printf("watch config err: %v", err)
	}
	select {}
}
```

this is output

```shell
DEBUG msg=config loaded: application format: json
2023/08/22 11:53:13 application: &{{map[timeout:100]}}
2023/08/22 11:53:26 config(key=application) changed: map[timeout:200]
2023/08/22 11:54:27 config(key=application) changed: map[timeout:400]
```
