### ISSUE TITLE
[Question]服务发现报错：Error response from daemon: manifest for consul:latest not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by xjiahong** [go-kratos/kratos#2923]
我总是需要在Watcher的Next方法增加一个首次判断，如果是首次调用则返回服务地址，如果不做这个操作就会报上面的错误。
![image](https://github.com/go-kratos/kratos/assets/19721126/ff76859a-3e44-4c41-9a47-1ff3b2a72aaa)
原因在于初始化连接的时候并不会获取一个连接，会导致报错
![image](https://github.com/go-kratos/kratos/assets/19721126/18fecca8-1012-4896-96b9-3afb6ab03cf8)
另外我发现了一个有趣的现象，服务发现里面的GetService方法并不会被调用，只会调用Watch方法，所以我不得不在Watch方法里面做一次初始化操作
![Uploading image.png…]()

**Comment by xjiahong** [comment]
最后一张图漏掉了
![image](https://github.com/go-kratos/kratos/assets/19721126/23c5c5df-102c-48ca-b4df-dedb669c86e4)

**Comment by shenqidebaozi** [comment]
first, describe the environment and dependencies clearly
