### ISSUE TITLE
[Proposal] Clear up go.mod. Remove github.com/golang/protobuf

### ISSUE THREAD

**Issue by david-zhong-qantas** [go-kratos/kratos#2940]
please clean up the go.mod file by removing the old protobuf version:  github.com/golang/protobuf [Line: 29] becase google.golang.org/protobuf is already in used.

![image](https://github.com/go-kratos/kratos/assets/132962770/8654d145-dd4c-40fc-af1f-ddb19bfe4d9c)

**Comment by ilovejs** [comment]
right now this 5yr old dependencies red-flag by IDE goland,
when update mod in console. Deprecation notice also popup.
Keep community move away from adopting kratos.

See, if you can exclude in go.mod or copy some code to deal with it.

**Comment by fifsky** [comment]
Because this is an indirect dependency, unless grpc-go removes this dependency

https://github.com/grpc/grpc-go/blob/master/go.mod#L11
