### ISSUE TITLE
[Question] how to get http.ResponseWriter in services with using middleware?

### ISSUE THREAD

**Issue by z760087139** [go-kratos/kratos#2953]
我想在 services 使用 http.ResponseWriter,但如果在 server 层增加中间件，且中间件进行了 context 封装，如例子中的 metadata 中间件，对 context 断言 http.Context 则会失败
有没有办法在使用中间件的同时能够获取 http.ResponseWriter？
有个类似的  #2429 question 但未考虑中间件对ctx 的封装问题
example 
```go
package main

import (
	"context"
	"fmt"
	"github.com/go-kratos/examples/helloworld/helloworld"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/errors"
	"github.com/go-kratos/kratos/v2/middleware/metadata"
	"github.com/go-kratos/kratos/v2/middleware/recovery"
	"github.com/go-kratos/kratos/v2/transport/grpc"
	"github.com/go-kratos/kratos/v2/transport/http"
	"log"
)

// go build -ldflags "-X main.Version=x.y.z"
var (
	// Name is the name of the compiled software.
	Name = "helloworld"
	// Version is the version of the compiled software.
	// Version = "v1.0.0"
)

// server is used to implement helloworld.GreeterServer.
type server struct {
	helloworld.UnimplementedGreeterServer
}

// SayHello implements helloworld.GreeterServer
func (s *server) SayHello(ctx context.Context, in *helloworld.HelloRequest) (*helloworld.HelloReply, error) {
        // 断言 http.Context，用于获取 http.ResponseWriter
	hctx, ok := ctx.(http.Context)
	if !ok {
		return nil, errors.BadRequest("custom_error", "not a http.Context")
	}
        hctx.Response()
	if in.Name == "error" {
		return nil, errors.BadRequest("custom_error", fmt.Sprintf("invalid argument %s", in.Name))
	}
	if in.Name == "panic" {
		panic("server panic")
	}
	return &helloworld.HelloReply{Message: fmt.Sprintf("Hello %+v", in.Name)}, nil
}

func main() {
	s := &server{}
	httpSrv := http.NewServer(
		http.Address(":8000"),
		http.Middleware(
			recovery.Recovery(),
                        // 增加中间件
			metadata.Server(),
		),
	)
	grpcSrv := grpc.NewServer(
		grpc.Address(":9000"),
		grpc.Middleware(
			recovery.Recovery(),
		),
	)
	helloworld.RegisterGreeterServer(grpcSrv, s)
	helloworld.RegisterGreeterHTTPServer(httpSrv, s)

	app := kratos.New(
		kratos.Name(Name),
		kratos.Server(
			httpSrv,
			grpcSrv,
		),
	)

	if err := app.Run(); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by guihouchang** [comment]
可以尝试在ResponseEncoder这里处理

**Comment by z760087139** [comment]
> 
ResponseEncoder 只是针对返回的内容进行 encode 
如果我希望在 service 获取 responseWriter 并升级成 websocket 呢？
由于现在 kratos 框架并不提供通用的 websocket 入口，我现在想通过中间件提前封装 http.Context 并提供获取方式

``` go
package main

import (
	"context"
	"github.com/go-kratos/examples/helloworld/helloworld"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/errors"
	"github.com/go-kratos/kratos/v2/middleware"
	"github.com/go-kratos/kratos/v2/middleware/metadata"
	"github.com/go-kratos/kratos/v2/middleware/recovery"
	"github.com/go-kratos/kratos/v2/transport/grpc"
	"github.com/go-kratos/kratos/v2/transport/http"
	"github.com/gorilla/websocket"
	"log"
)

// go build -ldflags "-X main.Version=x.y.z"
var (
	// Name is the name of the compiled software.
	Name = "helloworld"
	// Version is the version of the compiled software.
	// Version = "v1.0.0"
)

// server is used to implement helloworld.GreeterServer.
type server struct {
	helloworld.UnimplementedGreeterServer
}

// SayHello implements helloworld.GreeterServer
func (s *server) SayHello(ctx context.Context, in *helloworld.HelloRequest) (*helloworld.HelloReply, error) {
	hctx, ok := FromContext(ctx)
	if !ok {
		return nil, errors.BadRequest("custom_error", "not a http.Context")
	}
	req := hctx.Request()
	resp := hctx.Response()
	
	upgrader := websocket.Upgrader{}
	c, _ := upgrader.Upgrade(resp, req, nil)
	c.WriteMessage(websocket.TextMessage, []byte("websocket connect"))
	return nil, nil
}

type HttpC struct{}

func FromContext(ctx context.Context) (http.Context, bool) {
	h, ok := ctx.Value(HttpC{}).(http.Context)
	return h, ok
}

func HttpContext(handler middleware.Handler) middleware.Handler {
	return func(ctx context.Context, req interface{}) (reply interface{}, err error) {
		ctx = context.WithValue(ctx, HttpC{}, ctx)
		return handler(ctx, req)
	}
}

func main() {
	s := &server{}
	httpSrv := http.NewServer(
		http.Address(":8000"),
		http.Middleware(
			recovery.Recovery(),
			HttpContext,
			metadata.Server(),
		),
	)
	grpcSrv := grpc.NewServer(
		grpc.Address(":9000"),
		grpc.Middleware(
			recovery.Recovery(),
		),
	)
	helloworld.RegisterGreeterServer(grpcSrv, s)
	helloworld.RegisterGreeterHTTPServer(httpSrv, s)

	app := kratos.New(
		kratos.Name(Name),
		kratos.Server(
			httpSrv,
			grpcSrv,
		),
	)

	if err := app.Run(); err != nil {
		log.Fatal(err)
	}
}

```

**Comment by XiaoK29** [comment]
可以使用http.RequestFromServerContext(ctx)来做,这是我写的一个中间件可以参考一下，RequestFromServerContext返回的是你要的东西
![image](https://github.com/go-kratos/kratos/assets/38639105/a47f37e2-dc09-4a7d-b220-21c1e69a4111)
![image](https://github.com/go-kratos/kratos/assets/38639105/d527ed78-b838-4cc0-bc8e-e5cba9b1211e)

**Comment by whrss9527** [comment]
> 可以使用http.RequestFromServerContext(ctx)来做，这是我写的一个中间件可以参考一下，RequestFromServerContext返回你想要的东西 ![图像](https://user-images.githubusercontent.com/38639105/261493303-a47f37e2-dc09-4a7d-b220-21c1e69a4111.png) ![图像](https://user-images.githubusercontent.com/38639105/261493411-d527ed78-b838-4cc0-bc8e-e5cba9b1211e.png)

RequestFromServerContext的编码老哥可以给一下吗

**Comment by XiaoK29** [comment]
> 您能给我 RequestFromServerContext 的编码吗？

func getIP(handler middleware.Handler) middleware.Handler {
	return func(ctx context.Context, req interface{}) (interface{}, error) {
		if httpCtx, ok := http.RequestFromServerContext(ctx); ok {
			host, _, err := net.SplitHostPort(httpCtx.RemoteAddr)
			if err != nil {
				return nil, err
			}

			ctx = context.WithValue(ctx, "ip", host)
			return handler(ctx, req)
		}

		return handler(ctx, req)
	}
}

**Comment by XiaoK29** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> > You can use http.RequestFromServerContext(ctx) to do it. This is a middleware I wrote for reference. RequestFromServerContext returns what you want! [Image](https://user-images.githubusercontent.com/38639105/ 261493303-a47f37e2-dc09-4a7d-b220-21c1e69a4111.png) ![Image](https://user-images.githubusercontent.com/38639105/261493411-d527ed78-b838-4cc0-bc8e-e5cba9b1211 e.png)
> 
> Can you please give me the coding of RequestFromServerContext?

`func getIP(handler middleware.Handler) middleware.Handler {
	return func(ctx context.Context, req interface{}) (interface{}, error) {
		if httpCtx, ok := http.RequestFromServerContext(ctx); ok {
			// 除了第三方服务,city_walk也需要用到
			// if !strings.Contains(httpCtx.URL.Path, "merchant") {
			// 	return handler(ctx, req)
			// }

			host, _, err := net.SplitHostPort(httpCtx.RemoteAddr)
			if err != nil {
				return nil, err
			}

			ctx = context.WithValue(ctx, "ip", host)
			return handler(ctx, req)
		}

		return handler(ctx, req)
	}
}`

**Comment by XiaoK29** [comment]
``> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> > You can use http.RequestFromServerContext(ctx) to do it. This is a middleware I wrote for reference. RequestFromServerContext returns what you want! [Image](https://user-images.githubusercontent.com/38639105/ 261493303-a47f37e2-dc09-4a7d-b220-21c1e69a4111.png) ![Image](https://user-images.githubusercontent.com/38639105/261493411-d527ed78-b838-4cc0-bc8e-e5cba9b1211 e.png)
> 
> Can you please give me the coding of RequestFromServerContext?
```go
func getIP(handler middleware.Handler) middleware.Handler {
	return func(ctx context.Context, req interface{}) (interface{}, error) {
		if httpCtx, ok := http.RequestFromServerContext(ctx); ok {
			// 除了第三方服务,city_walk也需要用到
			// if !strings.Contains(httpCtx.URL.Path, "merchant") {
			// 	return handler(ctx, req)
			// }

			host, _, err := net.SplitHostPort(httpCtx.RemoteAddr)
			if err != nil {
				return nil, err
			}

			ctx = context.WithValue(ctx, "ip", host)
			return handler(ctx, req)
		}

		return handler(ctx, req)
	}
}
```

**Comment by XiaoK29** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> > You can use http.RequestFromServerContext(ctx) to do it. This is a middleware I wrote for reference. RequestFromServerContext returns what you want! [Image](https://user-images.githubusercontent.com/38639105/ 261493303-a47f37e2-dc09-4a7d-b220-21c1e69a4111.png) ![Image](https://user-images.githubusercontent.com/38639105/261493411-d527ed78-b838-4cc0-bc8e-e5cba9b1211 e.png)
> 
> Can you please give me the coding of RequestFromServerContext?

```go
func getIP(handler middleware.Handler) middleware.Handler {
	return func(ctx context.Context, req interface{}) (interface{}, error) {
		if httpCtx, ok := http.RequestFromServerContext(ctx); ok {
			host, _, err := net.SplitHostPort(httpCtx.RemoteAddr)
			if err != nil {
				return nil, err
			}

			ctx = context.WithValue(ctx, "ip", host)
			return handler(ctx, req)
		}

		return handler(ctx, req)
	}
}
```

**Comment by wjfmmyjj** [comment]
> 可以使用http.RequestFromServerContext(ctx)来做,这是我写的一个中间件可以参考一下，RequestFromServerContext返回的是你要的东西 ![image](https://private-user-images.githubusercontent.com/38639105/261493303-a47f37e2-dc09-4a7d-b220-21c1e69a4111.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNzMwNTIsIm5iZiI6MTcyNzE3Mjc1MiwicGF0aCI6Ii8zODYzOTEwNS8yNjE0OTMzMDMtYTQ3ZjM3ZTItZGMwOS00YTdkLWIyMjAtMjFjMWU2OWE0MTExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDEwMTIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhNDQwODJhNTQ5NjNiOWY3YWE0YzI1ODdiNDMxZTlhYmM1MTJmMTk0ZGZiY2ZkNmE2YjVjMmJlZWE5NDQ4ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xpuwiK2h71ykBqBB5CLBaPzE2x3jtWj9gKHhdd5fOYw) ![image](https://private-user-images.githubusercontent.com/38639105/261493411-d527ed78-b838-4cc0-bc8e-e5cba9b1211e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNzMwNTIsIm5iZiI6MTcyNzE3Mjc1MiwicGF0aCI6Ii8zODYzOTEwNS8yNjE0OTM0MTEtZDUyN2VkNzgtYjgzOC00Y2MwLWJjOGUtZTVjYmE5YjEyMTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDEwMTIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhYzdmMTBkZmY0NTU4ZDhmYWQwYzZjODhkMmMxMGVmNDhlYTg5ZTY5MDY0ZGMzZWE5YzE4NThjNDBkOGExOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7zz3_JbryToNKgVSQvlYUBTa-sfoo6Il9OR7AUCJBvg)

RequestFromServerContext返回的是request，请问有什么方法可以获取ResponseWriter吗，也是用于websocket的

**Comment by XiaoK29** [comment]
> 请问有什么方法可以获取Response

使用这个方法
https://go-kratos.dev/docs/component/transport/http#responseencoderen-encoderesponsefunc-serveroption

**Comment by afraidjpg** [comment]
> > 可以使用http.RequestFromServerContext(ctx)来做,这是我写的一个中间件可以参考一下，RequestFromServerContext返回的是你要的东西 ![image](https://private-user-images.githubusercontent.com/38639105/261493303-a47f37e2-dc09-4a7d-b220-21c1e69a4111.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNzMwNTIsIm5iZiI6MTcyNzE3Mjc1MiwicGF0aCI6Ii8zODYzOTEwNS8yNjE0OTMzMDMtYTQ3ZjM3ZTItZGMwOS00YTdkLWIyMjAtMjFjMWU2OWE0MTExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDEwMTIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhNDQwODJhNTQ5NjNiOWY3YWE0YzI1ODdiNDMxZTlhYmM1MTJmMTk0ZGZiY2ZkNmE2YjVjMmJlZWE5NDQ4ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xpuwiK2h71ykBqBB5CLBaPzE2x3jtWj9gKHhdd5fOYw) ![image](https://private-user-images.githubusercontent.com/38639105/261493411-d527ed78-b838-4cc0-bc8e-e5cba9b1211e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNzMwNTIsIm5iZiI6MTcyNzE3Mjc1MiwicGF0aCI6Ii8zODYzOTEwNS8yNjE0OTM0MTEtZDUyN2VkNzgtYjgzOC00Y2MwLWJjOGUtZTVjYmE5YjEyMTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDEwMTIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhYzdmMTBkZmY0NTU4ZDhmYWQwYzZjODhkMmMxMGVmNDhlYTg5ZTY5MDY0ZGMzZWE5YzE4NThjNDBkOGExOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7zz3_JbryToNKgVSQvlYUBTa-sfoo6Il9OR7AUCJBvg)
> 
> RequestFromServerContext返回的是request，请问有什么方法可以获取ResponseWriter吗，也是用于websocket的

I using middleware to store the `http.Context` type to context fist, and then get that in other place.

```golang
// NewHTTPServer new an HTTP server.
func NewHTTPServer(c *conf.Server, ss http2.ServiceRegister, wl http2.WhiteList, r redis.Cmdable, logger log.Logger) *http.Server {
	var opts = []http.ServerOption{//...}
	if c.Http.Network != "" {
		opts = append(opts, http.Network(c.Http.Network))
	}
	if c.Http.Addr != "" {
		opts = append(opts, http.Address(c.Http.Addr))
	}
	if c.Http.Timeout != nil {
		opts = append(opts, http.Timeout(c.Http.Timeout.AsDuration()))
	}

        // use middleware.Chain to ensure that middleware are called in order
        // make sure to call SaveKratosContext before any middleware that might call "context.WithContext()"
	chain := middleware.Chain(recovery.Recovery(), http2.SaveKratosContext() // ... other middleware)
	opts = append(opts, http.Middleware(chain))

	srv := http.NewServer(opts...)

	ss.RegisterHTTP(srv)
	return srv
}
```



middleware:
```golang
package http

import (
	"context"
	"github.com/go-kratos/kratos/v2/middleware"
	http2 "github.com/go-kratos/kratos/v2/transport/http"
)

func SaveKratosContext() middleware.Middleware {
	return func(next middleware.Handler) middleware.Handler {
		return func(ctx context.Context, req interface{}) (interface{}, error) {
			if c, ok := ctx.(http2.Context); ok {
				ctx = context.WithValue(ctx, "kratos_http_context", c)
			}

			return next(ctx, req)
		}
	}
}

func KratosContextFromContext(ctx context.Context) http2.Context {
	if c, ok := ctx.Value("kratos_http_context").(http2.Context); ok {
		return c
	}
	return nil
}
```

How to use:
```golang
func WriteDataToResponse(ctx context.Context, v interface{}) {
	serverCtx := KratosContextFromContext(ctx)
	if serverCtx == nil {
		fmt.Println("type assertion failed")
		return
	}
        var yourReply []byte()
	serverCtx.Response().Write(yourReply)
}
```

**Comment by afraidjpg** [comment]
我也有同样的问题，我这边的情况是需要使用SSE，需要在业务中就对客户端进行输出，我这边的处理方式有点粗暴，既然在封装后会导致断言失败，那就在封装前先存下来：

```golang
type kratosHttpContext struct{}
func SaveKratosHttpContext() middleware.Middleware {
	return func(next middleware.Handler) middleware.Handler {
		return func(ctx context.Context, req interface{}) (interface{}, error) {
			if c, ok := ctx.(http2.Context); ok {
				ctx = context.WithValue(ctx, kratosHttpContext{}, c)
			}
			return next(ctx, req)
		}
	}
}


func GetKratosHttpContextFromContext(ctx context.Context) http2.Context {
	if c, ok := ctx.Value(kratosHttpContext{}).(http2.Context); ok {
		return c
	}
	return nil
}
```

然后在 server 中注册的时候使用 middleware.Chain，放在第一个注册（或者任何会对context进行封装的操作之前）：

```golang
func NewHTTPServer(...) {
	var opts = []http.ServerOption{}
	chain := middleware.Chain(
		recovery.Recovery(),
		my_middleware.SaveKratosHttpContext(),
                 ...
        )
        ...
}

```

虽然丑陋，但有用
