### ISSUE TITLE
[Bug] The caller depth of log.Filter should be the same as log.logger.

### ISSUE THREAD

**Issue by kvii** [go-kratos/kratos#2954]
#### What happened:

Caller depth changed after create a log.Filter.

#### What you expected to happen:

log.Filter should print the same caller depth as log.logger.

#### How to reproduce it (as minimally and precisely as possible):

```go
package main

import (
	"github.com/go-kratos/kratos/v2/log"
)

func main() {
	// common use case: caller is displayed correctly.
	l1 := log.With(log.DefaultLogger,
		"caller", log.DefaultCaller,
	)
	h1 := log.NewHelper(l1)
	h1.Info("h1") // INFO caller=playground/main.go:12 msg=h1

	// after add a Filter: caller depth +1
	l2 := log.NewFilter(l1)
	h2 := log.NewHelper(l2)
	h2.Info("h2") // INFO caller=log/helper.go:91 msg=h2

	// Note: Can't write some code like log.Caller(depth + 1).
	// Because log.NewFilter and log.With can be nested, like
	// log.With(log.NewFilter(log.With(l)))
}
```

#### Anything else we need to know?:

Can't write some code like log.Caller(depth + 1). Because log.NewFilter and log.With can be nested, like `log.With(log.NewFilter(log.With(l)))`.

#### Environment:

- Kratos version (use `kratos -v`): kratos version v2.7.0
- Go version (use `go version`): go version go1.21.0 darwin/arm64
- OS (e.g: `cat /etc/os-release`): mac os Ventura 13.5 (22G74) with m1 pro

**Comment by shenqidebaozi** [comment]
`caller` supports custom skip levels

**Comment by kvii** [comment]
@shenqidebaozi 我就是在微信群里提问的那个人。问题不在于 caller 能不能自定义 depth。**问题在于使用 logger 的方式并不统一**。
可能您觉得 log.With 里处理 prefix 的逻辑就够了。但 log.Filter 并不是 log.logger，with 一个 Filter 的话 caller 就乱了。
可能您觉得在一个微服务工程里自定义 depth ，然后统一 logger 的使用方式就行了。但有些第三方的包，像 logging.Server，它是直接使用 log.Logger 而非 log.Helper，所以 caller 还是乱了。
假设 depth 是 4，那么直接用 log.Logger.Log 就是 3，用 log.Helper.Log 就是 4。这样无论写死成几都不对，自定义 caller 也无法处理这种逻辑。

**Comment by kvii** [comment]
@junneyang 已经解决了啊。pr 都合并到主线去了，应该早就发版了。如果说你遇到的其他系统的 logger 有这个问题的话，那么你可以学学 gorm 的 logger。它是动态计算 calller 的。也就是一层 caller 一层 caller 的往上找，一直找到目录名不包含 gorm 的那一层后停止。

**Comment by kvii** [comment]
@junneyang 你自己写的 `zapcore.NewConsoleEncoder`，到头来又觉得不是期望的格式？还有这个问题和我提出的是一个问题吗？如果问题不同，请单开 issue。如果想找我帮忙可以 @ 我。这个问题你问 AI 人家都能秒回你好吧。

<img width="463" height="25" alt="Image" src="https://github.com/user-attachments/assets/6549611f-7ff4-440f-b43d-935b3e5f68f1" />
