### ISSUE TITLE
wire occasionally reports an error

### ISSUE THREAD

**Issue by panziqun** [go-kratos/kratos#2966]
我什么都没做，前一次可以，后一次就报错
![image](https://github.com/go-kratos/kratos/assets/26440059/dd2a768f-4efb-4dfb-86b1-7803dfb4984e)

**Comment by fifsky** [comment]
try   
```
go mod tidy
```
then
```
wire ./...
```

**Comment by XiaoK29** [comment]
这是自己的wire注入没写好吧，建议看一下wire的文档
