### ISSUE TITLE
[Question] The service starts through kratos run and reports that the configuration file does not exist, but the configuration file does exist

### ISSUE THREAD

**Issue by jc9090kkkk** [go-kratos/kratos#2976]
Please see the FAQ in our main README.md before submitting your issue.
<img width="1588" alt="image" src="https://github.com/go-kratos/kratos/assets/62995891/182b9e4c-9168-417b-8635-932fb7e3659b">

<img width="381" alt="image" src="https://github.com/go-kratos/kratos/assets/62995891/33363dd3-36ad-4e66-885d-c13f17d42561">

**Comment by kvii** [comment]
这看起来就是你配置文件放错地方了……你的配置文件在 "./configs/locales/application-local.yaml"。
