### ISSUE TITLE
port in use error not prompt correctly

### ISSUE THREAD

**Issue by zssty2010** [go-kratos/kratos#2977]
#### What happened:
panic with "context cancel" when port in use.
#### What you expected to happen:
it shoud show an error about port XXX in use, not an unrefrence error -  "context cancel"
#### Anything else we need to know?:
I indicated the problem is in `vendor/github.com/go-kratos/kratos/v2/app.go:112`. it throw the error `port in use` but `eg.Wait()` is call at the end of this function after `a.opts.registrar` who will throw the "context cancel" error.
#### Environment:
- Kratos version (use `kratos -v`): newest
- Go version (use `go version`): not impotant
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by hoslo** [comment]
> #### What happened:
> panic with "context cancel" when port in use.
> 
> #### What you expected to happen:
> it shoud show an error about port XXX in use, not an unrefrence error - "context cancel"
> 
> #### How to reproduce it (as minimally and precisely as possible):
> #### Anything else we need to know?:
> I indicated the problem is in `vendor/github.com/go-kratos/kratos/v2/app.go:112`. it throw the error `port in use` but `eg.Wait()` is call at the end of this function after `a.opts.registrar` who will throw the "context cancel" error.
> 
> #### Environment:
> * Kratos version (use `kratos -v`): newest
> * Go version (use `go version`): not impotant
> * OS (e.g: `cat /etc/os-release`):
> * Others:

I cant reproduction your problem
```shell
kratos run
2023/09/25 18:21:20 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
DEBUG msg=config loaded: config.yaml format: yaml
INFO ts=2023-09-25T18:21:20+08:00 caller=data/data.go:21 service.id=LGNB-2023010001.local service.name= service.version= trace.id= span.id= msg=closing the data resources
INFO ts=2023-09-25T18:21:20+08:00 caller=config/config.go:67 service.id=LGNB-2023010001.local service.name= service.version= trace.id= span.id= msg=watcher's ctx cancel : context canceled
panic: listen tcp 0.0.0.0:8000: bind: address already in use
```

**Comment by pengdaCN** [comment]
我觉得，这个端口不能被监听而直接panic的处理方式没有问题，如果端口都不能用了，服务后续启动也没有意义了

**Comment by zssty2010** [comment]
@hoslo did you try by etcd registrar exist? what I means is alfter `eg.Wait()` even these is an port inuse error but also called `a.opts.registrar.Register` and issus an "context canneled" error。 and I only saw the reason is "context canneled" but realy reason is “port in use".

so you must try in "service discovery" configrations!

**Comment by hoslo** [comment]
```golang
func newApp(logger log.Logger, gs *grpc.Server, hs *http.Server) *kratos.App {
	// new etcd client
	client, err := clientv3.New(clientv3.Config{
		Endpoints: []string{"127.0.0.1:32769"},
	})
	if err != nil {
		panic(err)
	}
	// new reg with etcd client
	reg := etcd.New(client)

	return kratos.New(
		kratos.ID(id),
		kratos.Name(Name),
		kratos.Version(Version),
		kratos.Metadata(map[string]string{}),
		kratos.Logger(logger),
		kratos.Server(
			gs,
			hs,
		),
		kratos.Registrar(reg),
	)
}
```

```shell
2024/01/31 14:46:03 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
DEBUG msg=config loaded: config.yaml format: yaml
INFO ts=2024-01-31T14:46:03+08:00 caller=data/data.go:21 service.id=LGNB-2023010001.local service.name= service.version=v2.6.2-2-gba85299 trace.id= span.id= msg=closing the data resources
panic: listen tcp 0.0.0.0:9000: bind: address already in use

goroutine 1 [running]:
main.main()
```
@zssty2010 
Still can't repeat your question
