### ISSUE TITLE
[Question] When will the nacos sdk be updated?

### ISSUE THREAD

**Issue by iaimstar** [go-kratos/kratos#2978]
现在使用的nacos sdk 版本有很多的bug
不支持高版本nacos
升级sdk和nacos会导致协程卡死
删除正在监听的配置文件会导致cpu高负荷。瞬间产生大量日志占满硬盘
生产环境用起来风险很高。
不知道kratos团队打算什么时候更新nacos sdk的版本

**Comment by leyou240** [comment]
2.0版本的nacos sdk有race问题，通过不了单元测试

**Comment by KafuuEriri** [comment]
很期待这个更新
