### ISSUE TITLE
[Question] How to log Http method?

### ISSUE THREAD

**Issue by dobet** [go-kratos/kratos#2995]
Please see the FAQ in our main README.md before submitting your issue.

I only use kratos as a http server. Now, I want to log http method , but I don't how to get http header in Log()

**Comment by Panici4** [comment]
`if h, ok := ctx.(http.Context); ok {
		fmt.Println(h.Header())
	}`
Is this help?

**Comment by dobet** [comment]
> `if h, ok := ctx.(http.Context); ok { fmt.Println(h.Header()) }` Is this help?

I want log http method in caller log, not I code log.info(ctx)

**Comment by hoslo** [comment]
> > `if h, ok := ctx.(http.Context); ok { fmt.Println(h.Header()) }` Is this help?
> 
> I want log http method in caller log, not I code log.info(ctx)

you can custom your log middleware
```golang

func NewHTTPServer(c *conf.Server, greeter *service.GreeterService) *http.Server {
	opts := []http.ServerOption{
		http.Middleware(
			loggingMiddleware,
		),
	}
	if c.Http.Network != "" {
		opts = append(opts, http.Network(c.Http.Network))
	}
	if c.Http.Addr != "" {
		opts = append(opts, http.Address(c.Http.Addr))
	}
	if c.Http.Timeout != nil {
		opts = append(opts, http.Timeout(c.Http.Timeout.AsDuration()))
	}
	srv := http.NewServer(opts...)
	v1.RegisterGreeterHTTPServer(srv, greeter)
	return srv
}


func loggingMiddleware(handler middleware.Handler) middleware.Handler {
	return func(ctx context.Context, req interface{}) (reply interface{}, err error) {
		// fmt.Println("logging middleware in", req)
		if hCtx, ok := ctx.(http.Context); ok {
			log.Infow(
				"method", hCtx.Request().Method,
			)
		}
		reply, err = handler(ctx, req)
		return
	}
}
```
