### ISSUE TITLE
[Question] When using http, if I want to set timeouts for different routes, how should I set them?

### ISSUE THREAD

**Issue by dobet** [go-kratos/kratos#3014]
Please see the FAQ in our main README.md before submitting your issue.

**Comment by hoslo** [comment]
> Please see the FAQ in our main README.md before submitting your issue.

This is my solution, you can refer to it
```golang
// Detach returns a detached context
func Detach(ctx context.Context) context.Context { return detachedContext{ctx} }

type detachedContext struct{ parent context.Context }

func (v detachedContext) Deadline() (time.Time, bool)       { return time.Time{}, false }
func (v detachedContext) Done() <-chan struct{}             { return nil }
func (v detachedContext) Err() error                        { return nil }
func (v detachedContext) Value(key interface{}) interface{} { return v.parent.Value(key) }


// SayHello implements helloworld.GreeterServer.
func (s *GreeterService) SayHello(ctx context.Context, in *v1.HelloRequest) (*v1.HelloReply, error) {
         // Detach the service ctx and reset the timeout
	ctx, cancel := context.WithTimeout(Detach(ctx), time.Second*3)
	defer cancel()
	// ....
}
```

**Comment by shenqidebaozi** [comment]
> > Please see the FAQ in our main README.md before submitting your issue.
> 
> This is my solution, you can refer to it
> 
> ```go
> // Detach returns a detached context
> func Detach(ctx context.Context) context.Context { return detachedContext{ctx} }
> 
> type detachedContext struct{ parent context.Context }
> 
> func (v detachedContext) Deadline() (time.Time, bool)       { return time.Time{}, false }
> func (v detachedContext) Done() <-chan struct{}             { return nil }
> func (v detachedContext) Err() error                        { return nil }
> func (v detachedContext) Value(key interface{}) interface{} { return v.parent.Value(key) }
> 
> 
> // SayHello implements helloworld.GreeterServer.
> func (s *GreeterService) SayHello(ctx context.Context, in *v1.HelloRequest) (*v1.HelloReply, error) {
>          // Detach the service ctx and reset the timeout
> 	ctx, cancel := context.WithTimeout(Detach(ctx), time.Second*3)
> 	defer cancel()
> 	// ....
> }
> ```
@dobet 
You can also set timeout times for routes separately in middleware
