### ISSUE TITLE
[Feature] Some specification issues when Kratos registers services on Polaris

### ISSUE THREAD

**Issue by tan-zhuo** [go-kratos/kratos#3018]
### Feature-request

1、注册到 Polaris 上，服务名称和协议直接拼接在了一起
2、注册时协议这个字段的传入存在部分问题

1、目前注册之后的服务名称
<img width="966" alt="image" src="https://github.com/go-kratos/kratos/assets/32378959/6abfc255-2e08-4939-ab23-87b2e3b998a7">

2、目前协议这个字段完全无法填写，因为写了之后，两个注册的服务实例都会是 同一个协议标记。按设计来说应该在 Kratos 注册实现代码中直接填入对应协议字段，所以这里开发人员填写了也是没有用的。

<img width="893" alt="image" src="https://github.com/go-kratos/kratos/assets/32378959/81e19fc5-a09a-489d-9510-53e21c1202c0">
<img width="1163" alt="image" src="https://github.com/go-kratos/kratos/assets/32378959/2ecb3ef4-66f2-42c0-8058-e22ec7e4a02f">

### Proposal

1、注册到 Polaris 上，不应该是直接服务名称+协议这样拼接，至少有个分割符，rc-user.http 或者 rc-user-http 都是可以的。虽然目前不影响使用，但是我认为这个也算是一种规范

2、对于注册服务实例的协议字段，应该在 Kratos 项目中 contrib/registry/polaris/registry.go 文件中进行内部指定，而不是让开发人员传入。

<img width="1512" alt="image" src="https://github.com/go-kratos/kratos/assets/32378959/4e71c66b-7571-4fad-8a24-beab2bc840c2">

**Comment by shenqidebaozi** [comment]
Which SDK is being used? `contrib/registry/polaris` or `contrib/polaris`

**Comment by shenqidebaozi** [comment]
you can try using `contrib/polaris`

**Comment by tan-zhuo** [comment]
All right , I am currently using `contrib/registry/polaris`

**Comment by tan-zhuo** [comment]
But `contrib/registry/polaris` more in line with framework usage for `kratos`

**Comment by shenqidebaozi** [comment]
subsequent collaborations with Polaris will be conducted in `contrib/polaris`

**Comment by tan-zhuo** [comment]
ok. I switch to `contrib/polaris`

**Comment by tan-zhuo** [comment]
我已经使用了  `contrib/polaris` 包进行了注册，我发现现在的实现逻辑是 同一个服务名称 下 注册实例是通过协议区分的。这确实更符合注册逻辑，非常科学

<img width="845" alt="image" src="https://github.com/go-kratos/kratos/assets/32378959/aff13b8d-3e01-499b-9ba0-4a0b8223cb54">
<img width="1300" alt="image" src="https://github.com/go-kratos/kratos/assets/32378959/985d8af7-208c-4c05-8ca5-8c558e8bde38">

但是我想问下，关于限流，那现在是不是不能根据协议进行区分 限流规则了？比如同一个接口 http 我想 1分钟 1次请求，grpc 1分钟 2次请求的配置，这种现在能支持吗？
