### ISSUE TITLE
http.NewClient results in NODE_NOT_FOUND

### ISSUE THREAD

**Issue by yinyajun** [go-kratos/kratos#3022]
#### What happened:
Http.NewClient中使用Nacos Discovery，获取的service列表永远为空

#### How to reproduce it (as minimally and precisely as possible):
```go
registry := nacos.New(client, nacos.WithGroup("dev"))
//fmt.Println(registry.GetService(context.Background(), "Hermes.sd.http")) // 这里service列表不为空

cli, _ := http.NewClient(context.Background(),
http.WithEndpoint("discovery:///sd"),
http.WithDiscovery(registry))

c := sd.NewSDHTTPClient(cli)
resp, err := c.Text2Img(context.Background(), &sd.Text2ImgReq{}) 
fmt.Println(resp, err) // 这里报NODE_NOT_FOUND错误
```

#### Anything else we need to know?:
https://github.com/go-kratos/kratos/blob/6c026bce56a9e388006cb97e99036c0a043ae95d/transport/http/resolver.go#L116创建resolver中，r.update方法会存储service列表，但是这个方法并没有执行。因为在nacos的discovery的watcher的Next方法会一直阻塞，直到有service列表发生改动。但是这与Watcher的接口约束不符。

```go
// Watcher is service watcher.
type Watcher interface {
	// Next returns services in the following two cases:
	// 1.the first time to watch and the service instance list is not empty.
	// 2.any service instance changes found.
	// if the above two conditions are not met, it will block until context deadline exceeded or canceled
	Next() ([]*ServiceInstance, error)
	// Stop close the watcher.
	Stop() error
}
```
Discovery接口约束中，Watcher的Next针对首次调用，会有返回。但是`https://github.com/go-kratos/kratos/blob/main/contrib/registry/nacos/watcher.go`中的实现
```go
func (w *watcher) Next() ([]*registry.ServiceInstance, error) {
	select {
	case <-w.ctx.Done():
		return nil, w.ctx.Err()
	case <-w.watchChan:
	}
	res, err := w.cli.GetService(vo.GetServiceParam{
		ServiceName: w.serviceName,
		GroupName:   w.groupName,
		Clusters:    w.clusters,
	})
```
直接会阻塞到service列表发生改动。
也可以直接去看etcd的实现`https://github.com/go-kratos/kratos/blob/main/contrib/registry/etcd/watcher.go`，有针对首次调用的情况。

#### Environment:
- Kratos version (use `kratos -v`):
- Go version (use `go version`):
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by KafuuEriri** [comment]
2.7.3版本中仍然存在这个问题
https://github.com/go-kratos/kratos/blob/main/contrib/registry/etcd/watcher.go 中会持续阻塞导致获取不到节点
