### ISSUE TITLE
load apollo config yml format panic

### ISSUE THREAD

**Issue by hoslo** [go-kratos/kratos#3035]
#### What happened:
panic when load apollo yml config
#### What you expected to happen:
do not panic
#### How to reproduce it (as minimally and precisely as possible):
```golang
	type Project struct {
		Test int `yaml:"test" json:"test" yml:"test"`
	}
	type Bootstrap struct {
		Ns      string   `yaml:"ns" json:"ns" yml:"name"`
		Name    string   `yaml:"name" json:"name" yml:"name"`
		Project *Project `yaml:"project" json:"project" yml:"project"`
	}
	c := config.New(
		config.WithSource(
			apollo.NewSource(
				apollo.WithAppID("kratos"),
				apollo.WithCluster("dev"),
				apollo.WithEndpoint("http://localhost:8080"),
				apollo.WithNamespace("app.yml"),
				apollo.WithEnableBackup(),
				// apollo.WithOriginalConfig(),
				apollo.WithSecret("37b75fb736084e41b065fd11233f70e2"),
			),
		),
	)

	if err := c.Load(); err != nil {
		panic(err)
	}
```
#### Environment:
- Kratos version (use `kratos -v`): kratos version v2.7.0
- Go version (use `go version`): go version go1.21.1 darwin/arm64
- OS (e.g: `cat /etc/os-release`): macos
- Others:

**Comment by shenqidebaozi** [comment]
I don't think this is a bug, yaml or yml is just a difference in declaring suffixes. If we add a separate yml encoding package for yml, I think it would be strange

**Comment by hoslo** [comment]
> I don't think this is a bug, yaml or yml is just a difference in declaring suffixes. If we add a separate yml encoding package for yml, I think it would be strange

how you think should to solve this question?

**Comment by shenqidebaozi** [comment]
The two codes are exactly the same, only the package with the same name does not look very halal 😂

**Comment by hoslo** [comment]
> The two codes are exactly the same, only the package with the same name does not look very halal 😂

maybe we should put them in one package (yaml)?
