### ISSUE TITLE
[Question] The middleware is Executed at the end of the request?

### ISSUE THREAD

**Issue by ChangSZ** [go-kratos/kratos#3057]
![image](https://github.com/go-kratos/kratos/assets/26893331/609b984b-c000-4b48-9469-97d40e1b3ca8)

我看到文档中是这么介绍的，图片是符合我的认知的。

但实际操作时，我得到了不一样的日志输出：
![image](https://github.com/go-kratos/kratos/assets/26893331/dc3cdf59-8939-4264-a346-d228470060bd)

是否是我的使用姿势不对， 我在学习这个：https://github.com/go-kratos/examples/blob/main/http/middlewares/main.go

**Comment by shenqidebaozi** [comment]
The printed results are consistent with the diagram, and the onion ring model itself is like this

**Comment by ChangSZ** [comment]
> The printed results are consistent with the diagram, and the onion ring model itself is like this

Shouldn't the expected result be like this?  
```
service middleware in
service middleware 2 in
INFO msg=sayHelloHandler
service middleware 2 out
service middleware out
```

And I saw that if you only set this setting, the middleware will not take effect.
```golang
	var opts = []http.ServerOption{
		http.Address(":8000"),
		http.Middleware(
			serviceMiddleware,
			serviceMiddleware2,
		),
	}
	httpSrv := http.NewServer(opts...)
```

Please guide me, I don’t know where the problem is with the settings.  🫰

**Comment by shenqidebaozi** [comment]
HTTP middleware only works on routes defined through protobuf, and the use cases in the example are all tested. Please check your own code

**Comment by shenqidebaozi** [comment]
In addition, the schematic in the figure is only for middleware and does not include HTTP filter

**Comment by shenqidebaozi** [comment]
The 'your handle' in the figure refers to your business logic method defined through protocs, not the middleware HTTP handle

**Comment by ChangSZ** [comment]
> HTTP middleware only works on routes defined through protobuf, and the use cases in the example are all tested. Please check your own code

Ok, I see~  My understanding of this component is biased, thank you for correcting me
