### ISSUE TITLE
The trace_id between requests is getting mixed up

### ISSUE THREAD

**Issue by ionling** [go-kratos/kratos#3061]
#### What happened:

The trace_id between requests is getting mixed up.

#### What you expected to happen:

The `trace_id` between requests is independent.

#### How to reproduce it (as minimally and precisely as possible):

Use a `log.Filter` as the global logger 
and enable both `tracing.Server()` and `logging.Server()` middlewares.

#### Anything else we need to know?:

this is cauased by `log.WithContext()`.

https://github.com/go-kratos/kratos/blob/6cdd81811e102620ec93b125ea6ed38f06a5e03c/log/log.go#L65

#### Environment:

- Kratos version (use `kratos -v`): v2.6.3
- Go version (use `go version`): 1.20

**Comment by shenqidebaozi** [comment]
The method provided by global log is different from the helper, so it does not support printing traceid in logging

**Comment by shenqidebaozi** [comment]
Let's reorganize the issue. Your problem is that after using the log filter, cannot be printed trace_id? Can a minimum replication environment be provided

**Comment by shenqidebaozi** [comment]
alternatively, if you know how to fix it, you can directly submit a merge request
