### ISSUE TITLE
[Question] The pprof profile is not valid

### ISSUE THREAD

**Issue by asker-github** [go-kratos/kratos#3071]
I don't know how you can check the pprof profile. I'm through this period of command to view: go tool pprof - http = : 8001 -seconds=5 http://localhost:8000/debug/pprof/profile. But with kratos, the data is empty on the browser.
[pprof/main.go](https://github.com/go-kratos/examples/blob/main/http/pprof/main.go)
The following paragraph is the result of my modification.

func RegisterPprof(s *http.Server) {
	...
	s.HandleFunc("/sayhello", sayhello)
}

func sayhello(w http.ResponseWriter, r *http.Request) {
	fmt.Println("hello")
	time.Sleep(time.Second * 3)
}

**Comment by shenqidebaozi** [comment]
Partial code has been omitted from the provided code. From the provided code, it can be seen that there is no registered `pprof` interface. Duso has provided relevant prompts, please check if it cannot be obtained due to non registration

**Comment by asker-github** [comment]
> Partial code has been omitted from the provided code. From the provided code, it can be seen that there is no registered `pprof` interface. Duso has provided relevant prompts, please check if it cannot be obtained due to non registration

Thank you for your reply. I think it was because the processing was too fast and could not be detected.
