### ISSUE TITLE
[Question]How to print trace.id in log log

### ISSUE THREAD

**Issue by dagehuifei** [go-kratos/kratos#3089]
版本kratos version v2.7.1

1. kratos new kratos-log-trace

启动服务的log日志没有打印trace.id?

`	logger := log.With(log.NewStdLogger(os.Stdout),
		"ts", log.DefaultTimestamp,
		"caller", log.DefaultCaller,
		"service.id", id,
		"service.name", Name,
		"service.version", Version,
		"trace.id", tracing.TraceID(),
		"span.id", tracing.SpanID(),
	)
`

启动的日志和Service的日志都没有trace.id,
`INFO ts=2023-11-21T00:15:11+08:00 caller=http/server.go:317 service.id=Manfeis-MacBook-Pro.local service.name= service.version= trace.id= span.id= msg=[HTTP] server listening on: [::]:8000
INFO ts=2023-11-21T00:15:11+08:00 caller=grpc/server.go:212 service.id=Manfeis-MacBook-Pro.local service.name= service.version= trace.id= span.id= msg=[gRPC] server listening on: [::]:9000
INFO ts=2023-11-21T00:15:21+08:00 caller=biz/greeter.go:44 service.id=Manfeis-MacBook-Pro.local service.name= service.version= trace.id= span.id= msg=CreateGreeter: ss
INFO ts=2023-11-21T00:15:21+08:00 caller=service/greeter.go:29 service.id=Manfeis-MacBook-Pro.local service.name= service.version= trace.id= span.id= msg=打印TraceID
`

**Comment by dagehuifei** [comment]
这几个issue都试过，但是还是没解决问题

**Comment by shenqidebaozi** [comment]
https://github.com/go-kratos/examples/tree/main/traces

**Comment by shenqidebaozi** [comment]
Please check your code based on the example to see if the middleware order is correct, if a trace provider is provided, and if the logger uses a non global logger

**Comment by dagehuifei** [comment]
Tracing middleware can print trace.id , it's fine . how to print trace.id in service or biz ?

How to print trace.id in [https://github.com/go-kratos/examples/blob/main/traces/app/user/main.go:60] in the func (s *server) GetMyMessages(ctx context.Context, in *v1.GetMyMessagesRequest) (*v1.GetMyMessagesReply, error) func when the func add log like ```log.Infow("xxx", "xxx")```

INFO trace_id= span_id= caller=user/main.go:64 ssssss=sssssssssss
Handle connection.
INFO trace_id=8a37f38477b1ff60d22abefffa565c56 span_id=5a48b5a5640b0027 caller=tracing/tracing.go:57 kind=server component=http operation=/api.user.v1.User/GetMyMessages args=count:1 code=0 reason= stack= latency=0.005574167

**Comment by shenqidebaozi** [comment]
https://github.com/go-kratos/kratos/blob/9adece088b5151f6c1c214b46ee60a511c890da6/log/log.go#L52
