### ISSUE TITLE
Request context canceled during graceful shutdown

### ISSUE THREAD

**Issue by LinEvil** [go-kratos/kratos#3096]
#### What happened:
1. Send a http request, it is slow and takes 5s to return.
2. Terminate the program by Ctrl+C before the request returns.
3. Graceful shutdown and the context of the request is canceled.
4. Throwing context canceled error and exit.

Logs:
```log
INFO msg=[HTTP] server listening on: 127.0.0.1:8000
DEBUG msg=I'm going to sleep for 5 seconds.
INFO msg=[HTTP] server stopping
DEBUG msg=Time's up. Now to check my context.
DEBUG msg=context canceled
INFO msg=watcher's ctx cancel : context canceled
```
#### What you expected to happen:
The context of the request should not be canceled, and any request before executing a graceful shutdown should be processed normally unless the request time reaches `http.timeout` or shutdown time reaches `stopTimeout`.

#### How to reproduce it (as minimally and precisely as possible):
```yaml
# configs/config.yaml
server:
  http:
    addr: 127.0.0.1:8000
    timeout: 8s
```
```go
// internal/service/greeter.go
func (s *GreeterService) SayHello(ctx context.Context, in *v1.HelloRequest) (*v1.HelloReply, error) {
	s.log.WithContext(ctx).Infof("SayHello Received: %v", in.GetName())
	s.log.WithContext(ctx).Debug("I'm going to sleep for 5 seconds.")
	time.Sleep(5 * time.Second)	// press Ctrl+C
	s.log.WithContext(ctx).Debug("Time's up. Now to check my context.")
	if ctx.Err() == context.Canceled {
		s.log.WithContext(ctx).Debug("context canceled")
		return nil, ctx.Err()
	}
	return &v1.HelloReply{Message: "Hello " + in.GetName()}, nil
}
```

#### Anything else we need to know?:
The issue is similar to https://github.com/go-kratos/kratos/issues/1856, which was fixed in v2.2.1 (https://github.com/go-kratos/kratos/pull/1873 https://github.com/go-kratos/kratos/pull/1895).
My case works fine between v2.2.1 and v2.5.2

Since v2.5.3, the feature [#2403](https://github.com/go-kratos/kratos/pull/2403/files#diff-6c4b6ed7dc8834cef100f50dae61c30ffe7775a3f3f6f5a557517cb740c44a2dL105) changed `srv.Start(context)`, which may cause the current issue.
I tried rolling back that line and the problem was fixed, but I'm not sure if this is right.

#### Environment:
- Kratos version (use `kratos -v`): v2.7.1
- Go version (use `go version`): go1.21.4
- OS (e.g: `cat /etc/os-release`): Windows
- Others:

**Comment by shenqidebaozi** [comment]
If you already have a solution, you can directly submit a PR

**Comment by LinEvil** [comment]
Need review
https://github.com/go-kratos/kratos/pull/3097
