### ISSUE TITLE
The service startup error could not be printed correctly

### ISSUE THREAD

**Issue by cayller** [go-kratos/kratos#3101]
#### What happened:
using register a custom server and using registrar, when custom server return a error, terminal can not print correct error description

#### What you expected to happen:
printing the correct error 
![image](https://github.com/go-kratos/kratos/assets/48434371/13d28c12-41ad-48c6-b494-e468f05e6f9b)
but actually printing ctx canceled，because custom server return a error
![image](https://github.com/go-kratos/kratos/assets/48434371/e89bb81b-690d-4fe1-8533-4c9dd049aae2)

#### How to reproduce it (as minimally and precisely as possible):
![image](https://github.com/go-kratos/kratos/assets/48434371/37543385-04d2-4e62-be09-2a5e874abbc8)
![image](https://github.com/go-kratos/kratos/assets/48434371/4348a780-a187-4858-ad7a-0ee84ae15efb)
corresponding source code
![image](https://github.com/go-kratos/kratos/assets/48434371/827fe974-9d78-42a0-9174-8e5fcb745d43)

#### Environment:
- Kratos version (use `kratos -v`):2.7.1
- Go version (use `go version`):1.21
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by shenqidebaozi** [comment]
https://github.com/go-kratos/kratos/pull/3146
