### ISSUE TITLE
[Question] The rules before and after loading the configuration file are inconsistent. Can they be improved?

### ISSUE THREAD

**Issue by banfg56** [go-kratos/kratos#3104]
> 文件第一次加载与监听中加载规则不一致

 ## 一、第一次Load配置项的规则

在 config/file/file.go 中行51 会判断当前加载配置配置是目录以及 "." 开头的特殊文件。如果是则忽略

## 二、使用 fsnotify 监控目录变化后加载规则

在  config/file/watcher.go  行55， 直接加载所有文件

## 影响与改进

对于部署在Linux上，在线用vim查看配置文件很不友好。.swp 文件报错，而且整个内容都打印出来。是否能做以下改进：
 [ ] 配置加载时允许指定配置文件格式，比如:json 、ini等
 [ ] .swp类型文件记载规则保持一致 

## 附fsnotify监控目录中vi打开文件场景
![Uploading image.png…]()

**Comment by banfg56** [comment]
附fsnotify监控目录中vi打开文件场景
![Uploading WechatIMG919.jpg…]()

**Comment by CcCJeaz** [comment]
kindly to ask if there is somebody working for this issue? If not, I'm glad to undertake it @banfg56

**Comment by CcCJeaz** [comment]
kindly to ask if there is somebody working for this issue? If not, I'm glad to undertake it @shenqidebaozi

**Comment by shenqidebaozi** [comment]
@CcCJeaz ok
