### ISSUE TITLE
proto. When the field of the query string passed by the front end is an empty string, the field parsed by the back end is nil.

### ISSUE THREAD

**Issue by jeanh0w** [go-kratos/kratos#3117]
#### What happened:
proto中定义optional的字段，当前端传的query string的字段是空字符串时，后端解析到的字段是nil
#### What you expected to happen:
希望后端查询到的字段是非nil
#### How to reproduce it (as minimally and precisely as possible):
proto 定义如下：

message UserDetailReply {
	optional string Status = 1;
}

启动服务，查询接口：http://localhost:8888/?Status=

后端入参：req *pb.UserDetailRequest
打印出 fmt.Println(req.Status) 结果是 nil
希望得到的结果是非nil，*req.Status取到空字符串

#### Anything else we need to know?:
如果当前是 Post 请求，在body里传 {"Status":""}，后端是可以正常得到非nil的 req.Status
当是 Get 请求，query string 里 传 Status=    后端得到的req.Status就是nil

经过调试后发现是如下代码将字段设置为nil：
![CleanShot 2023-12-12 at 18 30 02@2x](https://github.com/go-kratos/kratos/assets/25869212/4d44c58a-6087-4938-9131-34c6957a4ebf)

请问这样设计的原因是什么呢？

#### Environment:
- Kratos version (use `kratos -v`): kratos version v2.7.1
- Go version (use `go version`): go version go1.21.1 darwin/amd64
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by kvii** [comment]
@tonybase Why did you add a `if value == "" { return nil }` is this #2848? It caused this issue. [changes detail](https://github.com/go-kratos/kratos/pull/2428/files#diff-1b842b6fba4c0fe725e057ab1e2cd0fff7a2617b46b4711afe92555a8b84f063)

See the code below, should we return errors in `parseField` when "fd" is a non-string kind and value is ""?

https://github.com/go-kratos/kratos/blob/c7fa51df7ae78935dc1a4cbefe045d6f02a83dcc/encoding/form/proto_decode.go#L116-L126

https://github.com/go-kratos/kratos/blob/c7fa51df7ae78935dc1a4cbefe045d6f02a83dcc/encoding/form/proto_decode.go#L161-L168
