### ISSUE TITLE
Add a scheduled task server, dependency injection error

### ISSUE THREAD

**Issue by tutengdihuang** [go-kratos/kratos#3120]
我想在newApp添加一个我自己写的cron server： cs *server.CronServer
func newApp(logger log.Logger, gs *grpc.Server, hs *http.Server, cs *server.CronServer) *kratos.App {
	return kratos.New(
		kratos.ID(id),
		kratos.Name(Name),
		kratos.Version(Version),
		kratos.Metadata(map[string]string{}),
		kratos.Logger(logger),
		kratos.Server(
			gs,
			hs,
			cs,
		),
	)
}

执行依赖注入报错inject wireApp: no provider found for *invalid type
 provider已经写入： 在server 包中 
var ProviderSet = wire.NewSet(
	NewGRPCServer,
	NewHTTPServer,
	NewCronWorker,
)
请帮忙解决一下或者给一个例子

**Comment by shenqidebaozi** [comment]
Is the injected type the same as the dependent type

**Comment by tutengdihuang** [comment]
> Is the injected type the same as the dependent type

Thanks for your replay, and I have fixed the issue, because of the type problme. And thanks again!
