### ISSUE TITLE
[Question] In the parameter verification section of the middleware in the official kratos documentation, the makefile instruction "Add the validate command in the Makefile" will report an error when copied.

### ISSUE THREAD

**Issue by Forrest-Tao** [go-kratos/kratos#3123]
Please see the FAQ in our main README.md before submitting your issue.
![1702799750716](https://github.com/go-kratos/kratos/assets/112991218/7de0f406-1edf-4733-bb62-78550168c822)

**Comment by Forrest-Tao** [comment]
Ha ha ha, I think I've found a solution. This should have something to do with the makefile plug-in.

**Comment by zishiguo** [comment]
@Forrest-Tao How to solve this question ?

**Comment by Forrest-Tao** [comment]
> @Forrest-Tao How to solve this question ?
之前是和空格有关系，你调整一下空格~
