### ISSUE TITLE
EncodeURL will ignore some fields if request message contains repeated custom message

### ISSUE THREAD

**Issue by CaoYan1** [go-kratos/kratos#3141]
#### What happened:
I defined an RPC method:

```
message MsgInline {
}

message Request {
  string id = 1;
  repeated MsgInline msg = 2;
}

message Response {
}

service MyService {
  rpc Call(Request) returns (Response) {
    option (google.api.http) = {
      post: "/my-api/{id}",
      body: "*",
    };
  }
}
```

And I called it via http client, the id field in url path  was always empty.

#### Anything else we need to know?:
<img width="791" alt="image" src="https://github.com/go-kratos/kratos/assets/28662543/505aa117-14c8-4de7-9d6f-37cb4d6ce46c">

I find that form.EncodeValues(msg) will return error[unsupported message type:] if the request message contains repeated custom message, and ignore the rest fields, then my `id` field is ignored. I think an unsupported field shouldn't make other fields don't work.

#### Environment:
- Kratos version: v2.7.2
- Go version (use `go version`):  1.21.1
- OS (e.g: `cat /etc/os-release`): macos

**Comment by CaoYan1** [comment]
My `Kratos` version is latest(2.7.2) and doesn't work still

**Comment by kvii** [comment]
Can you provide your http client code? I try to reproduce your case, but there was no issue found.

Here is my reproduce [repo](https://github.com/kvii/issue3141).

```sh
# send http request
curl http://localhost:8000/my-api/1 -X POST -H 'Content-Type: application/json' -d '{"msg":[{}]}'

# console
id:"1"  msg:{}

**Comment by CaoYan1** [comment]
Based on your repo, you can try this code. I can reproduce this issue.
'''
func TestHttpClient(t *testing.T) {
	client, _ := http.NewClient(context.Background(), http.WithEndpoint("localhost:8000"))
	c := NewMyServiceHTTPClient(client)
	resp, err := c.Call(context.Background(), &Request{
		Id: "id",
		Msg: []*MsgInline{
			{},
		},
	})
	fmt.Println(resp, err)
}
'''

**Comment by kvii** [comment]
Oh, this is an issue of kratos http client, not server. I pushed a commit to my repo, add tests for this issue at [here](https://github.com/kvii/issue3141/blob/main/internal/data/client_test.go).

Source codes:

* Generated http client side code in my reproduce repo:

https://github.com/kvii/issue3141/blob/dd94e68294372d6194fc440f41021ae4ea7aa98b/api/helloworld/v1/greeter_http.pb.go#L72-L73

* Codes in `binding.EncodeURL`:

https://github.com/go-kratos/kratos/blob/34d9666e0e1bbd8fb74a8b54f5bca0a223c1ebd8/transport/http/binding/encode.go#L15-L19

**Comment by CaoYan1** [comment]
Cool! Do you have a plan to fix it?

**Comment by kvii** [comment]
😭 I'm busy now.

**Comment by CaoYan1** [comment]
I'd like to help you.

**Comment by XiaoK29** [comment]
> Based on the information you've provided, it seems like you're encountering an issue where the `form.EncodeValues(msg)` function is returning an error when it encounters a repeated custom message in your request, causing the rest of the fields to be ignored.

![image](https://github.com/go-kratos/kratos/assets/38639105/0211d51a-aeef-492e-a8e6-c6fbba4f9d8c)
把这个括号删除就没问题了，你这个穿了也没有啥意义吧

**Comment by kvii** [comment]
I've created a PR for this issue. But the code style is terrible.

**Comment by web-xiaxia** [comment]
这个问题 [https://github.com/go-kratos/kratos/pull/2805](#2805) 应该是解决了的
