### ISSUE TITLE
[Question] http API returns json parameter name not as expected

### ISSUE THREAD

**Issue by FPNL** [go-kratos/kratos#3145]
Hi, 
我寫了一個簡單的 http API，預期上所有輸入輸出的 key 命名都以 snake case 為主，並且是以 json 溝通，可是在 response encode 的時候卻不如預期。

後來發現是因為在 package json 中的 codec.Marshal 他判斷型別為 proto.Message，不曉得是透過 proto gen 出 go 檔案時少下什麼指令，還是在 service 大家是如何使用的，才能讓回傳型別為 json.Marshaler？

為了解決這個問題，目前看到有兩個方法

1. 在 main.go 中 init 設置 protozoon.MarshalOptions.UseProtoNames = true
2. 修改 DefaultResponseEncoder

可是既然程式碼裡，Marhson 會判斷是否為 json.Marshaler，代表是有某種方法可以使用，只是我沒想到。

這是 proto
```proto
syntax = "proto3";

package helloworld.v1;

import "google/api/annotations.proto";

option go_package = "helloworld/v1;v1";

service Version {
	rpc Version (VersionRequest) returns (VersionReply) {
		option (google.api.http) = {
			get: "/api/version",
		};
	};
}

message VersionRequest {
	string is_egg = 1;
}
message VersionReply {
	string is_version = 1;
}
```

http response 的內容是
```
{
	"isVersion": "hello"
}
```

internal/service/version.go:
```go
func (s *VersionService) Version(ctx context.Context, req *pb.VersionRequest) (*pb.VersionReply, error) {
	return &pb.VersionReply{IsVersion: req.GetIsEgg()}, nil
}
```

原始碼： github.com/go-kratos/kratos/v2@v2.7.2/encoding/json/json.go:36
```go
func (codec) Marshal(v interface{}) ([]byte, error) {
	switch m := v.(type) {
	case json.Marshaler:
		return m.MarshalJSON()
	case proto.Message:
		return MarshalOptions.Marshal(m)
	default:
		return json.Marshal(m)
	}
}
```

**Comment by shenqidebaozi** [comment]
For a structure defined by protobuf, it will be asserted as proto Message, this is as expected. In addition, for protobuf, protojson is more commonly used as a serialization implementation because it implements protobuf JSON mapping
https://protobuf.dev/programming-guides/proto3/#json

**Comment by FPNL** [comment]
Hi, 

Do you mean to call the `http.ResponseEncoder` method to encode with [protojson](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson)?

Because `pb.RegisterVersionHTTPServer` needs to implement the interface below, I must return a `*pb.VersionReply` struct.
```go
Version(ctx context.Context, req *pb.VersionRequest) (*pb.VersionReply, error)
```

It seems there is no way to import a package in a proto file, or alter my syntax in `version.proto`. Could you please advise?

**Comment by FPNL** [comment]
> For a structure defined by protobuf, it will be asserted as proto Message, this is as expected. In addition, for protobuf, protojson is more commonly used as a serialization implementation because it implements protobuf JSON mapping https://protobuf.dev/programming-guides/proto3/#json

Hi, 

Do you mean to call the `http.ResponseEncoder` method to encode with [protojson](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson)?

Because `pb.RegisterVersionHTTPServer` needs to implement the interface below, I must return a `*pb.VersionReply` struct.
```go
Version(ctx context.Context, req *pb.VersionRequest) (*pb.VersionReply, error)
```

It seems there is no way to import a package in a proto file, or alter my syntax in `version.proto`. Could you please advise?

**Comment by shenqidebaozi** [comment]
@FPNL https://go-kratos.dev/docs/intro/faq/#10%E5%A6%82%E4%BD%95%E6%8E%A7%E5%88%B6-http-%E8%BF%94%E5%9B%9E%E7%9A%84%E5%AD%97%E6%AE%B50%E5%80%BC%E5%BF%BD%E7%95%A5%E5%AD%97%E6%AE%B5%E5%92%8C%E4%BD%BF%E7%94%A8proto%E7%9A%84message%E5%AD%97%E6%AE%B5%E4%BD%9C%E4%B8%BAhttp%E7%9A%84%E8%BF%94%E5%9B%9E%E5%AD%97%E6%AE%B5

**Comment by FPNL** [comment]
了解了，感謝你花時間回應
