### ISSUE TITLE
使用openapiv2,出现protoc-gen-openapiv2/options/annotations.proto: File not found.

### ISSUE THREAD

**Issue by swurtheone** [go-kratos/kratos#3156]
kratos目前仅支持openapiv2,但是按照官方示例，出现以下问题：
api目录中的proto文件
![image](https://github.com/go-kratos/kratos/assets/31538827/f5c561d4-c686-434d-9b63-8d6374e4ae4c)

third_part已添加protoc-gen-openapiv2
![image](https://github.com/go-kratos/kratos/assets/31538827/6e1aa7ca-0d07-41cc-a13b-b2400ec6b23d)

执行kratos proto client message.proto

![image](https://github.com/go-kratos/kratos/assets/31538827/89953e28-46e2-4575-b354-5a714531c469)

**Comment by kvii** [comment]
看你执行 kratos proto client 的方法，你应该是没有在工程根目录执行命令。我尝试着按你图中的方式搭了个工程，果然复现出了相同的报错。

问题解决方式也很简单，在工程根目录执行命令就行了。也可以直接在工程根目录执行 `make api` 生成代码。[工程链接](https://github.com/kvii/issue_3156) 在这里。

另外说一句，如果您能在提交 issue 的时候像这样给出一个最小复现的工程的话，也会减少别人复现和定位问题的时间。如果这个问题您已经解决了的话，也希望您能及时关闭这个 issue。这样也不会让别人白费力气。
