### ISSUE TITLE
Unable to customize http.ResponseWriter because of wrong implementation of Kratos' http.wrapper.Result()

### ISSUE THREAD

**Issue by xbchaos** [go-kratos/kratos#3174]
#### What happened:

i implemented `ResponseWriter` of `net/http` and use it in a custom Filter, but in my custom ResponseEncoder, the type assertion code below will fail:

`customResponseWriter := w.(*CustomResponseWriter)`

finally, i found that, in Kratos' `http.wrapper.Result()`, `wrapper.res` (which is right actually my custom ResponseWriter) is not used, instead, `wrapper.w` is used:

```
func (c *wrapper) Result(code int, v interface{}) error {
	c.w.WriteHeader(code)
	return c.router.srv.enc(&c.w, c.req, v)
}
```

and what's more, we can see any other method of the wrapper, like `JSON()` or `XML()`, they just use `wrapper.res`:

```
func (c *wrapper) JSON(code int, v interface{}) error {
	c.res.Header().Set("Content-Type", "application/json")
	c.res.WriteHeader(code)
	return json.NewEncoder(c.res).Encode(v)
}

func (c *wrapper) XML(code int, v interface{}) error {
	c.res.Header().Set("Content-Type", "application/xml")
	c.res.WriteHeader(code)
	return xml.NewEncoder(c.res).Encode(v)
}
```

so, i'm wondering, the `Result()` method of `wrapper` should use `wrapper.res` too, just like other methods.

#### What you expected to happen:

`http.wrapper.Result()` changed to:

```
func (c *wrapper) Result(code int, v interface{}) error {
	c.res.WriteHeader(code)
	return c.router.srv.enc(c.res, c.req, v)
}
```

#### Environment:
- Kratos version (use `kratos -v`): 2.1
- Go version (use `go version`): 1.20
- OS (e.g: `cat /etc/os-release`): macOS
- Others:

**Comment by kvii** [comment]
我看完源码后猜测可能是因为这个原因：

1. 仔细看 responseWriter 类型的方法，它实现了一个类似于“缓存响应码”的功能。
https://github.com/go-kratos/kratos/blob/a556a2b531202edc57f8b877b4d4ffbcc018ee6c/transport/http/context.go#L55-L59

2. 这是 Result 方法，可以看到和其他方法相比，如 "JSON"，它缺少了设置 "Content-Type" 响应头的步骤，直接设置了响应码。
https://github.com/go-kratos/kratos/blob/a556a2b531202edc57f8b877b4d4ffbcc018ee6c/transport/http/context.go#L110-L113

3. 在默认的 enc 函数中操作了 header，根据数据类型添加了对应响应头。
https://github.com/go-kratos/kratos/blob/a556a2b531202edc57f8b877b4d4ffbcc018ee6c/transport/http/codec.go#L98

4. go 源码中 ResponseWriter 的 Header 的注释中说了，设置了响应码之后，Header 的更改就无效了。
https://github.com/golang/go/blob/f719d5cffdb8298eff7a5ef533fe95290e8c869c/src/net/http/server.go#L99-L101

所以我推测，是因为必须在 Result 等方法中先设置响应码。而先设置响应码会导致响应头的修改无效。所以才有了 responseWriter。不过不论如何，这里肯定有问题就是了，起码 c.res 和 c.w 不应该同时存在。

**Comment by kvii** [comment]
@xbchaos Use can use the code below when kratos version >= v2.7.3 to get the underlying custom writer that you've set before:
If you think this code can solve your problem, remember to close this issue.
PR reference: #3265

```go
package main

import (
	"context"
	"fmt"
	"io"
	nt "net/http"
	"net/http/httptest"

	"github.com/go-kratos/kratos/v2/middleware"
	"github.com/go-kratos/kratos/v2/transport/http"
)

type customWriter struct {
	http.ResponseWriter
}

func main() {
	s := http.NewServer(
		http.Middleware(func(h middleware.Handler) middleware.Handler {
			return func(ctx context.Context, req any) (any, error) {
				hc := ctx.(http.Context)
				hc.Reset(customWriter{hc.Response()}, hc.Request()) // reset response writer
				return h(ctx, req)
			}
		}),
		http.ResponseEncoder(func(w http.ResponseWriter, r *http.Request, v any) error {
			// get underlying response writer
			var ok bool
			under := w
		out:
			for {
				switch cur := under.(type) {
				case customWriter:
					under = cur
					ok = true
					break out
				case interface{ Unwrap() http.ResponseWriter }:
					under = cur.Unwrap()
				default:
					break out
				}
			}
			return http.DefaultResponseEncoder(w, r, ok)
		}),
	)

	// simulate what happened in xx_http.pb.go
	s.Route("/").GET("/a", func(ctx http.Context) error {
		h := ctx.Middleware(func(ctx context.Context, req any) (any, error) {
			return nil, nil
		})
		out, _ := h(ctx, nil)
		return ctx.Result(200, out)
	})

	w := httptest.NewRecorder()
	r := httptest.NewRequest(nt.MethodGet, "/a", nil)
	s.ServeHTTP(w, r)
	res := w.Result()
	defer res.Body.Close()

	bs, _ := io.ReadAll(res.Body)
	fmt.Println(string(bs)) // true
}
```
