### ISSUE TITLE
Issue with configuration file to render the values from environment variables

### ISSUE THREAD

**Issue by akoserwal** [go-kratos/kratos#3198]
#### What happened:

There is an issue with the configuration file to render the values from environment variables.

 I am setting endpoint as environment variable
export TEST_ENDPOINT=localhost:8081

Setting $TEST_ENDPOINT in the config file.

```config.yaml
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  testDb:
    endpoint: "$TEST_ENDPOINT"
```

main.go
```
c := config.New(
		config.WithSource(
			env.NewSource("TEST_"),
			file.NewSource(flagconf),
		),
	)
	defer c.Close()

	if err := c.Load(); err != nil {
		panic(err)
	}
```

The environment variable gets resolved with KEY: "ENDPOINT," but it doesn't override the key value as "data.testDB.endpoint."

#### What you expected to happen:

Environment variable to get resolved as key value as "data.testDB.endpoint."

#### Environment:
- Kratos version (use `kratos -v`): v2.7.2
- Go version (use `go version`): 1.19-1.21
- OS (e.g: `cat /etc/os-release`):Mac os
- Others:

**Comment by kvii** [comment]
I think here is a bug. Consider to change "$TEST_ENDPOINT" to "${ENDPOINT}" to avoid this temporary.

I made a reproduce project at local. Some of key codes:

```yaml
server:
  http:
    addr: "${ADDR}"
```

```go
c := config.New(
	config.WithSource(
		env.NewSource("TEST_"),
		file.NewSource(flagconf),
	),
)
c.Load()

var bc conf.Bootstrap
c.Scan(&bc)

fmt.Println(bc.Server.Http.Addr)
fmt.Println(c.Value("ADDR").String())
fmt.Println(c.Value("server.http.addr").String())
```

After I execute `export TEST_ADDR=0.0.0.0:8000`, codes run properly(print "0.0.0.0:8000").

I guess there has some mistakes of the format of placeholder. The comment say that the correct format is "${key:default}".

https://github.com/go-kratos/kratos/blob/9106991c0931dafbab53495d954054358f3006f7/config/options.go#L85-L97

**Comment by kvii** [comment]
It's a mistake of doc. kratos don't support "$key" format by default. I found this test:

https://github.com/go-kratos/kratos/blob/9106991c0931dafbab53495d954054358f3006f7/config/options_test.go#L133-L136

**Comment by akoserwal** [comment]
Thanks, @kvii, for clarifying. 

It works if the export TEST_ADDR=0.0.0.0:8000 and use fmt.Println(bc.Server.Http.Addr)

**For boolean, I am getting**

Error
panic: proto: (line 1:133): invalid value for bool type: "true"

data:
  test:
    endpoint: "${ENDPOINT}"
    useTLS: "${TLS:false}"


export TEST_TLS=true

**Comment by kvii** [comment]
Same issue at #1565. Unfortunately, non-string types are not supported in `Scan` because that will include more complexity. You can use `c.Value("data.test.useTLS").Bool()` to get the bool value explicitly. But I think this doesn't match your case.

**Comment by akoserwal** [comment]
Issue is still relevant, I have PR opened to fix this issue
