### ISSUE TITLE
[Question] How to return other Status Code in a successful HTTP request?

### ISSUE THREAD

**Issue by init-center** [go-kratos/kratos#3227]
Now all successful requests return 200 status codes. What if some apis want to return 201 status codes?

**Comment by shenqidebaozi** [comment]
@init-center As with @dosu-bot reply, you can return a custom status by rewriting the response encoder, but you may need to pass the identifier in ctx

**Comment by kvii** [comment]
@init-center Refer this [gist](https://gist.github.com/kvii/94cf3a1ef9d7cc09f2417781f2e4f8a9).

**Comment by init-center** [comment]
> @init-center Refer this [gist](https://gist.github.com/kvii/94cf3a1ef9d7cc09f2417781f2e4f8a9).

Thank you.
