### ISSUE TITLE
[Feature] replace kratos metrics with otel metrics

### ISSUE THREAD

**Issue by shenqidebaozi** [go-kratos/kratos#3255]
The current `otel metrics` have been officially released, and Kratos currently does not need to continue maintaining custom abstractions.

Requirement:

- [ ]  Delete the current `metrics` interface
- [ ] Implement `middleware/metrics` using otel metrics

I submitted a PR before #2831, but at that time, the `otel metrics` feature was incomplete. You can use it as a reference.

**Comment by Ccheers** [comment]
assin me
