### ISSUE TITLE
Package version dependency issue

### ISSUE THREAD

**Issue by towithyou** [go-kratos/kratos#3273]
#### Environment:
- Kratos version (use `kratos -v`): kratos version v2.6.2
- Go version (use `go version`): go version go1.19 darwin/arm64 
- OS (e.g: `cat /etc/os-release`): mac m2 arm64
- Others:

**Comment by towithyou** [comment]
我们的服务调用  gcp api 时，他的包依赖 google.golang.org/grpc@v1.63.0, kratos 依赖 google.golang.org/grpc@v1.63.0 v1.46.2. 倒是包引用冲突

go mod tidy
go: finding module for package google.golang.org/grpc/test/grpc_testing
go: downloading google.golang.org/grpc v1.63.0
repo.xxxxxx.net/devops/a-cloud/workflow/controller imports
        repo.xxxxxx.net/devops/a-cloud/pkg/middleware imports
        github.com/go-kratos/kratos/v2/errors tested by
        github.com/go-kratos/kratos/v2/errors.test imports
        google.golang.org/grpc/test/grpc_testing: module google.golang.org/grpc@latest found (v1.63.0), but does not contain package google.golang.org/grpc/test/grpc_testing

**Comment by shenqidebaozi** [comment]
Google has removed this package and can upgrade to the Kratos version
https://github.com/go-kratos/kratos/pull/2824
