### ISSUE TITLE
go generate ./...failed

### ISSUE THREAD

**Issue by liu124** [go-kratos/kratos#3299]
![企业微信截图_17137690656900](https://github.com/go-kratos/kratos/assets/29817248/ef9736f8-31fd-406f-ad61-0dbd7fad96f5)

![企业微信截图_1713769139273](https://github.com/go-kratos/kratos/assets/29817248/3d73d45e-21cd-435a-a7bb-1e150c2fb99f)

**Comment by kvii** [comment]
没看见哪里出问题了。那个 "wire: helloworld……" 那一行是正常的控制台输出。

**Comment by noovertime7** [comment]
正常的，没有报错
