### ISSUE TITLE
[Feature]Add svrType related fields in proto to protoc-gen-go-http and http transport

### ISSUE THREAD

**Issue by MichealJl** [go-kratos/kratos#3301]
Please see the FAQ in our main README.md before submitting your issue.

### What problem is the feature used to solve?

有些场景（如需要根据每个svr名称做不同模块的权限管理）中需要获取proto中的svr名称
如果是自己定义常量与transport中operation提取出来的srv名称对比，那么proto的srv名称发生变化时可能导致判断错误

我们是否能支持这个功能

### Requirements description of the feature
在 Transport中添加svrType设置和获取的相关方法

![image](https://github.com/go-kratos/kratos/assets/31276367/3847ed6c-31ae-4442-92ec-c2d27101f387)
![image](https://github.com/go-kratos/kratos/assets/31276367/f7dbbe15-7a7c-434f-bc1d-6fd25dd0fd42)
![image](https://github.com/go-kratos/kratos/assets/31276367/996fb7ec-eade-4fc7-bab2-fa8d3bd52033)

**Comment by shenqidebaozi** [comment]
This is not a good design. According to the philosophy of GRPC, idl ensures that client and server calls are correct. You should not directly modify the method name, as it will cause code incompatibility. The client and server cannot call properly.

**Comment by MichealJl** [comment]
@shenqidebaozi 

那抛开 方法被修改的场景不谈，就是单纯的想获取Svr名称可行么，目前是根据当前transport中的operation分割两次获取的
