### ISSUE TITLE
consul watch, the server is offline and will not receive any notification

### ISSUE THREAD

**Issue by noovertime7** [go-kratos/kratos#3310]
#### What happened: 
使用consul作为注册中心，当服务端离线时并不会收到任何通知，无法触发离线的回调

#### What you expected to happen:
服务端离线使用watch收到通知

#### Anything else we need to know?:
使用etcd是可以的

#### Environment:
- Kratos version (use `kratos -v`):kratos version v2.7.3
- Go version (use `go version`): go version go1.21.2 darwin/arm64
- OS (e.g: `cat /etc/os-release`): mac book
- Others:

**Comment by noovertime7** [comment]
![image](https://github.com/go-kratos/kratos/assets/100392073/8cfa6eb0-57e5-4828-889d-5ce2dfb5aefd)
只有服务端上线时会收到消息，离线不会

**Comment by shenqidebaozi** [comment]
I'm not sure what you're referring to. I've been using this feature all along. Please provide a complete explanation or reproduce an example
