### ISSUE TITLE
[Feature] Add NewClient method to gRPC Client

### ISSUE THREAD

**Issue by shenqidebaozi** [go-kratos/kratos#3312]
Please see the FAQ in our main README.md before submitting your issue.

### What problem is the feature used to solve?
In the new version of gRPC, the `NewClient` method has been added, and the Dials will be discarded in the future. Therefore, it is necessary to add the `NewClient` method to the `kratos gRPC client` and discard the `Dial` tag.

**Comment by Ccheers** [comment]
assign me

**Comment by vaisakh-prod** [comment]
@shenqidebaozi I would like to give it a try

**Comment by fengyuwusong** [comment]
I would like to do this, please assign for me.
