### ISSUE TITLE
[Question] DDD的最佳实践方式？包括CQRS、Clean Architecture、六边形结构

### ISSUE THREAD

**Issue by WangX0111** [go-kratos/kratos#3314]
Please see the FAQ in our main README.md before submitting your issue.
在go-kratos中DDD的最佳实践方式是什么 ？
包括CQRS、Clean Architecture、六边形结构该如何引入

CQRS的分离应该在哪一层？或者更进一步，DDD的app层在go-kratos中如何体现

**Comment by moocss** [comment]
您可以看一下 https://go-kratos.dev/docs/intro/layout  项目结构, 就可以窥探一二; 我自己认为 DDD 没有最佳实战,  结合自己的项目经验和DDD理论, 完全可以找到一种适合自己的DDD最佳实战.
