### ISSUE TITLE
如何输出执行的sql 语句

### ISSUE THREAD

**Issue by gstormlee** [go-kratos/kratos#332]
执行sql 语句后，如何输出执行的sql语句。

**Comment by Terry-Mao** [comment]
需要一个debug database/sql的功能？

**Comment by gstormlee** [comment]
是的，是否可以输出当前执行的sql， 我没有找到办法。

**Comment by huanghe2015** [comment]
之前阿里安全部给工程技术团队提出一个需求就是记录每一条执行的SQL，不知道这里后面能不能实现。

**Comment by UnderTreeTech** [comment]
@Ehco1996 输出的SQL语句为什么不使用函数调用传递的context，而生成一个background context，这样的话SQL无法跟某次trace挂钩上了；或者完整SQL可以直接输出在trace.setTag里，目前只打了query没打args而已。

**Comment by huanghe2015** [comment]
args的安全性是个问题。。。
