### ISSUE TITLE
[Question]请教下kratos如何定义支持上传文件接口？

### ISSUE THREAD

**Issue by BgLuozhou** [go-kratos/kratos#3321]
报错
{
    "code": 400,
    "reason": "CODEC",
    "message": "unregister Content-Type: multipart/form-data; boundary=--------------------------332724899722898083179164",
    "metadata": {}
}

**Comment by Windfarer** [comment]
https://github.com/go-kratos/examples/blob/main/http/upload/main.go

**Comment by xu6jin** [comment]
func uploadRequestDecoder(r *http.Request, v interface{}) error {
	filename := r.FormValue("filename")
	file, _, err := r.FormFile("file")
	if err != nil {
		return err
	}
	defer file.Close()
	data, err := io.ReadAll(file)
	if err != nil {
		return err
	}
	if _, ok := v.(*baseMessage.UploadRequest); ok {
		v.(*baseMessage.UploadRequest).File = &baseMessage.File{Name: filename, Data: data}
	}
	return nil
}

func DefaultRequestDecoder(uploadOperations ...string) http.ServerOption {
	return http.RequestDecoder(func(r *http.Request, v interface{}) error {
		if transporter, ok := transport.FromServerContext(r.Context()); ok && slices.Contains(uploadOperations, transporter.Operation()) {
			return uploadRequestDecoder(r, v)
		}
		codec, _ := http.CodecForRequest(r, "Content-Type")
		// if !ok {
		// 	return errors.BadRequest("CODEC", fmt.Sprintf("unregister Content-Type: %s", r.Header.Get("Content-Type")))
		// }
		data, err := io.ReadAll(r.Body)
		r.Body = io.NopCloser(bytes.NewBuffer(data))
		if err != nil {
			return errors.BadRequest("CODEC", err.Error())
		}
		if len(data) == 0 {
			return nil
		}
		if err = codec.Unmarshal(data, v); err != nil {
			return errors.BadRequest("CODEC", fmt.Sprintf("body unmarshal %s", err.Error()))
		}
		return nil
	})
}
