### ISSUE TITLE
metrics statistics and usage issues [Question]

### ISSUE THREAD

**Issue by xuxiaoxia96** [go-kratos/kratos#3322]
使用kratos的服务后台可能是分布式的，并且随机hash到某一个节点。
但是现在内存收集的metric都是单机的数据，分布式情况会不会统计出现问题呢？

**Comment by Windfarer** [comment]
kratos收集和暴露的是当前实例的数据，通常的实践是用prometheus收集各实例的数据，进行后续的处理

**Comment by harbourlga** [comment]
想要采集到所有实例的数据，你可以把你的服务都注册到像consul这种服务注册中心。然后prometheus直接获取注册中心的注册实例去采集这样就不会遗漏数据了
