### ISSUE TITLE
`stream` response in proto failed to generate http client

### ISSUE THREAD

**Issue by akoserwal** [go-kratos/kratos#3324]
#### What happened:

``` 
rpc Subject(TestRequest) returns (stream TestResponse) {
        option (google.api.http) = {
            get: "/v1/subjects"
        };
    };
```
Running 
kratos proto client api/helloworld/demo.proto

doesn't generate only _grpc.pb.go

`_http.pb.go` 

#### What you expected to happen:

generate HTTP and grpc client

#### How to reproduce it (as minimally and precisely as possible):

Add `stream` response

#### Environment:
- Kratos version (use `kratos -v`): kratos version v2.7.3
- Go version (use `go version`): go version go1.22.3 
- OS (e.g: `cat /etc/os-release`): darwin/arm64
- Others:

**Comment by lonetrail** [comment]
http client is not supported yet. #1958 #2896

**Comment by shenqidebaozi** [comment]
HTTP has not yet thought of a good abstraction to implement one-way and two-way stream

**Comment by akoserwal** [comment]
That's true. Is it possible to handle the stream case like: grpc-gatewat https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/httpbody_messages/ ?

**Comment by shenqidebaozi** [comment]
> That's true. Is it possible to handle the stream case like: grpc-gatewat https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/httpbody_messages/ ?

I need some time to study it

**Comment by akoserwal** [comment]
Example project to showcase adding an HTTP handler for the gRPC stream endpoint: https://github.com/akoserwal/stream-ex-kratos/blob/main/internal/server/http.go#L40
@shenqidebaozi

**Comment by shenqidebaozi** [comment]
@akoserwal Let me take a look
