### ISSUE TITLE
I a new release due soon ?

### ISSUE THREAD

**Issue by slashformotion** [go-kratos/kratos#3344]
Dear @Ccheers , @wudi, @demoManito, @guoquanwei, @kvii, @ASkyFullOfStar ,

Firstly, I would like to express my appreciation for your framework. It has been instrumental in our professional work and my team and I are extremely satisfied with it.

We are keen to understand the timeline for the next release. Our interest stems from the observation that some dependencies have not been updated for a considerable time. For instance, Kratos v2.7.3, which was released on March 22, relies on zap v1.23.

Our project necessitates a more recent version of zap, which unfortunately makes it incompatible with the excellent kratoszap package that you offer.

Could you kindly provide some insight into the release roadmap for Kratos? We are eager to continue leveraging your framework and believe that this information will greatly assist us in planning our project.

Thank you for your time and consideration.

Best Regards, Théophile.

**Comment by kvii** [comment]
@shenqidebaozi It's your turn.

**Comment by shenqidebaozi** [comment]
Are you referring to https://github.com/go-kratos/kratos/tree/main/contrib/log/zap ？

**Comment by slashformotion** [comment]
Yes

**Comment by shenqidebaozi** [comment]
The problem has been closed, has it already been resolved?
