### ISSUE TITLE
[Question] Can I custom project layouts by using kratos to generate

### ISSUE THREAD

**Issue by TremblingV5** [go-kratos/kratos#3346]
I'm new to kratos and it look very great ! I think I will like it.

I know that I can use `kratos new` to generate a project layout. So can I use some other parameters or configuration files to custome the layout which generated by me? I read documents of kratos but I'm havn't found infomations about this question.

**Comment by shenqidebaozi** [comment]
Currently, only layout can be specified. 
`kratos new -r xxxx`
