### ISSUE TITLE
[Question]Excuse me, what is the error when compiling?

### ISSUE THREAD

**Issue by amoyx** [go-kratos/kratos#3347]
执行 make init 的时候报错
Makefile如下：
![makefile](https://github.com/go-kratos/kratos/assets/19795002/a1ba8cdd-15d6-4ded-9af2-d09de59a2362)

报错内容如下：
![errors](https://github.com/go-kratos/kratos/assets/19795002/5eab2deb-585c-4a08-b595-2f1570ea5986)

请问要怎么处理？

**Comment by shenqidebaozi** [comment]
gRPC has incompatible updates, please upgrade to Kratos version

**Comment by amoyx** [comment]
> gRPC has incompatible updates, please upgrade to Kratos version

是指升级Makefile中 go install github.com/go-kratos/kratos/cmd/kratos/v2@latest 这里的版本？

**Comment by kvii** [comment]
@amoyx 指的是升级 go.mod 里的版本。Makefile 里的那句代码的意思是“下载最新版本的 kratos 命令行生成工具“。这个工具和你依赖的 kratos 库不严谨地说，不是一个东西。

看你的命令行日志的最后几行。你实际上执行的应该是 `make all`，然后 `make all` 里调用的 `make generate` 导致的错误。从头到尾和 `make init` 没有半毛钱关系。
