### ISSUE TITLE
[Question]how to get all router

### ISSUE THREAD

**Issue by kissIce** [go-kratos/kratos#3366]
<img width="1094" alt="image" src="https://github.com/user-attachments/assets/c80dd876-cb64-4037-bc9e-4c9fdf805b76">
 

how to get all api router and method. in my project i use casbin and it need set Policy. so i want get all api router and method then show it on page. and then set api Policy for everybody.     i try find doc in website but canot get it.    is anyone can help me? thk

**Comment by lemon-1997** [comment]
gRPC reflect？

**Comment by shenqidebaozi** [comment]
https://github.com/go-kratos/kratos/pull/2181
