### ISSUE TITLE
[Question] Error: no_available_node

### ISSUE THREAD

**Issue by qing-turnaround** [go-kratos/kratos#3374]
在进行RPC调用的时候，偶尔会出现no_available_node的错误，完整的错误消息是： code = 503 reason = no_available_node message =  metadata = map[] cause = <nil> 

我们公司时使用consul作为服务发现和服务注册中心，当我在grpc.DialInsecure方法中增加WithNodeFilter选项函数后，就偶尔会报错no_available_node，想问应该使用什么样的参数可以尽量避免rpc调用的时候报错no_available_node（服务是一直注册在consul上的）

**Comment by harbourlga** [comment]
![image](https://github.com/user-attachments/assets/0bd5cee9-cc71-44cf-a4ed-abb2a59502b9)
这个八成是你的nodefilter方法出问题了，导致没有可用的节点就会报这个错

**Comment by qing-turnaround** [comment]
> ![image](https://private-user-images.githubusercontent.com/41185605/349865598-0bd5cee9-cc71-44cf-a4ed-abb2a59502b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTMwNTcsIm5iZiI6MTcyMTI5Mjc1NywicGF0aCI6Ii80MTE4NTYwNS8zNDk4NjU1OTgtMGJkNWNlZTktY2M3MS00NGNmLWE0ZWQtYWJiMmE1OTUwMmI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA4NTIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZDYxYjgzOWI3ODRlNjM5ZWE3YzBjZTIwYzM1OGYwOGQ2MGM1ZjgzZWYxYzYyNjdlOTA1Mzk1YzEyZmEzZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1q8mHaMXogPXGykimxO4twKSAVxu8qZKHB0Wg7yOfeQ) 这个八成是你的nodefilter方法出问题了，导致没有可用的节点就会报这个错


感谢回答，我补充一下其他信息哈~
在调用我的nodeFilter函数的时候，我会先打印当前获取到的节点数量，也就是图上对应的服务发现获取到的节点

日常的话，这个值为4，当报错no_available_node时，这个值为1，所以这里我是排除我nodeFilter函数的问题


因为这个错误是不频繁的，nodeFilter函数应该每次RPC调用都会使用吧

这里有没有可能是网络的问题，导致从consul没有获取的信息有误呢

**Comment by harbourlga** [comment]
建议贴个数据和nodeFilter代码

**Comment by shenqidebaozi** [comment]
I guess you made the call immediately after initialization was completed. If there are multiple instances of a load balancer, there is an uncontrollable order in which connections are established with each instance. When called, as long as there are available instances, they will be used directly.

**Comment by shenqidebaozi** [comment]
So your filter should not submit empty results. Or wait for a period of time after initialization before using it again.

**Comment by shenqidebaozi** [comment]
```
// regeneratePicker takes a snapshot of the balancer, and generates a picker
// from it. The picker is
//  - errPicker if the balancer is in TransientFailure,
//  - built by the pickerBuilder with all READY SubConns otherwise.
func (b *baseBalancer) regeneratePicker() {
   if b.state == connectivity.TransientFailure {
      b.picker = NewErrPicker(b.mergeErrors())
      return
   }
   readySCs := make(map[balancer.SubConn]SubConnInfo)
 
   // Filter out all ready SCs from full subConn map.
   for _, addr := range b.subConns.Keys() {
      sci, _ := b.subConns.Get(addr)
      sc := sci.(balancer.SubConn)
      if st, ok := b.scStates[sc]; ok && st == connectivity.Ready {
         readySCs[sc] = SubConnInfo{Address: addr}
      }
   }
 
 
   b.picker = b.pickerBuilder.Build(PickerBuildInfo{ReadySCs: readySCs})
}
```

**Comment by qing-turnaround** [comment]
> 建议贴个数据和nodeFilter代码

ok，下面是我的grpc Dail代码，包括filter逻辑，我每一个节点注册到consul，都会在metadata里面写入当前服务所处的sub_env

然后服务发现的时候，只去访问对应相同sub_env的环境

package main

import (
	"github.com/go-kratos/kratos/contrib/registry/consul/v2"
	"github.com/go-kratos/kratos/v2/config"
	"github.com/go-kratos/kratos/v2/selector"
	"github.com/go-kratos/kratos/v2/selector/wrr"
	KGrpc "github.com/go-kratos/kratos/v2/transport/grpc"
	"golang.org/x/net/context"
	"google.golang.org/grpc"
	"time"
)

func DialInsecureByServiceName(serviceName string, subEnv string) (*grpc.ClientConn, error) {

	selector.SetGlobalSelector(wrr.NewBuilder())
	conn, err := KGrpc.DialInsecure(
		context.Background(),
		KGrpc.WithEndpoint("discovery:///"+serviceName),
		KGrpc.WithDiscovery(ClientReg),
		KGrpc.WithNodeFilter(SubEnvFilter(subEnv)), // Filter nodes by sub environment
		KGrpc.WithTimeout(10*time.Second),          // Connection timeout
	)
	if err != nil {
		return nil, err
	}
	return conn, nil
}

const subEnvName = "SUB_ENV"

func SubEnvFilter(subEnv string) selector.NodeFilter {
	if subEnv == "" {
		return func(_ context.Context, nodes []selector.Node) []selector.Node {
			// If the sub environment is empty, return all nodes
			return nodes
		}
	} else {
		//If the sub environment is not empty, return the node corresponding to the sub environment
		return func(_ context.Context, nodes []selector.Node) []selector.Node {
			newNodes := make([]selector.Node, 0)
			nodeMetadataString := make([]string, len(nodes))
			for i, n := range nodes {
				nodeMetadataString[i] = n.Metadata()[subEnvName]
				//Retrieve sub environment information from metadata
				if n.Metadata()[subEnvName] == subEnv {
					// Complies with the current sub-env and is added to the new node list
					newNodes = append(newNodes, n)
				}
			}
			logger.AtLog.Infof("consul sub env filter: %s, new node count: %d, node sub_env metadata: %v", subEnv, len(newNodes), nodeMetadataString)
			// Return the new node list
			return newNodes
		}
	}
}

var ClientReg *consul.Registry

// Initialize Consul client
func InitConsulClient(env string, conf config.Config) error {
	// get config
	consulConfig, err := getConsulConfig(env, conf)
	if err != nil {
		return err
	}

	c, err := api.NewClient(consulConfig)
	if err != nil {
		return err
	}
	ClientReg = consul.New(c)
	return nil
}

**Comment by shenqidebaozi** [comment]
> I guess you made the call immediately after initialization was completed. If there are multiple instances of a load balancer, there is an uncontrollable order in which connections are established with each instance. When called, as long as there are available instances, they will be used directly.

@qing-turnaround The reason has already been replied here. Your code did not have a fallback logic and submitted an empty instance list

**Comment by qing-turnaround** [comment]
你说的 fallback logic是指什么

> > I guess you made the call immediately after initialization was completed. If there are multiple instances of a load balancer, there is an uncontrollable order in which connections are established with each instance. When called, as long as there are available instances, they will be used directly.
> 
> @qing-turnaround The reason has already been replied here. Your code did not have a fallback logic and submitted an empty instance list


感谢回答🙇‍，但这里说我没有设置兜底逻辑是什么意思呢？还有返回了一个空节点列表

我认为是 调用我的filter函数的时候，kratos就会传入所有当前可用节点，然后通过我里面写的过滤sub_env的节点，从而返回可使用的节点，但是有时候kratos传入的节点数少于 当前consul可用节点数

**Comment by shenqidebaozi** [comment]
The instance list obtained by Kratos is provided by grpc base balancer, and its logic is to submit to downstream as long as there are available instances when calling, instead of waiting for all instances to be ready before submitting. The code has already been replied to above.

**Comment by shenqidebaozi** [comment]
So due to mechanism reasons, calling directly after connection initialization may result in not being able to obtain all instances for a period of time, as the completion time of the load balancer and all instances connected separately is different. So you should add a fallback in your logic to avoid submitting empty lists. Or wait for a period of time after initialization before using it. This waiting time does not need to be very long, you can try it. In addition, it cannot be used in a short connection mode, which means creating a connection and calling it again every time it is called. Instead, the same connection should be persistently used
