### ISSUE TITLE
kratos proto client api/helloworld/v2 fail?

### ISSUE THREAD

**Issue by williamtse** [go-kratos/kratos#3381]
#### What happened:
kratos proto client api/helloworld/v2
go install github.com/go-kratos/kratos/cmd/kratos/v2@latest
go install github.com/go-kratos/kratos/cmd/protoc-gen-go-http/v2@latest
go install github.com/go-kratos/kratos/cmd/protoc-gen-go-errors/v2@latest
go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
go: google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest (in google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.0):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
exit status 1

#### How to reproduce it (as minimally and precisely as possible):
kratos proto client api/helloworld/v2
#### Environment:
- Kratos version (use `kratos -v`):kratos version v2.8.0
- Go version (use `go version`):go version go1.22.0 windows/amd64
- OS (e.g: `cat /etc/os-release`):windows/amd64
- Others:

**Comment by lonetrail** [comment]
Protoc-gen-go-grpc v1.5.0 is incompatible with `go install command`. Updating to the latest version v1.5.1, should fix this issue.

[Protoc-gen-go-grpc 1.5.1 release note](https://github.com/grpc/grpc-go/releases/tag/cmd%2Fprotoc-gen-go-grpc%2Fv1.5.1) mentioned this issue.
