### ISSUE TITLE
[Question] How to define 4xx, 5xx response codes in openapi spec generate from proto definitions

### ISSUE THREAD

**Issue by akoserwal** [go-kratos/kratos#3404]
I see a way to definite error codes, but it doesn't update the open API spec generation with HTTP error codes
https://go-kratos.dev/en/docs/component/errors

**Comment by kvii** [comment]
If I were you, I would prefer to add a comment to the rpc api, like below:

```proto
// GetUser return a user. It will return an error with reason "USER_NOT_FOUND" when user is not found.
rpc GetUser (GetUserRequest) returns (GetUserReply)
```
