### ISSUE TITLE
[Question] kratos generation pb file with omitempty tag

### ISSUE THREAD

**Issue by yyfyfyang** [go-kratos/kratos#3427]
<img width="1298" alt="image" src="https://github.com/user-attachments/assets/d9b0a9f9-2d32-4001-b39e-05061fa501ab">

`kratos proto client `生成的pb文件带有omitempty标签导致序列化的时候会忽略空值和默认值，怎么样可以在生成pb文件的时候不带这个标签

**Comment by shenqidebaozi** [comment]
This has nothing to do with kratos, it is the default behavior after compiling with `protoc-gen-go`, and it should not be removed. `protojson supports keeping null values.

**Comment by shenqidebaozi** [comment]
If you forcefully nested non proto structures outside the proto structure yourself, please refer to #1952
