### ISSUE TITLE
[BUG]Wrong parsing of config, when using config.Scan

### ISSUE THREAD

**Issue by godcong** [go-kratos/kratos#3439]
#### What happened:
The default output of toml is configured in UpperCase, which is converted to `map=>json` during transmission.
But proto's json supports the format of snake_case.
Eventually the `json=>Config` parsing fails.

```
flagconf, _ = filepath.Abs(flagconf)
	fmt.Println("load config at:", flagconf)

	client, err := api.NewClient(&api.Config{
		Address: "host:8500",
	})
	if err != nil {
		panic(err)
	}
	fs := file.NewSource(flagconf)
	kvs, err := fs.Load()
	if err != nil {
		panic(err)
	}

	for _, kv := range kvs {
		fmt.Println("key:", kv.Key)
		_, err := client.KV().Put(&api.KVPair{Key: "configs/" + kv.Key, Value: kv.Value}, nil)
		if err != nil {
			panic(err)
		}
	}

	//consul.WithPath(testPath)
	source, err := consul.New(client, consul.WithPath("configs/bootstrap.toml"))
	if err != nil {
		panic(err)
	}
	c := config.New(
		//config.WithSource(file.NewSource(flagconf), source),
		config.WithSource(source),
		//config.WithResolveActualTypes(true),
		config.WithDecoder(codec.SourceDecoder),
	)
	defer c.Close()
	if err := c.Load(); err != nil {
		panic(err)
	}

	var bc conf.Bootstrap
	if err := c.Scan(&bc); err != nil {
		panic(err)
	}
```

bootstrap.toml
```
ServiceName = "helloworld"
Version = "v1.0.0"
CryptoType = "argon2"
Id = ""

[Server]
[Server.Http]
Network = "0.0.0.0"
Addr = "8000"
UseTls = false
CertFile = ""
KeyFile = ""
[Server.Http.Timeout]
Seconds = 180
Nanos = 0
[Server.Http.ShutdownTimeout]
Seconds = 180
Nanos = 0
[Server.Http.ReadTimeout]
Seconds = 180
Nanos = 0
[Server.Http.WriteTimeout]
Seconds = 180
Nanos = 0
[Server.Http.IdleTimeout]
Seconds = 180
Nanos = 0
[Server.Grpc]
Network = "0.0.0.0"
Addr = "9000"
UseTls = false
CertFile = ""
KeyFile = ""
[Server.Grpc.Timeout]
Seconds = 180
Nanos = 0
[Server.Grpc.ShutdownTimeout]
Seconds = 180
Nanos = 0
[Server.Grpc.ReadTimeout]
Seconds = 180
Nanos = 0
[Server.Grpc.WriteTimeout]
Seconds = 180
Nanos = 0
[Server.Grpc.IdleTimeout]
Seconds = 180
Nanos = 0
```

proto
```
syntax = "proto3";
package kratos.api;

option go_package = "internal/mods/helloworld/conf;conf";

import "google/protobuf/duration.proto";
import "validate/validate.proto";

message Bootstrap {
  string service_name = 1 [json_name = "service_name"];
  string version = 2 [json_name = "version"];
  string crypto_type = 3 [json_name = "crypto_type"];
  Server server = 4;
  Data data = 5;
  Settings settings = 6;
  string id = 99 ;
}
```

#### What you expected to happen:
Converts profiles properly

#### Environment:
- Kratos version (use `kratos -v`): kratos version v2.8.0
- Go version (use `go version`): go version go1.23.2 windows/amd64
- OS (e.g: `cat /etc/os-release`): Windows
- Others:

**Comment by shenqidebaozi** [comment]
I don't quite understand what the specific problem is

**Comment by godcong** [comment]
![1729627669602](https://github.com/user-attachments/assets/5051ad75-bad1-4aa8-b10a-16f38a3db82c)
This is mainly the case when the source is specialized to v.
This is because the intermediate values are stored in a map. Therefore, they are not subject to the tag specification.
My configuration file is in `.toml` format, and it converts the data to `UpperCase` like this.

So I think it should be more than just `unmarshalJSON`. 
It should be decoded in the format of the source file.

example:
```
  string service_name = 1 [json_name = "service_name"];
```
in go:
```
   ServiceName string `json:"service_name"`
```
If the source is in a non-json format.
Then it will be parsed according to the default parsing method for that format.
If the configuration is `UpperCase` in the `.toml` file, the fields are parsed into `map[ServiceName]xxx`

Of course, if the configuration with `service_name` in the file, it can be resolved normally.
But I don't have the ability to change the case.
I just saved the bootstrap configuration as a file.

**Comment by czyt** [comment]
you need two step
1.register toml codec in kratos
simpe toml codec
```go
import (
	"github.com/BurntSushi/toml"
	"github.com/go-kratos/kratos/v2/encoding"
)

// Name is the name registered for the xml codec.
const Name = "toml"

func init() {
	encoding.RegisterCodec(codec{})
}

// codec is a Codec implementation with xml.
type codec struct{}

func (codec) Marshal(v interface{}) ([]byte, error) {
	return toml.Marshal(v)
}

func (codec) Unmarshal(data []byte, v interface{}) error {
	return toml.Unmarshal(data, v)
}

func (codec) Name() string {
	return Name
}

```
2、define your resolver see more https://go-kratos.dev/docs/component/config#6%E9%85%8D%E7%BD%AE%E5%A4%84%E7%90%86resolver
![image](https://github.com/user-attachments/assets/e428f280-e0e9-4378-9a2b-095dcb6886a8)

**Comment by godcong** [comment]
@czyt 意思是,我实际需要一个自定义的resolver将输入的配置转换成对的map格式对吧?

**Comment by godcong** [comment]
I tried to write my own Resolver, but I found a problem during the implementation. 
The main problem is that the input doesn't know what format my source format is, so it can't determine if it needs to be updated.

The idea is to update the fields according to the format after decoding. Then return the updated map

**Comment by godcong** [comment]
This doesn't solve the problem that yaml defaults to all lowercase...
Changed the initialization logic...
The local one is converted to a proto object.
That's it for now...
