### ISSUE TITLE
[Question] Middleware appears to use HTTP error codes even when the request was originally gRPC - is this intended?

### ISSUE THREAD

**Issue by wscalf** [go-kratos/kratos#3442]
While working with the metrics middleware, we noticed that all the error codes showing up in Prometheus were HTTP status codes (400, 504, etc) even though only the gRPC endpoints were being exercised, which surprised us at first, but it looks like all the middlewares behave this way:

- Kratos errors are declared with an HTTP status code [[link](https://github.com/go-kratos/kratos/blob/main/errors/types.go#L6)]
- And middlewares use this code field directly ([metrics](https://github.com/go-kratos/kratos/blob/main/middleware/metrics/metrics.go#L125), [logging](https://github.com/go-kratos/kratos/blob/main/middleware/logging/logging.go#L36))

Which left us wondering: is this intentional behavior? It seems like it could be meant to abstract logged error codes from the actual protocol used, maybe favoring HTTP because it's more widely recognized, but we wanted to reach out and check.

We also noticed that OK responses are logged as 0, which would be the correct status code for gRPC but is inconsistent with the HTTP ones and likely just an empty value.

**Comment by shenqidebaozi** [comment]
Yes, because HTTP and gRPC are isomorphic, they use the same identifier and are converted according to gRPC's conventions

**Comment by wscalf** [comment]
Okay, and so it's intentional then that logging and metrics always report HTTP status codes?

**Comment by shenqidebaozi** [comment]
Yes, the code for errors corresponds to the HTTP code
