### ISSUE TITLE
[Question] When using consul to register a service, how to manually specify the IP address of the service?

### ISSUE THREAD

**Issue by xray-bit** [go-kratos/kratos#3451]
使用容器运行 app 时，向 consul 注册的是容器的 ip 地址，怎么样手动指定服务的 IP 地址？

**Comment by AchilleasTsiamoulis** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by shenqidebaozi** [comment]
```kratos.Endpoint```

**Comment by xray-bit** [comment]
@shenqidebaozi, thanks a lot.

**Comment by shenqidebaozi** [comment]
I don't know why the previous reply was deleted by GitHub

**Comment by xray-bit** [comment]
Because there's a phishing link in that comment.
