### ISSUE TITLE
ecode 治理

### ISSUE THREAD

**Issue by Terry-Mao** [go-kratos/kratos#387]
- ecode错误码跨服务的传递应立刻处理来自下游服务的错误，将其转换/翻译成自己的错误码

跨服务之间的错误传递和处理，例如a->b，那么b返回的-1 ，其中的-1只作为b的scope可见，那么a应该将其转为自己的“-5”（-1在a里可能有别的含义），这个应作为作为错误码最佳实践；

- 富UI的错误码管理，基于配置文件/配置中心

kratos提供了ecode.Errorf（动态构建错误码），在代码内自定义错误message。ecode.New（静态错误码），通过Register注入了消息模板，但是不能够从配置文件paladin里动态加载或变更，因此准备抽象ecode.toml统一管理静态错误码message

- 如果每个服务可枚举错误了，对应swagger也可以描述我会返回什么了错误码

把api的proto定义，和code的proto定义，统一放置，对于api，以及ecode都是清晰可见，文档化的。

- 系统错误，ecode中的公共错误码，应该映射成HTTP/gRPC的标准Status

需要把ecode对应的tool，以及wiki完善

**Comment by zuiqiangqishao** [comment]
![image](https://user-images.githubusercontent.com/20850040/76678455-2175c700-6613-11ea-9632-561814a4a161.png)
您好，请问下是这样返回err吗，可是这样返回err的话，那s.dao.SaveArt里面errors.Wrap包含的堆栈不就丢了吗。。。难道是直接把err的堆栈打出来返回吗？
![image](https://user-images.githubusercontent.com/20850040/76678506-8f21f300-6613-11ea-8e8f-828262d218f8.png)
有点没理解ecode到底怎么return，还请指点下

**Comment by F1renze** [comment]
目前在使用 kratos 过程中发现以下几点问题：
- 自定义 ecode 不支持同时定义 code 与 message, 由于 message 存储于 atomic.Value 中，获取对应 message 及新增 ecode 对应的 message 非常不便
- 服务间传递 ecode 无法完整地解析回上游服务 ecode 所定义的 code 值，是否可以将 grpc 的 status 封装起来作为 ecode 传递的载体

由于看到 https://github.com/go-kratos/kratos/issues/433 中提到后续只会保留 Status 与 ErrorMessage，那么 ecode 这一块是否会在近期重新设计？

@Terry-Mao

**Comment by F1renze** [comment]
目前在使用 kratos 过程中发现以下几点问题：
- 自定义 ecode 不支持同时定义 code 与 message, 由于 message 存储于 atomic.Value 中，获取对应 message 及新增 ecode 对应的 message 非常不便
- error 需要经过繁琐的转换才可取得 code 值与 message，缺少直接将 error 直接转换回 ecode.Status 的 API 

对于第一点似乎在 https://github.com/go-kratos/kratos/issues/433 有提及，后续是否会弃用将 map 存储于 atomic.Value 的设计
