### ISSUE TITLE
kratos tool: 修改源码中的version，和git tag不一致

### ISSUE THREAD

**Issue by Terry-Mao** [go-kratos/kratos#389]
目前做法是修改代码中的version kratos 版本号，然后人肉打github 的tag，容易导致不一致

**Comment by yufeiminds** [comment]
我们借鉴了 Hashicorp 的做法，把 PR 的描述信息按照规范写成

```
FEATURES:

- some feature

ENHANCEMENTS:

- some enhancement 1

BUG FIXES:

- some bug fixes
```

之后

- 使用脚本归并上次 release 之间所有 PR 的 description
- 按照一定规则生成版本号，比如遇到 ENHANCEMENTS，minor +1，遇到 BUG FIXES，patch +1
- 使用脚本变更代码中的版本号
- 最后用 Github 的命令行工具 `hub release` 打 tag 上去
- 将上述过程固化到 CI 里，由人工触发

最近几天正好在公司的项目里搞这方面的，或许有借鉴意义

**Comment by Terry-Mao** [comment]
@yufeiminds 听上去不错：），我们参考下。

**Comment by ctrysbita** [comment]
版本号倒是可以考虑用 git describe 配合 tag 生成

**Comment by yufeiminds** [comment]
@ctrysbita 这个方案我们也使用过，后来放弃了

计算 tag commit 的难点在于，commit message 的修改成本较高，尤其是在 PR 已经被合并进主分支的时候。

经常会出现小伙伴 message 漏写某个关键特性的情况，而 master 是 protect 分支，改起来有点心虚，emmmmm~

PR message 就比较容易修改，还可以 reviewer/contributior 协作编辑~

**Comment by bigdot123456** [comment]
$  go get -u github.com/bilibili/kratos/tool/kratos
go: finding github.com/bilibili/kratos v0.3.1
go: downloading github.com/bilibili/kratos v0.3.1
go: extracting github.com/bilibili/kratos v0.3.1
go get: github.com/bilibili/kratos@v0.3.1 requires
        github.com/shirou/gopsutil@v2.19.6+incompatible: reading https://goproxy.io/github.com/shirou/gopsutil/@v/v2.19.6+incompatible.mod: 410 Gone

这个go.mod 是否需要修订一下。
如果手动修改也可以。
