### ISSUE TITLE
关于 ecode 包的疑问

### ISSUE THREAD

**Issue by Mivinci** [go-kratos/kratos#433]
ecode 包里的 ecode.go 文件中，Code 的 Error 方法的实现是下面这样的

```go
func (e Code) Error() string {
    return strconv.FormatInt(int64(e), 10)
}
```
这样不就只会返回 Code 的字符串形式吗？

且 context 的 JSON 方法是用 ecode 包里的 Cause 函数获取的错误来源，Cause 函数是对 errors.Cause 的封装：

```go
ec, ok := errors.Cause(e).(Codes)
```
这样如果在编码中要是返回了未使用 Register 函数注册的错误，就会使得返回的 JSON 里的 code 和 message 字段变为 0 和 "0"。看了一下 B 站的一些接口，的确有些出现这种情况。

请问这样设计的目的是什么呢，还是说有什么性能提升？

**Comment by Terry-Mao** [comment]
应该是一些历史原因导致，这块后续会把type ecode int作废了，分为Status、和ErrorMessage 两种类型来传递
