### ISSUE TITLE
prometheus收集HTTP数据以url为基准，但是没有区分方法

### ISSUE THREAD

**Issue by feixiao** [go-kratos/kratos#449]
prometheus收集HTTP数据以url为基准，但是没有区分方法
比如： GET /v1/book、 DELETE /v1/book没有区分，而是数据统计在一起

**Comment by younglifestyle** [comment]
请教下各位，社区当前是怎么解决的呀，我看middleware/metrics有"kind", "operation", "code", "reason"指标，不加method有什么考量不
