### ISSUE TITLE
关于Apollo配置中心，如何获取.properties格式的配置

### ISSUE THREAD

**Issue by xuzhzz** [go-kratos/kratos#456]
kratos 0.3.1

在Apollo里加上了相应配置并发布

![a](https://user-images.githubusercontent.com/10152482/70897573-dc4ef280-202d-11ea-86f5-62dca4fecc76.PNG)

对接了apollo配置中心，示例代码：

```Golang
package main

import (
	"flag"
	"github.com/bilibili/kratos/pkg/conf/paladin"
	"github.com/bilibili/kratos/pkg/conf/paladin/apollo"
	"github.com/bilibili/kratos/pkg/log"
)

func main() {
	flag.Parse()
	paladin.Init(apollo.PaladinDriverApollo)
	log.Info(paladin.Get("application").String())   // 均无内容输出
	log.Info(paladin.Get("application.properties").String())   // 均无内容输出
	log.Info(paladin.Get("application.txt").String())
	log.Info(paladin.Get("http.txt").String())
}

```

```sh
 go build
 ./cmd -apollo.appid kratos-demo  -apollo.cachedir ../tmp -apollo.cluster  default  -apollo.metaaddr  <<your apollo config addr>>  -apollo.namespaces application,application.properties,http.txt,application.txt
```

![b](https://user-images.githubusercontent.com/10152482/70897602-e8d34b00-202d-11ea-8429-4f505d6a79ab.PNG)

对于.txt格式的配置，是能正常取到内容的（.yml，.json的都可以），除了.properties的尝试了带格式和不带格式的似乎都拿不到，是我姿势有问题吗？

**Comment by xuzhzz** [comment]
@Colstuwjx 老哥请问下你那边是怎么做的呢

**Comment by Colstuwjx** [comment]
抱歉，我这边写的时候没加入对properties的支持，我们这边内部除了java应用其他都是YAML性质的配置文件格式。

**Comment by tonyboxes** [comment]
@Colstuwjx 这个是在那里限制了后缀的呢

**Comment by Colstuwjx** [comment]
用户在输入`paladin.Get("APOLLO_NAMESPACE_NAME").String()`的时候实际上是 paladin loadValue 通过调用 apollo client 的 [`content := a.client.GetNameSpaceContent(key, defaultValue)`](https://github.com/bilibili/kratos/blob/master/pkg/conf/paladin/apollo/apollo.go#L187) ，也即是 [这里](https://github.com/philchia/agollo/blob/master/client.go#L142) 代码调用的。

这里 agollo 客户端是通过尝试获取 namespace key 为 "content" 的对应值来获取该 namespace 全部文本内容的，我理解应该是 `.properties` 这样格式的 namespace 在 apollo 服务端 **不支持通过 content 来获取全部文本内容**。

暂时除了改用YAML来管理配置文件的话，我这边没有啥其他好的建议。
谢谢。

**Comment by Colstuwjx** [comment]
Link 一下我这边反馈到 apollo 官方的 [issue](https://github.com/ctripcorp/apollo/issues/2847) 留待跟踪。
