### ISSUE TITLE
internal/server/http/server.go中的pb.DemoServer修改成pb.DemoBMServer是否更合理？

### ISSUE THREAD

**Issue by shenzhigang** [go-kratos/kratos#470]
internal/server/http/server.go中的pb.DemoServer修改成pb.DemoBMServer是否更合理？
DemoServer属于grpc模块中的。

**Comment by Terry-Mao** [comment]
实际上，当初想法是想让grpc/http 服用一个interface，因为是一样的

**Comment by shenzhigang** [comment]
> 实际上，当初想法是想让grpc/http 服用一个interface，因为是一样的

如果复用一个interface并且生成到另一个单独文件中，那就完美了，这样我需要单独使用http或grpc时，都不会互相依赖

**Comment by namelcx** [comment]
http服怎么注册和发现啊,至今没搞清楚

**Comment by Terry-Mao** [comment]
@namelcx 需要自己手动注册

**Comment by namelcx** [comment]
@Terry-Mao 是手动去dicovery注册还是通过配置文件的方式注册？

**Comment by Terry-Mao** [comment]
@namelcx 就是在main函数里，自己手动注册和初始化服务发现
