### ISSUE TITLE
有个问题，目前似乎api.bm.go是依赖于api.pb.go的

### ISSUE THREAD

**Issue by shenzhigang** [go-kratos/kratos#471]
有个问题，目前似乎api.bm.go是依赖于api.pb.go的。
比如，api.bm.go里的HelloReq定义在api.pb.go中，这样可能有这样的不便：当我不需要使用grpc，在go:generate kratos tool protoc的时候，去掉--grpc选项，api.pb.go文件不生成，此时api.bm.go就不能正常工作了。

**Comment by Terry-Mao** [comment]
你的意思是，只需要bm时候，pb.go 没有生成是吧？

**Comment by shenzhigang** [comment]
> 你的意思是，只需要bm时候，pb.go 没有生成是吧？

是的，不生成pb.go就不能使用bm.go了，而我不需要用grpc，所以不需要pb.go

**Comment by tonyboxes** [comment]
protoc时，其实*.pb.go都会生成的，只是加上了plugins=grpc才附加了实现；
bm生成时，因为不想修改pb.go文件才独立生成了了一个，理论上grpc、bm应该都统一生成到pb.go的。
