### ISSUE TITLE
polls调用问题

### ISSUE THREAD

**Issue by dalaoting** [go-kratos/kratos#494]
原因：启动多个服务节点，当其中一个服务器(A)上的一个节点(A:A1)注销之后，其他服务节点会疯狂向discovery 发起polls请求拉取服务器(A)所有节点信息(A:all)

导致 discovery 服务器cpu瞬间满载

其中一个节点的polls日志如下
![image](https://user-images.githubusercontent.com/30154644/72416626-1c7ecd80-37b2-11ea-940b-b011637013be.png)

**Comment by lintanghui** [comment]
由于MomentService的节点被cancel后，每次返回的MomentService的节点列表都为空，导致client端一直没更新latest_timestamp。从而导致一直在请求discovery。感谢反馈，会尽快兼容修复

**Comment by dalaoting** [comment]
@lintanghui 也是最新master分支，问题不是必现，隔一段时间吧服务干掉，复现概率比较高

**Comment by lintanghui** [comment]
把服务干掉具体是怎么的操作呢，是cancel还是直接kill，被干掉的服务注册了多少节点

**Comment by dalaoting** [comment]
@lintanghui 我这边是每个服务有两个节点，干掉节点的逻辑是执行kill命令后，程序会先调用cancel然后退出
