### ISSUE TITLE
RPC 服务发现问题，帮忙看看，谢谢

### ISSUE THREAD

**Issue by kevinsir** [go-kratos/kratos#506]
rpc 服务已注册到 discovery, 通过http://127.0.0.1:7171/discovery/polls?appid=demo.service&env=dev&hostname=LAPTOP-7S54OGTM&latest_timestamp=0
也能查到, 
`{
    "code": 0,
    "message": "0",
    "ttl": 1,
    "data": {
        "demo.service": {
            "instances": {
                "zone01": [
                    {
                        "region": "region01",
                        "zone": "zone01",
                        "env": "dev",
                        "appid": "demo.service",
                        "hostname": "LAPTOP-7S54OGTM",
                        "addrs": [
                            "grpc://127.0.0.1:9000"
                        ],
                        "version": "",
                        "metadata": null,
                        "status": 1,
                        "reg_timestamp": 1581261208864765800,
                        "up_timestamp": 1581261208864765800,
                        "renew_timestamp": 1581263278866447800,
                        "dirty_timestamp": 1581261208864765800,
                        "latest_timestamp": 0
                    }
                ]
            },
            "latest_timestamp": 1
        }
    }
}` 

但是在客户端在调用rpc 服务时报错
`discovery://default/demo.service?subset=50&zone=zone01 error context deadline exceeded!panic: context deadline exceeded`

请问要如何解决

客户端点用方式
`
const AppID = "demo.service" // NOTE: example
// NewClient new member grpc client
func NewClient(cfg *warden.ClientConfig, opts ...grpc.DialOption) (demoapi.DemoClient, error) {
	client := warden.NewClient(cfg, opts...)
	conn, err := client.Dial(context.Background(), "discovery://default/"+AppID)
	if err != nil {
		return nil, err
	}
	return demoapi.NewDemoClient(conn), nil
}`

**Comment by xx132917** [comment]
我的也是

**Comment by xx132917** [comment]
加上代码ctx, cancel := context.WithDeadline(ctx, time.Now().Add(3*time.Second))试试

**Comment by xx132917** [comment]
我的问题是因为我的api.proto文件定义rpc时，
rpc UserSave(UserSaveReq) returns (UserSaveResp)；
定义成了这样，加了option，将url自定义了，也会出现这个错：
rpc UserSave(UserSaveReq) returns (UserSaveResp) {
    option (google.api.http) = {
      post: "/user/save"
    };
  };

**Comment by kevinsir** [comment]
我没有加这段，也不行。。。不支持哪里姿势不对了。。。

**Comment by kevinsir** [comment]
[https://www.cnblogs.com/ailumiyana/p/12188958.html](这里)说是在调用discovery polls的时候超时了，我配置的grpc dial 期限为10s， 在官方discovery文档介绍中写到discovery在做服务节点自发现的时候，如果server节点实例没有变更，则接口会阻塞直到30s返回-304。(poll(polls) 接口为长轮训接口)  硬是没看明白

**Comment by kevinsir** [comment]
"discovery://default/"+AppID  另外问一下 default 表示什么呢

**Comment by xx132917** [comment]
你是启动的时候报错吗？
你的客户端加这了吗：
resolver.Register(discovery.Builder())（表示要使用discovery进行服务发现，cmd  init里加）

**Comment by xx132917** [comment]
你的grpc服务端和客户端还要指定discovery节点，在启动应用时，可以通过flag(-discovery.nodes) 或者 环境配置(DISCOVERY_NODES)指定discovery节点

**Comment by kevinsir** [comment]
> Register

这一句是我放在客户端的 server/grpc.go 里面的New 函数里面

DISCOVERY_NODES 我环境配置里面全局写了，用http://127.0.0.1:7171/discovery/polls?appid=demo.service&env=dev&hostname=LAPTOP-7S54OGTM&latest_timestamp=0这个都能显示正常的rpc服务，就客户端不行。。。

**Comment by kevinsir** [comment]
> 你是启动的时候报错吗？
> 你的客户端加这了吗：
> resolver.Register(discovery.Builder())（表示要使用discovery进行服务发现，cmd init里加）


这一句是我放在客户端的 server/grpc.go 里面的New 函数里面

DISCOVERY_NODES 我环境配置里面全局写了，用http://127.0.0.1:7171/discovery/polls?appid=demo.service&env=dev&hostname=LAPTOP-7S54OGTM&latest_timestamp=0这个都能显示正常的rpc服务，就客户端不行。。。

**Comment by xx132917** [comment]
推荐你一个简单的demo，你可以做个对比，我也是参考这个的：https://github.com/ailumiyana/kratos-note/tree/master/warden/discovery

**Comment by kevinsir** [comment]
好的， 非常感谢

**Comment by kevinsir** [comment]
额。我又反复实验了一下。。。发现很多次里面，偶尔有一次能够客户端 启动成功。。。不知道怎么回事。。。。太玄幻了。。。

**Comment by wind417588** [comment]
> 但是在客户端在调用rpc 服务时报错
discovery://default/demo.service?subset=50&zone=zone01 error context deadline exceeded!panic: context deadline exceeded

对于这个问题而言，是客户端grpc stub上stream设置了超时时间造成的

另外，对于分布式架构，对于Service部分，基本上都是Master node + work node这种模式的，work node 会将提供的服务Register到Master上面。对于Client而言，调用一个服务，首先会和Master进行通信，Master会告知Client你该和那个work node进行交互。所以你应该搞清楚是在哪个环节出了问题，这个抓包很好确认的，其次就是检查代码，这一部分阅读官方的demo，反复的摸索、试验应该就能搞定的。

**Comment by kevinsir** [comment]
> > 但是在客户端在调用rpc 服务时报错
> > discovery://default/demo.service?subset=50&zone=zone01 error context deadline exceeded!panic: context deadline exceeded
> 
> 对于这个问题而言，是客户端grpc stub上stream设置了超时时间造成的
> 
> 另外，对于分布式架构，对于Service部分，基本上都是Master node + work node这种模式的，work node 会将提供的服务Register到Master上面。对于Client而言，调用一个服务，首先会和Master进行通信，Master会告知Client你该和那个work node进行交互。所以你应该搞清楚是在哪个环节出了问题，这个抓包很好确认的，其次就是检查代码，这一部分阅读官方的demo，反复的摸索、试验应该就能搞定的。

实在不好意思，那能问一下要怎么设置呢（stub上stream设置了超时时间）？为何有概率启动成功

**Comment by wind417588** [comment]
> > > 但是在客户端在调用rpc 服务时报错
> > > discovery://default/demo.service?subset=50&zone=zone01 error context deadline exceeded!panic: context deadline exceeded
> > 
> > 
> > 对于这个问题而言，是客户端grpc stub上stream设置了超时时间造成的
> > 另外，对于分布式架构，对于Service部分，基本上都是Master node + work node这种模式的，work node 会将提供的服务Register到Master上面。对于Client而言，调用一个服务，首先会和Master进行通信，Master会告知Client你该和那个work node进行交互。所以你应该搞清楚是在哪个环节出了问题，这个抓包很好确认的，其次就是检查代码，这一部分阅读官方的demo，反复的摸索、试验应该就能搞定的。
> 
> 实在不好意思，那能问一下要怎么设置呢（stub上stream设置了超时时间）？为何有概率启动成功。我设置了grp client 的 dial 为400s 但是400s 之后还是提示超时。。。

首先说明一下哈，我也是刚刚开始学习go和kratos框架的。对于rpc的理解我是基于以前掌握的zeroc ice 和 部分掌握的grpc理解的，各种rcp框架原理性的东西基本上都是一样的。

首先stub是grpc框架对于client端的一个概念，可以理解为一个object。设置超时这个基于grpc stream方式都是可以设置的(如果能到这一步表明，通讯链路已经建立起来了)，对于C/C++好像是set_deadline方法的。 “为何有概率启动成功”----我不知道你的实际情况是怎样的，对于服务端如果是master+worker node这种集群的模式，这个有很多种可能性的，work_node1 、work_node2 都成功register到master上， 如果此时client来请求服务了，Master调度选择的work_node1来为client服务，但是client 和 work_node1直接的网络不通(或者work_node1本身服务出现问题)，kratos我也是初学者，我理解应该有一些debug选项可以打开的(像zeroc ice)

**Comment by kevinsir** [comment]
> > > > 但是在客户端在调用rpc 服务时报错
> > > > discovery://default/demo.service?subset=50&zone=zone01 error context deadline exceeded!panic: context deadline exceeded
> > > 
> > > 
> > > 对于这个问题而言，是客户端grpc stub上stream设置了超时时间造成的
> > > 另外，对于分布式架构，对于Service部分，基本上都是Master node + work node这种模式的，work node 会将提供的服务Register到Master上面。对于Client而言，调用一个服务，首先会和Master进行通信，Master会告知Client你该和那个work node进行交互。所以你应该搞清楚是在哪个环节出了问题，这个抓包很好确认的，其次就是检查代码，这一部分阅读官方的demo，反复的摸索、试验应该就能搞定的。
> > 
> > 
> > 实在不好意思，那能问一下要怎么设置呢（stub上stream设置了超时时间）？为何有概率启动成功。我设置了grp client 的 dial 为400s 但是400s 之后还是提示超时。。。
> 
> 首先说明一下哈，我也是刚刚开始学习go和kratos框架的。对于rpc的理解我是基于以前掌握的zeroc ice 和 部分掌握的grpc理解的，各种rcp框架原理性的东西基本上都是一样的。
> 
> 首先stub是grpc框架对于client端的一个概念，可以理解为一个object。设置超时这个基于grpc stream方式都是可以设置的(如果能到这一步表明，通讯链路已经建立起来了)，对于C/C++好像是set_deadline方法的。 “为何有概率启动成功”----我不知道你的实际情况是怎样的，对于服务端如果是master+worker node这种集群的模式，这个有很多种可能性的，work_node1 、work_node2 都成功register到master上， 如果此时client来请求服务了，Master调度选择的work_node1来为client服务，但是client 和 work_node1直接的网络不通(或者work_node1本身服务出现问题)，kratos我也是初学者，我理解应该有一些debug选项可以打开的(像zeroc ice)

万分感谢，我这边节点只有一个。。。应该不是这个问题

**Comment by luyingjie** [comment]
这个问题我也遇到了，有两种问题，一种是超时，一种是地址错误，也会造成超时。最终我的问题是appid的服务没有注册grpc地址，所以客户端连接不上就造成超时。这里服务发现地址没有配置或者不正确也会造成问题。

**Comment by jialiming** [comment]
我遇到的问题是用127.0.0.X 本机的端口可以通，但是换成局域网的IP 比如192.168.1.X 就不能负载均衡了，我的局域网是没问题的，而且可以telnet 到端口

**Comment by Jmedal** [comment]
我两个服务相互调用的时候也会出现超时错误，本人不太懂原理，反正注册服务完了，接着创建client会阻塞自身服务上线，就死锁了，两个服务都上不了线，就超时了。然后我直接把创建client的步骤直接放携程里，让它不阻塞自身服务上线，死锁解除，等在超时时间内对方服务上线，client的创建就在超时之前实现了。

**Comment by realityone** [comment]
> 我两个服务相互调用的时候也会出现超时错误，本人不太懂原理，反正注册服务完了，接着创建client会阻塞自身服务上线，就死锁了，两个服务都上不了线，就超时了。然后我直接把创建client的步骤直接放携程里，让它不阻塞自身服务上线，死锁解除，等在超时时间内对方服务上线，client的创建就在超时之前实现了。

一般尽可能避免循环依赖的出现，默认死锁是预期中的现象。

**Comment by Jmedal** [comment]
> > 我两个服务相互调用的时候也会出现超时错误，本人不太懂原理，反正注册服务完了，接着创建client会阻塞自身服务上线，就死锁了，两个服务都上不了线，就超时了。然后我直接把创建client的步骤直接放携程里，让它不阻塞自身服务上线，死锁解除，等在超时时间内对方服务上线，client的创建就在超时之前实现了。
> 
> 一般尽可能避免循环依赖的出现，默认死锁是预期中的现象。

好的好的，下次不敢了😂

**Comment by machengling** [comment]
亲生经历这个问题。
首先如果只是单机测试，ip没有设置错误的情况下，大概率是 服务端rpc的服务没有启动
就是demo给的这个地方，如果没有启动，客户端访问超时那是肯定的了
（反正我加上这句话就好了 doge ）
> var rc struct {
		Server *warden.ServerConfig
	}
	err = paladin.Get("grpc.toml").UnmarshalTOML(&rc)
	if err == paladin.ErrNotExist {
		err = nil
	}
	ws = warden.NewServer(rc.Server)
	pb.RegisterHelloServer(ws.Server(), svc)
	ws, err = ws.Start()
