### ISSUE TITLE
注入这块没弄太明白，如果有多个service怎么处理？

### ISSUE THREAD

**Issue by busizshen** [go-kratos/kratos#513]
比如一个服务有用户，角色，菜单三个service 要改动哪些地方？

**Comment by busizshen** [comment]
package service

import (
	"context"
	"fmt"

	"github.com/bilibili/kratos/pkg/conf/paladin"
	pb "goAdmin/admin/api"
	"goAdmin/admin/internal/dao"

	"github.com/golang/protobuf/ptypes/empty"
)

type AdminServer interface {
	RoleService
	pb.DemoServer
}
type AdminBMServer interface {
	pb.DemoBMServer
}

在service 和dao 写了这样类似注册的 这种代码结构还能优化吗

**Comment by leonzhangxf** [comment]
serivce可以按照业务分多个svc结构体，修改di注入就可以了。
