### ISSUE TITLE
kratos new demo 的时候总是报这样的错误

### ISSUE THREAD

**Issue by jialiming** [go-kratos/kratos#515]
kratos tool protoc --grpc --bm api.proto
go get -u github.com/bilibili/kratos/tool/kratos-protoc
# github.com/bilibili/kratos/tool/kratos-protoc
../src/github.com/bilibili/kratos/tool/kratos-protoc/main.go:15:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in slice literal:
        cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
../src/github.com/bilibili/kratos/tool/kratos-protoc/main.go:20:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in slice literal:
        cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
../src/github.com/bilibili/kratos/tool/kratos-protoc/main.go:25:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in slice literal:
        cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
../src/github.com/bilibili/kratos/tool/kratos-protoc/main.go:30:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in slice literal:
        cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
../src/github.com/bilibili/kratos/tool/kratos-protoc/protoc.go:30:19: cannot convert ctx.Args() (type cli.Args) to type []string
运行 protoc 出错: fork/exec /home/gopath/bin/kratos-protoc: no such file or directory
fork/exec /home/gopath/bin/kratos-protoc: no such file or directory

**Comment by jialiming** [comment]
是不是 protoc 版本问题，官方建议版本是多少？

**Comment by ypfsoul** [comment]
> 是不是 protoc 版本问题，官方建议版本是多少？

这个错误首先是kratos-protoc没有安装成功，建议检查一下代理设置，go版本不同，代理设置有点区别（https://goproxy.io/zh/），我也遇到相同的问题，重新设置过代理以后没问题了

**Comment by tonyboxes** [comment]
#540
