### ISSUE TITLE
DeployEnv为prod的时候默认不输出到stdout这个逻辑有些奇怪

### ISSUE THREAD

**Issue by Colstuwjx** [go-kratos/kratos#521]
应用代码启动时这样写：

```
import (
    ...    
    "github.com/bilibili/kratos/pkg/log"
    ...
)

...
log.Init(nil) // debug flag: log.dir={path}
...
```

然后我这边服务是以容器形式部署到生产，带有环境变量`DEPLOY_ENV=prod`，这样一来就会走到[这个逻辑](https://github.com/bilibili/kratos/blob/master/pkg/log/log.go#L131) ，这样就没日志输出了，因为`DEPLOY_ENV=prod`。

由于我是走容器形式部署的，因此我这边是希望默认打到stdout的，所以这块逻辑是不是要处理一下？还是说让用户自行定义一个环境变量 `LOG_STDOUT=true` ？

谢谢！

**Comment by Terry-Mao** [comment]
这里面的这些代码当时是为了适配内部的，感觉可以改一下
