### ISSUE TITLE
慢操作日志记录

### ISSUE THREAD

**Issue by Terry-Mao** [go-kratos/kratos#531]
之前慢操作日志，都是整合到各个基础库中目录里独立维护，导致大量冗余代码，以及不利于统一初始化配置（比如redis:50ms，mysql:100ms）。

在net/trace中，跟踪了各个family的耗时情况，可以直接在net/trace中(trace.Finsh)，统一的拦截记录日志。

**Comment by leonzhangxf** [comment]
在redis库的trace.go文件里边有这样的结构体：

```
type traceConn struct {
	// tr for pipeline, if tr != nil meaning on pipeline
	tr trace.Trace
	// connTag include e.g. ip,port
	connTags []trace.Tag

	ctx context.Context

	// origin redis conn
	Conn
	pending int
	// TODO: split slow log from trace.
	slowLogThreshold time.Duration
}
```

这个 `// TODO: split slow log from trace.` 当时又是基于什么考虑呢？
