### ISSUE TITLE
 warden Resolver direct 换成局域网IP后会报错超时，127.0.0.1本机可以。

### ISSUE THREAD

**Issue by jialiming** [go-kratos/kratos#534]
direct 换成局域网IP后会报错超时，127.0.0.1本机可以。

warden client: dial direct://default/192.168.31.84:9002?subset=50 error context deadline exceeded!panic: context deadline exceeded

**Comment by lintanghui** [comment]
服务监听地址是啥。
ss -anlpt 看看监听的是啥地址，如果监听了127那肯定没法通过局域网ip访问

**Comment by jialiming** [comment]
> 服务监听地址是啥。
> ss -anlpt 看看监听的是啥地址，如果监听了127那肯定没法通过局域网ip访问

服务器监听的的确是局域网的IP地址，但是服务端连接的时候会报错 panic: context deadline exceeded

State      Recv-Q Send-Q                                                            Local Address:Port                                                                           Peer Address:Port
LISTEN     0      128                                                               192.168.31.88:9000                                                                                      *:*

**Comment by jialiming** [comment]
> > 服务监听地址是啥。
> > ss -anlpt 看看监听的是啥地址，如果监听了127那肯定没法通过局域网ip访问
> 
> 服务器监听的的确是局域网的IP地址，但是服务端连接的时候会报错 panic: context deadline exceeded
> 
> State Recv-Q Send-Q Local Address:Port Peer Address:Port
> LISTEN 0 128 192.168.31.88:9000 _:_

很是费解，为啥局域网内client端连不上，但是通过 telnet 局域网端口是通的，而且通过浏览器也能打开网页。

**Comment by jialiming** [comment]
> > > 服务监听地址是啥。
> > > ss -anlpt 看看监听的是啥地址，如果监听了127那肯定没法通过局域网ip访问
> > 
> > 
> > 服务器监听的的确是局域网的IP地址，但是服务端连接的时候会报错 panic: context deadline exceeded
> > State Recv-Q Send-Q Local Address:Port Peer Address:Port
> > LISTEN 0 128 192.168.31.88:9000 _:_
> 
> 很是费解，为啥局域网内client端连不上，但是通过 telnet 局域网端口是通的，而且通过浏览器也能打开网页。


把clinet端打包后运行就可以了，再ieda中会有问题。

**Comment by SUKF** [comment]
> > > > 服务监听地址是啥。
> > > > SS -anlpt看看监听的是啥地址，如果监听了127那肯定没法通过局域网IP访问
> > > 
> > > 
> > > 服务器监听的的确确是初始化的IP地址，但是服务端连接的时候会报错；
> > > 状态超过了上下文的截止时间。Recv -Q Send-Q本地地址：Port Peer地址：Port 
> > > LISTEN 0 128 192.168.31.88:9000 _：_
> > 
> > 
> > 很是费解，为啥要内部客户端端连不上，但是通过telnet插入端口是通的，而且通过浏览器也能打开网页。
> 
> 把clinet端打包后运行就可以了，再ieda中会有问题。



> > > > 服务监听地址是啥。
> > > > ss -anlpt 看看监听的是啥地址，如果监听了127那肯定没法通过局域网ip访问
> > > 
> > > 
> > > 服务器监听的的确是局域网的IP地址，但是服务端连接的时候会报错 panic: context deadline exceeded
> > > State Recv-Q Send-Q Local Address:Port Peer Address:Port
> > > LISTEN 0 128 192.168.31.88:9000 _:_
> > 
> > 
> > 很是费解，为啥局域网内client端连不上，但是通过 telnet 局域网端口是通的，而且通过浏览器也能打开网页。
> 
> 把clinet端打包后运行就可以了，再ieda中会有问题。

关闭idea的代理试试

**Comment by jialiming** [comment]
> > > > > 服务监听地址是啥。
> > > > > SS -anlpt看看监听的是啥地址，如果监听了127那肯定没法通过局域网IP访问
> > > > 
> > > > 
> > > > 服务器监听的的确确是初始化的IP地址，但是服务端连接的时候会报错；
> > > > 状态超过了上下文的截止时间。Recv -Q Send-Q本地地址：Port Peer地址：Port
> > > > LISTEN 0 128 192.168.31.88:9000 _：_
> > > 
> > > 
> > > 很是费解，为啥要内部客户端端连不上，但是通过telnet插入端口是通的，而且通过浏览器也能打开网页。
> > 
> > 
> > 把clinet端打包后运行就可以了，再ieda中会有问题。
> 
> > > > > 服务监听地址是啥。
> > > > > ss -anlpt 看看监听的是啥地址，如果监听了127那肯定没法通过局域网ip访问
> > > > 
> > > > 
> > > > 服务器监听的的确是局域网的IP地址，但是服务端连接的时候会报错 panic: context deadline exceeded
> > > > State Recv-Q Send-Q Local Address:Port Peer Address:Port
> > > > LISTEN 0 128 192.168.31.88:9000 _:_
> > > 
> > > 
> > > 很是费解，为啥局域网内client端连不上，但是通过 telnet 局域网端口是通的，而且通过浏览器也能打开网页。
> > 
> > 
> > 把clinet端打包后运行就可以了，再ieda中会有问题。
> 
> 关闭idea的代理试试

谢谢，关闭idea的代理后可以了。
