### ISSUE TITLE
kratos安装失败

### ISSUE THREAD

**Issue by shiquan1988** [go-kratos/kratos#535]
执行GO111MODULE=on && go get -u github.com/go-kratos/kratos/tool/kratos

出现下面错误

go: downloading github.com/go-kratos/kratos v0.3.3
go: extracting github.com/go-kratos/kratos v0.3.3
go get: github.com/go-kratos/kratos@v0.3.3: parsing go.mod:
	module declares its path as: github.com/bilibili/kratos
	        but was required as: github.com/go-kratos/kratos

below is my go env:

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/shiquan/Library/Caches/go-build"
GOENV="/Users/shiquan/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/shiquan/.gvm/pkgsets/go1.13/global"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/shiquan/.gvm/gos/go1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/shiquan/.gvm/gos/go1.13/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_3/krxyp3x92d358gd8zxxqd8rh0000gn/T/go-build887245376=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by ctrysbita** [comment]
kratos项目刚刚迁移到新的组织，等待下个版本或手动把模块名该一下就行。

**Comment by shiquan1988** [comment]
go get -u github.com/go-kratos/kratos/tool/kratos@master
可以安装成功，但是创建项目依然失败

➜  devspace kratos new kratos-demo2
go get -u github.com/go-kratos/kratos/tool/kratos-gen-project
go get: github.com/go-kratos/kratos@v0.3.3: parsing go.mod:
	module declares its path as: github.com/bilibili/kratos
	        but was required as: github.com/go-kratos/kratos
运行 genproject 出错: fork/exec /Users/shiquan/.gvm/pkgsets/go1.13.5/global/bin/kratos-gen-project: no such file or directory
panic: fork/exec /Users/shiquan/.gvm/pkgsets/go1.13.5/global/bin/kratos-gen-project: no such file or directory

goroutine 1 [running]:
main.main()
	/Users/shiquan/.gvm/pkgsets/go1.13.5/global/pkg/mod/github.com/go-kratos/kratos@v0.3.4-0.20200328100648-e0daed38dd23/tool/kratos/main.go:59 +0x89f

**Comment by Terry-Mao** [comment]
主干已经更新了pkg地址

**Comment by jinjiangcc** [comment]
更新下文档啊

**Comment by tonyboxes** [comment]
@shiquan1988 现在可以试试，我们更新了对应替换包名的版本

**Comment by shiquan1988** [comment]
@@感谢快速响应，依然存在如下问题：

kratos tool protoc --grpc --bm api.proto
go get -u github.com/go-kratos/kratos/tool/kratos-protoc
# github.com/go-kratos/kratos/tool/kratos-protoc
../src/github.com/go-kratos/kratos/tool/kratos-protoc/main.go:15:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
../src/github.com/go-kratos/kratos/tool/kratos-protoc/main.go:20:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
../src/github.com/go-kratos/kratos/tool/kratos-protoc/main.go:25:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
../src/github.com/go-kratos/kratos/tool/kratos-protoc/main.go:30:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
../src/github.com/go-kratos/kratos/tool/kratos-protoc/protoc.go:30:19: cannot convert ctx.Args() (type cli.Args) to type []string
运行 protoc 出错: fork/exec /Users/shiquan/.gvm/pkgsets/go1.13.5/global/bin/kratos-protoc: no such file or directory
f

**Comment by Terry-Mao** [comment]
Kratos 工具重新install了吗

**Comment by shiquan1988** [comment]
重新install了，另外新建了一全新的go环境，依然相同的错误

**Comment by tonyboxes** [comment]
```
github.com/urfave/cli v1.22.1
github.com/urfave/cli/v2 v2.1.1
```
应该是这个cli flag版本冲突了，我修复了下可以试试 #540

**Comment by qizhoumeng** [comment]
安装成功，但是安装wire这一步没有成功，报错：
wire: go [-e -json -compiled=true -test=false -export=false -deps=true -find=false -tags=wireinject -- .]: exit status 1: go: kratos-demo/internal/di imports
		kratos-demo/internal/server/grpc imports
		kratos-demo/api imports
		github.com/bilibili/kratos/pkg/net/http/blademaster: github.com/bilibili/kratos@v0.4.1: parsing go.mod:
		module declares its path as: github.com/go-kratos/kratos
		        but was required as: github.com/bilibili/kratos

wire: generate failed
exit status 1
kratos tool wire
wire: kratos-demo/internal/dao: wrote /Users/xx/Documents/learn-go/kratos-demo/internal/dao/wire_gen.go

创建项目之后执行go build 时报错：
go: kratos-demo/cmd imports
	kratos-demo/internal/di imports
	kratos-demo/internal/service imports
	kratos-demo/api imports
	github.com/bilibili/kratos/pkg/net/http/blademaster: github.com/bilibili/kratos@v0.4.1: parsing go.mod:
	module declares its path as: github.com/go-kratos/kratos
	        but was required as: github.com/bilibili/kratos

**Comment by shiquan1988** [comment]
go get -u github.com/go-kratos/kratos/tool/kratos-protoc
go: finding github.com/urfave/cli v1.22.3
go: downloading github.com/urfave/cli v1.22.3
go: extracting github.com/urfave/cli v1.22.3
protoc: 安装成功!
2020/03/30 12:54:05 go get -u github.com/go-kratos/kratos/tool/protobuf/protoc-gen-bm
go: downloading github.com/siddontang/go v0.0.0-20180604090527-bdc77568d726
go: extracting github.com/siddontang/go v0.0.0-20180604090527-bdc77568d726
go: finding github.com/golang/protobuf v1.3.5
go: finding github.com/pkg/errors v0.9.1
go: finding google.golang.org/genproto latest
go: finding github.com/siddontang/go latest
go: downloading github.com/golang/protobuf v1.3.5
go: downloading github.com/pkg/errors v0.9.1
go: downloading google.golang.org/genproto v0.0.0-20200326112834-f447254575fd
go: extracting github.com/golang/protobuf v1.3.5
go: extracting github.com/pkg/errors v0.9.1
go: extracting google.golang.org/genproto v0.0.0-20200326112834-f447254575fd
2020/03/30 12:54:42 protoc --proto_path=/Users/shiquan/.gvm/pkgsets/go1.13/global/src --proto_path=/Users/shiquan/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/go-kratos/kratos@v0.4.2-0.20200330023123-5475b629384c/third_party --proto_path=/Users/shiquan/.gvm/pkgsets/go1.13/global/src/kratos-demo3/api --bm_out=:. api.proto
api.proto: File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).
exit status 1
exit status 1

**Comment by qizhoumeng** [comment]
> 安装成功，但是安装wire这一步没有成功，报错：
> ·
> `wire: go [-e -json -compiled=true -test=false -export=false -deps=true -find=false -tags=wireinject -- .]: exit status 1: go: kratos-demo/internal/di imports
> kratos-demo/internal/server/grpc imports
> kratos-demo/api imports
> github.com/bilibili/kratos/pkg/net/http/blademaster: github.com/bilibili/kratos@v0.4.1: parsing go.mod:
> module declares its path as: github.com/go-kratos/kratos
> but was required as: github.com/bilibili/kratos
> 
> wire: generate failed
> exit status 1
> kratos tool wire
> wire: kratos-demo/internal/dao: wrote /Users/xx/Documents/learn-go/kratos-demo/internal/dao/wire_gen.go
> `
> 
> 创建项目之后执行go build 时报错：
> `go: kratos-demo/cmd imports kratos-demo/internal/di imports kratos-demo/internal/service imports kratos-demo/api imports github.com/bilibili/kratos/pkg/net/http/blademaster: github.com/bilibili/kratos@v0.4.1: parsing go.mod: module declares its path as: github.com/go-kratos/kratos but was required as: github.com/bilibili/kratos `

应该是替换包的时候这个没有替换吧？

**Comment by tonyboxes** [comment]
`go get -u github.com/go-kratos/kratos/tool/kratos@master`

@qizhoumeng 你的估计是安装了旧版本，需要更新一下

**Comment by tonyboxes** [comment]
@shiquan1988 --proto_path指定的目录是否存在的呢，我看怎么是在.gvm下面，生成的项目对应是那个path的？

**Comment by qizhoumeng** [comment]
我把go bin目录下生成的相关kratos文件全部删除了，然后又执行了`go clean --modcache`
安装使用的是`go get -u github.com/go-kratos/kratos/tool/kratos@master` 安装的版本也是
<pre> 
Version:      0.4.1
 Go version:   go1.14.1
 Built:        2020/3/29
 OS/Arch:      darwin/amd64
</pre>
安装到`kratos tool wire`这一步之后就报错了。
`
2020/03/30 15:41:52 generate api.proto success.
kratos tool genbts
Close: 无声明 忽略此方法
Ping: 无声明 忽略此方法
dao.bts.go: 生成成功
kratos tool genmc
mc.cache.go: 生成成功
kratos tool wire
wire: go [-e -json -compiled=true -test=false -export=false -deps=true -find=false -tags=wireinject -- .]: exit status 1: go: finding module for package github.com/bilibili/kratos/pkg/net/http/blademaster/binding
	go: finding module for package github.com/bilibili/kratos/pkg/net/http/blademaster
	go: downloading github.com/bilibili/kratos v0.4.1
	go: found github.com/bilibili/kratos/pkg/net/http/blademaster in github.com/bilibili/kratos v0.4.1
	go: kratos-demo/internal/di imports
		kratos-demo/internal/server/grpc imports
		kratos-demo/api imports
		github.com/bilibili/kratos/pkg/net/http/blademaster: github.com/bilibili/kratos@v0.4.1: parsing go.mod:
		module declares its path as: github.com/go-kratos/kratos
		        but was required as: github.com/bilibili/kratos

wire: generate failed
exit status 1
kratos tool wire
wire: kratos-demo/internal/dao: wrote /Users/mengqizhou/Documents/learn-go/kratos-demo/internal/dao/wire_gen.go
Project: kratos-demo
OnlyGRPC: false
OnlyHTTP: false
Directory: /Users/mengqizhou/Documents/learn-go/kratos-demo

项目创建成功.
`
这个文件__wire_gen.go__创建失败

**Comment by tonyboxes** [comment]
#544

**Comment by qizhoumeng** [comment]
@tonyboxes  是旧版本的问题引起的我把  bin 下的都删除了，然后重新安装就可以了。

**Comment by kingGang** [comment]
> 安装成功，但是安装wire这一步没有成功，报错：
> ·
> `wire: go [-e -json -compiled=true -test=false -export=false -deps=true -find=false -tags=wireinject -- .]: exit status 1: go: kratos-demo/internal/di imports
> kratos-demo/internal/server/grpc imports
> kratos-demo/api imports
> github.com/bilibili/kratos/pkg/net/http/blademaster: github.com/bilibili/kratos@v0.4.1: parsing go.mod:
> module declares its path as: github.com/go-kratos/kratos
> but was required as: github.com/bilibili/kratos
> 
> wire: generate failed
> exit status 1
> kratos tool wire
> wire: kratos-demo/internal/dao: wrote /Users/xx/Documents/learn-go/kratos-demo/internal/dao/wire_gen.go
> `
> 
> 创建项目之后执行go build 时报错：
> `go: kratos-demo/cmd imports kratos-demo/internal/di imports kratos-demo/internal/service imports kratos-demo/api imports github.com/bilibili/kratos/pkg/net/http/blademaster: github.com/bilibili/kratos@v0.4.1: parsing go.mod: module declares its path as: github.com/go-kratos/kratos but was required as: github.com/bilibili/kratos `
> **替换包的时候这个没有替换吧？**

怎么解决的？我这边一样的错误
2020/05/30 13:25:38 generate api.proto success.
kratos tool genbts
Close: 无声明 忽略此方法
Ping: 无声明 忽略此方法
dao.bts.go: 生成成功
kratos tool genmc
mc.cache.go: 生成成功
kratos tool wire
wire: go [-e -json -compiled=true -test=false -export=false -deps=true -find=false -tags=wireinject -- .]: exit status 1: go: finding github.com/bilibili/kratos v0.5.0
	go: downloading github.com/bilibili/kratos v0.5.0
	go: extracting github.com/bilibili/kratos v0.5.0
	go: kratos-demo/internal/di imports
		kratos-demo/internal/server/grpc imports
		kratos-demo/api imports
		github.com/bilibili/kratos/pkg/net/http/blademaster: github.com/bilibili/kratos@v0.5.0: parsing go.mod:
		module declares its path as: github.com/go-kratos/kratos
		        but was required as: github.com/bilibili/kratos
	
wire: generate failed
exit status 1
kratos tool wire
