### ISSUE TITLE
kratos cli工具无法生成新项目

### ISSUE THREAD

**Issue by yimingsir** [go-kratos/kratos#546]
> kratos new demo
go get -u github.com/go-kratos/kratos/tool/kratos-gen-project@v0.4.2
go: cannot use path@version syntax in GOPATH mode
运行 genproject 出错: fork/exec /Users/yiming/go/bin/kratos-gen-project: no such file or directory
panic: fork/exec /Users/yiming/go/bin/kratos-gen-project: no such file or directory

**Comment by tonyboxes** [comment]
`go get -u github.com/go-kratos/kratos/tool/kratos-gen-project@v0.4.2`

看着是这个没安装成功，可以看下go version是否1.13.0以上，或者export GO111MODULE=on是否打开了

**Comment by yimingsir** [comment]
> `go get -u github.com/go-kratos/kratos/tool/kratos-gen-project@v0.4.2`
> 
> 看着是这个没安装成功，可以看下go version是否1.13.0以上，或者export GO111MODULE=on是否打开了

已经可以了，我手动不带版本号执行
go get -u github.com/go-kratos/kratos/tool/kratos-gen-project
安装上了
