### ISSUE TITLE
最新版本 wire依赖注入执行失败

### ISSUE THREAD

**Issue by xgaxpp** [go-kratos/kratos#547]
通过kratos new新建项目后无法执行wire方法

错误信息

wire: go [-e -json -compiled=true -test=false -export=false -deps=true -find=false -tags=wireinject -- .]: exit status 1: go: finding module for package github.com/b
ilibili/kratos/pkg/net/http/blademaster/binding
        go: finding module for package github.com/bilibili/kratos/pkg/net/http/blademaster
        go: found github.com/bilibili/kratos/pkg/net/http/blademaster in github.com/bilibili/kratos v0.4.2
        go: kratos-demo/internal/di imports
                kratos-demo/internal/server/grpc imports
                kratos-demo/api imports
                github.com/bilibili/kratos/pkg/net/http/blademaster: github.com/bilibili/kratos@v0.4.2: parsing go.mod:
                module declares its path as: github.com/go-kratos/kratos
                        but was required as: github.com/bilibili/kratos

**Comment by tonyboxes** [comment]
```
go get -u github.com/go-kratos/kratos/tool/kratos@master
go get -u github.com/go-kratos/kratos/tool/kratos-protoc@master
go get -u github.com/go-kratos/kratos/tool/kratos-gen-project@master
go get -u github.com/go-kratos/kratos/tool/kratos-gen-bts@master
go get -u github.com/go-kratos/kratos/tool/kratos-gen-mc@master
```
应该是go mod缓存了，可以直接更新下，或者：
```
cd kratos/tool
go install ./...
```

**Comment by xgaxpp** [comment]
你好。更新了最新版可以了。但是在运行项目的时候还是报错。
错误信息
在cmd目录下 go build

# github.com/go-kratos/kratos/pkg/net/rpc/warden/resolver
D:\go\pkg\mod\github.com\go-kratos\kratos@v0.4.2\pkg\net\rpc\warden\resolver\resolver.go:53:78: undefined: resolver.BuildOption
D:\go\pkg\mod\github.com\go-kratos\kratos@v0.4.2\pkg\net\rpc\warden\resolver\resolver.go:110:33: undefined: resolver.ResolveNowOption
# github.com/go-kratos/kratos/pkg/net/rpc/warden/balancer/p2c
D:\go\pkg\mod\github.com\go-kratos\kratos@v0.4.2\pkg\net\rpc\warden\balancer\p2c\p2c.go:158:52: undefined: balancer.PickOptions
D:\go\pkg\mod\github.com\go-kratos\kratos@v0.4.2\pkg\net\rpc\warden\balancer\p2c\p2c.go:190:52: undefined: balancer.PickOptions

**Comment by tonyboxes** [comment]
gRPC版本被本地更新了，可以先改到1.24.0版本

**Comment by zeromake** [comment]
我也碰上了，`go.mod` 里的 `google.golang.org/grpc` 为 `v1.27.0` 手动执行:

```bash
go get google.golang.org/grpc@v1.24.0
```

**Comment by tonyboxes** [comment]
#550
