### ISSUE TITLE
kratos 最新版 wire报错

### ISSUE THREAD

**Issue by georgehao** [go-kratos/kratos#559]
~/goproject/kratos-demo/demo1/cmd ᐅ kratos tool wire
wire: go [-e -json -compiled=true -test=false -export=false -deps=true -find=false -tags=wireinject -- .]: exit status 1: go: finding module for package github.com/bilibili/kratos/pkg/net/http/blademaster/binding
	go: finding module for package github.com/bilibili/kratos/pkg/net/http/blademaster
	go: found github.com/bilibili/kratos/pkg/net/http/blademaster in github.com/bilibili/kratos v0.4.2
	go: demo1/cmd imports
		demo1/internal/di imports
		demo1/internal/server/grpc imports
		demo1/api imports
		github.com/bilibili/kratos/pkg/net/http/blademaster: github.com/bilibili/kratos@v0.4.2: parsing go.mod:
		module declares its path as: github.com/go-kratos/kratos
		        but was required as: github.com/bilibili/kratos

wire: generate failed
exit status 1

~/goproject/kratos-demo/demo1/cmd ᐅ kratos -v
kratos version v0.4.2

执行过kratos tool upgrade all 并且全部成功

清除过mod缓存: go clean --modcache

**Comment by dasheyuan** [comment]
从错误提示可以看到，`kratos tool protoc api/api.protoc` 自动生成的go代码中仍然`import github.com/bilibili/kratos`     
我解决的方法比较粗暴，直接删除原来的kratos tool二进制文件，重新kratos tool install all就好了。

**Comment by tonyboxes** [comment]
```
cd kratos/tool
go install ./...
```
可以master然后直接安装新版本，go get -u有时候无法安装到新版本
