### ISSUE TITLE
请问这次更新从0.3到0.4有更新目录具体更新了哪些东西吗？

### ISSUE THREAD

**Issue by luyingjie** [go-kratos/kratos#563]
0.3版本kratos new 报错，重新获取并安装了0.4版本, kratos new正常，但是运行报错。
main.runAction(0xc00009c280, 0x1, 0x1)
        C:/qcmm/lib/code/pkg/mod/github.com/go-kratos/kratos@v0.4.2/tool/kratos/run.go:25 +0x431
github.com/urfave/cli/v2.(*Command).Run(0xc000094240, 0xc00009c1c0, 0x0, 0x0)
        C:/qcmm/lib/code/pkg/mod/github.com/urfave/cli/v2@v2.1.1/command.go:161 +0x4e7
github.com/urfave/cli/v2.(*App).RunContext(0xc000084180, 0x6a8520, 0xc00000a0d8, 0xc0000044c0, 0x2, 0x2, 0x0, 0x0)
        C:/qcmm/lib/code/pkg/mod/github.com/urfave/cli/v2@v2.1.1/app.go:302 +0x81b
github.com/urfave/cli/v2.(*App).Run(...)
        C:/qcmm/lib/code/pkg/mod/github.com/urfave/cli/v2@v2.1.1/app.go:211
main.main()
        C:/qcmm/lib/code/pkg/mod/github.com/go-kratos/kratos@v0.4.2/tool/kratos/main.go:57 +0x511

虽然不是1.0版本，但是还是得保持稳定吧，这样项目无法上线啊。

**Comment by Jmedal** [comment]
这路径改了，本地项目不更新可以不，哈哈

**Comment by tonyboxes** [comment]
直接更新最新版本就可以了，只是更了pkg名字而已
