### ISSUE TITLE
paladin reload file fail

### ISSUE THREAD

**Issue by UnderTreeTech** [go-kratos/kratos#566]
server os:centos7.2
file list:
-rw-r--r-- 1 root root  53 Apr 18 13:22 application.toml
-rw-r--r-- 1 root root 418 Apr 18 13:22 db.toml
-rw-r--r-- 1 root root  48 Apr 18 13:22 etcd.toml
-rw-r--r-- 1 root root  54 Apr 18 13:22 grpc.toml
-rw-r--r-- 1 root root 742 Apr 18 22:20 http.toml
-rw-r--r-- 1 root root 183 Apr 18 13:22 memcache.toml
-rw-r--r-- 1 root root 175 Apr 18 13:22 redis.toml

I use vim to modify my http.toml, but it can't save the changes but output errors.
2020/04/18 22:17:34 unsupport event "configs/http.toml~": REMOVE ingored
2020/04/18 22:20:27 unsupport event "configs/4913": REMOVE ingored
2020/04/18 22:20:27 unsupport event "configs/http.toml": RENAME ingored
2020/04/18 22:20:27 load file configs/http.toml~ error: open configs/http.toml~: no such file or directory, skipped

Notice: unsupport event "configs/http.toml~": REMOVE ingored, so where this file comes from?

**Comment by ptechen** [comment]
我也遇到这个问题了，解决了？请告知，谢谢

**Comment by ptechen** [comment]
配置文件路径后边多了一个～线， configs/http.toml~， 导致找不到文件！
