### ISSUE TITLE
grpc服务逻辑是不是应该写在server层

### ISSUE THREAD

**Issue by godsoul** [go-kratos/kratos#569]
目前框架生成出来的代码，wire把grpc和service绑定了，所有实现必须写在service里面，这样service直接暴露出去了，我的理解应该是grpc逻辑实现写在server里面，然后server里面的grpc或者http都可以去调用service，service相当于内部的一些服务，暴露出去的是server文件下的grpc和http。

**Comment by tonyboxes** [comment]
这个需要看mircoservice的粒度，如果分得比较细，并且grpc和http基本一致，是可以直接可以；
如果项目拆分偏大，可以service目录化，然后多出grpc/http controller层。
