### ISSUE TITLE
kratos new kratos-demo generate failed

### ISSUE THREAD

**Issue by hammersmith-xie** [go-kratos/kratos#570]
version:0.4.2
wire: go [-e -json -compiled=true -test=false -export=false -deps=true -find=false -tags=wireinject -- .]: exit status 1: go: finding github.com/bilibili/kratos v0.4.2
        go: downloading github.com/bilibili/kratos v0.4.2
        go: extracting github.com/bilibili/kratos v0.4.2
        go: 2/internal/di imports
                2/internal/server/grpc imports
                2/api imports
                github.com/bilibili/kratos/pkg/net/http/blademaster: github.com/bilibili/kratos@v0.4.2: parsing go.mod:
                module declares its path as: github.com/go-kratos/kratos
                        but was required as: github.com/bilibili/kratos

wire: generate failed
it seems that generate_script still has some path about bilibili rather go-kratos.

**Comment by tonyboxes** [comment]
This needs to be updated to the latest version of kratos.

**Comment by BigKuCha** [comment]
@tonyboxes  0.5.0 貌似还有这个问题
![image](https://user-images.githubusercontent.com/5095944/80871538-c772b300-8cdf-11ea-8af6-09535958261d.png)

**Comment by BestPei** [comment]
![issue](https://user-images.githubusercontent.com/26396103/83835130-8b899e00-a722-11ea-9f4c-1b7325dc6066.png)

**Comment by dingyuanhong** [comment]
最新版本的kratos也碰到了这个问题 同求解决方法

**Comment by Windfarer** [comment]
@dingyuanhong @BestPei 包的路径已经改了，现在应该用这个命令安装

`go get -u github.com/go-kratos/kratos`

**Comment by BestPei** [comment]
收到



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Windfarer"<notifications@github.com&gt;; 
发送时间: 2020年6月12日(星期五) 晚上6:01
收件人: "go-kratos/kratos"<kratos@noreply.github.com&gt;; 
抄送: "裴奇星"<1148029659@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [go-kratos/kratos] kratos new kratos-demo generate failed (#570)





 
@dingyuanhong @BestPei 包的路径已经改了，现在应该用这个命令安装
 
go get -u github.com/go-kratos/kratos
