### ISSUE TITLE
请问下dao和service目录下的文件数越来越多看起来特别乱，用什么方法拆分比较好呢？

### ISSUE THREAD

**Issue by jinnzy** [go-kratos/kratos#571]
service下有将近20个文件，dao下也有10多个文件，这种怎么拆分比较好呢？ 
如login拆分成 login service struct,login dao struct这样吗？
现在是只有一个service和dao目录下面放了很多xxx.go文件。
![image](https://user-images.githubusercontent.com/33449123/80224215-f9e73500-867b-11ea-914f-289d8ba0f882.png)

**Comment by godsoul** [comment]
新建文件夹，用不同的包名，拆成多个service

**Comment by tonyboxes** [comment]
service
-user
-xx

可以按业务进行目录拆分的

**Comment by jinnzy** [comment]
好的，谢谢两位
