### ISSUE TITLE
windows环境下 kratos tool乱码

### ISSUE THREAD

**Issue by ke00ke** [go-kratos/kratos#573]
PS D:\ckh\GOPATH\src> **kratos tool**
[95mprotoc[0m[94m(已安装)[0m: [96m快速方便生成pb.go的protoc封装，windows、Linux请先安装protoc工具[0m Author(kratos) [2020/03/31]
[95mgenbts[0m[94m(已安装)[0m: [96m缓存回源逻辑代码生成器[0m Author(kratos) [2020/03/31]
[95mgenmc[0m[94m(已安装)[0m: [96mmc缓存代码生成[0m Author(kratos) [2020/03/31]
[95mtestgen[0m[92m(未安装)[0m: [96m测试代码生成[0m Author(kratos) [2020/03/31]
[95mtestcli[0m[92m(未安装)[0m: [96m测试代码运行[0m Author(kratos) [2020/03/31]
[95mswagger[0m[92m(未安装)[0m: [96mswagger api文档[0m Author(goswagger.io) [2020/03/31]

**Comment by tonyboxes** [comment]
这个好像只是简单fmt.Println()，直接自己写也会乱码不呢

**Comment by 1000Delta** [comment]
应该是终端的问题，乱码部分是颜色代码，Windows powershell/cmd 在系统终端和 goland 中都会乱码，wsl 在 goland 中不会乱码，powershell/cmd/wsl 在 windows terminal 里都可以正确着色XD
