### ISSUE TITLE
生成bm代码失败

### ISSUE THREAD

**Issue by RivenZoo** [go-kratos/kratos#581]
## 报错命令
在api目录下执行
`kratos tool protoc --bm api.proto`

## 错误信息
> 2020/05/08 11:04:14 protoc --proto_path=/Users/workspace/go/src --proto_path=/Users/workspace/go/pkg/mod/github.com/go-kratos/kratos@v0.5.0/third_party --proto_path=/Users/workspace/code/kratos-demo/api --bm_out=:. api.proto
api.proto: File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).

## 版本信息
kratos --version
> kratos version v0.5.0

protoc --version
> libprotoc 3.0.0

如果把 `--proto_path=/Users/workspace/code/kratos-demo/api` 替换成 `-I.` ，在api目录下执行protoc命令是可以生成代码的。

麻烦看一下是什么问题，谢谢~

**Comment by Windfarer** [comment]
升级下libprotoc的版本试试吧，我这里libprotoc 3.11.4没有遇到这个问题

**Comment by jxxl1203** [comment]
我把protoc 版本换到3.11.4也不行。kratos版本也是0.5.0
得在--proto_path里吧proto文件的路径也加上
protoc --proto_path=$GOPATH/src/demo/api --proto_path=xxxx --bm_out=. $GOPATH/src/demo/api/api.proto
或者
protoc --proto_path=. --proto_path=xxxx --bm_out=. ./api.proto
感觉应该是这个版本拼命令行的时候漏了  "--proto_path=."
