### ISSUE TITLE
Goland 中 Debugger 失败

### ISSUE THREAD

**Issue by ryanwx** [go-kratos/kratos#585]
Goland IDE 中配置好运行参数后，选择 Debugger 启动会抛出如下异常，正常运行无异常

unsupported architecture of windows/386 - only windows/amd64 is supported

**Comment by whtiehack** [comment]
看起来是你的配置问题,  配置成32位了

**Comment by ryanwx** [comment]
> 看起来是你的配置问题, 配置成32位了

应该不是，我配置的是 64 位，
![image](https://user-images.githubusercontent.com/52447036/81779299-034f1900-9527-11ea-9cf4-a590ecdf7d90.png)

**Comment by ryanwx** [comment]
忽略，下载的 go 版本不对，下载了 386 的，应该下载 64 的
