### ISSUE TITLE
[Proposal] Contribute a to a benchmark

### ISSUE THREAD

**Issue by waghanza** [go-kratos/kratos#591]
Hi,

I'm leading a benchmarking project => https://github.com/the-benchmarker/web-frameworks

The purpose of this project is to compare performances (other indicators will come), based on a fairest, as we can, comparison for `go` **frameworks** (comparing on the same version, **production-grade** environments, same compilation options ...).

Do you mind that I (or any member) add `kratos`  ? :heart:

Regards,

**Comment by Windfarer** [comment]
@waghanza kratos is designed for creating micro-services, not for web, but benchmarks are welcome.

**Comment by waghanza** [comment]
@Windfarer The above project is about comparing routing time (not anything specific to web usage, could be related to IoT or else).

As I understand, there is no problem adding it.

I'll work on it ...
