### ISSUE TITLE
这个是什么情况？

### ISSUE THREAD

**Issue by asen477** [go-kratos/kratos#595]
go build  error?

# kratos-demo/api
../api/client.go:15:68: undefined: DemoClient
../api/client.go:21:9: undefined: NewDemoClient

**Comment by Windfarer** [comment]
go get -u github.com/go-kratos/kratos/tool/kratos@v0.5.0

装个最新版的工具再生成一次项目试试

**Comment by tomatopunk** [comment]
can u have to api.bm.go,api.pb.go?  **path is PROJECT(you project)/api .**

i think u not installed to protoc, when exec : kratos new ,Is there a prompt that protobuf has not been installed?

you can get it from here:[protobuf](https://github.com/protocolbuffers/protobuf)

after installation,re-run **kratos new kratos-demo**,you can build normally~~

![image](https://user-images.githubusercontent.com/40015047/85263990-970af200-b4a2-11ea-871a-3608421e5bb6.png)
