### ISSUE TITLE
module declares its path as

### ISSUE THREAD

**Issue by StartHua** [go-kratos/kratos#598]
github.com/bilibili/kratos/pkg/net/http/blademaster: github.com/bilibili/kratos@v0.5.0: parsing go.mod:
	module declares its path as: github.com/go-kratos/kratos
	        but was required as: github.com/bilibili/kratos

**Comment by Windfarer** [comment]
go get -u github.com/go-kratos/kratos/tool/kratos@v0.5.0

仓库路径改了，你得装下最新版本的工具
