### ISSUE TITLE
container/group 懒加载容器，同样的key在并发访问时可能会初始化多次

### ISSUE THREAD

**Issue by DemonsLu** [go-kratos/kratos#605]
附上重现代码：
```
type Time struct {
	ts string
}
```
```
func main() {
	newFunc := func() interface{} {
		return &Time{ts: strconv.FormatInt(time.Now().UnixNano(), 10)}
	}
	group := NewGroup(newFunc)
	for i := 1; i < 10; i++ {
		go func() {
			fmt.Println(group.Get("xx"))
		}()
	}
	time.Sleep(time.Second)
}
```

**Comment by DemonsLu** [comment]
已经提交PR，不过改动比较大，可以讨论下有没有更好的方式修复此问题
https://github.com/go-kratos/kratos/pull/604

**Comment by xiaoxiaodek** [comment]
1. sync.LoadOrStore(key, new()) 可以保证查询和存储原子操作，缺点就是不管存不存在都会执行new
2. 
```go
    g.Lock()
	obj, ok := g.objs.Load(key)
	if !ok {
		obj = new()
		g.objs.Store(key, obj)
	}
    g.Unlock()
```

**Comment by DemonsLu** [comment]
> 1. sync.LoadOrStore(key, new()) 可以保证查询和存储原子操作，缺点就是不管存不存在都会执行new
> 2. 
> ```go
>     g.Lock()
> 	obj, ok := g.objs.Load(key)
> 	if !ok {
> 		obj = new()
> 		g.objs.Store(key, obj)
> 	}
>     g.Unlock()
> ```

在pr里，我把sync.map换成了普通的map。你的两种方案完全可以解决问题，但是我觉得，用sync.map的初衷应该就是想抛弃这把mutex锁。现在的用法，既用了sync.map又来了把锁，感觉设计上有点鬼畜

**Comment by realityone** [comment]
可以试试只在第一次没有 `Get` 到的时候用 `LoadOrStore`，保证只有第一个创建出来的对象有效，设计上这里应该倾向于只存储无状态的对象。
