### ISSUE TITLE
go build报错

### ISSUE THREAD

**Issue by kris425** [go-kratos/kratos#608]
go build
# kratos-demo/api
../api/client.go:15:68: undefined: DemoClient
../api/client.go:21:9: undefined: NewDemoClient
系统环境：centos7.6
go版本：1.13.9 linux/amd64
已经升级到0.5.0版本
go get -u github.com/go-kratos/kratos/tool/kratos@v0.5.0

**Comment by zxlwdgithub** [comment]
估计是api目录下的proto没生成对.

**Comment by liu599** [comment]
protoc编译器安装时，需要将kratos的[third_party](https://github.com/go-kratos/kratos/tree/master/third_party/)下面的依赖拷贝到protoc的include文件中，对应就是 include/google/api, github.com的gogo也要拷贝到系统的github.com依赖中去。

**Comment by Dravening** [comment]
ennm。。hi。。我用的是windows，下载了protoc.exe放在D:\protoc-3.12.3\bin\下了，加了环境变量；
目前我就是上述报错，是因为没有安装protobuf，请问一下这个protobuf在windows应该如何安装（安装方式好像很多）。
@zxlwdgithub @liu599

**Comment by liu599** [comment]
@Dravening  

嗯Goland的问题不影响使用
在修改dao目录下的文件后每次都要运行go generate(每个文件都要)
dao.go是根据interface去运行go generate生成dao.bts.go注意一下//bts 后面的缓存的部分也要改, 相应的mc.bts.go, wire_gen.go等等部分修改了都要重新生成。。然后在api中修改之后运行工具重新生成api.pb和api.bm等等， 就可以build了。

**Comment by Dravening** [comment]
@liu599 给你这个demo点个star，岂不美滋滋。

**Comment by Madoka-Kaname** [comment]
protobuf装好就可以了 项目跑起来还是挺简单的
