### ISSUE TITLE
errors: Go 1.13 error chain 优化

### ISSUE THREAD

**Issue by Terry-Mao** [go-kratos/kratos#61]
https://godoc.org/golang.org/x/exp/errors

Go 1.13 会有大改进，期待跟进

### 从 pkg/errors 到 exp/errors

目前 go-common 主要试用 pkg/errors 来封装错误链(err's chain) 典型的用法如下

```go
var ErrNotFound = errors.New("not found")

err := errors.Wrap(ErrNotFound, "user xxx")

fmt.Println(err.Error())
// user xxx: not found
fmt.Println(errors.Cause(err) == ErrNotFound)
// true
```
通过 Wrap 封装错误然后通过 Cause 取回原始的 err, 这样可以做到判断 err 的类型同事丰富错误信息。

同样的 exp/errors 也提供了同样的处理方法。

```go
var ErrNotFound = errors.New("not found")

// NOTE: 必须要 : %w 接我才会被 wrapper
err := fmt.Errorf("user xxx: %w", ErrNotFound)

fmt.Println(err.Error())
// user xxx: not found
fmt.Println(errors.Is(err, ErrNotFound))
// true
```
### exp/errors 其他功能

Formatter interface 更加友好的错误显示 https://godoc.org/golang.org/x/exp/errors#Formatter

**Comment by leobuzhi** [comment]
这么做应该是为了 sentry 吧？

**Comment by Terry-Mao** [comment]
@tomwei7
