### ISSUE TITLE
build kratos-demo/cmd failed

### ISSUE THREAD

**Issue by zxlwdgithub** [go-kratos/kratos#612]
cd kratos-demo/cmd
go build
"
build kratos-demo/cmd: cannot load google/protobuf: malformed module path "google/protobuf": missing dot in first path element
"
帮忙看看,谢谢.

**Comment by Windfarer** [comment]
请尝试按照文档重新安装最新版的kratos工具，重新生成项目试试，先close了，有问题请reopen
