### ISSUE TITLE
"kratos new" on windows failed maybe because using a bad file path

### ISSUE THREAD

**Issue by sxdsongda** [go-kratos/kratos#619]
kratos new krados-demo
... all seems right until

2020/07/30 11:40:22 protoc --proto_path=D:\Gopath/src --proto_path=D:\Gopath/pkg/mod/github.com/go-kratos/kratos@v0.5.1-0.20200526160825-521d240568d0/third_party --proto_path=D:\Gopath\src\kratos-demo\api --bm_out=:. api.proto
google/protobuf/descriptor.proto: File not found.

which eventually failed to generate api.pb.go api.bm.go and wire_gen.go in di directory
Any idea?

**Comment by Owen-Zhang** [comment]
我也遇到这种问题
kratos tool protoc --grpc --bm api.proto
api\client.go:25: running "kratos": exec: "kratos": executable file not found in %PATH%

protoc 本地环境变量中都是有的

**Comment by Owen-Zhang** [comment]
我把代码checkout 到v0.50版本，它又生成对了, 个人感觉tool应该与框架代码分开，搞到另一个项目中

**Comment by XuChaoChi** [comment]
@sxdsongda 把protoc的include\google\protobuf 目录放到 $GOPATH的src\github.com\go-kratos\kratos\third_party\google下

**Comment by zhl11b** [comment]
#514有解决方案

**Comment by sxdsongda** [comment]
@XuChaoChi @zhl11b  谢谢，果然成功了，之前一直用go mod的方式，$GOPATH\src\github.com\下就没有go-kratos这个目录
