### ISSUE TITLE
report a bug!!!

### ISSUE THREAD

**Issue by 1418894586** [go-kratos/kratos#624]
pkg/naming/discovery/discovery.go:282 +0x152

		var appIns *naming.InstancesInfo
		appIns, ok = app.zoneIns.Load().(*naming.InstancesInfo)
		ins = new(naming.InstancesInfo)
		ins.LastTs = appIns.LastTs
		ins.Scheduler = appIns.Scheduler

ins can be nil
panic: runtime error: invalid memory address or nil pointer dereference

**Comment by lintanghui** [comment]
麻烦贴写完整的栈

**Comment by logo306142054** [comment]
这个问题很好复现，连续起两个协程执行grpc.Dial，并传入同一个target就会出现，
也就是当连续两次调用Discovery.Build(appid, opts ...naming.BuildOpt)函数，并传入同一个appid

github.com/go-kratos/kratos/pkg/naming/discovery.(*Resolve).Fetch(0xc000472840, 0x1237b40, 0xc0000a4020, 0x1, 0xc00004de01)
        /xxx/src/github.com/go-kratos/kratos/pkg/naming/discovery/discovery.go:282 +0x132
github.com/go-kratos/kratos/pkg/net/rpc/warden/resolver.(*Resolver).updateproc(0xc00044f1a0)
        /xxx/src/github.com/go-kratos/kratos/pkg/net/rpc/warden/resolver/resolver.go:136 +0x143
created by github.com/go-kratos/kratos/pkg/net/rpc/warden/resolver.(*Builder).Build
        /xxx/src/github.com/go-kratos/kratos/pkg/net/rpc/warden/resolver/resolver.go:95 +0x358

**Comment by lintanghui** [comment]
麻烦贴下你的具体代码实现，多个客户端同时发起请求按理解应该是需要你在New里做并发控制

**Comment by logo306142054** [comment]
简单的复现代码如下，剔除了pool的部分，这里使用for循环起两个goroutine目的是模拟多个客户端同时调用pool.Get()获取连接的过程，而我的使用场景就是在pool.New = func(){}函数中执行Dial，是我的使用有问题吗

package main

import (
	"context"
	"flag"

	"github.com/go-kratos/kratos/pkg/net/rpc/warden/resolver"

	"github.com/go-kratos/kratos/pkg/naming/discovery"
	"github.com/go-kratos/kratos/pkg/net/rpc/warden"
)

func main() {
	flag.Parse()
	resolver.Register(discovery.Builder())
	for i := 0; i < 2; i++ {
		go func() {
			c := warden.NewClient(&warden.ClientConfig{})
			c.Dial(context.Background(), "discovery://default/test")
		}()
	}
	select {}
}
