### ISSUE TITLE
google.golang.org/grpc@v1.31.1/balancer/balancer.go 中的Pick函数移除了Context

### ISSUE THREAD

**Issue by SuKaiFei** [go-kratos/kratos#626]
https://github.com/grpc/grpc-go/blob/v1.31.1/ #balancer/balancer.go

`../../../../../pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/rpc/warden/balancer/p2c/p2c.go:34:5: cannot use &p2cPickerBuilder literal (type *p2cPickerBuilder) as type base.PickerBuilder in assignment:
        *p2cPickerBuilder does not implement base.PickerBuilder (wrong type for Build method)
                have Build(map[resolver.Address]balancer.SubConn) balancer.Picker
                want Build(base.PickerBuildInfo) balancer.Picker
../../../../../pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/rpc/warden/balancer/p2c/p2c.go:35:5: cannot use &p2cPicker literal (type *p2cPicker) as type balancer.Picker in assignment:
        *p2cPicker does not implement balancer.Picker (wrong type for Pick method)
                have Pick(context.Context, balancer.PickInfo) (balancer.SubConn, func(balancer.DoneInfo), error)
                want Pick(balancer.PickInfo) (balancer.PickResult, error)
../../../../../pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/rpc/warden/balancer/p2c/p2c.go:42:32: not enough arguments in call to base.NewBalancerBuilder
        have (string, *p2cPickerBuilder)
        want (string, base.PickerBuilder, base.Config)
../../../../../pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/rpc/warden/balancer/p2c/p2c.go:144:2: cannot use p (type *p2cPicker) as type balancer.Picker in return argument:
        *p2cPicker does not implement balancer.Picker (wrong type for Pick method)
                have Pick(context.Context, balancer.PickInfo) (balancer.SubConn, func(balancer.DoneInfo), error)
                want Pick(balancer.PickInfo) (balancer.PickResult, error)
`

**Comment by realguan** [comment]
这个问题还没解决吗

**Comment by SuKaiFei** [comment]
> 这个问题还没解决吗

应该还没有，可以在`go.mod`中引用`v1.24.0`来临时解决
`replace google.golang.org/grpc => google.golang.org/grpc v1.24.0`

**Comment by realguan** [comment]
好的，谢谢！发自我的华为手机-------- 原始邮件 --------发件人： sukaifei <notifications@github.com>日期： 2020年11月23日周一 18:32收件人： go-kratos/kratos <kratos@noreply.github.com>抄送： Guan <1032238721@qq.com>, Comment <comment@noreply.github.com>主    题： Re: [go-kratos/kratos] google.golang.org/grpc@v1.31.1/balancer/balancer.go 中的Pick函数移除了Context (#626)



这个问题还没解决吗



应该还没有，可以在go.mod中引用v1.24.0来临时解决

replace google.golang.org/grpc => google.golang.org/grpc v1.24.0

**Comment by realguan** [comment]
![image](https://user-images.githubusercontent.com/27861635/100033439-2ee78000-2e35-11eb-8c5c-0ed062e687d3.png)
编译还是有问题

```go
# github.com/go-kratos/kratos/pkg/net/rpc/warden/resolver
/home/guan/go/pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/rpc/warden/resolver/resolver.go:53:78: undefined: resolver.BuildOptions
/home/guan/go/pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/rpc/warden/resolver/resolver.go:110:33: undefined: resolver.ResolveNowOptions
# github.com/go-kratos/kratos/pkg/net/rpc/warden/balancer/p2c
/home/guan/go/pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/rpc/warden/balancer/p2c/p2c.go:158:52: undefined: balancer.PickInfo
/home/guan/go/pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/rpc/warden/balancer/p2c/p2c.go:190:52: undefined: balancer.PickInfo
guan@ubuntu:~/git/demo/dymicro/cmd$ 
```

**Comment by SuKaiFei** [comment]
这样再试试
```golang
module demo

go 1.13

replace google.golang.org/grpc v0.0.0 => google.golang.org/grpc v1.24.0

require (
	github.com/go-kratos/kratos v0.5.1-0.20201019061239-217cc8e5e918
	github.com/gogo/protobuf v1.3.1
	github.com/golang/protobuf v1.4.1
	github.com/google/wire v0.4.0
	google.golang.org/genproto v0.0.0-20200526211855-cb27e3aa2013
	google.golang.org/grpc v1.28.1
	google.golang.org/protobuf v1.25.0
)

```

**Comment by SuKaiFei** [comment]
这样再试试
`replace google.golang.org/grpc v0.0.0 => google.golang.org/grpc v1.24.0`

**Comment by realguan** [comment]
![image](https://user-images.githubusercontent.com/27861635/100034472-314ad980-2e37-11eb-8925-01e01d882987.png)
这样就恢复到之前的报错了。都两个月了，官方怎么还不维护一下

**Comment by realguan** [comment]
> 这样再试试
> `replace google.golang.org/grpc v0.0.0 => google.golang.org/grpc v1.24.0`

换成1.29好了
```
replace google.golang.org/grpc => google.golang.org/grpc v1.29.0
```

**Comment by AmarsDing** [comment]
google.golang.org/grpc v1.34.0  也是同样的错误   V1.29.0正常

**Comment by AmarsDing** [comment]
界面输出：{"code":0,"message":"0","ttl":1,"data":{"Hello":"Golang 大法好 !!!"}}
