### ISSUE TITLE
p2c

### ISSUE THREAD

**Issue by Cc360428** [go-kratos/kratos#631]
cannot use &p2cPickerBuilder literal (type *p2cPickerBuilder) as type base.PickerBuilder in assignment:
	*p2cPickerBuilder does not implement base.PickerBuilder (wrong type for Build method)
		have Build(map[resolver.Address]balancer.SubConn) balancer.Picker
		want Build(base.PickerBuildInfo) balancer.Picker

**Comment by Terry-Mao** [comment]
难道是grpc的版本不一致导致

**Comment by Windfarer** [comment]
duplicated #626

**Comment by Cc360428** [comment]
> 难道是grpc的版本不一致导致
我使用google.golang.org/grp 1.30 以上就会报错

**Comment by Windfarer** [comment]
@Cc360428 应该就是这个问题，grpc新版本的interface改了，我们后续会考虑如何升级，进度追踪和相关讨论就在 #626 吧
