### ISSUE TITLE
在service中如何做分模块

### ISSUE THREAD

**Issue by ningge123** [go-kratos/kratos#640]
Service结构体中有上百个方法，过于臃肿，怎么分模块

**Comment by Windfarer** [comment]
在一个模块内按功能划分到多个文件中应该还是够用的吧

**Comment by ningge123** [comment]
是够用，但是还是想拆分出来，按模块文件夹划分功能，目前还没有好的解决方案吗？

**Comment by tonyboxes** [comment]
一般可以先从微服务拆分功能开始，如果单个服务还是很多模块，还可以拆成小 UserService/VIPService这方式进行目录或代码增加结构

**Comment by ningge123** [comment]
👌
