### ISSUE TITLE
微服务方面的新手级别疑惑。。

### ISSUE THREAD

**Issue by mrlayki** [go-kratos/kratos#642]
比如我现在准备用kratos来做一个商城项目，采用微服务架构，细化出来很多服务，如商品，订单，短信，用户等服务。
那么。。
1、一个服务拉一个kratos项目，每个项目用docker去部署？QAQ
2、统一在一个kratos项目里维护？如果是这样，具体怎么去互相隔离，划分业务线的。。又是怎么样去部署的

**Comment by mrlayki** [comment]
感觉迟迟入不了微服务的门，RPC是在服务间去通信，但是我看着框架目录internal/server有RPC有http，如果我拿来用，很有可能就是定义一堆http handle,把kratos当做一个有很多功能的、划分好MVC的gin框架，而不是微服务框架去使用

**Comment by realityone** [comment]
http 也是一种形式的 RPC，学习微服务的话可以看《微服务设计》。

**Comment by mrlayki** [comment]
> http也是一种形式的RPC，学习微服务的话可以看《微服务设计》。

一个服务拉一个kratos项目，每个项目用docker去部署？还是说写在一个kratos里

**Comment by realityone** [comment]
> > http也是一种形式的RPC，学习微服务的话可以看《微服务设计》。
> 
> 一个服务拉一个kratos项目，每个项目用docker去部署？还是说写在一个kratos里

这个只是代码组织的方式而已，两种都行。

你可以直接 go get kratos 来用。

**Comment by mrlayki** [comment]
> > > http也是一种形式的RPC，学习微服务的话可以看《微服务设计》。
> > 
> > 
> > 一个服务拉一个kratos项目，每个项目用docker去部署？还是说写在一个kratos里
> 
> 这个只是代码组织的方式而已，两种都行。
> 
> 你可以直接 go get kratos 来用。

好的 谢谢
