### ISSUE TITLE
官方文档打不开，有其它文档吗

### ISSUE THREAD

**Issue by ningge123** [go-kratos/kratos#644]
[https://go-kratos.github.io/kratos](https://go-kratos.github.io/kratos)

**Comment by Windfarer** [comment]
github.io由于某些原因经常不稳定，我们还在找有没有合适的境内站点做镜像，如果有好的可以推荐。文档就在项目里面，您可以直接看https://github.com/go-kratos/kratos/tree/master/docs

**Comment by Windfarer** [comment]
国内镜像 https://go-kratos.gitee.io/kratos/
