### ISSUE TITLE
 cannot use &p2cPickerBuilder

### ISSUE THREAD

**Issue by xiaoxiaosu** [go-kratos/kratos#645]
run的时候报这个错误

**Comment by tonycafe** [comment]
对应的错误帮贴一下看看

**Comment by AmarsDing** [comment]
PS E:\GOLANG\src\kratos-demo\cmd> go build
# github.com/go-kratos/kratos/pkg/net/rpc/warden/balancer/p2c
..\..\..\pkg\mod\github.com\go-kratos\kratos@v0.5.0\pkg\net\rpc\warden\balancer\p2c\p2c.go:34:5: cannot use &p2cPickerBuilder literal (type *p2cPickerBuilder) as type base.PickerBuilder in assignment:
        *p2cPickerBuilder does not implement base.PickerBuilder (wrong type for Build method)
                have Build(map[resolver.Address]balancer.SubConn) balancer.Picker
                want Build(base.PickerBuildInfo) balancer.Picker
..\..\..\pkg\mod\github.com\go-kratos\kratos@v0.5.0\pkg\net\rpc\warden\balancer\p2c\p2c.go:35:5: cannot use &p2cPicker literal (type *p2cPicker) as type balancer.Picker in 
assignment:
        *p2cPicker does not implement balancer.Picker (wrong type for Pick method)
                have Pick(context.Context, balancer.PickInfo) (balancer.SubConn, func(balancer.DoneInfo), error)
                want Pick(balancer.PickInfo) (balancer.PickResult, error)
..\..\..\pkg\mod\github.com\go-kratos\kratos@v0.5.0\pkg\net\rpc\warden\balancer\p2c\p2c.go:42:32: not enough arguments in call to base.NewBalancerBuilder
        have (string, *p2cPickerBuilder)
        want (string, base.PickerBuilder, base.Config)
..\..\..\pkg\mod\github.com\go-kratos\kratos@v0.5.0\pkg\net\rpc\warden\balancer\p2c\p2c.go:144:2: cannot use p (type *p2cPicker) as type balancer.Picker in return argument:
        *p2cPicker does not implement balancer.Picker (wrong type for Pick method)
                have Pick(context.Context, balancer.PickInfo) (balancer.SubConn, func(balancer.DoneInfo), error)
                want Pick(balancer.PickInfo) (balancer.PickResult, error)

**Comment by xiaoyudian-huahua** [comment]
把mod清空，使用mod tidy 解决版本问题。mod中grpc版本 v1.31.0的时候出现过此问题
