### ISSUE TITLE
小白求解惑，关于微服务项目-目录规划的问题

### ISSUE THREAD

**Issue by qianbeibuzui** [go-kratos/kratos#648]
业务场景：一台机器，需要部署两个微服务，分别是用户服务和订单服务

疑惑点：
      1.使用kratos new project 两次，生成两个微服务，分别作为用户服务和订单服务
      2.使用kratos new project 一次，把用户服务和订单服务都在同一项目目录去处理
      3.多次使用kratos new project，一个kratos new project 就是对应 用户服务里的登录模块 或 注册模块

求大佬们解惑呀！！！

**Comment by realityone** [comment]
你已经规划好两个服务的话就按 1 来，如果逻辑复杂到一定程度可以考虑 3。

**Comment by qianbeibuzui** [comment]
感谢大佬的回复，这样我就十分清楚了。
