### ISSUE TITLE
swagger文档无法启动

### ISSUE THREAD

**Issue by realguan** [go-kratos/kratos#653]
![image](https://user-images.githubusercontent.com/27861635/100825172-6c31ba80-3492-11eb-91c5-7c567aca4ddc.png)

**Comment by realguan** [comment]
怎么解决

**Comment by Windfarer** [comment]
这个命令只是封装了下go-swagger，后面可以加该工具的参数，比如`--no-open`来跳过调用浏览器打开的步骤。

参考 https://goswagger.io/usage/serve_ui.html

**Comment by realguan** [comment]
> 这个命令只是封装了下go-swagger，后面可以加该工具的参数，比如`--no-open`来跳过调用浏览器打开的步骤。
> 
> 参考 https://goswagger.io/usage/serve_ui.html

好的，谢谢。
