### ISSUE TITLE
压测场景出现context deadline exceeded

### ISSUE THREAD

**Issue by SgtDaJim** [go-kratos/kratos#657]
压测流量走公网，客户端和服务端在同一个网段，理论上网络没有问题，机器带宽也没有跑满，fd也没有消耗完。
压测场景中一直出现504错误码，信息是context deadline exceeded
客户端配置了breaker.Config{SwitchOff: false}，调用rpc时使用context.Background()
服务端配置了Timeout: 30 * 1000 * 1000
![image](https://user-images.githubusercontent.com/10288044/101365397-b2e24300-38de-11eb-9482-70a28b5d3b0b.png)
请问这个报错可能是什么导致的？

**Comment by Windfarer** [comment]
客户端的timeout设了多少？

**Comment by SgtDaJim** [comment]
@Windfarer 同样是30 * 1000 * 1000

**Comment by Windfarer** [comment]
这样的话最好能提供客户端和服务端的代码了，您目前提供的信息看不出来是什么问题

**Comment by tonybase** [comment]
可以检查client传递超时，或者server超时参数
