### ISSUE TITLE
【bm代码生成】kratos生成的bm代码不支持从路径中解析参数写法

### ISSUE THREAD

**Issue by Never12581** [go-kratos/kratos#659]
情况：
1. 使用 proto 文件，同时生成 grpc 和 http 代码。
2. 在proto 文件中，使用 
    option (google.api.http) = {
      get: "/lanyue/api/object/:env/:bucket/body"
    };  代码
3. 使用 kratos tool protoc *.protoc (本质上使用 protoc  --bm_out=:. *.proto)
4. 生成的路由绑定代码中无法，url 中的 :env 、:bucket 等信息

请问后续是否支持？

**Comment by tonybase** [comment]
在v2版本会进行google.api.http的rest-api支持，并且会按官方规范进行实现
