### ISSUE TITLE
确定性子集算法使用的id是否应该是连续的而不是hash值

### ISSUE THREAD

**Issue by Linpjia** [go-kratos/kratos#664]
`func defulatSubset(inss []*Instance, size int) []*Instance {
	backends := inss
	if len(backends) <= int(size) {
		return backends
	}
	clientID := env.Hostname
	sort.Slice(backends, func(i, j int) bool {
		return backends[i].Hostname < backends[j].Hostname
	})
	count := len(backends) / size
	// hash得到ID
	id := farm.Fingerprint64([]byte(clientID))
	// 获得rand轮数
	round := int64(id / uint64(count))

	s := rand.NewSource(round)
	ra := rand.New(s)
	//  根据source洗牌
	ra.Shuffle(len(backends), func(i, j int) {
		backends[i], backends[j] = backends[j], backends[i]
	})
	start := (id % uint64(count)) * uint64(size)
	return backends[int(start) : int(start)+int(size)]
}`

测试len(backends)=200，size=10，200个clientID（ip）经过hash得到id，最后的结果不均匀；使用连续的id值得到的结果均匀；

**Comment by tonybase** [comment]
目前我们是结合了p2c基于cpu一些均衡达到比较好的效果，这个subset因为使用了hash大概最大相差20%左右

**Comment by Linpjia** [comment]
了解了，谢谢
