### ISSUE TITLE
小白请教：在kratos做微服务的分布式事务？

### ISSUE THREAD

**Issue by qianbeibuzui** [go-kratos/kratos#665]
如题，怎么去处理微服务的分布式事务？
1.我找遍了kratos 的文档：也没有介绍，怎么实现微服务分布式事务？
2.是自己手动用rabbitmq 一类的工具实现吗？
3.如果有这方面的资料，请指个路！！

**Comment by lintanghui** [comment]
kratos是个微服务框架  分布式事务可以参考 https://github.com/seata/seata
