### ISSUE TITLE
【bm middleware】请教如何合理的在自定义中间件中使用dao层方法

### ISSUE THREAD

**Issue by silenceExia** [go-kratos/kratos#672]
目前自定义了一个bm中间件，来实现jwt的鉴权，基本功能都写好了，但目前遇到一个问题，我如果在中间件中想要调用dao层的方法（比如调取rpc client或者redis client等），该如何设计更合理啊（比如我解析jwt token以后拿到了uid，需要去验证这个用户是否被禁用），求大佬指教

**Comment by C-isCoder** [comment]
是否禁用还是业务侧判断吧，中间件只要提供 UID 就好了。或者独立个服务，业务侧 RPC 调用判断。职责单一
