### ISSUE TITLE
【V2 Design】关于 V2 版本设计的一些小疑惑

### ISSUE THREAD

**Issue by CoderPoet** [go-kratos/kratos#674]
最近学习了下 kratos v2 版本的新代码 ，感觉分层抽象更清晰了，代码也更优雅了 ，受益匪浅！

不过有几个小疑问，希望可以得到大佬解答，哈哈！

1、http 改用 gorilla 的 mux 是出于什么样的考虑呢?（我记得之前是改造的 gin）

mux 的路由是一个数组存储，然后路由匹配是一个暴力的遍历循环，相较于之前的 gin 使用 trie 树的实现，mux 的数组遍历明显时间复杂度不是最优，所以性能这块也会差很多

2、目前抽象出的 transport 分层的意义是？

是参考 go-kit 的思路方便拓展 Middleware 中间件机制么？

比如：ServeGRPC（目前 V2  grpc transport 的实现这块）， 是在 grpc 的拦截器机制上，去执行自己实现的 chain 化 middlewares，这块为什么不直接使用 grpc 本身支持的 chain 化拦截器呢？

**Comment by tonybase** [comment]
gin其实在设计context时有点问题，不好通过middleware with value进行传递；
还有是rest-api路由是 `/v1/api/:var/` 方式，而`google.api.http`是使用了 `/v1/api/{var}` 方式，而 `mux` 也符合这个规范；

其实在做middleware时，也想了很多问题，也参考了很多，最终还是类似http.Handler和go-kit的类似；
这样子相对是比较纯粹一些，统一通过context进行上下文信息传递；
还有就是打算用户使用 `middleware` 时只对 `transport` 感知，而不是 `server` 层；

所以，打算先是 `server layer` ，可能对一些默认信息进行简单封装（或者用户可以不用 `server layer` ，直接使用旧版本的 `bm server` 也可以）；
这样子用户使用 `transport` 和 `middleware` 就可以了，然后用户可以使用不同的 `server`；

可以看作为：`server layer -> transport layer -> middleware -> service(endpoint)`

**Comment by hbinr** [comment]
tony 老师，推荐了解下https://github.com/go-chi/chi 100%兼容原生net/http，路由处理比mux快的多

**Comment by tonybase** [comment]
目前v2版本的 transport 只提供基础的 Handle 和 HandleFunc，然后做了proto google.api.http的对应annotation生成，框架使用时用户可以任意选择router的

**Comment by Mikaelemmmm** [comment]
v2 版本在那里？

**Comment by tonybase** [comment]
branch v2
