### ISSUE TITLE
go-kratos 官方微信群 | Chat Room

### ISSUE THREAD

**Issue by Windfarer** [go-kratos/kratos#682]
For developers who use English:
Discord：[go-kratos](https://discord.com/invite/BWzJsUJ)

---
欢迎关注公众号（Kratos开源社区）：
<img src="https://user-images.githubusercontent.com/3871120/116278139-cb34fa80-a7b8-11eb-9374-a6e85ee9a6a8.png" alt="kratos wechat" width="240px" />
- 通过菜单【联系我们】> 【加入社区】> 【二维码】
- 发送消息 `加入社区`

**Comment by wakaryry** [comment]
wx: pptpdf

求拉。看不到图片 😭

**Comment by IamDJJ** [comment]
求拉，看不到图片
wx: JJ9338d

**Comment by on7line** [comment]
已失效

**Comment by Windfarer** [comment]
> 已失效

已更新，感谢提醒

**Comment by fordream2014** [comment]
![image](https://user-images.githubusercontent.com/6639795/118921339-96a50080-b96a-11eb-9205-b9ff7dc26357.png)使用go 1.13，下载包有问题，如图所示，请问如何解决？

**Comment by tonybase** [comment]
@fordream2014 可以多go get -u 几次试试
