### ISSUE TITLE
用kratos v2 new出来的项目生成的grpc.pb.go 用etcd做服务注册与发现版本问题

### ISSUE THREAD

**Issue by LargeOrange** [go-kratos/kratos#700]
具体问题已经在群里同步给tony老师了，在这里记录下，免得在群里一直问进度。
简单说下就是我在写kratos基于etcd 服务注册与发现的时候发现：
kratos v2生成的grpc.pb.go用的是grpc 1.3+的版本
但是etcd只支持到1.26（好像是这个）
现在两个死锁了   一个降不下去，一个升不上来。

**Comment by tonybase** [comment]
目前etcd已经在开发支持grpc v1.30.x的支持了，近期也有合对应的适配，我们也反复考虑过这个问题，因为现在protoc工具需要安装旧版本，并且settings也不一致，最新的grpc v1.30.x其实做法是比较正确的，进行独立出来了

等kratos release时，其实etcd v3.5.x其实也发布了，到时可以使用对应的版本

**Comment by tonybase** [comment]
其实最好的做法是，etcd client-go可以独立个仓库，这样子比较容易升级或者依赖

**Comment by tonybase** [comment]
https://github.com/go-kratos/examples

我们把examples迁移到了独立仓库，目前看是可以兼容旧版本grpc了
