### ISSUE TITLE
V2版本  流式服务不能很好的生成service 

### ISSUE THREAD

**Issue by Naist4869** [go-kratos/kratos#706]
```go
// UnimplementedChannelCallbackServer must be embedded to have forward compatible implementations.
type UnimplementedChannelCallbackServer struct {
}

func (UnimplementedChannelCallbackServer) CallbackByGet(*HttpCallbackRequest, ChannelCallback_CallbackByGetServer) error {
	return status.Errorf(codes.Unimplemented, "method CallbackByGet not implemented")
}
func (UnimplementedChannelCallbackServer) CallbackByPost(*HttpCallbackRequest, ChannelCallback_CallbackByPostServer) error {
	return status.Errorf(codes.Unimplemented, "method CallbackByPost not implemented")
}
```

调用 
```
kratos-v2 proto service api/callback/callback.proto -t internal/service/callback/
```
```go
type ChannelCallbackService struct {
	pb.UnimplementedChannelCallbackServer
}

func (s *ChannelCallbackService) CallbackByGet(ctx context.Context, req *pb.HttpCallbackRequest) (*google.api.HttpBody, error) {
	return &pb.google.api.HttpBody{}, nil
}
func (s *ChannelCallbackService) CallbackByPost(ctx context.Context, req *pb.HttpCallbackRequest) (*pb.google.api.HttpBody, error) {
	return &pb.google.api.HttpBody{}, nil
}
```

**Comment by tonybase** [comment]
v2.0.x 目前打算先支持unary的，等v2.1.x可以考虑加上stream的支持

**Comment by codgo** [comment]
elloworld kratos proto service api/helloworld/helloworld.proto -t internal/service
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x153b54b]

goroutine 1 [running]:
github.com/go-kratos/kratos/cmd/kratos/internal/proto/service.run(0x1a37060, 0xc00017e3c0, 0x1, 0x3)
        /Users/progogame/go/pkg/mod/github.com/go-kratos/kratos/cmd/kratos@v0.0.0-20210206162932-0f780b480daa/internal/proto/service/service.go:76 +0x46b
github.com/spf13/cobra.(*Command).execute(0x1a37060, 0xc00017e390, 0x3, 0x3, 0x1a37060, 0xc00017e390)
        /Users/progogame/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x1a375a0, 0x0, 0x0, 0x0)
        /Users/progogame/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/progogame/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
        /Users/progogame/go/pkg/mod/github.com/go-kratos/kratos/cmd/kratos@v0.0.0-20210206162932-0f780b480daa/main.go:24 +0x2d
