### ISSUE TITLE
希望 V2 能新增 Windows 的支持

### ISSUE THREAD

**Issue by drrrMikado** [go-kratos/kratos#713]
Create a service 中的三条命令： 
- `make init`
- `make proto`
- `make build`

Windows 系统下是不支持 `make` 的。
现在的解决方案都是手动输完整命令，不是很方便。
或者像v1版本一样：`kratos build`

**Comment by dormonbear** [comment]
Win可以安装make
参考https://chocolatey.org/packages/make

**Comment by drrrMikado** [comment]
> Win可以安装make
> 参考https://chocolatey.org/packages/make

谢谢，看了下 Makefile，就算 `make` 解决了，Makefile 中的 `PROTO_FILES=$(shell find . -name *.proto)` 也有问题，Windows 不支持这样 `find` 的写法。

**Comment by tonybase** [comment]
可以通过 `chocolate install make` 安装工具，有些 windows 不支持的指令我们也打算修改过来

**Comment by dormonbear** [comment]
> > Win可以安装make
> > 参考https://chocolatey.org/packages/make
> 
> 谢谢，看了下 Makefile，就算 `make` 解决了，Makefile 中的 `PROTO_FILES=$(shell find . -name *.proto)` 也有问题，Windows 不支持这样 `find` 的写法。另外还有 `KRATOS_VERSION=$(shell go mod graph |grep go-kratos/kratos/v2 |head -n 1 |awk -F '@' '{print $$2}')` 这个。

在git bash下跑没有问题

**Comment by tonybase** [comment]
目前已经通过kratos实现对应的支持，我们把Makefiles已经去掉了
