### ISSUE TITLE
为啥感觉V2改动这么大？

### ISSUE THREAD

**Issue by greyireland** [go-kratos/kratos#729]
V1很多约定式的规范，到V2感觉都变成配置式了，让开发者自己去选择配置，会有额外的成本啊

内部有实际使用或者迁移升级实践吗？

没有最佳实践，感觉这个框架就没啥用了啊

**Comment by greyireland** [comment]
Redis和MySQL需要自己打点和trace追踪？

**Comment by greyireland** [comment]
为啥配置使用PB反序列化呢？

**Comment by tonybase** [comment]
v2 可以更多的定制化的，现在很多组件已经支持添加hook方式进行trace添加
