### ISSUE TITLE
Fatal bug: Lost context

### ISSUE THREAD

**Issue by storyicon** [go-kratos/kratos#757]
## Problem Description
I'm using the code on `v2.0.0-alpha3` and I found that the middleware modified context is lost when calling the http interface.       
The reproduction process is as follows:            
![image](https://user-images.githubusercontent.com/29772821/110668619-750af880-8206-11eb-8dbf-73534c9a4af5.png)
The value written in the `context` will not be available in the service's handler:               
![image](https://user-images.githubusercontent.com/29772821/110668747-98ce3e80-8206-11eb-8405-94d397f2dca1.png)

## Causes
I simply looked at the code and found that the root cause is that when calling the method registered by `xxx_http.pb.go`, it ignores the `context` passed in by the `middleware`.             

## Scope of Impact
This bug probably affects at least the following versions:               

### v2.0.0-alpha5
https://github.com/go-kratos/kratos/blob/v2.0.0-alpha5/transport/http/server.go#L101-L107
### v2.0.0-alpha4
https://github.com/go-kratos/kratos/blob/v2.0.0-alpha4/transport/http/server.go#L141
### v2.0.0-alpha3
https://github.com/go-kratos/kratos/blob/v2.0.0-alpha3/transport/http/server.go#L141
### v2.0.0-alpha2
https://github.com/go-kratos/kratos/blob/v2.0.0-alpha2/transport/http/server.go#L136

I note that the latest version(`v2.0.0-alpha6`) has been extensively refactored, and that the problem has been fixed consciously or unconsciously, but it will still affect users with older versions.

===

I think:
1. this issue should be fixed immediately.
2. If the problem is difficult or not particularly necessary to fix, a bug marker should be added to the `tag`.
3. users may need to be notified of the issue.
4. if kratos is not currently at production level, it should be declared in the head of Readme.md.
5. a full `github flow` should be set up, it should be like any other large open source project: `PR -> Member Code Review -> Merge`, not by anyone submitting code directly to master.

**Comment by Windfarer** [comment]
Thanks for your report. The release versions with "alpha" means not stable, and don't use in production.

**Comment by storyicon** [comment]
@Windfarer 

Yes, you are right.
Generally speaking, until GA, it can be considered as a version that can not be used in the production environment, which is correct, but very official and impersonal:
Open source projects are able to meet GA standards, not just by relying on core developers.
It relies more on real issues from people who have put it to use **early** in small and medium-sized projects.
It might save these people a lot of time by letting them know when there are serious bugs in some of the historical versions.
I think it's respectful of the community.
Of course this is just my suggestion, you can make your own choice.
