### ISSUE TITLE
NewHTTPServer 如何正确地注册多个 HandlePrefix/Handler

### ISSUE THREAD

**Issue by MarsonShine** [go-kratos/kratos#763]
想请问下如何在 `NewHTTPServer` 注册多个 handler？
首先我在 /api 文件夹下创建了一个名为 org 的 api 模块，并定义了 org.proto 接口协议
在 `kratos proto client .\api\org\org.proto` 生成 pb 文件之后，定义好每层的 service，最终我还要在 `internal/server/http.go.NewHTTPServer` 注册生成的 `NewOrgHandler` handler，但是注册发现没有效果，完整代码如下：
```go
service Org {
    rpc CreateOrg (CreateOrgRequest) returns (DataResponse) {
        option (google.api.http) = {
            post: "/org/create",
            body: "*"
        };

    }
    rpc UpdateOrg (UpdateOrgRequest) returns (DataResponse) {
        option (google.api.http) = {
            post: "/org/update",
            body: "*"
        };
    }
}
... 其它省略
```
注册 handler
```go
// NewHTTPServer new a HTTP server.
func NewHTTPServer(c *conf.Server, greeter *service.GreeterService, org *service.OrgService) *http.Server {
	var opts = []http.ServerOption{}
	if c.Http.Network != "" {
		opts = append(opts, http.Network(c.Http.Network))
	}
	if c.Http.Addr != "" {
		opts = append(opts, http.Address(c.Http.Addr))
	}
	if c.Http.Timeout != nil {
		opts = append(opts, http.Timeout(c.Http.Timeout.AsDuration()))
	}
	srv := http.NewServer(opts...)
	m := http.Middleware(
		middleware.Chain(
			recovery.Recovery(),
			tracing.Server(),
			logging.Server(),
		),
	)
	srv.HandlePrefix("/", v1.NewGreeterHandler(greeter, m))
	srv.HandlePrefix("/org", orgapi.NewOrgHandler(org, m))
	return srv
}
```
当访问 `http://localhost:5000/helloworld/username` 这个是没问题的
但访问 `http://localhost:5000/org/create` 这个就是 404
我在 mux 的 [route.go#L360](https://github.com/gorilla/mux/blob/master/route.go#L360) 解释说明中，默认是 false，所以在我的理解中这样是可以的。
请问这种该如何解决？有什么其它解决方式呢？

**Comment by tonybase** [comment]
应该是不同Service，进行绑定不同的prefix，其实在考虑外面是否进行前缀绑定到接口，可能不太好实现

**Comment by MarsonShine** [comment]
感谢回复。
是我领会错 mux 注释上的意思了，这个 perfix 是只能在内部 NewGreeterHandler 内部注册的具体 api path **相同的前缀部分**才能起效果。打个比方，我新建的 NewOrgHandler 内部的 curd 接口，api path 都是以 `/org/` 为前缀，所以外部注册 HandlePrefix 就只能写成 `srv.HandlePrefix("/org", orgapi.NewOrgHandler(org, m))` 与之匹配，那么我上面的写法没有效果是因为 `srv.HandlePrefix("/", v1.NewGreeterHandler(greeter, m))` 所有的 api path 都能匹配 `/`，所以都重路由到第一个 Handler 里面去了。所以完整正确的写法应该改成
```go
srv.HandlePrefix("/helloworld", v1.NewGreeterHandler(greeter, m))
srv.HandlePrefix("/org", orgapi.NewOrgHandler(org, m))
```
@tonybase 感谢

**Comment by kqbi** [comment]
这个issue应该Pinned下，遇到了同样的问题，感谢 MarsonShine

**Comment by menglikaibin** [comment]
同样遇到这个问题,感谢

**Comment by xinruozhishui** [comment]
同样遇到这个问题,感谢
