### ISSUE TITLE
v2 要如何实现配置自动更新？

### ISSUE THREAD

**Issue by drrrMikado** [go-kratos/kratos#765]
```go
// conf/conf.go
var Cfg TestCfg

// cmd/main.go
c := config.New(
	config.WithSource(file.NewSource("test.yml")),
	config.WithDecoder(func(kv *config.KeyValue, v map[string]interface{}) error {
		return yaml.Unmarshal(kv.Value, v)
	}),
)
if err := c.Load(); err != nil {
	panic(err)
}
if err := c.Scan(&conf.Cfg); err != nil {
	panic(err)
}
```
这是读取 `test.yml` 配置文件的代码，并设置到 `conf/conf.go` 中 `Cfg` 变量。
假设 `test.yml` 内容修改了，看了代码，`Cfg` 不会自动更新。
那么要实现配置自动更新，要怎么做呢？

**Comment by tonybase** [comment]
可以通过 Value(key) 方式获取到引用，会随着值动态变更，或者进行对应 Watch(key, observer)

**Comment by drrrMikado** [comment]
> 可以通过 Value(key) 方式获取到引用，会随着值动态变更，或者进行对应 Watch(key, observer)

通过上面的方式解决了，感谢

**Comment by junneyang** [comment]
> 可以通过 Value(key) 方式获取到引用，会随着值动态变更

可以通过 Value(key) 方式获取到引用，会随着值动态变更
这个可以具体一点吗？谢谢
