### ISSUE TITLE
关于 v2 生成 swagger 问题：unknown command "tool" for "kratos"

### ISSUE THREAD

**Issue by MarsonShine** [go-kratos/kratos#770]
运行 `kratos tool swagger serve .\api\api.swagger.json` 报 `unknown command "tool" for "kratos"`
v2 版本是取消了生成 swagger 的功能么？
如果取消的话，有没有可替代的方案？

**Comment by drrrMikado** [comment]
我现在是在安装 protoc-gen-swagger 之后，每次生成 swagger.json 都是通过以下命令生成：
```shell
protoc -I. -I "C:/Users/User/go/pkg/mod/github.com/go-kratos/kratos/v2@v2.0.0-20210311152607-a4409adf164e/third_party" --swagger_out=logtostderr=true:. ./api/helloworld/v1/gree
ter.proto
```

**Comment by MarsonShine** [comment]
@drrrMikado 谢谢回复，我的确是通过 protoc-gen-swagger，也就是现在的 protoc-gen-openapiv2 生成 swagger。但是在我启动的时候遇到了这种问题：
`swagger serve swagger.json --host=localhost -p=5000` 这样是能正常启动，但是我这个时候再启动 kratos，因为 kraots 绑定的 ip 也是localhost，所以没法正常启动了，而如果切换 IP 的话，swagger 就不能正常使用（调用 api）了，因为 curl 的地址就是 swagger 启动的地址，而不是 app（ktraos）启动的地址了。我翻阅 swagger 的文档，也没有单独更改 curl 的地址的 option。
想请问下，swagger 启动的时候同 app 寄宿在同一个进程？

**Comment by drrrMikado** [comment]
@MarsonShine 我是使用 [Swagger UI](https://github.com/swagger-api/swagger-ui) 来着，可以看看。

**Comment by pokitpeng** [comment]
我采用了导入yapi的方式
