### ISSUE TITLE
v2 中的 tracing 中间件为什么不考虑 OpenTelemetry 呢？

### ISSUE THREAD

**Issue by drrrMikado** [go-kratos/kratos#771]
v2 自带的 tracing 中间件使用的 OpenTracing，在项目中，对接下来发现没有成熟的方案，都是需要自己实现接口。

`go-redis/redis` 却原生提供了 OpenTelemertry 标准的Hook（`redisotel.TracingHook{}`）。

opentelemetry-go 也提供了 zipkin/jaeger 跟踪系统的 api，例如：zipkin 只需要 `zipkin.InstallNewPipeline`，jaeger 也只需要 `jaeger.InstallNewPipeline`，很方便。

> 个人使用下来，使用 v2 自带的 tracing 中间件 + `redisotel.TracingHook{}` 无法收集到数据。改为 `examples/blog` 下的 [中间件](https://github.com/go-kratos/kratos/blob/5a8acec80875e518d27c335b65f15dd4658b43b9/examples/blog/pkg/middleware/trace.go) 是可以收集到数据。

所以是否可以把 v2 中的 tracing 中间件替换为 OpenTelemetry ？

另外 `examples/blog` 中的 `jaeger` 也是使用的 OpenTelemetry 。

**Comment by Windfarer** [comment]
@drrrMikado 您好，感谢反馈。blog里的trace middleware就是用来尝试接入otel作为trace以及对go-redis进行适配的，但目前由于比较忙，这部分还没进行完善的测试，如果在使用时有什么问题可以反馈下，也欢迎提PR帮忙完善。

**Comment by drrrMikado** [comment]
@Windfarer 好的。目前使用 blog 里的 trace middleware 是能正常收集到数据的。
