### ISSUE TITLE
执行kratos new helloworld报错

### ISSUE THREAD

**Issue by susengo** [go-kratos/kratos#780]
**错误提示如下：**
`Creating service helloworld
ERROR: Get "https://github.com/go-kratos/kratos-layout.git/info/refs?service=git-upload-pack": read tcp 10.3.100.90:50781->13.250.177.223:443: read: connection reset by peer`  
**环境：**
macos 10.15.7

**Comment by php403** [comment]
开启代理就行了,或者手动拉取 https://github.com/go-kratos/kratos-layout 代替kratos new helloworld

**Comment by susengo** [comment]
> 开启代理就行了,或者手动拉取 https://github.com/go-kratos/kratos-layout 代替kratos new helloworld
感谢解答，可能是最近GitHub被q了的原因。
