### ISSUE TITLE
建议：关于读取 configs 配置文件的优化，建议增加环境变量 config.environment.yaml

### ISSUE THREAD

**Issue by MarsonShine** [go-kratos/kratos#793]
在 app 启动读取并加载 `../../configs` 的时候，我觉得可以把环境变量当参数考虑进去组成一个完整的配置文件。
如一个项目一般有三个环境：dev,stag,pro，那么我们就会对应三个带有环境变量的配置文件：
- config.dev.yaml
- config.stag.yaml
- config.pro.yaml
这样我们在部署程序的时候就不用更改 config 的文件了，也减少了部署过程中因环境不同配置错的可能。也不用在启动的时候指定对应的文件。

目前我的实现方式如下：
```go
func init() {
	flag.StringVar(&flagconf, "conf", "../../configs/"+getConfigPath(), "config path, eg: -conf config.yaml")
}

func getConfigPath() string {
	environment := os.Getenv("Environment")
	config := ""
	if common.IsNullOrEmpty(environment) {
		config = "config.yaml"
	} else {
		config = "config." + environment + ".yaml"
	}
	return config
}
```
我觉得在 kraots 中的 source.load 方法中遍历文件的时候可以结合环境变量来实现部署配置文件的统一

**Comment by tonybase** [comment]
这个建议自己按需实现 source 就可以了，不打算加到 framework
