### ISSUE TITLE
解决http cors 跨域问题

### ISSUE THREAD

**Issue by xionglongjun** [go-kratos/kratos#798]
proto 文件中定义接口请求方式，GET 无需担心跨域问题，但在POST接口中浏览器进行OPTIONS请求，gorilla/mux 中需要绑定请求类型才能进行访问，OPTIONS的类型怎样与POST一起定义。可以使用nginx进行OPTIONS过滤，但是在开发对接阶段，有没有更方便的处理方式？？

**Comment by tonybase** [comment]
https://github.com/gorilla/handlers/blob/master/cors.go

在注册Handle时可以指定对应的cors handler就可以了

**Comment by xionglongjun** [comment]
OK，这样处理很方便
