### ISSUE TITLE
protobuf文件能否增加嵌套组合

### ISSUE THREAD

**Issue by dcsunny** [go-kratos/kratos#800]
由于api基本使用protobuf书写，对于返回值的reply用很多重复字段，go中可以用组合的方式达到效果。 和protobuf现在实现不了。这增加了工作量。
如，接口使用分页
返回值为
```
{"page":1,"page_size":10,"list":[]}
```
这里的page和page_size就是大量重复的。

**Comment by tonybase** [comment]
这个应该是定义对应的common proto，然后对应接口进行引用就可以了
