### ISSUE TITLE
run failed

### ISSUE THREAD

**Issue by chenbyby** [go-kratos/kratos#801]
panic: proto: (line 1:119): unknown field "dial_timeout"

**Comment by tonybase** [comment]
这个有详细的信息不的，比如配置和proto对应的是怎么样的？

**Comment by chenbyby** [comment]
跟着配置走，就几步，在goland terminal执行会报错。
iterm执行，又可以了

**Comment by novliang** [comment]
这个是模版的锅，kratos-template里/configs/内redis配置文件还有一个dial_timeout配置，如果使用的是较新版本的kratos例如beat2版本，删除了conf.proto里的dial_timeout配置，所以出现这个错误。

解决方式是删除/configs/config.yaml的redis dial_timeout那一行配置

**Comment by Windfarer** [comment]
模板里也去掉了，fixed
