### ISSUE TITLE
这个 service 怎么获取header 头参数呢？

### ISSUE THREAD

**Issue by luckylsx** [go-kratos/kratos#806]

**Comment by tonybase** [comment]
```
import github.com/go-kratos/kratos/transport/http

http.FromServerContext(ctx)
```

可以直接通过ctx获取到上下文相关信息

**Comment by luckylsx** [comment]
> ```
> import github.com/go-kratos/kratos/transport/http
> 
> http.FromServerContext(ctx)
> ```
> 
> 可以直接通过ctx获取到上下文相关信息

哦哦，目前就是通过这个方式获取到了，但是感觉有点麻烦，还以为有更好到方式呢，感谢tony老师

**Comment by ChrisLo0751** [comment]
说实话，有点骚
