### ISSUE TITLE
Content-Type支持多种类扩展问题

### ISSUE THREAD

**Issue by kqbi** [go-kratos/kratos#807]
![图片](https://user-images.githubusercontent.com/40823194/112959442-028e9800-9176-11eb-863b-2ccaee99ea94.png)
![图片](https://user-images.githubusercontent.com/40823194/112959461-06bab580-9176-11eb-9120-9c90d4b8ebdc.png)
如何扩展支持其他的Content-Type

**Comment by tonybase** [comment]
API层目前只支持 encoding的content-type，对应文件或者图片需要自己按标准HTTP注册http.Handler就可以了

**Comment by kqbi** [comment]
用哪个函数，有例子吗，初学，不太懂

**Comment by tonybase** [comment]
https://github.com/go-kratos/kratos/blob/main/examples/http/upload/main.go

可以直接使用标准库的 http.Handler

**Comment by kqbi** [comment]
OK，感谢

**Comment by kqbi** [comment]
不对，你给的 http.Handler是server 路由注册，我的问题在于使用的
![图片](https://user-images.githubusercontent.com/40823194/114640333-78f8d180-9d02-11eb-9476-e68505c21756.png)
使用的kratos的http  client访问第三方的restful接口，对方直接回复的image/jpeg

**Comment by tonybase** [comment]
这种目前需要自己decode body才可以，封装还局限于 API 有类型的（Encoding），如果实现binary encoding其实没太大必要，不如直接 io reader
