### ISSUE TITLE
快速开始教程，过程中有报错，但可以顺利启动Server

### ISSUE THREAD

**Issue by Tzuhaochen** [go-kratos/kratos#820]
教程进行到这两处时报了warning和报错，想问下可能是什么原因，但最后server卻可以正常起来，curl 成功
 go version go1.16.3 linux/amd64 
操作系统是 Ubuntu-20.04 (win10 21H1 WSL2)

1.  kratos proto client api/helloworld/helloworld.proto

`src: warning: directory does not exist.
proto: api/helloworld/helloworld.proto`

2. go generate ./...

`zsh: correct './...' to './..' [nyae]? n
src: warning: directory does not exist.
google/protobuf/descriptor.proto: File not found.
kratos/api/annotations.proto:9:1: Import "google/protobuf/descriptor.proto" was not found or had errors.
kratos/api/annotations.proto:11:8: "google.protobuf.EnumOptions" is not defined.
helloworld.proto:5:1: Import "kratos/api/annotations.proto" was not found or had errors.
exit status 1
../../../../go/pkg/mod/github.com/google/wire@v0.5.0/internal/wire/copyast.go:21:2: missing go.sum entry for module providing package golang.org/x/tools/go/ast/astutil (imported by github.com/google/wire/internal/wire); to add:
        go get github.com/google/wire/internal/wire@v0.5.0
../../../../go/pkg/mod/github.com/google/wire@v0.5.0/internal/wire/parse.go:30:2: missing go.sum entry for module providing package golang.org/x/tools/go/packages (imported by github.com/google/wire/internal/wire); to add:
        go get github.com/google/wire/internal/wire@v0.5.0
../../../../go/pkg/mod/github.com/google/wire@v0.5.0/internal/wire/analyze.go:26:2: missing go.sum entry for module providing package golang.org/x/tools/go/types/typeutil (imported by github.com/google/wire/cmd/wire); to add:
        go get github.com/google/wire/cmd/wire@v0.5.0
cmd/helloworld/wire_gen.go:3: running "go": exit status 1`

**Comment by tonybase** [comment]
https://go-kratos.dev/docs/getting-started/faq

这个应该是 protobuf 引入的proto有关，可以看看FAQ这个解决试试

**Comment by Tzuhaochen** [comment]
我这边检查 protoc 有正确安装，因为可以成功创建 Server 

只是当使用 golang 官方安装教程时
`export $PATH=$PATH:/usr/local/go/bin`

会显示  
`src: warning: directory does not exist. proto: api/helloworld/helloworld.proto`

看了 client.go 的源码后发现有使用 `os.Getenv("GOPATH")`，而上述安装路径的 `$GOPATH` 是空的

后来换成
`export PATH=$PATH:$HOME/go/bin:$HOME/bin:$HOME/local/include`
就没有以上两个问题，可能是zsh权限的关系，ubuntu好像不能跟mac用相同的方式设定，或是我这边的zsh还没调整好，总之解决了，谢谢！

**Comment by tx7do** [comment]
1. 关于 proto的错误：

在执行protoc的时候，需要使用proto_path参数将所有的proto引用路径引入，比如：

`protoc --proto_path=. --proto_path=../../../../../third_party`

建议在api的proto文件同级目录下面建立一个`generate.go`，其内容大概如此：

```go
package v1

// 生成 proto
//go:generate protoc --proto_path=. --proto_path=../../../../../third_party --proto_path=../../../../../third_party/pagination --proto_path=../../../../ --go_out=paths=source_relative:../ ./*.proto

// 生成 proto grpc
//go:generate protoc --proto_path=. --proto_path=../../../../../third_party --proto_path=../../../../../third_party/pagination --proto_path=../../../../ --go-grpc_out=paths=source_relative:../ ./*.proto

// 生成 proto http
//go:generate protoc --proto_path=. --proto_path=../../../../../third_party --proto_path=../../../../../third_party/pagination --proto_path=../../../../ --go-http_out=paths=source_relative:../ ./*.proto

// 生成 proto errors
//go:generate protoc --proto_path=. --proto_path=../../../../../third_party --proto_path=../../../../../third_party/pagination --proto_path=../../../../ --go-errors_out=paths=source_relative:../ ./*.proto

// 生成 swagger
//go:generate protoc --proto_path=. --proto_path=../../../../../third_party --proto_path=../../../../../third_party/pagination --proto_path=../../../../ --openapiv2_out ../ --openapiv2_opt logtostderr=true --openapiv2_opt json_names_for_fields=true ./*.proto
```

2.关于wire错误：

因为wire的CLI依赖`github.com/google/subcommands`这个库，而工程当中找寻不到，故而，引入即可：

```go
package tools

import (
	_ "github.com/google/subcommands"
)
```

然后调用，更新mod：

`go mod tidy`

再去执行`go generate ./...`，此时不再会报错。

另，如果你调用过`go install github.com/google/wire/cmd/wire@latest`安装了二进制的wire，那么你其实可以直接在命令行下面执行wire进行代码生成。layout提供的Makefile的`make wire`其实就是调用的它。
