### ISSUE TITLE
 proto: file "xxxx.proto" is already registered

### ISSUE THREAD

**Issue by shamartor** [go-kratos/kratos#843]
https://github.com/go-kratos/kratos/blob/2a47af33c0037a5dab72af1340ba890818eecc7d/cmd/kratos/internal/proto/client/client.go#L97

#### What happened:
启动程序输出：
```
2021/04/16 20:17:25 WARNING: proto: file "helloworld.proto" is already registered
	previously from: "helloworld1/api/helloworld"
	currently from:  "helloworld2/api/helloworld"
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

2021/04/16 20:17:25 WARNING: proto: message api.helloworld.CreateHelloworldRequest is already registered
	previously from: "helloworld1/api/helloworld"
	currently from:  "helloworld2/api/helloworld"
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

...
```

#### How to reproduce it (as minimally and precisely as possible):
按文档https://github.com/go-kratos/kratos#getting-started,创建两个demo
```bash
~/workspace$ kratos new helloworld1
~/workspace$ kratos new helloworld2
~/workspace$ cd helloworld1
~/workspace$ go mod download
~/workspace$ kratos proto add api/helloworld/helloworld.proto
~/workspace$ kratos proto client api/helloworld/helloworld.proto
~/workspace$ kratos proto server api/helloworld/helloworld.proto -t internal/service
~/workspace$ go generate ./...
~/workspace$ cd helloworld2
...同样执行add,client,server...
```
下面实现helloworld1中service调用helloworld1的接口,产生依赖关系，比如修改helloworld1中:

./go.mod:

```
require (
	helloworld2 v0.0.0-00010101000000-000000000000
	...
)

replace (
	helloworld2 => ../helloworld2
)
```

./internal/service/helloworld.go:

```
import(
	"context"

	pb "helloworld1/api/helloworld"
	innterapi "helloworld2/api/helloworld"
)

type HelloworldService struct {
	pb.UnimplementedHelloworldServer
}

func NewHelloworldService() pb.HelloworldServer {
	_ = innterapi.CreateHelloworldReply{}
	return &HelloworldService{}
}

```
启动helloworld1，报错
```
~/workspace$ go build -o ./bin/ ./...
~/workspace$ ./bin/helloworld1 -conf ./configs
```
go1.16.3
protoc 3.13.0
protoc-gen-go v1.26.0

在google.golang.org/protobuf@v1.25.0中，处理为warn.
在google.golang.org/protobuf@v1.26.0中，处理为panic. 虽可通过环境变量`GOLANG_PROTOBUF_REGISTRATION_CONFLICT`控制，

kratos proto client 调用protoc应该可调整更符合这种场景？

**Comment by tonybase** [comment]
这个应该修正每个应用api proto比较合适，按不同的包名，不同的目录即可

**Comment by Naist4869** [comment]
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/37408934/178760604-ee6a0bcd-0fe1-44c5-9f74-ba983e494ecc.png">
不同的目录还是失败, 我需要在bff导入两个grpc Client, 应该怎么做

**Comment by Naist4869** [comment]
<img width="401" alt="image" src="https://user-images.githubusercontent.com/37408934/178762461-7ee447c2-833a-4940-8f44-8c2ecc8d2149.png">
改了proto文件名就可以运行了
