### ISSUE TITLE
kratos not found

### ISSUE THREAD

**Issue by wnz27** [go-kratos/kratos#849]
go env :
```
GOBIN=""
GOPATH="/Users/fzk27/go"
GOROOT="/usr/local/go"
```
![截屏2021-04-2101 52 27](https://user-images.githubusercontent.com/12094918/115441937-0d53be80-a244-11eb-9d9f-640a08c245ae.png)

**Comment by lingwei0604** [comment]
配置 终端的环境变量。

**Comment by wnz27** [comment]
> 配置 终端的环境变量。

您说的是.bash_profile ? 我加了。
而且echo $PATH 这个go的bin也在路径里

**Comment by lingwei0604** [comment]
.zshrc， 你截图不是用的 zsh 么。两者不一样。

**Comment by lingwei0604** [comment]
> > 配置 终端的环境变量。
> 
> 您说的是.bash_profile ? 我加了。
> 而且echo $PATH 这个go的bin也在路径里

.zshrc， 你截图不是用的 zsh 么。两者不一样。

**Comment by wnz27** [comment]
> > > 配置 终端的环境变量。
> > 
> > 
> > 您说的是.bash_profile ? 我加了。
> > 而且echo $PATH 这个go的bin也在路径里
> 
> .zshrc， 你截图不是用的 zsh 么。两者不一样。

应该也是配了一下，我再确认一下，感谢
