### ISSUE TITLE
log/internal/filewriter: 逻辑简化

### ISSUE THREAD

**Issue by Terry-Mao** [go-kratos/kratos#85]
从 log/internal/filewriter 移除异步以及 buffer 逻辑，顺序写同步切分文件

暴露给外部caller 决定要不要bufio，或者自己控制异步，应该事先为low-level的API

**Comment by Icedroid** [comment]
为什么不直接用zap或logrus，发现这个项目基本常用库都修改了一遍，学习曲线陡增。
