### ISSUE TITLE
api/proto: github.com/gogo/protobuf/gogoproto/gogo.proto: File not found

### ISSUE THREAD

**Issue by 0xMadao** [go-kratos/kratos#854]
如题，执行`kratos proto client api/xx.proto`的时候，报如下错：
```
github.com/gogo/protobuf/gogoproto/gogo.proto: File not found.
xx.proto:4:1: Import "github.com/gogo/protobuf/gogoproto/gogo.proto" was not found or had errors.
exit status 1
```
kratos 版本: `kratos version v2.0.0-beta3`
对比了下v2和之前的版本，发现third_party里面少了github.com/gogo的库，现在只有google api的库，请问如何解决

**Comment by tonybase** [comment]
不打算支持gogo这个库，目前看着也已经不更新了，并且protobuf官方v1.4.x已经不支持gogo

**Comment by 0xMadao** [comment]
> 不打算支持gogo这个库，目前看着也已经不更新了，并且protobuf官方v1.4.x已经不支持gogo

那如果项目里面需要这个库，kratos v2咋解决呢？

**Comment by tonybase** [comment]
可以在自己项目中引入就可以了，或者放在 gopath/src 下面，可以通过 import github.com/gogo/protobuf/gogoproto/gogo.proto；

不过真的不推荐使用这个 gogoproto

**Comment by 0xMadao** [comment]
> 可以在自己项目中引入就可以了，或者放在 gopath/src 下面，可以通过 import github.com/gogo/protobuf/gogoproto/gogo.proto；
> 
> 不过真的不推荐使用这个 gogoproto

多谢tomorrow！还有个问题，为啥v2版本里，取消了bm、warden作为默认的server？

**Comment by tonybase** [comment]
v2 进行了重新设计，比如HTTP可以有更多的选择 Mux、Gin、BM等等

**Comment by gozelus** [comment]
如果不推荐使用 gogoproto，之前的部分需求比如 embed，pointer 有推荐的实现吗？
