### ISSUE TITLE
[Question]服务发现调用grpc，服务发现用本地127.0.01的consul没问题，换成远程的consul会报错

### ISSUE THREAD

**Issue by blue110** [go-kratos/kratos#855]
服务发现调用grpc，服务发现用本地127.0.01的consul没问题，换成远程的consul会报错
![image](https://user-images.githubusercontent.com/26561594/115692962-0a66e400-a392-11eb-8d42-26553b90e107.png)
![image](https://user-images.githubusercontent.com/26561594/115693307-62054f80-a392-11eb-82be-7bcb8435c9f9.png)

**Comment by blue110** [comment]
服务发现调用grpc，服务发现用本地127.0.01的consul没问题，换成远程的consul会报错

**Comment by tonybase** [comment]
这个看着是panic了，可以看下处理逻辑
