### ISSUE TITLE
etcd/registry: 注册中心模块是否能够加上重试机制呢？

### ISSUE THREAD

**Issue by realjustice** [go-kratos/kratos#856]
比如一个service 因为网络抖动，没有及时续上etcd 的lease ，之后网络恢复，但租约已经revoke。此时service 处于无法被发现的状态

**Comment by tonybase** [comment]
这个可以帮提个mr看看不的，看看需要怎么验证下

**Comment by longXboy** [comment]
是指注册和心跳的重试？

**Comment by realjustice** [comment]
是的，能否在租约失效的情况下，重新发起服务注册
