### ISSUE TITLE
[Question]2.0版本 zipkin.Init(）可继续使用不

### ISSUE THREAD

**Issue by blue110** [go-kratos/kratos#859]
按下面的demo跑了，没数据写入zipkin

zipkin使用
可以看zipkin的协议上报实现，具体使用方式如下：

前提是需要有一套自己搭建的zipkin集群
在业务代码的main函数内进行初始化，代码如下：
// 忽略其他代码
import "github.com/go-kratos/kratos/pkg/net/trace/zipkin"
// 忽略其他代码
func main(){
    // 忽略其他代码
    zipkin.Init(&zipkin.Config{
        Endpoint: "http://localhost:9411/api/v2/spans",
    })
    // 忽略其他代码
}

**Comment by tonybase** [comment]
用v2tshg，这个需要用户自己注册到 opentelemetry，然后使用对应的 tracing middleware就可以了
