### ISSUE TITLE
blog/cmd/blog cmd/blog/wire_gen.go:22:6: initApp redeclared in this block         previous declaration at cmd/blog/wire.go:17:96 note: module requires Go 1.15

### ISSUE THREAD

**Issue by sjfxy** [go-kratos/kratos#869]
Please see the FAQ in our main README.md before submitting your issue.

**Comment by sjfxy** [comment]
2

**Comment by wnz27** [comment]
<img width="1257" alt="截屏2021-12-18 16 45 06" src="https://user-images.githubusercontent.com/12094918/146635310-f7494351-d82b-49b4-94e8-693fa23b4f52.png">
and i search https://go-kratos.dev/docs/intro/faq/ i still dont find something.

> Please see the FAQ in our main README.md before submitting your issue.

**Comment by wnz27** [comment]
i fix this problem,
in the wire.go file , in the top line tap this:
```
// +build wireinject
```
