### ISSUE TITLE
log: 日志打印和采集

### ISSUE THREAD

**Issue by tonybase** [go-kratos/kratos#882]
```go
Logger logger = log.MultiLogger(log.NewStdLogger(os.Stdout), syslog.NewLogger())

logger = log.With(logger,
    "service.name", "hellworld",
    "service.version", "v1.0.0",
    "ts", log.DefaultTimestamp,
    "caller", log.DefaultCaller,
)

logger.Log(log.LevelInfo, "key", "value")

Helper helper = log.NewHelper(logger)
helper.Log(log.LevelInfo, "key", "value")
helper.Info("info message")
helper.Infof("info %s", "message")
helper.Infow("key", "value")
```

# References
* https://dave.cheney.net/2015/11/05/lets-talk-about-logging
* https://dave.cheney.net/2017/01/23/the-package-level-logger-anti-pattern
* https://go-talks.appspot.com/github.com/ChrisHines/talks/structured-logging/structured-logging.slide#1
* https://pkg.go.dev/github.com/juju/loggo
* https://speakerdeck.com/chrishines/go-kit-log-package?slide=1
* https://cloud.google.com/logging/docs/reference/libraries#client-libraries-install-go
* https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md
* https://groups.google.com/g/golang-dev/c/F3l9Iz1JX4g/m/2TpGYsTkAQAJ
* https://docs.oracle.com/javase/8/docs/api/java/util/logging/Logger.html
* http://logback.qos.ch/apidocs/index.html
* https://logging.apache.org/log4j/2.x/log4j-api/apidocs/index.html

**Comment by shenqidebaozi** [comment]
- https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/overview.md
- https://github.com/go-kit/kit/tree/master/log

**Comment by shenqidebaozi** [comment]
- https://github.com/open-telemetry/opentelemetry-log-collection

**Comment by tonybase** [comment]
https://docs.google.com/document/d/1ix9_4TQO3o-qyeyNhcOmqAc1MTyr-wnXxxsdWgCMn9c/edit#
