### ISSUE TITLE
transport/http: 需要为特殊router添加中间件的时候很麻烦 可能需要AppendMiddleware方法

### ISSUE THREAD

**Issue by Naist4869** [go-kratos/kratos#890]
Please see the FAQ in our main README.md before submitting your issue.

### Use case(s) - what problem will this feature solve?
 - 我在搭建oauth2的时候需要授权时重定向到redrect_url 
 - 在service层需要判断用户名密码是否正确 正确就重定向 不正确就返回错误 而service层只能操作ctx 所以需要在server层操作http serve 我使用了两种方法 但是觉得很麻烦
#### 方法一
![image](https://user-images.githubusercontent.com/37408934/116666882-1542f980-a9ce-11eb-85e7-7a1d5bb22965.png)
![image](https://user-images.githubusercontent.com/37408934/116666973-33105e80-a9ce-11eb-84f5-dfcbd5b4bbb2.png)

#### 方法二 
![image](https://user-images.githubusercontent.com/37408934/116666900-1a07ad80-a9ce-11eb-82cd-17ea7a3178d1.png)
![image](https://user-images.githubusercontent.com/37408934/116666987-37d51280-a9ce-11eb-8d23-151848b7579c.png)

### Proposed Solution
 为了复用生成的mux.router  可能需要添加一个AppendMiddleware方法 
### Alternatives Considered
 又或者service层直接操控http.ResponseWriter?
### Additional Context
Tony老师赛高

**Comment by tonybase** [comment]
这个 oauth2 middleware 是否合适直接通过 http.Handler middleware 进行实现鉴权，以及 redirect 逻辑？

**Comment by Goxiaoy** [comment]
service 层和 transport 无关，应该不能直接操控http.ResponseWriter。 跳转逻辑应该放在api层直接调用http相关方法然后注册在server上，不过这样确实导致了Middleware无法复用。比较好的方法可能是有第三方的Middleware包来和kratos的middleware对齐==

**Comment by Naist4869** [comment]
> 这个 oauth2 middleware 是否合适直接通过 http.Handler middleware 进行实现鉴权，以及 redirect 逻辑？

不能  v1.NewBlogServiceHandler()返回http.Handler而不是http.HandleFunc  一旦ServeHTTP()调用之后resp就关闭了...

大概是这种感觉
![image](https://user-images.githubusercontent.com/37408934/117236015-6d5c7e80-ae5a-11eb-9ece-4e24d3c39569.png)

**Comment by tonybase** [comment]
可以明确是两种不同的 middleware：
- service，业务层可以不区分不同的接入层做业务通用中间件层
- transport，传输层需要区分不同的，比如：gRPC Interceptor、HTTP Handler
