### ISSUE TITLE
proto生成http服务

### ISSUE THREAD

**Issue by wxwliris** [go-kratos/kratos#894]
在看krotaos框架里面例子的时候，

kratos/examples/blog/api/blog/v1/blog.proto 

这个文件用以下命令生成对应http服务的时候

protoc --proto_path=.  -I $GOPATH/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.14.6/third_party/googleapis --grpc-gateway_out .  blog.proto

报如下错误：
--grpc-gateway_out: segment neither wildcards, literal or variable: expected "{" but got "\x00": /v1/article/

这个怎么处理？

proto 文件内容如下：
syntax = "proto3";

package api.v1;

option go_package = "./;v1";
option java_multiple_files = true;
option java_package = "api.v1";

import "google/api/annotations.proto";

service BlogService {
    rpc CreateArticle (CreateArticleRequest) returns (CreateArticleReply) {
        option (google.api.http) = {
            post: "/v1/article/"
            body: "*"
        };
    }
    rpc UpdateArticle (UpdateArticleRequest) returns (UpdateArticleReply) {
        option (google.api.http) = {
            put: "/v1/article/{id}"
            body: "*"
        };
    }
    rpc DeleteArticle (DeleteArticleRequest) returns (DeleteArticleReply) {
        option (google.api.http) = {
            delete: "/v1/article/{id}"
        };
    }
    rpc GetArticle (GetArticleRequest) returns (GetArticleReply) {
        option (google.api.http) = {
            get: "/v1/article/{id}"
        };
    }
    rpc ListArticle (ListArticleRequest) returns (ListArticleReply) {
        option (google.api.http) = {
            get: "/v1/article/"
        };
    }
}

message Article {
    int64 id = 1;
    string title = 2;
    string content = 3;
    int64 like = 4;
}

message CreateArticleRequest {
    string title = 1;
    string content = 2;
}

message CreateArticleReply {
    Article Article = 1;
}

message UpdateArticleRequest {
    int64 id = 1;
    string title = 2;
    string content = 3;
}

message UpdateArticleReply {
    Article Article = 1;
}

message DeleteArticleRequest {
    int64 id = 1;
}
message DeleteArticleReply {
}

message GetArticleRequest {
    int64 id = 1;
}

message GetArticleReply {
    Article Article = 1;
}

message ListArticleRequest {
}

message ListArticleReply {
    repeated Article results = 1;
}

**Comment by tonybase** [comment]
这个path感觉有隐藏字符？
可以去掉，重新写试试

**Comment by wxwliris** [comment]
嗯嗯，已经解决了，proto不支持结尾带/ ，删除结尾的 / 就好了。我想问另外一个问题。我用protoc --proto_path=. -I $GOPATH/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.14.6/third_party/googleapis --grpc-gateway_out . blog.proto 生成的是 blog.pb.gw.go。想请问 blog 例子里面 blog_http.pb.go 是如何生成的？

**Comment by tonybase** [comment]
是通过 `https://github.com/go-kratos/kratos/tree/main/cmd/protoc-gen-go-http` 进行生成，如果使用grpc-gateway可以也可以去掉这个的
