### ISSUE TITLE
2.0预计什么时间Stable

### ISSUE THREAD

**Issue by zeuszhao-hub** [go-kratos/kratos#895]
请问2.0版本预计什么时间点能够发布稳定版？

**Comment by tonybase** [comment]
应该在一两周后考虑 release v2.0.0

**Comment by igo9go** [comment]
二周了，接下来还需要二周吗

**Comment by igo9go** [comment]
> 应该在一两周后考虑 release v2.0.0

二周了，接下来还需要二周吗

**Comment by tonybase** [comment]
目前一直没有进行 release 的主要有几个方面考虑：
1、http，使用方式多种化，比较难做工程规范化，在想如何结合 middleware；
2、middleware，在考虑这块的后期设计，比如 auth、ratelimit、restful、metrics，其实主要围绕 service+method 的资源名称控制，所以在想 ServiceInfo 的粘合；
3、metadata，链接传递的元信息，正常在开发中，以及 header carrier 的支持；

主要流程：
Transport -> Middleware -> Service -> Biz -> Data

目前主要是 middleware 层的一些设计在考虑，如何进行粘合 ServiceInfo 处理资源控制，类似 Selector ：
https://github.com/googleapis/googleapis/blob/master/google/pubsub/v1/pubsub_v1.yaml

**Comment by febelery** [comment]
所以，这几个问题考虑得咋样了，stable有进度了吗？

**Comment by shenqidebaozi** [comment]
2.0.0 stable 发布
