### ISSUE TITLE
[Question] v2.0.0-beta4 中的error 返回是否需要隐藏details？

### ISSUE THREAD

**Issue by realjustice** [go-kratos/kratos#899]
http server一般是与客户端对接，目前返回的数据格式中既有message，也包含了details，如何隐藏details？

**Comment by tonybase** [comment]
details 这个主要就是更业务约定的错误信息的

**Comment by realjustice** [comment]
也就是说，如果需要记录更为详尽的错误日志，应该自己打印log，而不是依赖logging组件，不知道这个理解是否正确

**Comment by realjustice** [comment]
了解了，非常感谢
