### ISSUE TITLE
proto文件生成http服务的命令是什么

### ISSUE THREAD

**Issue by wxwliris** [go-kratos/kratos#902]
krotos 框架里面 examples/blog/api/blog/v1/blog_http_pb.go 是用protoc的什么插件生成的？可以具体发下命令么？项目中有类似的需求。protoc文件需要生成两个类型的服务。一个是http给客户端使用。一个是grpc给服务端使用。
目前后端只生成了grpc的服务，面向客户端的请求流程是这样的：curl用post向gateway发送请求，gateway作为proxy将请求转化一下通过grpc转发给server，server通过grpc返回结果，gateway收到结果后，转化成json返回给前端。整个链路多了一层gtateway。
看kratos框架里面的例子的意思是直接用proto直接生成了http的服务，所以想请教下protoc 的具体命令是什么？谢谢！！

**Comment by shenqidebaozi** [comment]
建议提交 issue 前,先去文档里面找一下相关的文档
```
# 创建项目模板
kratos new helloworld

cd helloworld
# 拉取项目依赖
go mod download
# 生成proto模板
kratos proto add api/helloworld/helloworld.proto
# 生成proto源码
kratos proto client api/helloworld/helloworld.proto
# 生成server模板
kratos proto server api/helloworld/helloworld.proto -t internal/service
```
https://go-kratos.dev/docs/getting-started/start
