### ISSUE TITLE
kratos怎么接入sentry，异常有统一捕捉的地方吗？

### ISSUE THREAD

**Issue by Phantoms007** [go-kratos/kratos#914]
如题

**Comment by Cluas** [comment]
可以自己加一个middleware

**Comment by Windfarer** [comment]
感觉可以提供个官方的集成middleware

**Comment by Phantoms007** [comment]
> 可以自己加一个middleware

加了，panic没有捕捉到。。。

**Comment by Phantoms007** [comment]
> 可以自己加一个middleware
加了一个中间件，但实现的效果不太好，panic没有捕捉到。期望内的err反而给捕捉到了，有没有参考的代码？

**Comment by Phantoms007** [comment]
> 可以自己加一个middleware

可以自己加一个middleware
加了一个中间件，但实现的效果不太好，panic没有捕捉到。期望内的err反而给捕捉到了，有没有参考的代码？

**Comment by Phantoms007** [comment]
> 可以自己加一个middleware

加了一个中间件，但实现的效果不太好，panic没有捕捉到。期望内的err反而给捕捉到了，有没有参考的代码？

**Comment by Windfarer** [comment]
> > 可以自己加一个middleware
> 
> 加了一个中间件，但实现的效果不太好，panic没有捕捉到。期望内的err反而给捕捉到了，有没有参考的代码？

实验性地实现了sentry middleware，仓库在https://github.com/go-kratos/sentry
功能尚未完善，部分上下文信息没有上报，后续仍会作出很多调整，但目前已经实现了panic时上报错误栈，仅供参考。
