### ISSUE TITLE
err 不应该在 defer 处引用

### ISSUE THREAD

**Issue by dowenliu-xyz** [go-kratos/kratos#927]
https://github.com/go-kratos/kratos/blob/ba5b8d1ee372b31c5f8061ca55a04a8b444a4d61/middleware/tracing/tracing.go#L61

我基本是个 GO 新手，记得有教程教过，defer func 的参数是立即计算的，这个位置的 err 可能不是取得最终 err 值吧

**Comment by tonybase** [comment]
defer 是在退出时执行的，可以取到 err 当前对象

**Comment by dowenliu-xyz** [comment]
https://play.golang.org/p/cp6t97et2pr

**Comment by dowenliu-xyz** [comment]
通过在闭包中调用就可以解决。 https://play.golang.org/p/mC1I1YmT95u
PR： #928

**Comment by tonybase** [comment]
试了下，确实不行
