### ISSUE TITLE
[Feature] Registrar 希望可以控制注册哪些实例,而不是注册全部实例

### ISSUE THREAD

**Issue by shenqidebaozi** [go-kratos/kratos#933]
在当前版本实现中,通过 **kratos.new()** 传入的实例,会被全部注册到注册中心,但是有一些 **transport** 概念 可能与 **http/grpc** 不同, 不需要注册到注册中心,在当前版本中只能通过返回 err 来控制不被注册. 

希望可以通过某些方法来实现用户主动控制,或者通过 **transport** 控制实例是否需要被注册.

**Comment by tonybase** [comment]
这个后面版本可以进行调整下Register设计，目前看着还影响不大

**Comment by shenqidebaozi** [comment]
> 这个后面版本可以进行调整下Register设计，目前看着还影响不大

嗯,影响不大,记录一下,怕忘了
