### ISSUE TITLE
transport/http: 关于重写ResponseEncoder

### ISSUE THREAD

**Issue by xushuhui** [go-kratos/kratos#955]
以前老项目，为了兼容以前的数据返回格式，要在pb的reply中外部再包一层struct。我看了下代码需要重写ResponseEncoder方法，
应该从哪里入手？codecForRequest是私有方法，无法外部调用，我尝试重写codecForRequest方法，无法import "github.com/go-kratos/kratos/v2/internal/http"包

thank you

**Comment by tonybase** [comment]
可以帮忙提个mr，可以把 codecForRequest -> CodecForRequest，改成公开接口就可以了
