### ISSUE TITLE
能否增加meno-repo这种模式的layout

### ISSUE THREAD

**Issue by HuLuWang** [go-kratos/kratos#959]
能否增加beer-shop 这种meno-repo的layout

**Comment by Windfarer** [comment]
layout是面向单个微服务应用的项目结构，从微观层面上来讲，beer项目所用的结构与layout差别不大，app下面每个service就是由layout生成的，只是把api部分提到外面统一管理了。

实践上也可以将公共的api放在单独的一个仓库进行管理，例如google的https://github.com/googleapis/googleapis

我们建议您继续使用layout来创建单个微服务的项目，并根据您的需要调整您在宏观层面上的多个微服务项目组织形式，也可以参考beer项目的结构进行组织。

**Comment by HuLuWang** [comment]
感谢解答～

**Comment by codingcn** [comment]
https://github.com/codingcn/kratos-mono-repo

**Comment by mackwan84** [comment]
> layout是面向单个微服务应用的项目结构，从微观层面上来讲，beer项目所用的结构与layout差别不大，app下面每个service就是由layout生成的，只是把api部分提到外面统一管理了。
> 
> 实践上也可以将公共的api放在单独的一个仓库进行管理，例如google的https://github.com/googleapis/googleapis
> 
> 我们建议您继续使用layout来创建单个微服务的项目，并根据您的需要调整您在宏观层面上的多个微服务项目组织形式，也可以参考beer项目的结构进行组织。

请教一下，假如**将公共的api放在单独的一个仓库进行管理**，那该如何单个微服务应用中引入这个统一管理api部分呢？通过git的submodule吗？还是？

**Comment by realityone** [comment]
googleapis 有对应生成代码的 `pb.go` 仓库，你可以用 CI 或者 buf.build 之类的工具帮你达到类似的效果。

https://github.com/googleapis/go-genproto
