### ISSUE TITLE
net/trace 只是一个client端，后续collector，数据处理展示有开源计划吗？

### ISSUE THREAD

**Issue by greyireland** [go-kratos/kratos#97]
net/trace 只是一个client端，后续collector，数据处理展示有开源计划吗？

想问下公司trace数据量每天大概多少？

数据怎么存储？

数据如何展示？

数据如何计算？

**Comment by lintanghui** [comment]
内部collector项目dapper后续会逐步开源，数据采用hbase进行存储，通过dapper后台支持用项目名，traceid进行查询。同时会进行耗时分布以及错误分布统计展示

**Comment by wujunze** [comment]
你好 请问  trace 可以桥接支持 Jeager 方案吗 @Terry-Mao

**Comment by tonyboxes** [comment]
trace正在讨论适配第三方的方案，对于适配方式有什么建议不的；@wujunze

**Comment by tonyboxes** [comment]
比如：
```
net/trace/reporter/zipkin
net/trace/reporter/jagging
```
使用：
```
zipkin.Init(config)
// or
jagging.Init(config)
```

**Comment by Terry-Mao** [comment]
两个改法：

1、类似gRPC Resolver 那种 实现一个Builder，自己注入实现，基于名字；

2、Init 方法 提供自定义实现暴露Reporter 接口；

这样方便go mod引入的人来扩展和替换，而不是在kratos 代码目录里去改

另外可以考虑内部直接支持 zipkin、jagging

**Comment by lcg635** [comment]
类似go-micro那样, 定好接口之后在框架内部使用.

具体的不同实现不要放在框架内, 放在另外的包里. 这样安装kratos时不用下载没用到的东西

**Comment by yufeiminds** [comment]
建议走 CNCF [OpenTelemetry](https://opentelemetry.io/) 的路线，这样将来对 CNCF 系的开源项目比如 OpenTracing 之类的支持会比较好~

**Comment by Terry-Mao** [comment]
@yufeiminds 确实这样更好， @tomwei7 可以看看

**Comment by Terry-Mao** [comment]
@lcg635 目前进行扩展都要在kratos里来展开，确实不利于外面的同学来扩展，必须把代码修改放入到kratos里，目前会分为两步来做：
1、基于driver或者builder来进行注册 实现；
2、剥离实现到独立的仓库（这个要待讨论，本质上会增加使用者的成本，一个仓库一波搞定比较简单）；

**Comment by bingzhilanmo** [comment]
@Terry-Mao 是否考虑Kratos的Trace 改为标准的Opentracing 实现，比如直接对接jaeger这种，这样更方便外面的同学使用，后期上Istio也更方便，我司内部是采用的Kratos为基础的框架，改了Log和Trace等支持上K8s云等更加方便

**Comment by tonybase** [comment]
v2已经 opentracing实现，可以考虑直接使用jeager
