### ISSUE TITLE
文档中的 blog 简单的CRUD工程 make run 失败

### ISSUE THREAD

**Issue by guowei-gong** [go-kratos/kratos#971]
#### What happened:
根据文档 [综合项目](https://go-kratos.dev/docs/example/overview#%E7%BB%BC%E5%90%88%E9%A1%B9%E7%9B%AE) ，我找到了 blog 示例，再根据 blog 下的 README.md，我尝试运行它，在执行 `make run`，我得到了 

`make: *** No rule to make target `run'.  Stop.`

#### What you expected to happen:
本地运行 blog 项目，通过 debug 链路追踪 blog 项目中的 crud 流程，协助我快速上手

#### How to reproduce it (as minimally and precisely as possible):
1. git clone https://github.com/go-kratos/kratos.git
2. cd kratos/examples/blog/
3. 在 mysql 中创建了 testdb
4. 编辑 configs/config.yaml 为我的 mysql 本地配置
5. make run

#### Anything else we need to know?:
我是一个 go 新手，这可能是个愚蠢的问题，而不是 bug，希望得到大佬们的回复 
![image](https://user-images.githubusercontent.com/62499904/120136257-814e9280-c204-11eb-8ada-864fcac46eab.png)

#### Environment:
- Kratos version (use `kratos -v`): kratos version v2.0.0-rc1
- Go version (use `go version`): go version go1.16.4 darwin/amd64
- OS (e.g: `cat /etc/os-release`): macOS 11.3.1
- Others: 暂无

**Comment by tonybase** [comment]
可以 cd blog/cmd，直接进行 go build，然后 ./blog -conf ../../configs 就可以了

**Comment by tonybase** [comment]
没有 make run 这个命令的

**Comment by guowei-gong** [comment]
> 可以 cd blog/cmd，直接进行 go build，然后 ./blog -conf ../../configs 就可以了

感谢大佬，这样做我成功了，我对 Makefile 没有了解

**Comment by StormSpirit22** [comment]
这不是楼主的问题，make run运行不了就不应该出现在README里，希望能修改一下，不要让更多人花时间去搜这个问题。
