### ISSUE TITLE
v2里errgroup为什么没用用v1中的errgroup，而是选择使用X包里的？

### ISSUE THREAD

**Issue by qloog** [go-kratos/kratos#974]
RT，看了下app.go里的 errgroup, 使用的是 `golang.org/x/sync/errgroup`,  为什么没有使用v1中自己封装的？ v1的还自带recover机制。

**Comment by tonybase** [comment]
util，会在后续逐步加进来~

**Comment by qloog** [comment]
> util，会在后续逐步加进来~

soga, 感谢Tony老师这么速度的回复。
