### ISSUE TITLE
CLI "kratos new"命令拉取应该默认设置layout版本

### ISSUE THREAD

**Issue by Windfarer** [go-kratos/kratos#977]
https://github.com/go-kratos/kratos/blob/main/cmd/kratos/internal/project/project.go#L25

我们应该在release时分别对layout和kratos仓库设置相同的tag，并且在new项目时拉取对应的layout版本，以使两个仓库版本保持一致，避免出现破坏性升级时造成新创建出的项目不可用。

**Comment by shenqidebaozi** [comment]
加个 branch 标签？ 如果自定义了 repo，不传branch的话，走默认拉取，如果传入了，拉取指定版本。如果没有指定源则拉取 kratos对应版本的 layout？

**Comment by shenqidebaozi** [comment]
默认 repo。始终拉取 kratos 对应版本，也可以手动指定版本怎么样

**Comment by tonybase** [comment]
可以加按 branch 或者 tag 进行拉指定版本

**Comment by shenqidebaozi** [comment]
@tonybase 直接branch就行了吧，branch也可以检出tag -b v2.0.0-rc1
