### ISSUE TITLE
[Feature] v2 config支持apollo

### ISSUE THREAD

**Issue by younglifestyle** [go-kratos/kratos#997]
config接口变化，apollo需要重新适配才能支持

**Comment by younglifestyle** [comment]
感觉现在的value.go只开放一个config/scan接口，并不适合apollo这种要获取多namespace的数据格式

**Comment by tonybase** [comment]
可以把这个 namespace 加到 key 上面实现不的？

例如：key = {namespance}.{key}

**Comment by younglifestyle** [comment]
没有详细理解大佬说的key是哪里的。

不过按我的理解，假设需要从A，B两个namespace中获取数据，Load会将数据均拉取组合成一个Json数据，这样的话，而scan是用一个结构体去接受，这里就无法甄别我需要获取的是这个结构体中的哪个字段下的数据了。

**Comment by shenqidebaozi** [comment]
#1297
